### ISSUE TITLE
Hardcoded `cluster.local` DNS suffix

### ISSUE THREAD

**Issue by Wexxion** [Altinity/clickhouse-operator#1001]
Hi! `metrics_exporter` from clickhouse-operator can't scrape metrics from clickhouse cluster because of hardcoded `cluster.local` suffix. In our k8s installation we use custom domain name, which differs from `cluster.local`

If I understand right, domain suffix is optional and we can get rid of it, because suffix will be taken from k8's DNS

How to fix issue:
Remove all `cluster.local` occurrences from repo or provide ability to configure cluster domain in clickhouse-operator installation

**Comment by lololozhkin** [comment]
Facing the same issue :(

**Comment by iak2004** [comment]
I have same problem too.

**Comment by sunsingerus** [comment]
take a look on the example with explicit domain name: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/18-namespace-domain-pattern.yaml
