### ISSUE TITLE
Metrics-exporter doesn't support credentials from secret.

### ISSUE THREAD

**Issue by patrickdash** [Altinity/clickhouse-operator#1002]
It appears the metrics-exporter only supports hardcoded credentials (https://github.com/Altinity/clickhouse-operator/blob/master/cmd/metrics_exporter/app/metrics_exporter.go#L100).

This means that even if we pass the credentials to the operator as a secret, we still have to hardcode it for the metrics-exporter.

**Comment by sunsingerus** [comment]
please check 0.20.0 branch

**Comment by alex-zaitsev** [comment]
@patrickdash , could you confirm 0.20.0 fixes your issue?

**Comment by ispirals** [comment]
Hey, I tried to use the 0.20.0 branch because I'm facing the same issue but seems there is a label value missing here https://github.com/Altinity/clickhouse-operator/blob/0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml#L3174

**Comment by sunsingerus** [comment]
> ...there is a label value missing here...
Fixed in 0.20.0. Please, take a look
