### ISSUE TITLE
Root element in config <clickhouse> does not match config.d files <yandex>

### ISSUE THREAD

**Issue by pauljohnston2009** [Altinity/clickhouse-operator#1004]
Should the config maps be updated to be `<clickhouse>` instead of `<yandex>`?
The default image has switched to clickhouse/clickhouse-server which uses `<clickhouse>` for its root element
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-bundle.yaml#L3598

The config.d directory still contains `<yandex>` elements eg.
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-bundle.yaml#L3490

The docs say the root elements should match
https://clickhouse.com/docs/en/operations/configuration-files/
> All XML files should have the same root element, usually `<clickhouse>`.

The config in  /var/lib/clickhouse/preprocessed_configs/config.xml appears to be correct for now.

**Comment by alex-zaitsev** [comment]
Both <yandex> and <clickhouse> work.

We are hesitant to change it in default configuration files, since it will result restart of ClickHouse pods when operator is upgraded.
