### ISSUE TITLE
Speed up cluster scale up

### ISSUE THREAD

**Issue by cw9** [Altinity/clickhouse-operator#1005]
Hi, 

Is there a way to config the speed of rolling upgrade? In our environment it takes about 2-3minutes per node to restart, so when we are trying to scale up a cluster from e.g.100 nodes to 101 nodes, we need to wait for the first 100 nodes to be restarted first before the 101st node can be added, which takes a long time.

Is there a way to speed up the process?

Thanks

**Comment by godwhoa** [comment]
Maybe a duplicate of https://github.com/Altinity/clickhouse-operator/issues/996?
