### ISSUE TITLE
Operator upgrade: 0.20.0 Authentication failed metrics pod

### ISSUE THREAD

**Issue by midhuns3343** [Altinity/clickhouse-operator#1007]
Operator was upgraded to 0.20.0 and then the metrics container in operator pod started throwing authentication errors:

DB::Exception: clickhouse operator: Authentication failed: password is incorrect or there is no user with such name
 net/url: invalid userinfo

There are multiple clickhouse clusters running and operator is not able to authenticate to any of them. 

Operator installation Manifest file:
```yanl
      access:
        # ClickHouse credentials (username, password and port) to be used by operator to connect to ClickHouse instances
        # for:
        # 1. Metrics requests
        # 2. Schema maintenance
        # 3. DROP DNS CACHE
        # User with such credentials can be specified in additional ClickHouse .xml config files,
        # located in `chUsersConfigsPath` folder
        username: "clickhouse_operator"
        password: "lZU@^bq0TQBvXl1"
        #secret:
          # Location of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
          # Can be used instead of explicitly specified username and password
          #namespace: ""
          #name: ""
        # Port where to connect to ClickHouse instances to
        port: 8123
```

**Comment by Slach** [comment]
how exactly do you upgrade operator? just change image versions in operator deployment? or do use full manifest from
https://github.com/Altinity/clickhouse-operator/raw/0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml ?

**Comment by midhuns3343** [comment]
> how exactly do you upgrade operator? just change image versions in operator deployment? or do use full manifest from https://github.com/Altinity/clickhouse-operator/raw/0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml ?

I followed https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_upgrade.md
removed current one and deployed new one

**Comment by Slach** [comment]
check /etc/clickhouse-server/config.d/chop-generated-users.xml
inside clickhouse-pod
and compare sha hash with your password from your installation

**Comment by midhuns3343** [comment]
> /etc/clickhouse-server/config.d/

I'm not able to see 'chop-generated-users.xml' at /etc/clickhouse-server/config.d/

Attached image with list of files, its same for all clusters

![image](https://user-images.githubusercontent.com/88483737/189864548-2add163a-6d11-48ea-a0a7-7952d5a38628.png)

**Comment by Slach** [comment]
sorry  users.d instead of config.d
`/etc/clickhouse-server/users.d/chop-generated-users.xml`

**Comment by midhuns3343** [comment]
> sorry users.d instead of config.d `/etc/clickhouse-server/users.d/chop-generated-users.xml`

chop-generated-users.xml contains SHA256 password of the user created while deploying clusters which is different from the one mentioned in operator manifest file. Attached screenshot of file. 

![image](https://user-images.githubusercontent.com/88483737/189871640-535de49e-79bc-4b2d-a42a-b9cf3427e3d9.png)

**Comment by Slach** [comment]
looks strange, `clickhouse_operator` present
but miss  `password_sha256_hex` for this user
could you check `/etc/clickhouse-server/users.d/01-clickhouse-user.xml` ?

I would like to propose install operator from scratch from 
```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml
```

after it create separate `kind: ClickHouseOperatorConfiguration` and define 
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseOperatorConfiguration
metadata:
  name: chopconf-password-example
spec:
  clickhouse:
     access:
        username: clickhouse_operator
        password: XXX
```         
or manually change configmap `etc-clickhouse-operator-files` and restart operator and check `chop-generated-users.xml` and `01-clickhouse-user.xml` in `/etc/clickhouse-server/config.d` inside created clickhouse pods

**Comment by midhuns3343** [comment]
> looks strange, `clickhouse_operator` present but miss `password_sha256_hex` for this user could you check `/etc/clickhouse-server/users.d/01-clickhouse-user.xml` ?
> 
> I would like to propose install operator from scratch from
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml
> ```
> 
> after it create separate `kind: ClickHouseOperatorConfiguration` and define
> 
> ```yaml
> apiVersion: "clickhouse.altinity.com/v1"
> kind: ClickHouseOperatorConfiguration
> metadata:
>   name: chopconf-password-example
> spec:
>   clickhouse:
>      access:
>         username: clickhouse_operator
>         password: XXX
> ```
> 
> or manually change configmap `etc-clickhouse-operator-files` and restart operator and check `chop-generated-users.xml` and `01-clickhouse-user.xml` in `/etc/clickhouse-server/config.d` inside created clickhouse pods

Creating CRD ClickHouseOperatorConfiguration worked,  thank you for the guidance.
