### ISSUE TITLE
Avoid clickhouse restarts on some settings change

### ISSUE THREAD

**Issue by filimonov** [Altinity/clickhouse-operator#1017]
e.g. macros/xxx
 max_concurrent_queries

etc.  See 
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files/#settings--restart

**Comment by alex-zaitsev** [comment]
Similar to #978

**Comment by filimonov** [comment]
Adressed in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.21.0
