### ISSUE TITLE
Adding shard secret text from ClickHouseInstallation manifest

### ISSUE THREAD

**Issue by arbreezy** [Altinity/clickhouse-operator#1019]
I'd like to configure TLS for Distributed queries which require a preshared text in every shard.

The only reference to it was this [comment](https://github.com/Altinity/clickhouse-operator/issues/797#issuecomment-962178166)
```
...
settings:
      remote_servers/mycluster/secret: test
...
``` 

I've tried to configure something similar to my installation manifest but the config ends up in `chop-generated-settings.xml` although per docs, this has to be in  `chop-generated-remote_servers.xml` 

```
$ cat chop-generated-settings.xml
 <remote_servers>
        <mycluster>
            <secret>test</secret>
        </mycluster>
    </remote_servers>
```
Is it possible to set this for every shard from the manifest ?

My operator's version is `0.18.1`

**Comment by alex-zaitsev** [comment]
@arbreezy , operator 0.20.0 has support for secrets in remote_servers.xml. See examples there:
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-01-auto.yaml
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-02-plaintext.yaml
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-03-secret-ref.yaml
