### ISSUE TITLE
Bug deploying a CHI in clickhouse-operator >=0.19.0 to Rancher

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#1021]
The addition of the label `ready=<yes|no>` is causing an issue when deploying a CHI on Rancher. 

By default, in our Rancher all network connections are disabled across projects. We have clickhouse-operator installaed in its own namespace (and in its own project). When a user installs a CHI in their namespace the operator will create the various resources but will get stuck because it can't ping the servers. To prevent that, when a LoadBalancer service is created in Rancher, it will create a NetworkPolicy to allow communications from the clickhouse-operator namespace to the namespace where it created the Service. That used to work because the matching selector labels didn't include ready=yes but now that you changed that, the NetworkPolicy is expecting to pass traffic ONLY if ready=yes, which will never happen because the operator can't ping the server and so ready always stays equal to NO.

Hope that makes sense... Can you suggest a workaround, other than having to manually edit the automatically created NetworkPolicy to remove the ready=yes label in the selector? Thanks!

**Comment by alex-zaitsev** [comment]
@a-dot , not sure what the problem is, and how NetworkPolicy is related to headless services user by operator in order to communicate to pods. LoadBalancer is only used for an outside world. Could you give an example?

Alternatively, you may probably deploy operator at the same namespace as CHI.

**Comment by a-dot** [comment]
Ok, let me try to clarify this...

Our Rancher deployment is multi-tenant and so we block traffic from one project to another. A project is composed of a number of namespaces. We support multiple clients and want to give our users the ability to instantiate clickhouse (a CHI) using the clickhouse-operator installed in one of the namespace. By default, in our cluster, outbound traffic from a namespace is allowed to any other namespace, but inbound traffic is blocked. Unless a [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) is applied in that namespace to allow ingress traffic. To automate this, whenever a Service of type LoadBalancer is created in a namespace, Rancher will automatically create a NetworkPolicy in that namespace to allow ingress traffic to that Service.

This was fine in version <0.19.0 because when Rancher creates that NetworkPolicy, it grabs the set of labels used to match the Service to the Pods and applies the same set of labels as a selector on the NetworkPolicy to allow ingress traffic to those same Pods.

Before 0.19.0, those labels did not contain `ready=<yes|no>` and were used to specify the Pods for the CHI (chi name, namespace, etc.). But since 0.19.0, this set of labels now contain `ready=yes`, which will never be set to `yes` until the operator successfully connects to the CHI Pod and ping it, which will never happen because the network traffic is blocked by default, _until_ the label `ready=yes` matches, and it never will.

Hope that makes more sense now ?

**Comment by alex-zaitsev** [comment]
What comes first -- a chicken or an egg :)

I see the problem. Before 0.19 there was a selector only for the label name 'clickhouse.altinity.com/ready'. In 0.19+ selector has been changed to 'clickhouse.altinity.com/ready: yes'. 

We can probably change it back if it causes such problems. But it looks like a Rancher bug to me that makes wrong assumptions about service configuration.

**Comment by a-dot** [comment]
@alex-zaitsev, I agree, it's not ideal that Rancher does such a thing. We looked for a setting to revert the behaviour or change how the set of labels is selected but didn't make any progress.

Instead of changing back the `ready` label, what about adding maybe a configuration option to toggle whether the ready label is included or not? I realize it's a very specific configuration option and a bit awkward but I don't necessarily think removing it is the solution either. There's a reason why you want the `ready=yes` in the matching selector for the Service so it shouldn't be removed entirely.

**Comment by a-dot** [comment]
We ended up creating a more permissive NetworkPolicy at the time of the creation of the CHI in a namespace to allow incoming traffic. That will work for our workaround! Thanks!
