### ISSUE TITLE
Grafana dashboard exported_namespace

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#1028]
The grafana dashboard available here: https://github.com/Altinity/clickhouse-operator/blob/master/grafana-dashboard/Altinity_ClickHouse_Operator_dashboard.json has several hundred references to the `exported_namespace` label but that label is not a label that is available from the metrics-exporter. The label is actually called `namespace`, not `exported_namesapce`. The dashboard will still render but filtering on the namespace won't be possible. Am I missing something or is this a mistake?

**Comment by Slach** [comment]
exported_namespace depends of conflicting namespace label from kubernetes in our prometheus scraping config
look details
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-template.yaml#L48-L50

you can replace `exported_namespace` to `namespace`
