### ISSUE TITLE
Operator upgrade from 0.12 to 0.19 restarts cluster

### ISSUE THREAD

**Issue by midhuns3343** [Altinity/clickhouse-operator#1042]
I recently upgraded operator from version 0.12 to 0.19 which caused a restart of shard pods. Is this normal and is there any way to prevent the restart of shards? Below is the manifest used to deploy cluster

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "pl-clh"
spec:
  configuration:
       clusters:
         - name: shard
           layout:
                shardsCount: 5
                replicasCount: 1
                internalReplication: Enabled
           templates:
             dataVolumeClaimTemplate: clh-claim
             podTemplate: clickhouse:20.6
       zookeeper:
         nodes:
         - host: zookeeper.clh-zkpr
       settings:
         logger/level: trace
         logger/log: /var/log/clickhouse-server/clickhouse-server.log
         logger/errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
         logger/size: 1000M
         logger/count: 10
         compression/case/method: zstd
         max_concurrent_queries: 1000
       users:
         default/networks/ip:
         - "::/0"
         - "0.0.0.0/0"
         pluser/networks/ip:
         - "::/0"
         - "0.0.0.0/0"
         xx/profile: default
         xx/quotas: default
         xx/access_management: 1
         xx/password_sha256_hex: xxxxx
       profiles:
         readonly/readonly: "0"
         default/max_memory_usage: "1000000000"
       quotas:
         default/interval/duration: "3600"

  templates:
      volumeClaimTemplates:
      - name: pl-clh-claim
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: csi-rbd-fast
          resources:
            requests:
              storage: 2000Gi
      podTemplates:
      - name: clickhouse:20.6
        spec:
          containers:
            - name: clickhouse-pod
              image:  yandex/clickhouse-server:20.6
              volumeMounts:
                - name: pl-clh-claim
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "32000Mi"
                  cpu: "1000m"
                limits:
                  memory: "64000Mi"
                  cpu: "8000m"

**Comment by alex-zaitsev** [comment]
Hi @midhuns3343 , there was a number of configuration changes in 0.13 and 0.14 versions that required restart of the cluster. Since 0.14 upgrades of operator does not result in restart anymore.

Please do not use 0.19 but use 0.20 instead.

**Comment by midhuns3343** [comment]
> Hi @midhuns3343 , there was a number of configuration changes in 0.13 and 0.14 versions that required restart of the cluster. Since 0.14 upgrades of operator does not result in restart anymore.
> 
> Please do not use 0.19 but use 0.20 instead.

Thanks for the info. Is there any bug in 0.19? I had already deployed 0.19 to couple of production servers.
