### ISSUE TITLE
Missing create secret RBAC permissions in operator ClusterRole

### ISSUE THREAD

**Issue by chancez** [Altinity/clickhouse-operator#1051]
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-01-auto.yaml doesn't work because the permissions for the operator to create a secret haven't been added: https://github.com/Altinity/clickhouse-operator/blob/release-0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml#L2718-L2722

Could probably just add secrets to the same list as the configmaps, service and pvcs: https://github.com/Altinity/clickhouse-operator/blob/release-0.20.0/deploy/operator/clickhouse-operator-install-bundle.yaml#L2596-L2599

**Comment by alex-zaitsev** [comment]
ack. Will be fixed in 0.20.1

**Comment by alex-zaitsev** [comment]
https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.20.1
