### ISSUE TITLE
Use secret for keep users and users settings

### ISSUE THREAD

**Issue by expake** [Altinity/clickhouse-operator#1069]
How I can use secret for keep users and users settings?
Example:

users:
   - secret
          user_in_secret

**Comment by alex-zaitsev** [comment]
Hi @expake , 

There are two possibilities. 
1. You can specify user passwords as a secret using a special syntax, see this: https://github.com/Altinity/clickhouse-operator/blob/master/tests/e2e/manifests/chi/test-011-secrets.yaml
2. Use 'from-env' ClickHouse syntax, and provide values via env variables mapped to secrets. See discussion and examples in there: https://github.com/Altinity/clickhouse-operator/issues/700

**Comment by expake** [comment]
Looks great! I will be research it, thanks!

**Comment by expake** [comment]
If I use clickhouse-operator-install-bundle.yaml for kubernetes first option will be works?

**Comment by expake** [comment]
What should I do to use passwords in secrets when deploying clickhouse in k8s?Thanks for the answer)

**Comment by alex-zaitsev** [comment]
@expake see https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md
