### ISSUE TITLE
clickhouse-operator should pause rolling changes when more than 1shard (nods) unhealthy / unavailable

### ISSUE THREAD

**Issue by rtkgjacobs** [Altinity/clickhouse-operator#1070]
**New Feature Request**

Ideally from a feature set point of view, clickhouse-operator should try and provide what a single StatefulSet and disruption budget would from a roll out / protection / availability control
* Ensure that if any more than 1 shards are unavailable, further rolling changes are not applied - this condition / count should be checked on a regular basis, and not be limited to a permissive on pod readiness probe check only of today

**Background**

Conventional StatefulSet Kubernetes design patterns can rely on per pod probe(s) which verify that sufficient members of a Statefulset count meet or exceed a defined disruption budget (similar for ReplicaSets). When a disruption budget is exceeded, a rolling change will be blocked until the healthy count is above the required disruption budget thresholds again.

Recently we had a deployment applied by the clickhouse-operator, where a bug caused replicas (pods) to fail after 5~ minutes of operation, well after they passed the liveliness and readiness probe states.  With the design of the Clickhouse-Operator using a StatefulSet per each pod (replica), there was no default mechanism that could stop the rolling change / update after the initial permissive per each pods update passed. 

With this new proposed feature in place with our production issue above, it would mean, the first pod would have fallen into a failed state, and further roll out changes would have been held by the interlock once one or more remained in their failed state.  It may be desired to optionally including a longer delay time before the operator will proceed to its next seperate StatefulSet per shard (pod). 

Said another way, having a disruption budget apply to the collection of StatefulSets that the operator sets up, as though they are a single StatefulSet would be ideal.

**Comment by alex-zaitsev** [comment]
Hi @rtkgjacobs , the behaviour on failure is configurable: https://github.com/Altinity/clickhouse-operator/blob/master/config/config.yaml#L140

The PodDisruptionBudget is in place in order to account for Kubernetes side changes, but since operator re-creates statefulsets on changes it does not help here.

I do not understand how yo handle your case, when replicas fail after 5 minutes of being ok. Maybe you can elaborate.

**Comment by alex-zaitsev** [comment]
Since 0.21.2 operator abort changes in case of pod failure by default
