### ISSUE TITLE
Helm chart and secret.username value

### ISSUE THREAD

**Issue by Drabuna** [Altinity/clickhouse-operator#1071]
Not sure if I'm correct, but maybe I am: 

1. Specified custom `values.yaml` when deploying helm chart. `secret.username` and `secret.password` were set to a custom value
2. Deployed pretty standard `ClickHouseInstallation`
3. Got an error: 

```
2023.01.06 18:17:06.213945 [ 1 ] {} <Error> Application: DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos' or 'ssl_certificates' must be specified for user clickhouse_operator.: while parsing user 'clickhouse_operator' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml
```

It took some time to debug, but it seems if `secret.username` has a value that differs from `clickhouse_operator` this keeps happening.

Would be good to document this I think.

**Comment by Slach** [comment]
secret.username and secret.password used 

you need to specify
```yaml
spec:
 configuration:
    users:
       clickhouse_operator/password_sha256_hex: XXXX
```

inside kind: ClickHouse installation after that

you can use additionalResources
in values for it

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/values.yaml#L531

**Comment by Slach** [comment]
@slamdev could you look?
