### ISSUE TITLE
Mount TLS ca cert in the operator's deployment, instead of specifying it as a string

### ISSUE THREAD

**Issue by arbreezy** [Altinity/clickhouse-operator#1073]
Hello,

This is more of a question, I am using v0.20 and I want to get to a fully TLS configuration. My only problem is the way I generate certificates which is via cert-manager within the cluster. From my understanding, the only way to setup rootCA in the operator is to include it as a string on deployment time.

Is it possible to mount the certificate or define it as a K8s secret which for example can be generated by cert-manager?

Renewal of this certificate is another operation that can be automated without redeploying operator's config and changing the [rootCA](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/values.yaml#L232)

Thank you in advance

**Comment by arbreezy** [comment]
@Slach 
I have been reading the related [code](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/clickhouse/connection.go#L75) to `rootCA` and it seems that it's missing the decoding to .der before it tries to [parse](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/clickhouse/connection.go#L75) the rootca certificate, which  fails with `malformed certificate`
an example with pem.decode,  https://go.dev/play/p/duvjooWozLI
any thoughts?

**Comment by arbreezy** [comment]
I can prepare a small PR as well, if someone from the operator team acknowledges the missing der decoding.

**Comment by Slach** [comment]
you are welcome to make PR

**Comment by alex-zaitsev** [comment]
@arbreezy , looking forward for your PR. rootCA has been contributed by a community member, so we have not checked it fully.

**Comment by arbreezy** [comment]
hey guys, I will be happy to add a small PR to the project, I'll try to find time this or next weekend.

**Comment by alex-zaitsev** [comment]
@arbreezy -- this is available in 0.23.x. See examples of mounting certificate files at https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#enabling-secure-connections-to-clickhouse-server
