### ISSUE TITLE
MySQL and some other engines are not synced to a new replica

### ISSUE THREAD

**Issue by xzy256** [Altinity/clickhouse-operator#1076]
I have 1s-1r clickhouse server, creating Lazy and MySQL database engine and creating some tables. Then i scale up replica(cluster change to 1s-2r), login in new replica client, i find created Lazy and MySQL engine not exist. Why?

clickhouse: 22.3.11.12
operator: v0.18.5

**Comment by Slach** [comment]
unfortunatelly, during scale-up only distributed + replicated merge tree tables synced now
@alex-zaitsev could you confirm this behavior?

**Comment by R-omk** [comment]
Related https://github.com/Altinity/clickhouse-operator/issues/969

**Comment by alex-zaitsev** [comment]
MySQL engine and other engines with parameters can not be created automatically on new replicas. It requires a feature that is only available in ClickHouse 22.12 and above. We will add support in new versions.

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.23.3

**Comment by R-omk** [comment]
@alex-zaitsev 

> Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.23.3



Code 497, Message: clickhouse_operator: Not enough privileges. To execute this query, it's necessary to have the grant NAMED COLLECTION ON ....


operator 0.23.3
ch 23.8.11.28
