### ISSUE TITLE
Understanding CH Replication

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1083]
### infra
- I have replicaCount to 2 in chi CR which create one statefulset per replica.
- To connect to chi cluster i am using loadbalancer exposed k8s service, which connects to both the sts services.

### problem
- If i create a table using the LB svc, table is present on one node and not on other node. Since LB round robins the request to the service. 

### question
- Incase i add another CH node by increasing replicas, how will the data sync between nodes ? 
- Is this in an infra operator issue OR this has to be done on Clickhouse ? ( IMHO as far as i understand this can be only done using replicated merge tree, want to confirm if there is any other way out or i am missing something )

Thanks

**Comment by Slach** [comment]
> If i create a table using the LB svc, table is present on one node and not on other node. Since LB round robins the request to the service.

`clickhouse-server` itself contains two ways for achieve your goals
will work only if you separately install zookeeper\keeper
look https://github.com/Altinity/clickhouse-operator/tree/master/deploy/zookeeper/quick-start-persistent-volume
 and add zookeeper section in spec (look `kubectl explain chi.spec.configuration.zookeeper` for details)

```yaml
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
```

first of all, use Distributed DDL during creation table
`CREATE TABLE db.table ON CLUSTER '{cluster}' .. `
look detalls https://clickhouse.com/docs/en/sql-reference/distributed-ddl/

second way  create database with ENGINE=Replicated like
`CREATE DATABASE db ON CLUSTER '{cluster}' ENGINE=Replicated`
look detalls https://clickhouse.com/docs/en/engines/database-engines/replicated/



> Incase i add another CH node by increasing replicas, how will the data sync between nodes ?

during change cluster layout (change shardsCount or replicaCount)
`clickhouse-operator` will create all engine=Distributed, and dependent object and ReplicatedMergeTree on new node

then `ReplicatedMergeTree` tables will sync data part names from another replicas via ZK
and will fetch it via HTTP protocol over interserver_port (9009) between replicas

> Is this in an infra operator issue OR this has to be done on Clickhouse ? 

it will manage by clickhouse-operator for Distributed, ReplicatedMergeTree tables and dictionaries

if you will use ENGINE=Replicared, it should manage by clickhouse-server itself, but currently it's not clean for me how clickhouse-server will sync metadata schema via ZK, just try and report in this issue
