### ISSUE TITLE
Cannot deploy CR clickhouseinstallations without finalizer

### ISSUE THREAD

**Issue by flant-team-zulu** [Altinity/clickhouse-operator#1088]
I tried to install CR without finalizer but I failed
`
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "stage"
  finalizers: []
`

Operator adds it anyway.

Also I think it may be helpful to have option in CR for finalizer - delete or not underlying PV after CR elimination

**Comment by alex-zaitsev** [comment]
Operator adds finalizer for reason. It is required in order to clean resources properly when CR is deleted.
