### ISSUE TITLE
Error from kustomize cmd on CustomResourceDefinition

### ISSUE THREAD

**Issue by JeromeFroment** [Altinity/clickhouse-operator#1089]
Hello,

While retrieving the template of the last version published on git in order to upgrade my clickhouse manifest files (release v0.20.1), I encountered an error with the kustomize command.

cmd: ``kubectl kustomize ./clickhouse``
tree: 
- clickhouse
  - base
    - clickhouse-operator-install-template.yaml
  - patches
  - secrets
  - kustomization.yml

Log: (can't have a file formated sorry) 
[error_log.txt](https://github.com/Altinity/clickhouse-operator/files/10570618/error_log.txt)

I noticed the presence of special characters that appear after version 0.19.3 (<<). 
Example: 
![image](https://user-images.githubusercontent.com/43061265/216371008-35e7aa45-b0ac-4837-a3ce-56054f1a38ea.png)

By deleting or replacing these characters with a "type" field, the error disappears but the CRD is no longer valid. 
Where do these new characters come from? What is their purpose? And how to make kustomize not crash ? I didn't find anything about this on the web. 

Thank you

**Comment by Slach** [comment]
which version of kubectl do you use?

yaml fragment above is valid and successfully used in production

**Comment by JeromeFroment** [comment]
Here my kubectl version: 
````bash
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
````
And i'm using kustomize supplied with kubectl. I found this to answer your question: 
![image](https://user-images.githubusercontent.com/43061265/216647486-2f71fad2-d643-43ab-8014-45578ad7e588.png)

If I do `kubectl apply clickhouse-manifest.yml` all is working. But with `kubectl kustomize ...` it isn't

**Comment by Slach** [comment]
Ok, did you solve your `kustomize` related issues or just choose another method of templating?

**Comment by JeromeFroment** [comment]
Hello, sorry for the delay. 
Yes I solved my kustomize. I was using kustomize through kubectl and my kubectl version was too old. I simply upgraded kubectl and it worked
