### ISSUE TITLE
clickhouse-keeper: Readiness probe failed: Get "http://10.244.4.12:7000/metrics": EOF

### ISSUE THREAD

**Issue by NicGanon** [Altinity/clickhouse-operator#1090]
clickhouse-keeper version: 22.12.3.5
deploy yaml:  https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml
Environment: AKS

keep failing, it shows Readiness and Livness probe failed when I describe pod 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/5427555/216919054-a88ac7a1-0890-40fc-9ee7-e85b0aee4f4a.png">

when I port forward one pod:7000 to localhost:8999, I visit localhost:8999/metrics, I get error.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/5427555/216920408-3e955642-47a5-4092-b4a5-74b10c586edd.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/5427555/216920658-1e80b30b-633a-487d-97c3-2dd2d5f284c3.png">

seems like it does not work for output metrics on port 7000, what could cause this issue?

keeper config:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/5427555/216921746-c6da9d86-eda1-4db9-ab4e-56d3c01972a3.png">

**Comment by Slach** [comment]
clickhosue-keeper: 22.3.3.44 
 doesn't contains prometheus metrics endpoint
 upgrade clickhouse-keeper to latest version
 
 old version of manifests contains separate container in pod with zookeeper exporter which use mntr command

**Comment by NicGanon** [comment]
@Slach the failed clickhouse-keeper is 22.12.3.5. 
sorry for making you misunderstand, I have a old version 22.3.3.44 is working now, and I want to upgrade to 22.12.3.5, so I deploy 22.12.3.5 in a different namespace to test first but it keeps failing.

**Comment by NicGanon** [comment]
the whole log of one pod:
`++ hostname -s
+ HOST=clickhouse-keeper-0
++ hostname -d
+ DOMAIN=clickhouse-keepers.test-keeper.svc.cluster.local
+ [[ clickhouse-keeper-0 =~ (.*)-([0-9]+)$ ]]
+ NAME=clickhouse-keeper
+ ORD=0
+ export MY_ID=1
+ MY_ID=1
+ mkdir -p /tmp/clickhouse-keeper/config.d/
+ echo '<yandex><keeper_server>'
+ echo '<server_id>1</server_id>'
+ echo '<raft_configuration>'
+ (( i=1 ))
+ (( i<=1 ))
+ echo '<server><id>1</id><hostname>clickhouse-keeper-0.clickhouse-keepers.test-keeper.svc.cluster.local</hostname><port>9444</port></server>'
+ (( i++  ))
+ (( i<=1 ))
+ echo '</raft_configuration>'
+ echo '</keeper_server></yandex>'
+ cat /tmp/clickhouse-keeper/config.d/generated-keeper-settings.xml
<yandex><keeper_server>
<server_id>1</server_id>
<raft_configuration>
<server><id>1</id><hostname>clickhouse-keeper-0.clickhouse-keepers.test-keeper.svc.cluster.local</hostname><port>9444</port></server>
</raft_configuration>
</keeper_server></yandex>
+ clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper_config.xml --force-recovery
Processing configuration file '/etc/clickhouse-keeper/keeper_config.xml'.
Including configuration file '/tmp/clickhouse-keeper/config.d/generated-keeper-settings.xml'.
Couldn't save preprocessed config to /etc/clickhouse-keeper/keeper_config-preprocessed.xml: File is read-only: /etc/clickhouse-keeper/keeper_config-preprocessed.xml
2023.02.06 13:50:28.523797 [ 1 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2023.02.06 13:50:28.541044 [ 1 ] {} <Information> : Starting ClickHouse Keeper 23.1.3.5(revision : 54470, git hash: 548b494bcce13462ab61af6a2cfa6b4ff7eb848a, build id: 93A40A3706E75D58DEBA4B84D77416B4BBF108E6), PID 1
2023.02.06 13:50:28.541067 [ 1 ] {} <Information> Application: starting up
2023.02.06 13:50:28.541073 [ 1 ] {} <Information> Application: OS Name = Linux, OS Version = 5.4.0-1098-azure, OS Architecture = x86_64
2023.02.06 13:50:28.541181 [ 1 ] {} <Debug> Application: Initializing DateLUT.
2023.02.06 13:50:28.541193 [ 1 ] {} <Trace> Application: Initialized DateLUT with time zone 'UTC'.
2023.02.06 13:50:28.541478 [ 1 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2023.02.06 13:50:28.541494 [ 1 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2023.02.06 13:50:28.541573 [ 1 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2023.02.06 13:50:28.541595 [ 1 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2023.02.06 13:50:28.541637 [ 1 ] {} <Debug> KeeperDispatcher: Initializing storage dispatcher
2023.02.06 13:50:28.542591 [ 1 ] {} <Information> KeeperLogStore: force_sync enabled
2023.02.06 13:50:28.542606 [ 1 ] {} <Debug> KeeperDispatcher: Waiting server to initialize
2023.02.06 13:50:28.542611 [ 1 ] {} <Debug> KeeperStateMachine: Totally have 1 snapshots
2023.02.06 13:50:28.542619 [ 1 ] {} <Debug> KeeperStateMachine: Trying to load state machine from snapshot up to log index 89
2023.02.06 13:50:28.543072 [ 1 ] {} <Debug> KeeperStateMachine: Loaded snapshot with last committed log index 89
2023.02.06 13:50:28.543370 [ 1 ] {} <Trace> KeeperLogStore: Totally read from changelog /var/lib/clickhouse-keeper/logs/changelog_1_100000.bin.zstd 89 entries
2023.02.06 13:50:28.543379 [ 1 ] {} <Trace> KeeperLogStore: Continue to write into /var/lib/clickhouse-keeper/logs/changelog_1_100000.bin.zstd
2023.02.06 13:50:28.543402 [ 1 ] {} <Information> KeeperServer: Preprocessing 0 log entries
2023.02.06 13:50:28.543404 [ 1 ] {} <Information> KeeperServer: Preprocessing done
2023.02.06 13:50:28.543410 [ 1 ] {} <Information> KeeperServer: Will use config from log store with log index 89
2023.02.06 13:50:28.543507 [ 1 ] {} <Warning> KeeperServer: This instance is in recovery mode. Until the quorum is restored, no requests should be sent to any of the cluster instances. This instance will start accepting requests only when the recovery is finished.
2023.02.06 13:50:28.543963 [ 1 ] {} <Information> RaftInstance: Raft ASIO listener initiated on :::9444, unsecured
2023.02.06 13:50:28.544011 [ 1 ] {} <Information> KeeperStateManager: Read state from /var/lib/clickhouse-keeper/state
2023.02.06 13:50:28.544029 [ 1 ] {} <Information> RaftInstance: parameters: election timeout range 1000 - 2000, heartbeat 500, leadership expiry 10000, max batch 100, backoff 50, snapshot distance 100000, enable randomized snapshot creation NO, log sync stop gap 99999, reserved logs 100000, client timeout 10000, auto forwarding on, API call type async, custom commit quorum size 1, custom election quorum size 1, snapshot receiver included, leadership transfer wait time 0, grace period of lagging state machine 0, snapshot IO: blocking, parallel log appending: on
2023.02.06 13:50:28.544036 [ 1 ] {} <Information> RaftInstance: new election timeout range: 1000 - 2000
2023.02.06 13:50:28.544045 [ 1 ] {} <Information> RaftInstance:    === INIT RAFT SERVER ===
commit index 89
term 380
election timer allowed
log store start 1, end 89
config log idx 90, prev log idx 0
2023.02.06 13:50:28.544054 [ 1 ] {} <Information> RaftInstance: peer 1: DC ID 0, clickhouse-keeper-0.clickhouse-keepers.test-keeper.svc.cluster.local:9444, voting member, 1
my id: 1, voting_member
num peers: 0
2023.02.06 13:50:28.544058 [ 1 ] {} <Information> RaftInstance: global manager does not exist. will use local thread for commit and append
2023.02.06 13:50:28.544124 [ 1 ] {} <Information> RaftInstance: wait for HB, for 50 + [1000, 2000] ms
2023.02.06 13:50:28.544140 [ 27 ] {} <Information> RaftInstance: bg append_entries thread initiated
2023.02.06 13:50:28.594248 [ 1 ] {} <Debug> KeeperDispatcher: Server initialized, waiting for quorum
2023.02.06 13:50:28.594263 [ 1 ] {} <Information> KeeperDispatcher: Starting Keeper asynchronously, server will accept connections to Keeper when it will be ready
2023.02.06 13:50:28.594364 [ 1 ] {} <Debug> KeeperDispatcher: Dispatcher initialized
2023.02.06 13:50:28.594421 [ 29 ] {} <Information> KeeperDispatcher: Server still not initialized, will not apply configuration until initialization finished
2023.02.06 13:50:28.594610 [ 1 ] {} <Information> Application: Listening for Keeper (tcp): 0.0.0.0:2181
2023.02.06 13:50:28.594665 [ 1 ] {} <Information> Application: Listening for Prometheus: http://0.0.0.0:7000
2023.02.06 13:50:28.594817 [ 1 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 31.92 KiB, peak 31.92 KiB, free memory in arenas 5.01 MiB, will set to 60.64 MiB (RSS), difference: 60.61 MiB
2023.02.06 13:50:28.595994 [ 1 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-keeper/keeper_config.xml'
Processing configuration file '/etc/clickhouse-keeper/keeper_config.xml'.
Including configuration file '/tmp/clickhouse-keeper/config.d/generated-keeper-settings.xml'.
Couldn't save preprocessed config to /etc/clickhouse-keeper/keeper_config-preprocessed.xml: File is read-only: /etc/clickhouse-keeper/keeper_config-preprocessed.xml
2023.02.06 13:50:28.597170 [ 1 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-keeper/keeper_config.xml', performing update on configuration
2023.02.06 13:50:28.597283 [ 1 ] {} <Trace> KeeperDispatcher: Configuration update triggered, but nothing changed for RAFT
2023.02.06 13:50:28.597297 [ 1 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-keeper/keeper_config.xml', performed update on configuration
2023.02.06 13:50:28.597464 [ 1 ] {} <Information> Application: Ready for connections.
2023.02.06 13:50:29.000182 [ 32 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 62.84 MiB, peak 67.83 MiB, free memory in arenas 9.96 MiB, will set to 66.64 MiB (RSS), difference: 3.81 MiB
2023.02.06 13:50:30.058398 [ 22 ] {} <Warning> RaftInstance: Election timeout, initiate leader election
2023.02.06 13:50:30.058427 [ 22 ] {} <Information> RaftInstance: [PRIORITY] decay, target 1 -> 1, mine 1
2023.02.06 13:50:30.058443 [ 22 ] {} <Information> RaftInstance: [ELECTION TIMEOUT] current role: follower, log last term 380, state term 380, target p 1, my p 1, hb dead, pre-vote NOT done
2023.02.06 13:50:30.058452 [ 22 ] {} <Information> RaftInstance: pre-vote term (0) is different, reset it to 380
2023.02.06 13:50:30.062801 [ 22 ] {} <Information> RaftInstance: [VOTE INIT] my id 1, my role candidate, term 381, log idx 89, log term 380, priority (target 1 / mine 1)
2023.02.06 13:50:30.062822 [ 22 ] {} <Information> RaftInstance: number of pending commit elements: 0
2023.02.06 13:50:30.062834 [ 22 ] {} <Information> RaftInstance: state machine commit index 89, precommit index 89, last log index 89
2023.02.06 13:50:30.062848 [ 22 ] {} <Information> RaftInstance: [BECOME LEADER] appended new config at 90
2023.02.06 13:50:30.070095 [ 26 ] {} <Information> RaftInstance: config at index 90 is committed, prev config log idx 90
2023.02.06 13:50:30.070111 [ 26 ] {} <Information> RaftInstance: skipped config 90, latest config 90
2023.02.06 13:50:30.070117 [ 26 ] {} <Information> RaftInstance: new config log idx 90, prev log idx 0, cur config log idx 90, prev log idx 0
2023.02.06 13:50:30.070132 [ 26 ] {} <Information> RaftInstance: new configuration: log idx 90, prev log idx 0
peer 1, DC ID 0, clickhouse-keeper-0.clickhouse-keepers.test-keeper.svc.cluster.local:9444, voting member, 1
my id: 1, leader: 1, term: 381
2023.02.06 13:50:30.070150 [ 26 ] {} <Information> RaftInstance: parameters: election timeout range 1000 - 2000, heartbeat 500, leadership expiry 10000, max batch 100, backoff 50, snapshot distance 100000, enable randomized snapshot creation NO, log sync stop gap 99999, reserved logs 100000, client timeout 10000, auto forwarding on, API call type async, custom commit quorum size 0, custom election quorum size 0, snapshot receiver included, leadership transfer wait time 0, grace period of lagging state machine 0, snapshot IO: blocking, parallel log appending: on
2023.02.06 13:50:30.070168 [ 26 ] {} <Information> RaftInstance: new election timeout range: 1000 - 2000
2023.02.06 13:50:30.070174 [ 26 ] {} <Information> KeeperServer: Recovery is done. You can continue using cluster normally.
2023.02.06 13:50:31.000188 [ 32 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 66.65 MiB, peak 67.83 MiB, free memory in arenas 12.30 MiB, will set to 69.21 MiB (RSS), difference: 2.57 MiB
2023.02.06 13:51:09.000177 [ 32 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 69.21 MiB, peak 69.21 MiB, free memory in arenas 12.30 MiB, will set to 67.92 MiB (RSS), difference: -1.29 MiB
2023.02.06 13:51:15.815767 [ 12 ] {} <Trace> PrometheusHandler-factory: HTTP Request for PrometheusHandler-factory. Method: GET, Address: 10.244.2.7:46038, User-Agent: Prometheus/2.34.0, Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)`

**Comment by Slach** [comment]
Error in implementation of prometheus endpoint for standalone clickhouse-keeper
look details https://github.com/ClickHouse/ClickHouse/issues/46136
