### ISSUE TITLE
no longer needed replace line in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [Altinity/clickhouse-operator#1102]
It seems that `Altinity/clickhouse-operator` at now indirectly depends on newer safe version `v0.5.0` of `golang.org/x/text`.
Keep following replace line in go.mod makes no sense but limits the update of `golang.org/x/text`. Should it be dropped or commented? <br>
<https://github.com/Altinity/clickhouse-operator/blob/master/go.mod#L7>
```txt
replace (
    ...
    golang.org/x/text => golang.org/x/text v0.3.8
)
```
<https://github.com/Altinity/clickhouse-operator/blob/master/go.mod#L85>
```txt
golang.org/x/text v0.5.0 // indirect
```

**Comment by alex-zaitsev** [comment]
@sunsingerus ^

**Comment by sunsingerus** [comment]
explicit `replace` was used to satisfy dependencies version and looks like is not required any more. updated in 0.20.3 version
