### ISSUE TITLE
Clickhouse not working after scaling replica count up then down

### ISSUE THREAD

**Issue by lachiejamesCTC** [Altinity/clickhouse-operator#1103]
I'm running Posthog on EKS via and I recently tried to bump our resource allocations and replica count for Clickhouse to increase performance.

At one point I set `replicasCount: 2` in [values.yaml](https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/values.yaml#L1359), and then later changed it back to `replicasCount: 1`.  Ever since then I've been unable to connect to Clickhouse.

Some things I've noted:
- Since setting `replicasCount: 2`, I now have `chi-posthog-posthog-0-0-0` and `chi-posthog-posthog-0-1-0` pods.  
- When doing a helm upgrade, these pods no longer restart, but all other pods do
- The `chi-posthog-posthog-0-1-0` pod did not go down after applying `replicasCount: 1`.  It's as if my changes aren't being applied to those pods during the deployment
- I can still connect to our DB via the Clickhouse client and run queries
- This query works `SELECT count(*) FROM events`, but this query hangs indefinitely `SELECT toStartOfWeek(timestamp) as week, count(*) FROM events WHERE person_properties = ''`

Also seeing many error logs from the `chi-posthog-posthog-0-0-0` pod stating 'DB::Exception: No active replica has part xxxxxx'

```
2023.02.10 15:31:26.451403 [ 16 ] {} <Information> posthog.sharded_session_recording_events: No active replica has part 20230209_8248_8252_1. Will fetch merged part instead.
2023.02.10 15:31:26.451432 [ 16 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts for merge 202302_86961_87086_25; will try to fetch it instead
2023.02.10 15:31:26.451459 [ 163 ] {} <Warning> posthog.person (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part all_72075_72165_18 or covering part.
2023.02.10 15:31:26.451543 [ 24 ] {} <Information> posthog.sharded_session_recording_events: No active replica has part 20230209_8365_8369_1. Will fetch merged part instead.
2023.02.10 15:31:26.451569 [ 24 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts for merge 202302_86961_87031_14; will try to fetch it instead
2023.02.10 15:31:26.451731 [ 45 ] {} <Information> posthog.person: DB::Exception: No active replica has part all_72201_72201_0 or covering part
2023.02.10 15:31:26.451798 [ 141 ] {} <Warning> posthog.sharded_session_recording_events (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 20230209_8382_8382_0 or covering part.
2023.02.10 15:31:26.452263 [ 54 ] {} <Information> MergeFromLogEntryTask: DB::Exception: No active replica has part all_72075_72200_25 or covering part
```

So it seems like we still have all of our data, but there is some kind of connection issue now as a result of the replicasCount change.

I haven't managed to find a single thread or Github issue that describes this problem, and Posthog just [dropped support for self-hosted Kubernetes](https://posthog.com/blog/sunsetting-helm-support-posthog), so any hints would be much appreciated 😅

**Comment by alex-zaitsev** [comment]
Hi @lachiejamesCTC , could you check what version of clickhouse-operator are you using? Maybe something is wrong with a Helm chart provided by Posthog.

You can try scaling it down manually in ClickHouseInstallation. Try this:
```kubectl get chi -n <your_namespace>```

I think you will see 'posthog' ClickHouseInstallation.

Then  dump contents:

```kubectl get chi posthog -n <your_namespace> -o yaml```

Check number of replicas here. If it is 2, then scale it down to 1 (edit the manifest and re-apply).
