### ISSUE TITLE
Can multiple storageclassname be added in the volumeclaimtemplates 

### ISSUE THREAD

**Issue by sivasarathchandra** [Altinity/clickhouse-operator#1107]
Can a different storageclassname be added in the volumeclaimtemplate for data-volume and log-volume?

**Comment by Slach** [comment]
as author you can post comment to cllosed issues on github

this restriction from PersistentVolumeClaim specification
`storageClassName` have string type
look 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
for details
