### ISSUE TITLE
any specific reason @Slach for not setting up two storageclassname in the volumeclaimtemplates in clickhouse chi?

### ISSUE THREAD

**Issue by sivasarathchandra** [Altinity/clickhouse-operator#1108]
any specific reason @Slach for not setting up two storageclassname in the volumeclaimtemplates in clickhouse chi?

_Originally posted by @sivasarathchandra in https://github.com/Altinity/clickhouse-operator/issues/1107#issuecomment-1430115848_

**Comment by Slach** [comment]
as author you can post comment to cllosed issues on github

this restriction from PersistentVolumeClaim specification
`storageClassName` have string type
look 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
for details
