### ISSUE TITLE
zookeeper liveness and readiness probe may ocassionally fail

### ISSUE THREAD

**Issue by cangyin** [Altinity/clickhouse-operator#1112]
execute this script in a healthy zookeeper pod:

```sh
hit=0 miss=0;
for i in $(seq 1 10000); do
    OK=$(echo ruok | nc 127.0.0.1 2181);
    [ -z "$OK" ] && { ((hit++)); continue; };
    ((miss++)) ;
done

echo $hit $miss
```

result:
```
4 9996
```
there can be worse cases where `miss` is high.

**Comment by cangyin** [comment]
solution may be: `echo ruok | nc -q 1 127.0.0.1 2181`

**Comment by Slach** [comment]
already fixed in 0.21.0 release
https://github.com/Altinity/clickhouse-operator/blob/0.21.0/deploy/zookeeper/quick-start-persistent-volume/zookeeper-1-node.yaml#L222-L227

**Comment by cangyin** [comment]
is `tee` more reliable than `cat` ?

**Comment by Slach** [comment]
it doesn't matter IMHO, you can use `cat` if you want, main reason is replace `nc` to something better
