### ISSUE TITLE
Not found backup engine S3

### ISSUE THREAD

**Issue by Drabuna** [Altinity/clickhouse-operator#1125]
Hi!

Running the latest version of helm chart `0.20.3`.

Trying to restore a database from a backup previously made by a different clickhouse instance via `BACKUP TABLE ... TO S3(...)`

The query looks like the one documented [here](https://clickhouse.com/docs/en/operations/backup/#restore-from-the-incremental-backup):

```
RESTORE DATABASE stats AS stats FROM S3('s3path', 's3keyid', 's3secret')
```

And I get an error:

```
Code: 627. DB::Exception: Not found backup engine S3. (BACKUP_ENGINE_NOT_FOUND) (version 22.9.7.34 (official build))
```

Any ideas on how to fix this or what I am doing wrong?

**Comment by Slach** [comment]
Question is not related to clickhouse-operator itself
try `clickhouse/clickhouse-server:23.1` image for support S3 backup engine

all https://clickhouse.com/docs documentations always generated from `master` branch and could contains features which not supported in older versions
