### ISSUE TITLE
Support configurable settings for logger for the CH instance

### ISSUE THREAD

**Issue by patrickdung** [Altinity/clickhouse-operator#1129]
Specific parameters for logger

    ```<size>1000M</size>
    <count>10</count>```

It seems this setting is not configurable in the operator.

**Comment by alex-zaitsev** [comment]
spec:
  configuration:
     logger/size: "1000M"
     logger/count: 10

**Comment by patrickdung** [comment]
@alex-zaitsev 

I think it should work
```
clickhouse@chi-clickhouse-installation1-cluster1-0-0-0:/etc/clickhouse-server$ cat config.d/..2023_03_13_16_59_11.2987786511/chop-generated-settings.xml
<yandex>
    <logger>
        <count>3</count>
        <level>information</level>
        <size>100M</size>
    </logger>
</yandex>
```

But before asking this question:
a) I had searched `logger` in this GitHub repo
b) I did not seems to find a direct example or documentation about this in
https://kb.altinity.com/altinity-kb-setup-and-maintenance/logging/
or 
https://docs.altinity.com/

Maybe I had missed this information somewhere.
Thanks for the help.

**Comment by Slach** [comment]
any clickhouse-server settings could be defined via chi.spec.configuration.settings or chi.spec.configuration.files
https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationsettings
