### ISSUE TITLE
clickhouse v22.33 update to v23.2, One of the machines cpu load goes up high

### ISSUE THREAD

**Issue by Caius1L** [Altinity/clickhouse-operator#1133]
The clickhouse cluster in our team has three shards. when upgraded all three machines from 22.33 to 23.2, but we found that the CPU of one of them increased, even if we stopped data writing, We also found that another shard has been distributing write requests to it, what is the reason?other two shard is ok

**Comment by Slach** [comment]
question is not related to clickhouse-operator itself

look to
`system.processes`
`system.distributed_queue`
and
`system.merges`

tables on high CPU replica

an read
https://kb.altinity.com/altinity-kb-setup-and-maintenance/who-ate-my-cpu/
https://kb.altinity.com/altinity-kb-setup-and-maintenance/high-cpu-usage/
