### ISSUE TITLE
Help！ How can I get the clickhouse-operator match the clickhouse version

### ISSUE THREAD

**Issue by lhcg** [Altinity/clickhouse-operator#1135]
I user clickhouse-operator-install-bundle.yaml get 
"image": "clickhouse/clickhouse-server:22.3"
Can I use the 22.8 version?

**Comment by Slach** [comment]
bundle.yaml contains only confirMap with 001-templates.json.example
which not affect anything

defaultClickHouseDockerImage =  "clickhouse/clickhouse-server:latest"

so if you create `kind: ClickHouseInstallation` resource without define image in spec.templates.podTemplates
operator will use clickhouse/clickhouse-server:latest

look https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-01-pod-template.yaml#L32
and try to figure out how to define custom image inside your clusters
