### ISSUE TITLE
CRD's "OutOfSync" after installing via ArgoCD

### ISSUE THREAD

**Issue by dbackeus** [Altinity/clickhouse-operator#1137]
When installing the operator (either via the bundle or Helm chart) using [ArgoCD](https://argo-cd.readthedocs.io/) the CRD's will end up in "OutOfSync" state due to Kubernetes implicitly removing some `priority: 0` entries from the resources, causing the state inside Kubernetes to differentiate with the state of the original manifests. Eg:

<img width="1316" alt="Screenshot 2023-03-29 at 11 44 32" src="https://user-images.githubusercontent.com/3461/228494945-39ade32d-7067-46f3-a580-69feafff160c.png">

Removing all superfluous `priority: 0` entries would solve this issue.

**Comment by Slach** [comment]
which clickhouse-operator CRD version did you try to install?

**Comment by dbackeus** [comment]
The latest one: 0.20.3.

Here's a github search to highlight the problematic entries existing in this repo at the moment: https://github.com/search?q=repo%3AAltinity%2Fclickhouse-operator%20%22priority%3A%200%22&type=code

**Comment by Slach** [comment]
priority: 0 was present in CRD from 0.16.0 
looks like something was wrong with your ArgoCD

**Comment by dbackeus** [comment]
@Slach you're misinterpreting what's happening here. The problem is that the entries exist, not that they don't exist. The kubernetes API will implicitly remove these entries when applying the manifests which causes the diff.

**Comment by Slach** [comment]
which kubernetes version do you use?

**Comment by dbackeus** [comment]
1.26.1 but I believe we saw the same diff using 1.24.x as well.

**Comment by amadrizwan** [comment]
We have been dealing with the same issue. argoCD application is out of sync because kubernetes implicitly removes `priority=0` entries thus creating a diff. Would be great to have the CRD fixed.

**Comment by dbackeus** [comment]
Thank for attending to this. I'll try out the update as soon as 0.21.0 is released on the Helm repository.

**Comment by zakariais** [comment]
We are also having the same issue.

**Comment by AurimasNav** [comment]
Same here, AKS 1.26.3

**Comment by Slach** [comment]
@zakariais @AurimasNav try 0.21.0 branch (unreleased yet)

**Comment by AurimasNav** [comment]
I can confirm that with 0.21.0 branch CRDs are not OutOfSync.
