### ISSUE TITLE
operatorhub only offers old version

### ISSUE THREAD

**Issue by ibotty** [Altinity/clickhouse-operator#1143]
As of today https://operatorhub.io/operator/clickhouse only offers 0.18.3, but the current release is 0.20.3.  Can you update the operator on operatorhub?

**Comment by alex-zaitsev** [comment]
@ibotty , we are working on that. OperatorHub is somewhat slow accepting new releases

**Comment by ibotty** [comment]
A few days ago 0.20.1 was accepted which is still very old:
 https://github.com/k8s-operatorhub/community-operators/pull/2800
 
Is there anything I can do to speed it up?

**Comment by Slach** [comment]
@ibotty @sunsingerus  will work on it on the next week

**Comment by sunsingerus** [comment]
operatorhub is up-to-date, latest release in 0.21.1
