### ISSUE TITLE
Config max_memory_usage value of clickhouse

### ISSUE THREAD

**Issue by Jason666LIU** [Altinity/clickhouse-operator#1144]
I deployed altinity clickhouse-operator 0.20.3 on my local kubernetes cluster following by altinity official deploy instuction. Because of the huge data I stored (about 15 billion records) in clickhouse, I need to change users.xml config file parameter max_memory_usage for making group by query doesn't raise MEMORY_LIMIT_EXCEEDED error.

How could I change this value while deploying clickhouse cluster?

I added some config into chi resource like below.
```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      ...
  creationTimestamp: "2023-04-10T08:56:39Z"
  finalizers:
  - finalizer.clickhouseinstallation.altinity.com
  generation: 10
  name: ch-cluster
  namespace: clickhouse
  resourceVersion: "27275038"
  uid: 2506b554-6eda-4826-a03c-234faf9fd737
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 5
      name: ch-cluster
      templates:
        podTemplate: clickhouse-stable
        volumeClaimTemplate: storage-vc-template
    profiles:
      default/max_memory_usage: "100000000000"
      default/max_memory_usage_for_user: "100000000000"
      max_bytes_before_external_group_by: "100000000000"
      readonly/readonly: "1"
      use_uncompressed_cache: 0
```
After that the max_memory_usage value is still 10Gi as before, I checked it in the pods.

Please help me about how to config the value in ClickHouseInstallation yaml. Or is there anothor way to make it work?

**Comment by Slach** [comment]
could you share
```
kubectl exec -n clickhouse chi-ch-cluster-ch-cluster-0-0-0 -- grep -r max_memory_usage /etc/clickhouse-server/
```

**Comment by Jason666LIU** [comment]
@Slach Sure. 
```
/etc/clickhouse-server/users.d/..2023_04_17_07_56_15.5992817/chop-generated-profiles.xml:            <max_memory_usage>100000000000</max_memory_usage>
/etc/clickhouse-server/users.d/..2023_04_17_07_56_15.5992817/chop-generated-profiles.xml:            <max_memory_usage_for_user>100000000000</max_memory_usage_for_user>
/etc/clickhouse-server/users.xml:            <max_memory_usage>10000000000</max_memory_usage>
```

**Comment by Slach** [comment]
Check
`kubectl exec -n clickhouse chi-ch-cluster-ch-cluster-0-0-0 -- clickhouse-client -q "SELECT * FROM system.settings WHERE name='max_memory_usage' FORMAT Vertical"`

**Comment by Slach** [comment]
@Jason666LIU is setting changed?

**Comment by Jason666LIU** [comment]
@Slach I added "default/" before max_bytes_before_external_group_by of my chi config, I just found the limit just expand to 100G. And I check the value via the second command you mentioned, it's 100G, it is do changed. Thanks Slash!
