### ISSUE TITLE
Comparison DateTime64 to DateTime / Date

### ISSUE THREAD

**Issue by YudGuo** [Altinity/clickhouse-operator#1150]
like the issues https://github.com/ClickHouse/ClickHouse/issues/11222
I find the issues is fixed:  https://github.com/ClickHouse/ClickHouse/pull/18050
However, my Clickhouse did not work. I can't select yesterday's data with Metabase
my Clikchouse version is ![image](https://user-images.githubusercontent.com/32190849/236613863-14ac94b9-c7c1-44f8-9055-7105edb98b69.png)

**Comment by YudGuo** [comment]
:) show create table test.test_data_day
CREATE TABLE test.test_data_day
(
    `Timestamp` DateTime64(3,
 'Asia/Shanghai'),
    `FromChatRoom` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(Timestamp)
ORDER BY Timestamp
SETTINGS index_granularity = 8192';

:) SELECT toDateTime(now(), 'Asia/Shanghai')
2023-05-06 17:04:23.000 +0800

working  with toDateTime(now())
:) SELECT `Timestamp` AS `Timestamp`  FROM `test`.`test_data_day` WHERE  `Timestamp` < toDateTime(now(), 'Asia/Shanghai') order by `Timestamp`  DESC LIMIT 3

Timestamp
2023-05-06 17:03:08.551 +0800
2023-05-06 17:03:08.000 +0800
2023-05-06 17:03:07.567 +0800

not work with toDate(now())
:) SELECT `Timestamp` AS `Timestamp`  FROM `test`.`test_data_day` WHERE  `Timestamp` < toDate(now(), 'Asia/Shanghai') order by `Timestamp`  DESC LIMIT 3

working with toDate(`Timestamp`)
:)SELECT `Timestamp` AS `Timestamp`  FROM `test`.`test_data_day` WHERE  toDate(`Timestamp`) < toDate(now(), 'Asia/Shanghai') order by `Timestamp`  DESC LIMIT 3
2023-05-05 23:59:59.999 +0800
2023-05-05 23:59:59.330 +0800
2023-05-05 23:59:59.093 +0800

working 
SELECT `Timestamp` FROM `test`.`test_data_day` WHERE `Timestamp` >= toDate((CAST(now() AS timestamp) + INTERVAL -1 day),'Asia/Shanghai')  ORDER BY `Timestamp`  LIMIT 3
Timestamp
2023-05-05 00:00:00.131 +0800
2023-05-05 00:00:00.216 +0800
2023-05-05 00:00:00.381 +0800

**Comment by Slach** [comment]
issue is not related to clickhouse-operator
upgrade your clickhouse-server version
21.8 is outdated

**Comment by YudGuo** [comment]
thanks,I will upgrade my clickhouse-server version
