### ISSUE TITLE
Is there any out-of-box GUI tools for clickhouse-operator

### ISSUE THREAD

**Issue by Alex-Cheng** [Altinity/clickhouse-operator#1154]
My understanding is that clickhouse-operator is a k8s-based tool which provides command-line way to manipulate ClickHouse cluster. I am wondering that whether there is an out-of-box GUI tools.

Thank you.

**Comment by Slach** [comment]
look to https://github.com/Altinity/altinity-dashboard

**Comment by Slach** [comment]
also we provide more advanced version UI for manage kubernetes

look to https://altinity.com/altinity-cloud-anywhere/

**Comment by Alex-Cheng** [comment]
> also we provide more advanced version UI for manage kubernetes
> 
> look to https://altinity.com/altinity-cloud-anywhere/

It seems that the software is not open-source, is it right?

**Comment by Alex-Cheng** [comment]
> look to https://github.com/Altinity/altinity-dashboard

Is there any way to experience it without having to install it myself?

**Comment by Slach** [comment]
> > also we provide more advanced version UI for manage kubernetes
> > look to https://altinity.com/altinity-cloud-anywhere/
> 
> It seems that the software is not open-source, is it right?

Yes, this is our commercial product

**Comment by Slach** [comment]
> > look to https://github.com/Altinity/altinity-dashboard
> 
> Is there any way to experience it without having to install it myself?

Open-source products usually assume you have enough qualification to install a dashboard inside your exists Kubernetes cluster

**Comment by Alex-Cheng** [comment]
Can I have a trial on altinity-dashboard and clickhouse-operator? After evaluation we can decide whether to buy the product.

**Comment by Slach** [comment]
Just start managed clickhouse + Altinity Cloud Manager UI
https://altinity.com/altinity-cloud-test-drive/

after it, you could decide use Altinity Cloud Anywhere if you prefer manager clickhouse clusters inside your Kubernetes infrastructure
