### ISSUE TITLE
[zoomkeeper] when install the zookeeper some error occur

### ISSUE THREAD

**Issue by HaoJianguang** [Altinity/clickhouse-operator#1173]
when execute the command 'kubectl apply -f 05-stateful-set.yaml -n zoons'
some error occur"

chown: changing ownership of '/conf/configuration.xsl': Operation not permitted
failed to change ownership of '/conf/configuration.xsl' from 501 to zookeeper
chown: changing ownership of '/conf/logback.xml': Operation not permitted
chown: changing ownership of '/conf/zoo_sample.cfg': Operation not permitted
failed to change ownership of '/conf/logback.xml' from 501 to zookeeper
failed to change ownership of '/conf/zoo_sample.cfg' from 501 to zookeeper

I investigate the problem, l think it cause by the images 'docker.io/zookeeper:3.8.1' when create the container use 'zookeeper' as user to login, but the files belong to user 501, zookeeper don't have authority to change the onwer from 501 to zookeeper. 

Do you have any method to resolve this issue and use the image

**Comment by Slach** [comment]
try to apply fixed manifest without unnecessary chown from
https://github.com/Altinity/clickhouse-operator/tree/0.21.2/deploy/zookeeper/quick-start-persistent-volume
