### ISSUE TITLE
Replicated table : TABLE_ALREADY_EXISTS

### ISSUE THREAD

**Issue by jdalia001** [Altinity/clickhouse-operator#1175]
Hello,

I installed altinity clickhouse cluster on my kubernetes cluster, it looks to works but I have a problem when trying to create a replicated table.

I create a database on cluster with this command : 
`CREATE DATABASE logs ON CLUSTER clickhouse;
`_This command worked, and I can see the new db in every nodes (So, that's sound the cluster connection is working)._

But, when I try to create a table inside the new database, there is a problem, my creation command is : 
```
CREATE TABLE requests ON CLUSTER clickhouse(
    date Date,
    hour UInt8,
    site String,
    country String,
    device_type String,
    total_requests Int32
) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/1/logs/requests', '3', (total_requests))
PARTITION BY date
ORDER BY (date, hour, site);
```

After the execution, the table has been created on the node where I execute it, but not on other nodes and I got this error message : 
`ERROR: DB::Exception: There was an error on [chi-clickhouse-clickhouse-0-0:8122]: Code: 57. DB::Exception: Table logs.requests already exists. (TABLE_ALREADY_EXISTS) (version 22.8.13.21.altinitystable (altinity build))`

And it is the same if I try on it from another node, do you think it can be a problem of zookeeper ? 

Thanks

**Comment by Slach** [comment]
try 
```sql
DROP TABLE IF EXISTS requests  ON CLUSTER '{cluster}' NO DELAY; // NO DELAY required for delete in Atomic database engine
CREATE TABLE requests ON CLUSTER clickhouse(
    date Date,
    hour UInt8,
    site String,
    country String,
    device_type String,
    total_requests Int32
) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/1/logs/requests', '3', (total_requests))
PARTITION BY toYYYYMM(date)
ORDER BY (date, hour, site);

**Comment by jdalia001** [comment]
Thank you for your reply.
The DROP command is well working but the Create table still return me the same error : 

`Query 1 ERROR: DB::Exception: There was an error on [chi-clickhouse-clickhouse-0-2:8122]: Code: 253. DB::Exception: Replica /clickhouse/tables/1/requests/requests/replicas/3 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.8.13.21.altinitystable (altinity build))`

**Comment by jdalia001** [comment]
In addition, I executed the command from the node 2, and the tables has been created only on the node 1... that's really strange..

**Comment by Slach** [comment]
run DROP TABLE IF EXISTS .. NO DELAY again

change
`ReplicatedSummingMergeTree('/clickhouse/tables/1/logs/requests', '3', (total_requests))`

to 
`ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}', (total_requests))`

**Comment by jdalia001** [comment]
It works! Thanks very much!
Can I know why ?

**Comment by Slach** [comment]
Static `replica_name` parameter in `ReplicatedMergeTree`, looks like you mislead it with replicas count

look https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#replicatedmergetree-parameters
