### ISSUE TITLE
bootstrap of cluster (IE addition of new node, not change to old one) should be parallel "unconditionally"

### ISSUE THREAD

**Issue by UnamedRus** [Altinity/clickhouse-operator#1186]
Extension of https://github.com/Altinity/clickhouse-operator/pull/1124

But for specific case, when we add new nodes (or start cluster from 0), not change old one.
For that particular case, sequential start for first shard can be unneeded, plus "Max percentage of the cluster's shards that may be reconciled concurrently (up to X% shards in parallel)" can be ignored.

**Comment by alex-zaitsev** [comment]
It works this way since 0.22.0. Here is 4 shard cluster

```
I0214 06:06:40.821117       1 worker.go:1548] createStatefulSet():Create StatefulSet eu/chi-test-4-test-4-1-0 - started
I0214 06:06:41.021358       1 worker.go:1548] createStatefulSet():Create StatefulSet eu/chi-test-4-test-4-3-0 - started
I0214 06:06:41.221569       1 worker.go:1548] createStatefulSet():Create StatefulSet eu/chi-test-4-test-4-2-0 - started
I0214 06:06:41.425166       1 worker.go:1548] createStatefulSet():Create StatefulSet eu/chi-test-4-test-4-0-0 - started
```
