### ISSUE TITLE
system db can not be seen through DBeaver Client with default user logged

### ISSUE THREAD

**Issue by the-elder** [Altinity/clickhouse-operator#1191]
all dbs can be seen through clickhouse-client in pod:

![image](https://github.com/Altinity/clickhouse-operator/assets/28731366/85ef7c58-abff-42dd-aabe-3c3abc87167b)

but i cannot see anything other than the default database when logging in to ClickHouse through the DBeaver client:
![image](https://github.com/Altinity/clickhouse-operator/assets/28731366/fd973ea8-4182-4b5a-9ac7-1f0149b0db68)

I don't know if that's a limitation

**Comment by Slach** [comment]
This is not `clickhouse-operator` limitation

![image](https://github.com/Altinity/clickhouse-operator/assets/105560/9f5d94f8-c156-4f1a-a3d1-7e503a69d4aa)
![image](https://github.com/Altinity/clickhouse-operator/assets/105560/0c595675-6703-4c37-ae1e-2718ac58f45f)
![image](https://github.com/Altinity/clickhouse-operator/assets/105560/a423a278-8d68-4ccb-a806-445850429f68)
