### ISSUE TITLE
Security Hardening Tag Mismatch

### ISSUE THREAD

**Issue by JustinMason** [Altinity/clickhouse-operator#1195]
This documentation has invalid XML.
https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md?plain=1#L328-L341
```
<clickhouse>
   <openSSL> .......
   </clickhouse>
</openSSL>
```

**Comment by Slach** [comment]
Thank you kindly for reporting, will fix on 0.21.3 operator release
