### ISSUE TITLE
How to increase pollStatefulSet's wait timeout

### ISSUE THREAD

**Issue by lazywei** [Altinity/clickhouse-operator#1196]
_I did a quick search but didn't find it in issues or codebase, if there is already such feature we would greatly appreciate._

We're getting this error when the operator is running the reconcilation. I think this is due to the fact that our CH will take a long time to be ready (we are checking against the `/replicas_status` for the readiness probe. This (long CH startup time) is a known issue for us. We've configured the k8s probes' thresholds to accommodate this.

However, it seems the operator itself also has a timeout regardless the probes' settings. It seems after around 5 minutes, if the pod is still not in the ready state, the operator will abort and terminate the pod. And it will also mark `reconcile completed unsuccessfully`

**My question is**: is it possible to configure this timeout so the operator can wait however long we want it to wait? 

Attach is the error log from the operator pod:
```
I0717 22:26:10.909201       1 poller.go:245] pollStatefulSet():clickhouse/chi-ed-v0-default-0-0:%s/%s - TIMEOUT reached
E0717 22:26:10.909254       1 creator.go:118] updateStatefulSet():StatefulSet update wait failed. err: waitStatefulSet(clickhouse/chi-ed-v0-default-0-0) - wait timeout
I0717 22:26:10.909285       1 creator.go:237] onStatefulSetUpdateFailed():going to ROLLBACK FAILED StatefulSet clickhouse/chi-ed-v0-default-0-0
I0717 22:26:10.934760       1 deleter.go:97] Delete Pod clickhouse/chi-ed-v0-default-0-0-0
E0717 22:26:10.938690       1 deleter.go:105] statefulSetDeletePod():FAIL delete Pod clickhouse/chi-ed-v0-default-0-0-0 err:pods "chi-ed-v0-default-0-0-0" is forbidden: User "system:serviceaccount:kube-system:clickhouse-operator-altinity-clickhouse-operator" cannot delete resource "pods" in API group "" in the namespace "clickhouse"
I0717 22:26:10.938727       1 worker.go:1458] Got abort. Abort
E0717 22:26:10.938816       1 worker-reconciler.go:735] reconcileStatefulSet():FAILED to reconcile StatefulSet: chi-ed-v0-default-0-0 CHI: ed-v0 
I0717 22:26:11.006831       1 creator.go:58] CreateServiceCHI():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:clickhouse/ch-ed-v0
I0717 22:26:11.007190       1 worker.go:1164] updateService():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:reuse Port 9000 values
I0717 22:26:11.007250       1 worker.go:1164] updateService():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:reuse Port 8123 values
I0717 22:26:11.020461       1 worker.go:1201] updateService():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:Update Service clickhouse/ch-ed-v0
E0717 22:26:11.145853       1 worker-reconciler.go:91] reconcileCHI():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:FAILED to update err: crud error - should abort
I0717 22:26:12.541686       1 worker.go:657] markReconcileComplete():clickhouse/ed-v0/0ccb6da7-a924-497b-a901-be07aa8a5eb8:reconcile completed unsuccessfully, task id: 0ccb6da7-a924-497b-a901-be07aa8a5eb8
```

<img width="1344" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/2840571/56635227-afb3-4791-b039-987caa76a078">

**Comment by Slach** [comment]
root reason is not timeout
root reason is access forbidden
```
statefulSetDeletePod():FAIL delete Pod clickhouse/chi-ed-v0-default-0-0-0 err:pods "chi-ed-v0-default-0-0-0" is forbidden: User "system:serviceaccount:kube-system:clickhouse-operator-altinity-clickhouse-operator" cannot delete resource "pods" in API group "" in the namespace "clickhouse"
```

**Comment by Slach** [comment]
timeout reached because accessforbidden


how did you install clickhouse-operator?
did yuo upgrade ClusterRoleBindings for clickhouse-operator service account?

**Comment by Slach** [comment]
for properly upgrade helm chart you need to install CRDS separatelly, we will try to fix it by add CRDs to `crds` folder and to `templates` folder in the next Helm Chart release

could you share
`kubectl get clusterrole  clickhouse-operator-altinity-clickhouse-operator -o yaml` ?

**Comment by Slach** [comment]
CRDS already added to crds folder
you could manually upgrade crds from https://github.com/Altinity/clickhouse-operator/tree/master/deploy/helm/crds

according to
https://github.com/Altinity/clickhouse-operator/blob/0.21.3/deploy/operator/clickhouse-operator-install-bundle.yaml#L2770-L2777

need to figure out when and why `statefulSetDeletePod` executed, and what exactly it do

**Comment by sunsingerus** [comment]
`statefulSetDeletePod` is executed in case updated StatefulSet is not in 'Ready' after `reconcile.statefulSet.update.timeout` seconds and `onFailure` is set to `rollback`. So operator tries to rollback StatefulSet to previous generation and tries to help StatefulSet by deleting current pod (which is considered to be broken). Unfortunately, RBAC has no `delete` allowed for pods. Right now I've added `delete` permission, but we may want to review the whole process of `rollback`.

**Comment by OodounaikingoO** [comment]
> `statefulSetDeletePod` is executed in case updated StatefulSet is not in 'Ready' after `reconcile.statefulSet.update.timeout` seconds and `onFailure` is set to `rollback`. So operator tries to rollback StatefulSet to previous generation and tries to help StatefulSet by deleting current pod (which is considered to be broken). Unfortunately, RBAC has no `delete` allowed for pods. Right now I've added `delete` permission, but we may want to review the whole process of `rollback`.

Hey, we got the same problem as StatefulSet is not in 'Ready' after reconcile.statefulSet.update.timeout seconds(but sometime not happen), did u know why it happened or what is the relevance of this problem?

**Comment by alex-zaitsev** [comment]
@OodounaikingoO , could be different reasons for that, e.g. ClickHouse starts too long. In this case, you need to add a startup probe to podTemplate. Maybe we can add a syntactic sugar for that at some point.
