### ISSUE TITLE
Operator restarting replica 1 too soon after replica 0 causing distributed queries to fail

### ISSUE THREAD

**Issue by aaron276h** [Altinity/clickhouse-operator#1197]
When running our data cluster with a RF=2 we have observed that during cluster restarts, distributed queries to the cluster temporarily fail after the replica 0 has finished restarting and when replica 1 begins to restart. 

The specific errors we get are:
```
Code: 198. DB::Exception: Not found address of host: chi-replica-1. (DNS_ERROR) (version 23.3.2.37 (official build))
```

We performed local testing by building in a temporary buffer period before replica 1 is restarted, and the connection errors went away.

**Comment by alex-zaitsev** [comment]
@aaron276h , what is an operator version?

The restart is happening with a following logic:
1. Exclude not from load balancer
2. Remove from remote servers if this does not reduce the number of shards
3. Wait for all active queries to complete (5 minutes)
4. Terminate gracefuly

You may also increase the termination period if default is not sufficient:
https://github.com/Altinity/clickhouse-operator/blob/master/config/config.yaml#L278
