### ISSUE TITLE
Helm Upgrade to latest operator breaking change

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1198]
- We recently upgraded the operator to use [helm installation for deployment of the operator](https://github.com/Altinity/clickhouse-operator/tree/master/deploy/helm), prior to this we had installed the operator using quickstart manifest . 
- The existing Clickhouse clusters are not being able to reconcile due to this error
```
E0719 11:58:40.792938       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseInstallation: failed to list *v1.ClickHouseInstallation: v1.ClickHouseInstallationList.Items: []v1.ClickHouseInstallation: v1.ClickHouseInstallation.Status: v1.ChiStatus.NormalizedCHI: v1.ClickHouseInstallation.Spec: v1.ChiSpec.Configuration: v1.Configuration.Clusters: []*v1.Cluster: v1.Cluster.Layout: v1.ChiClusterLayout.Replicas: []v1.ChiReplica: v1.ChiReplica.Hosts: []*v1.ChiHost: v1.ChiHost.Secure: ReadString: expects " or n, but found t, error found in #10 byte of ...|"secure":true,"tcpPo|..., bigger context ...|"interserverHTTPPort":9010,"name":"0-0","secure":true,"tcpPort":9440,"templates":{"hostTemplate":"ho|...
```

- For new clickhouse cluster we had to add quotes to ```templates.hostTemplates[0].name.spec.secure``` to ```"true"``` to get it working. 

- For the existing clusters we did add to true ```templates.hostTemplates[0].name.spec.secure``` to ```"true"``` seems like the operator is calculating the status and is getting this error. Can we recreate the status object ?

**Comment by Slach** [comment]
please look to 
https://github.com/Altinity/clickhouse-operator/blob/0.21.3/deploy/helm/Chart.yaml#L9-L11

we will try to fix it in next chart release

**Comment by Slach** [comment]
@AdheipSingh could you confirm upgrade CRDs manually help?

**Comment by AdheipSingh** [comment]
no still facing the issue. 
running image 0.21.3

Let me downgrade the operator version and check ( i faced it 0.21.2 ) also

**Comment by AdheipSingh** [comment]
@Slach i downgraded to 0.19.1 to get it working. 
Also if you upgrade operator using ```helm``` the crd will need to have annotations and labels specific to helm. 
So doing apply on the CRD make it a re-do.

**Comment by AdheipSingh** [comment]
@Slach will a release fix this ?

**Comment by Slach** [comment]
@AdheipSingh 
helm can't fix it
you need manual upgrade crds before upgrade helm chart, this is standard
we will try to create separate helm chart `altinity-clickhouse-operator-crds` but it require a time to understanding how to to it with our current CI/CD

**Comment by AdheipSingh** [comment]
@Slach got it. Thanks for your response.

BTW i had to get the latest CRD working with v0.19 , v0.21.x did not work. 

Got this error
```
E0719 11:58:40.792938       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseInstallation: failed to list *v1.ClickHouseInstallation: v1.ClickHouseInstallationList.Items: []v1.ClickHouseInstallation: v1.ClickHouseInstallation.Status: v1.ChiStatus.NormalizedCHI: v1.ClickHouseInstallation.Spec: v1.ChiSpec.Configuration: v1.Configuration.Clusters: []*v1.Cluster: v1.Cluster.Layout: v1.ChiClusterLayout.Replicas: []v1.ChiReplica: v1.ChiReplica.Hosts: []*v1.ChiHost: v1.ChiHost.Secure: ReadString: expects " or n, but found t, error found in #10 byte of ...|"secure":true,"tcpPo|..., bigger context ...|"interserverHTTPPort":9010,"name":"0-0","secure":true,"tcpPort":9440,"templates":{"hostTemplate":"ho|...

```
