### ISSUE TITLE
curl xxx:8888/metrics when hangs

### ISSUE THREAD

**Issue by xingyunyang01** [Altinity/clickhouse-operator#1205]
My environment has 37 instances right now, looking at the logs of metrics-exporter, there are no errors reported, metrics are able to grab the metrics of each instance, but when I execute 
`kubectl exec -it clickhouse-operator-57d48c676d-tnsgx -c metrics- exporter -n clickhouse-system -- curl -vvv http://localhost:8888/metrics | grep fetch`
 it keeps hanging without returning data.

**Comment by xingyunyang01** [comment]
![image](https://github.com/Altinity/clickhouse-operator/assets/94745901/72fb4ce2-be4e-4762-87e5-7bb98c2e4054)

**Comment by xingyunyang01** [comment]
I tested it on another set of environments with fewer instances and just

**Comment by Slach** [comment]
Why do you use `kubectl exec -it`? Instead of just `kubectl exec`?

Could you share?
`kubectl log clickhouse-operator-57d48c676d-tnsgx -c metrics- exporter -n clickhouse-system --since=1h`

**Comment by xingyunyang01** [comment]
![image](https://github.com/Altinity/clickhouse-operator/assets/94745901/f294c7c0-34b0-4cff-96a5-3b43e83c4f11)

**Comment by xingyunyang01** [comment]
[deployer@master01 ~]$ kubectl logs clickhouse-operator-57d48c676d-tnsgx -c metrics-exporter -n clickhouse-system --since=1h
E0729 05:42:48.494638       1 connection.go:136] QueryContext():FAILED Query(http://***:***@chi-brd-prod-ck9-brd-prod-ck9-2-1.nicadmin.svc.cluster.local:8123/) write tcp 192.168.170.21:43180->192.168.113.3:8123: use of closed network connection for SQL:     SELECT
        concat('metric.', metric) AS metric,
        toString(value)           AS value,
        ''                        AS description,
        'gauge'                   AS type
        FROM system.asynchronous_metrics
        UNION ALL
        SELECT
       concat('metric.', metric) AS metric,
       toString(value)           AS value,
            ''                        AS description,
       'gauge'                   AS type
   FROM system.metrics
   UNION ALL
   SELECT
       concat('event.', event)   AS metric,
       toString(value)           AS value,
       ''                        AS description,
       'counter'                 AS type
   FROM system.events
   UNION ALL
   SELECT
       'metric.MemoryDictionaryBytesAllocated'  AS metric,
       toString(sum(bytes_allocated))           AS value,
       'Memory size allocated for dictionaries' AS description,
       'gauge'                                  AS type
   FROM system.dictionaries
   UNION ALL
   SELECT
          'metric.LongestRunningQuery' AS metric,
          toString(max(elapsed))       AS value,
          'Longest running query time' AS description,
          'gauge'                      AS type
   FROM system.processes
UNION ALL
SELECT
          'metric.ChangedSettingsHash'       AS metric,
          toString(groupBitXor(cityHash64(name,value))) AS value,
          'Control sum for changed settings' AS description,
          'gauge'                            AS type
FROM system.settings WHERE changed
E0729 05:43:47.302209       1 connection.go:136] QueryContext():FAILED Query(http://***:***@chi-jtfprodfrom-jtfprodfrom-0-0.jiangtf.svc.cluster.local:8123/) EOF for SQL:         SELECT
        concat('metric.', metric) AS metric,
        toString(value)           AS value,
        ''                        AS description,
        'gauge'                   AS type
        FROM system.asynchronous_metrics
        UNION ALL
        SELECT
       concat('metric.', metric) AS metric,
       toString(value)           AS value,
            ''                        AS description,
       'gauge'                   AS type
   FROM system.metrics
   UNION ALL
   SELECT
       concat('event.', event)   AS metric,
       toString(value)           AS value,
       ''                        AS description,
       'counter'                 AS type
   FROM system.events
   UNION ALL
   SELECT
       'metric.MemoryDictionaryBytesAllocated'  AS metric,
       toString(sum(bytes_allocated))           AS value,
       'Memory size allocated for dictionaries' AS description,
       'gauge'                                  AS type
   FROM system.dictionaries
   UNION ALL
   SELECT
          'metric.LongestRunningQuery' AS metric,
          toString(max(elapsed))       AS value,
          'Longest running query time' AS description,
          'gauge'                      AS type
   FROM system.processes
UNION ALL
SELECT
          'metric.ChangedSettingsHash'       AS metric,
          toString(groupBitXor(cityHash64(name,value))) AS value,
          'Control sum for changed settings' AS description,
          'gauge'                            AS type
FROM system.settings WHERE changed
E0729 05:43:47.304017       1 connection.go:136] QueryContext():FAILED Query(http://***:***@chi-prod-log-app-prod-log-app-1-1.weiwo.svc.cluster.local:8123/) EOF for SQL:         SELECT
        concat('metric.', metric) AS metric,
        toString(value)           AS value,
        ''                        AS description,
        'gauge'                   AS type
        FROM system.asynchronous_metrics
        UNION ALL
        SELECT
       concat('metric.', metric) AS metric,
       toString(value)           AS value,
            ''                        AS description,
       'gauge'                   AS type
   FROM system.metrics
   UNION ALL
   SELECT
       concat('event.', event)   AS metric,
       toString(value)           AS value,
       ''                        AS description,
       'counter'                 AS type
   FROM system.events
   UNION ALL
   SELECT
       'metric.MemoryDictionaryBytesAllocated'  AS metric,
       toString(sum(bytes_allocated))           AS value,
       'Memory size allocated for dictionaries' AS description,
       'gauge'                                  AS type
   FROM system.dictionaries
   UNION ALL
   SELECT
          'metric.LongestRunningQuery' AS metric,
          toString(max(elapsed))       AS value,
          'Longest running query time' AS description,
          'gauge'                      AS type
   FROM system.processes
UNION ALL
SELECT
          'metric.ChangedSettingsHash'       AS metric,
          toString(groupBitXor(cityHash64(name,value))) AS value,
          'Control sum for changed settings' AS description,
          'gauge'                            AS type
FROM system.settings WHERE changed
E0729 05:58:02.339407       1 connection.go:136] QueryContext():FAILED Query(http://***:***@chi-ck-1-share01-ck-1-share01-2-0.share.svc.cluster.local:8123/) context deadline exceeded for SQL: SELECT
        database,
        table,
        toString(active)                       AS active,
        toString(uniq(partition))              AS partitions,
        toString(count())                      AS parts,
        toString(sum(bytes))                   AS bytes,
        toString(sum(data_uncompressed_bytes)) AS uncompressed_bytes,
        toString(sum(rows))                    AS rows,
       toString(sum(bytes_on_disk))           AS metric_DiskDataBytes,
       toString(sum(primary_key_bytes_in_memory_allocated)) AS metric_MemoryPrimaryKeyBytesAllocated
FROM system.parts
GROUP BY active, database, table
E0729 06:21:44.403588       1 connection.go:136] QueryContext():FAILED Query(http://***:***@chi-ncopp-gateway-ncopp-gateway-1-0.zhangkk4.svc.cluster.local:8123/) write tcp 192.168.170.21:39568->172.24.125.105:8123: use of closed network connection for SQL:   SELECT
        concat('metric.', metric) AS metric,
        toString(value)           AS value,
        ''                        AS description,
        'gauge'                   AS type
        FROM system.asynchronous_metrics
        UNION ALL
        SELECT
       concat('metric.', metric) AS metric,
       toString(value)           AS value,
            ''                        AS description,
       'gauge'                   AS type
   FROM system.metrics
   UNION ALL
   SELECT
       concat('event.', event)   AS metric,
       toString(value)           AS value,
       ''                        AS description,
       'counter'                 AS type
   FROM system.events
   UNION ALL
   SELECT
       'metric.MemoryDictionaryBytesAllocated'  AS metric,
       toString(sum(bytes_allocated))           AS value,
       'Memory size allocated for dictionaries' AS description,
       'gauge'                                  AS type
   FROM system.dictionaries
   UNION ALL
   SELECT
          'metric.LongestRunningQuery' AS metric,
          toString(max(elapsed))       AS value,
          'Longest running query time' AS description,
          'gauge'                      AS type
   FROM system.processes
UNION ALL
SELECT
          'metric.ChangedSettingsHash'       AS metric,
          toString(groupBitXor(cityHash64(name,value))) AS value,
          'Control sum for changed settings' AS description,
          'gauge'                            AS type
FROM system.settings WHERE changed

**Comment by xingyunyang01** [comment]
Hi, here's the log, I don't think it would cause the service to block even if there was an instance timeout?

**Comment by Slach** [comment]
`http://:@chi-jtfprodfrom-jtfprodfrom-0-0.jiangtf.svc.cluster.local:8123/`
did you change `clickhouse_operator` credentials?
it should be
`http://clickhouse_operator:***@chi-jtfprodfrom-jtfprodfrom-0-0.jiangtf.svc.cluster.local:8123/`

**Comment by xingyunyang01** [comment]
No, it uses the clickhouse_operator user and password that clickhouse-operator creates by default.And looking at the code, when an instance times out, the code assembles a metrics indicating an error, and then connects to the next instance instead of the one it's stuck on.

**Comment by xingyunyang01** [comment]
With the same configuration, I tested on a k8s with only 10 instances and this does not happen, could it be that too many instances leads to too much data?

**Comment by Slach** [comment]
Data should be Collect in parallel

**Comment by Slach** [comment]
which clickhouse-operator version do you use? 0.21.2?

**Comment by xingyunyang01** [comment]
0.19.0

**Comment by Slach** [comment]
could you upgrade to 0.21.2?

**Comment by xingyunyang01** [comment]
Upgrade just the metrics-exporter or should I upgrade the clickhouse-operator as well?

**Comment by Slach** [comment]
Please full upgrade operator + metrics-exporter + CRD

**Comment by xingyunyang01** [comment]
Is there support for upgrading cr instances from my currently existing 0.19.0 version to 0.21.2?

**Comment by Slach** [comment]
just use
`cusl -sL https://github.com/Altinity/clickhouse-operator/raw/0.21.1/deploy/operator-web-installer/clickhouse-operator-install.sh | OPERATOR_NAMESPACE=clickhouse-system bash`
