### ISSUE TITLE
Clickhouse operator still uses <yandex> tag

### ISSUE THREAD

**Issue by soeunj** [Altinity/clickhouse-operator#1206]
I am trying to upgrade clickhouse and clickhouse operator to latest version. I found that _config.xml_ in latest version of clickhouse use `<clickhouse>` tag but operator still uses `<yandex>`. Current config.xml in clickhouse: https://github.com/ClickHouse/ClickHouse/blob/a70127baecc451f1f7073bad7b6198f6703441d8/programs/server/config.xml#L7 The change was done quite some time ago: https://github.com/ClickHouse/ClickHouse/pull/29182 I am wondering if our settings configuration from `ClickHouseInstallation` will apply correctly or not, since tags are different between clickhouse and clickhouse operator.

**Comment by Slach** [comment]
config applied correctly
currently clickhouse-server allow mix <yandex> and <clickhouse>

https://github.com/ClickHouse/ClickHouse/blob/bba9a2cd2856ddf346221268b31f01ea64c5ac05/src/Common/Config/ConfigProcessor.cpp#L342-L348

**Comment by soeunj** [comment]
Thank you for the answer! 🙏
