### ISSUE TITLE
Configure access.port without overriding entire config.yaml

### ISSUE THREAD

**Issue by chancez** [Altinity/clickhouse-operator#1207]
I want to override the port the operator uses to connect to clickhouse from port 8123 to port 8443 because we've configured clickhouse with TLS. However, currently the port is within the `config.yaml` string, making it difficult to override without having to copy the entire set of default values in the config.yaml.

I see a few options:
- Since the `config.yaml` is passed through `tpl` here: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/templates/generated/ConfigMap-etc-clickhouse-operator-files.yaml#L13 then it could be redefined as `port: {{ .Values.access.port | default "8123" }}` or something similar
- `config.yaml` could be changed from a string value to an object. This would allow overriding individual options since normal YAML merging behavior would be possible
- You could add a new `structuredConfigs` field in the values which gets merged with the parsed `config.yaml`: Eg something like this:
````data: {{ tpl (mergeOverWrite (toYaml .Values.configs.files | tpl | fromYaml) .Values.structuredConfigs | toYaml) . | nindent 2 }}```

**Comment by alex-zaitsev** [comment]
@chancez , see https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md

**Comment by chancez** [comment]
Where do you configure what's suggested here? https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#forcing-https-for-operator-connections

```
configuration:
  access:
    scheme: https
    port: 8443
```

Helm values do not have this configuration.

**Comment by alex-zaitsev** [comment]
You do not need to configure scheme anymore, it is detected automatically since 0.21.2

**Comment by alex-zaitsev** [comment]
@chancez , how did you upgrade? Make sure you re-apply installation manifests, including CRD.

**Comment by alex-zaitsev** [comment]
Hi @chancez , have you figured it out?

**Comment by chancez** [comment]
I haven't had a chance to check back in on this.
