### ISSUE TITLE
IAM roles to access s3 

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1211]
Just wondering if the clickhouse underlying sdk support iam role's instead of using creds.
Has anyone tried using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) in config.xml ?

**Comment by Slach** [comment]
to use IMDS
look
https://github.com/Altinity/clickhouse-operator/tree/0.21.3/docs/chi-examples/25-s3-arn-role-ec2-credentials.yaml

to use IRSA
https://github.com/Altinity/clickhouse-operator/tree/0.21.3/docs/chi-examples/26-s3-iam-role-irsa.yaml

if you properly applied these examples
then
`SELECT ... FROM s3()`
should work without explicit credentials inside AWS EKS

**Comment by AdheipSingh** [comment]
@Slach thanks a lot :)
