### ISSUE TITLE
Table does not appear after creation 

### ISSUE THREAD

**Issue by suharevA** [Altinity/clickhouse-operator#1216]
when creating  
```
ALTER TABLE vmware.project_hardware on cluster 'all-replicated' ADD COLUMN hdd_bl_delivery4 Float32;
``` 
table does not appear, when repeating the command it says that the table already exists.
For some reason the table appears after I do the command.
```
DESCRIBE vmware.project_hardware hdd_bl_delivery4
```
What can this behavior be related to?
v.clickhouse-server:22.3.8.40.altinitystable

**Comment by Slach** [comment]
> that the table already exists.

do you mean column already exists?

> For some reason the table appears after I do the command.

do you mean column appears?

**Comment by suharevA** [comment]
After executing the alter command, the table does not appear, although it writes that it already exists.

**Comment by Slach** [comment]
sorry, i don't understand

could you run `clickhouse-client` inside clickhouse container
try to execute queries 
and share full error message?

**Comment by suharevA** [comment]
here is an example of creating hdd_bl_delivery5. Note that the table has not appeared, although it says that it has been created.
![Снимок экрана от 2023-08-05 08-28-02](https://github.com/Altinity/clickhouse-operator/assets/48557725/e2e2f265-fb8a-443d-bc3e-8
![Снимок экрана от 2023-08-05 08-29-51](https://github.com/Altinity/clickhouse-operator/assets/48557725/e7ddef23-9020-40d5-b03b-d7b0613b8309)
b5043577b5e)

**Comment by suharevA** [comment]
Anyway realized from the 4 nodes it has now started to write instead of 1-0 and 0-0. To 1-1 and 0-1.

**Comment by Slach** [comment]
issue is not related to clickhouse-operator
please share
`SHOW CREATE TABLE vmware.project_hardware ON CLUSTER '{cluster}' FORMAT Vertical;`

**Comment by suharevA** [comment]
![Снимок экрана от 2023-08-06 12-26-17](https://github.com/Altinity/clickhouse-operator/assets/48557725/37b8c1d9-e732-4877-b34c-44a048200cb2)

**Comment by Slach** [comment]
please stop share text information as picture, is unusable

`SELECT hostName(), create_table_query FROM cluster('all-sharded',system.tables) WHERE database='vmware' AND table='project_hardware' FORMAT Vertical`

**Comment by suharevA** [comment]
```
SELECT
    hostName(),
    create_table_query
FROM cluster('all-sharded', system.tables)
WHERE (database = 'vmware') AND (table = 'project_hardware')
FORMAT Vertical

Query id: 5a340f37-9eca-453b-bedd-8af2cad37d39

Row 1:
──────
hostName():         chi-prod-click-prod-0-0-0
create_table_query: CREATE TABLE vmware.project_hardware (`name` String, `name_gr1` String, `dc` String, `ram` Float64, `ram_used` Float64, `ram_ost` Float64, `ram_delivery1` Float64, `ram_delivery2` Float64, `hdd_bl_delivery3` Float32, `hdd_bl_delivery4` Float32) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/{shard}/project_hardware', '{replica}') ORDER BY name SETTINGS index_granularity = 8192

Row 2:
──────
hostName():         chi-prod-click-prod-1-1-0
create_table_query: CREATE TABLE vmware.project_hardware (`name` String, `name_gr1` String, `dc` String, `ram` Float64, `ram_used` Float64, `ram_ost` Float64, `ram_delivery1` Float64, `ram_delivery2` Float64, `hdd_bl_delivery3` Float32, `hdd_bl_delivery4` Float32, `hdd_bl_delivery5` Float32, `hdd_bl_delivery6` Float32) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/{shard}/project_hardware', '{replica}') ORDER BY name SETTINGS index_granularity = 8192

Row 3:
──────
hostName():         chi-prod-click-prod-1-0-0
create_table_query: CREATE TABLE vmware.project_hardware (`name` String, `name_gr1` String, `dc` String, `ram` Float64, `ram_used` Float64, `ram_ost` Float64, `ram_delivery1` Float64, `ram_delivery2` Float64, `hdd_bl_delivery3` Float32, `hdd_bl_delivery4` Float32, `hdd_bl_delivery5` Float32, `hdd_bl_delivery6` Float32) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/{shard}/project_hardware', '{replica}') ORDER BY name SETTINGS index_granularity = 8192

Row 4:
──────
hostName():         chi-prod-click-prod-0-1-0
create_table_query: CREATE TABLE vmware.project_hardware (`name` String, `name_gr1` String, `dc` String, `ram` Float64, `ram_used` Float64, `ram_ost` Float64, `ram_delivery1` Float64, `ram_delivery2` Float64, `hdd_bl_delivery3` Float32, `hdd_bl_delivery4` Float32) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/{shard}/project_hardware', '{replica}') ORDER BY name SETTINGS index_granularity = 8192
```

**Comment by alex-zaitsev** [comment]
@suharevA , I think the problem is in ALTER TABLE:

```ALTER TABLE vmware.project_hardware on cluster 'all-replicated' ADD COLUMN hdd_bl_delivery4 Float32;```

You do not need ON CLUSTER for replicated tables. And if you use ON CLUSTER, then use '{cluster}' macro; ```ON CLUSTER '{cluster}'```

What has happened now, is that table has been altered on one shard, but not on other one.  You may manually run ALTER on 1-0-0 or 1-1-1 (without ON CLUSTER) in order to make it consistent.
