### ISSUE TITLE
clickhouse keeper: questions about --force-recovery

### ISSUE THREAD

**Issue by OodounaikingoO** [Altinity/clickhouse-operator#1224]
clickhouse-keeper version: v22.3 & v23.4.1
deploy yaml: [https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml)

```
if [[ "1" == "$MY_ID" ]]; then
  clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper_config.xml --force-recovery
else
  clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper_config.xml
fi
```

1. What I'm curious about is why this first node starts with --force-recovery.  What does it means ? If I removed it and modified it to have only one line like  `clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper_config.xml`

I found that all three keeper nodes can be started, but when I had  a DDL sql (like `create database db on cluster 'xxx'`) by clickhouse-client, it blocked until timeout. The following is what I found when I checked the znode.

<img width="1402" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/56195074/16d24fc4-e779-41bb-b964-19c351fa8545">

2. So what's wrong with this, why it's blocked..

3. The third problem I met was that I don't modify anything just used the same yaml [https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml).  When the fisrt keeper node restart, it looked like split-brain (while the first node was restarting, one of the left two nodes would be leader, and after the first node finished restarting, it also became a leader), I wonder know why, is it related to force-recovery ?  And how to resovle it...

**Comment by Slach** [comment]
Provided manifests still experimental and `test_keeper.py` still failed

We'll update keeper manifests and try to replace `--force-recovery` to `reconfig` support look details https://github.com/ClickHouse/ClickHouse/pull/49450, but no have ETA for it
