### ISSUE TITLE
Increasing replicas results in hardcoded UUID in the metadata for ReplicatedMergeTree (sql)

### ISSUE THREAD

**Issue by lazywei** [Altinity/clickhouse-operator#1227]
## Problem

On the first replica, the metadata for the created table may look like this
```
$ cat /var/lib/clickhouse/metadata/default/testing.sql
ATTACH TABLE _ UUID 'd45069c3-e744-4096-b3d7-9bf6858bed1b'
(
    `name` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/chi-{installation}/c-{cluster}/s-{shard}/{uuid}', '{replica}')
```

However, if we increase the replica count, the newly created replica will have following metadata for this table

```
cat /var/lib/clickhouse/metadata/default/testing.sql
ATTACH TABLE _ UUID 'a790e3a9-ae83-4c4f-ae46-0dc1c8b30342'
(
    `name` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/chi-{installation}/c-{cluster}/s-{shard}/a790e3a9-ae83-4c4f-ae46-0dc1c8b30342', '{replica}')
```

Notice that the `{uuid}` part in the keeper path is expaned.

## Repro Steps

1. Create a CHI with 1 shard 1 replicas
2. Run this SQL to create a ReplicatedMergeTree table
3. Update the CHI to increase the replica counts to 2
4. After reconcilation complete, check the metadata created on the second replica

SQL for the table creation:
```
CREATE TABLE testing ON CLUSTER '{cluster}' (name String)
ENGINE=ReplicatedMergeTree('/clickhouse/tables/chi-{installation}/s-{shard}/{uuid}', '{replica}')
ORDER BY name
```

## Why this is an issue

When using ClickHouse's own backup, like running `BACKUP DATABASE ...`, the backed up metadata may be having the hardcoded UUID as the keeper's path, rather than using the macro to represent the path. As a result, the restoration would be forced to use the old keeper's path rather than the newly created table's path.

This will cause the keeper's path's UUID be inconsistent than the newly created table's actual uuid, like this

```
cat /var/lib/clickhouse/metadata/default/archive_logs.sql 
ATTACH TABLE _ UUID 'd9ad332b-bed4-4e51-8b59-37fb4558ac5b'
(
...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/chi-{installation}/c-{cluster}/s-{shard}/db_uuid/1bd8b613-b89f-4bc2-b899-d886a495a7eb', '{replica}')
```

Note that the table's UUID (in the attach statement) is different from the keeper's path.

**Comment by Slach** [comment]
this is not clickhouse-operator issue
this is default {uuid} macros and UUID `value` clause behavior for `ReplicatedMergeTree` 


drop table or clean keeper data before restore

`clickhouse-backup` also keep UUID value and restore hardcoded value
