### ISSUE TITLE
how to change metric-exporter port number ?

### ISSUE THREAD

**Issue by Shankara-git** [Altinity/clickhouse-operator#1230]
Presently metrics-exporter is exposed at 8888 port, How to change this port number in clickhouse-operator ?

NAME                                                                  READY   STATUS    RESTARTS   AGE
pod/clickhouse-operator-altinity-clickhouse-operator-b59cd6b5fcv97f   2/2     Running   0          5m47s

NAME                                                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
**service/clickhouse-operator-altinity-clickhouse-operator-metrics   ClusterIP   10.103.235.15   <none>        8888/TCP   5m47s**

NAME                                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/clickhouse-operator-altinity-clickhouse-operator   1/1     1            1           5m47s

NAME                                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/clickhouse-operator-altinity-clickhouse-operator-b59cd6b5f   1         1         1       5m47s

**Comment by Slach** [comment]
You need to manually change deployment of clickhouse-operator

and add to `spec.containers` something like that
```yaml
command:
 - "-logtostderr=true"
 - "-v=1"
 - "-metrics-endpoint=:9999"
```

**Comment by Shankara-git** [comment]
in our case prometheus is using 8081 port for metrics, so, wanted to configure same port for expose

**Comment by Shankara-git** [comment]
> You need to manually change deployment of clickhouse-operator
> 
> and add to `spec.template.spec.containers` something like that
> 
> ```yaml
> command:
>  - "/metrics-exporter" 
>  - "-logtostderr=true"
>  - "-v=1"
>  - "-metrics-endpoint=:9999"
> ```
> 
> and also change `spec.template.metadata.annotations` in deployment to something like that
> 
> ```
>       annotations:
>         prometheus.io/port: '9999'
>         prometheus.io/scrape: 'true'
> ```
> 
> why you need to change it?

in our case prometheus is using 8081 port for metrics, so, wanted to configure same port for expose. We are using helm release to deploy the clickhouse operator
