### ISSUE TITLE
question: Access only one specific shard

### ISSUE THREAD

**Issue by gabriel-suela** [Altinity/clickhouse-operator#1242]
I'm trying to create a service to access (connect on dbeaver for example) directly in only one shard of my chi. It's possible to do it? I've already tried many ways and fails at all.  Currently i'm working with 2 shards and 2 replicas, but for testing purposes, i want to connect in a specific shard without getting the round robing effect.

**Comment by alex-zaitsev** [comment]
Yes, you may create a dedicated service template for that purpose. See this example:
https://github.com/Altinity/clickhouse-operator/blob/master/tests/e2e/manifests/chi/test-012-service-template.yaml

**Comment by lucasfcnunes** [comment]
@alex-zaitsev
I wanted to be able to prioritize the service LB traffic to pods in order. *Always same pod if available.
e.g.:
- pod-0-0
- pod-0-1
- pod-1-0
- pod-1-1

**Comment by alex-zaitsev** [comment]
@lucasfcnunes , not sure I understand the requirement. The LB spec does not have this feature. There could be external LB implementations that can do it. Alternatively, you may do it on the application side.

ClickHouse can help with this as well. You may use Distrubuted table and load_balancing=in_order. See https://clickhouse.com/docs/en/operations/settings/settings#load_balancing
