### ISSUE TITLE
DB::Exception: admin: Authentication failed: password is incorrect or there is no user with such name. 

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [Altinity/clickhouse-operator#1244]
I have installed clickhouse-operator and clickhouse with 3 shards and 2 replicas. I have created secret for username and password for clickhouse-operator to communicate with clickhouse. The same username and password is present in clickhouse-server and the admin user has access_control_management is set to true. When I see the logs of clickhouse pod, the below exception is throwing in all pods. What might be cause of this exception? Would anyone from clickhouse please help here?

2023.09.22 09:55:04.878072 [ 49 ] {} <Debug> HTTP-Session: e5a0c8ca-a220-48df-88b5-945deac1358e Authenticating user 'admin' from 10.0.142.237:58728
2023.09.22 09:55:04.878248 [ 49 ] {} <Error> Access(user directories): from: 10.0.142.237, user: admin: Authentication failed: Code: 193. DB::Exception: Invalid credentials. (WRONG_PASSWORD), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e91fbf7 in /usr/bin/clickhouse
1. ? @ 0x00000000092fd740 in /usr/bin/clickhouse
2. DB::IAccessStorage::throwInvalidCredentials() @ 0x0000000013072683 in /usr/bin/clickhouse
3. DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x000000001307236e in /usr/bin/clickhouse
4. DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x00000000130a68e9 in /usr/bin/clickhouse
5. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x0000000012fbe63e in /usr/bin/clickhouse
6. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x0000000014217aed in /usr/bin/clickhouse
7. DB::HTTPHandler::authenticateUser(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0x000000001522041f in /usr/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000015221bb2 in /usr/bin/clickhouse
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000152290e9 in /usr/bin/clickhouse
10. DB::HTTPServerConnection::run() @ 0x0000000015298632 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x0000000018295054 in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x0000000018296271 in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x000000001841f487 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001841cebc in /usr/bin/clickhouse
15. ? @ 0x00007f979cf32609 in ?
16. __clone @ 0x00007f979ce57133 in ?
 (version 23.7.5.30 (official build))

**Comment by itssimon** [comment]
Struggling with the same issue here. Some extra lines in my log output hint at the client IP address not being allowed, but this is a connection from within the cluster. Weird.

```
2023.10.03 06:00:31.236198 [ 611 ] {} <Debug> TCPHandler: Connected ClickHouse asynch version 20.10.0, revision: 54453, database: mydb, user: admin.
2023.10.03 06:00:31.236278 [ 611 ] {} <Debug> TCP-Session: 2c30ec47-241e-4a72-9fa9-fea857d7c57e Authenticating user 'admin' from [::ffff:10.244.0.24]:32968
2023.10.03 06:00:31.236464 [ 611 ] {} <Warning> AddressPatterns: Failed to check if the allowed client hosts contain address ::ffff:10.244.0.24. DB::Exception: ::ffff:10.244.0.24 could not be resolved, code = 198
2023.10.03 06:00:31.236633 [ 611 ] {} <Error> Access(user directories): from: ::ffff:10.244.0.24, user: admin: Authentication failed: Code: 195. DB::Exception: Connections from ::ffff:10.244.0.24 are not allowed. (IP_ADDRESS_NOT_ALLOWED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c7498f7 in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000723280d in /usr/bin/clickhouse
2. DB::IAccessStorage::throwAddressNotAllowed(Poco::Net::IPAddress const&) @ 0x0000000011049cf1 in /usr/bin/clickhouse
3. DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x0000000011049c24 in /usr/bin/clickhouse
4. DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x000000001107fdc9 in /usr/bin/clickhouse
5. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x0000000010fbe4de in /usr/bin/clickhouse
6. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x0000000012269923 in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0x000000001334090b in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0x0000000013354f99 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x0000000015d33b34 in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d34d31 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x0000000015e40387 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e3e61c in /usr/bin/clickhouse
13. ? @ 0x00007f103253f609 in ?
14. ? @ 0x00007f1032464133 in ?
 (version 23.9.1.1854 (official build))
2023.10.03 06:00:31.236731 [ 611 ] {} <Debug> TCP-Session: 2c30ec47-241e-4a72-9fa9-fea857d7c57e Authentication failed with error: admin: Authentication failed: password is incorrect, or there is no user with such name.
2023.10.03 06:00:31.237030 [ 611 ] {} <Error> ServerErrorHandler: Code: 516. DB::Exception: admin: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c7498f7 in /usr/bin/clickhouse
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000725a091 in /usr/bin/clickhouse
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x0000000010fbe77f in /usr/bin/clickhouse
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x0000000012269923 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x000000001334090b in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x0000000013354f99 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x0000000015d33b34 in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d34d31 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x0000000015e40387 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e3e61c in /usr/bin/clickhouse
10. ? @ 0x00007f103253f609 in ?
11. ? @ 0x00007f1032464133 in ?
 (version 23.9.1.1854 (official build))
```

Strangely I can connect fine from my local environment when port-forwarding port 9000 with kubectl, with the same credentials. So this only happens for connections from a different pod within the cluster.

**Comment by itssimon** [comment]
I was able to figure it out. I had to explicitly allow connections from other pods within the cluster using the IPv4-mapped IPv6 address format. ChatGPT was surprisingly helpful with this. This might be worth mentioning in the docs/examples too.

```yaml
        users:
          admin/networks/ip:
            - ::ffff:10.0.0.0/104
```

**Comment by Ragavendra-Vigneshwaran-R** [comment]
In my case, I had a special character "%" in my password. This special character is causing the above issue because clickhouse-operator is trying to connect to clickhouse-server but it's not able to connect to it. I just removed this special character from my password. After this, It got connected and this error got resolved. 

@Slach One question, does clickhouse doesn't support special character like "%" or "[" in its password?

**Comment by Slach** [comment]
no strong restriction, but could be errors in connectors when password convert special characters wrong

you need to use kubectl sniff plugin capture traffic to 8123 port, inside `clickhouse-operator` container and compare `sha256` from `password` which pass from `clickhouse-operator` to `clickhouse-server` with `/etc/clickhouse-server/users.d/chop-generated-users.xml`
