### ISSUE TITLE
Why is do_not_merge_across_partitions_select_final 1 by default?

### ISSUE THREAD

**Issue by minhes** [Altinity/clickhouse-operator#1246]
Hi all,

I could not find any documents in Altinity to explain why this settings is set 1 by default. Is it a problem to change it back to 0 like the CH official github?

[do_not_merge_across_partitions_select_final ](https://github.com/Altinity/clickhouse-operator/commit/bc6896b14f5271c0a9facacb0358b92424295b48)

Thanks,

**Comment by Slach** [comment]
it improve speed for SELECT ... FINAL ... queries

https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-final-clause-speed/

you can modify `ConfigMap` for operator and return default behavior

**Comment by francescorivola** [comment]
Hi @Slach , we were wondering why the default to 1 as per our understanding this setting could lead in query with wrong results if the table partition key is not aligned with the table order by.

Example, if I have a **replacing merge tree table** with **order by** based on field: **email** and versioned by field **timestamp**. But the **partition key** is based on another field, let's say **city**. What if I have 2 rows with the same email but different cities, the FINAL won't merge the result if in the two rows are in different partitions right? That could lead in wrong results. Am I right?

Thank yo so much for your help. Really appreciated.

**Comment by Slach** [comment]
@alex-zaitsev could you share your mention here?

**Comment by UnamedRus** [comment]
> What if I have 2 rows with the same email but different cities, the FINAL won't merge the result if the two rows are in different partitions right?

Yes

>  That could lead in wrong results. Am I right?

Kinda,
Lets say that FINAL keyword does finalization **merge**, so it looked like all partitions in table in finalized state (only one part per partition). But according to ClickHouse merge logic in MergeTree table, merges not happen across partitions, so it's completely ok to have duplicated rows in different partitions and it's expected.

So we can say that `do_not_merge_across_partitions_select_final=1`, make FINAL behavior expected and match behavior of ReplacingMergeTree table engine.

From another side, in before FINAL was merging data across partitions which is different from ReplacingMergeTree, so default behavior is to keep that.

**Comment by francescorivola** [comment]
Hi @UnamedRus , 

Thank you so much for clarifying this. It makes sense.

BTW I am not able to find in the clickhouse documentation that "merges not happen across partitions". I would appreciate if you can point us to where this is explained in detail.

The issue can be closed from our side.

Thank you again for your time and help.

**Comment by UnamedRus** [comment]
> I would appreciate if you can point us to where this is explained in detail.

I guess, you can check some webinars on how MergeTree table working initially. It didn't written somewhere explicitly.

https://kb.altinity.com/engines/mergetree-table-engine-family/part-naming-and-mvcc/
