### ISSUE TITLE
Security hardening guide doesn't discuss protecting access_key_id and secret_access_key

### ISSUE THREAD

**Issue by sporkmonger** [Altinity/clickhouse-operator#1249]
I think the lack of discussion on proper secrets handling for S3-compatible disks in Clickhouse configuration is a bit of a gap here:
https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md

Should probably explicitly cover `from_env` for that use-case.

**Comment by Slach** [comment]
yes, the best way is `from_env` + `secret` mounted in environment variable inside `podTemplate.spec.containers`
do you need a complete manifest?

**Comment by sporkmonger** [comment]
I've already figured it out for myself, I was just thinking it was a missing scenario in the docs. I suspect a snippet w/ a small example would be sufficient to get others headed in the right direction.

**Comment by Slach** [comment]
@sporkmonger don't be shy to make pull request ;)

**Comment by plantfansam** [comment]
👋  I'm also looking into this and cannot find a first-class way to reference `fromenv` in `ClickHouseInstallation` 

```xml
  configuration:
    clusters:
      - name: "simple"
    settings:
      storage_configuration/would_like_to_read_this_from_env: ???
```

Probably I've just missed docs somewhere, but I thought it was worth a mention!

**Comment by Slach** [comment]
@plantfansam you can use kubernetes secrets/configmap for it and customize podTemplate.spec to mount some files inside config.d

usually storage_confugration doesn't contains sensitive data
even when you use S3 disk
you can use IRSA metadata.annotations in `spec.podTemplates[].spec.containers` for it or provide environment variables with valueFrom + secretKeyRef inside `spec.podTemplates[].spec.containers`

**Comment by plantfansam** [comment]
Ah, that is super helpful @Slach, thank you!

**Comment by alex-zaitsev** [comment]
@sporkmonger , agree we need docs on this. In fact, there are several ways to use S3 securely:
- secret mounted via env variables, as discussed above. 
- service-account and IRSA
- named collection defined in DDL -- this is more difficult to manage on infra side though

**Comment by alex-zaitsev** [comment]
Secrets for configuration settings are supported in 0.23. See https://github.com/Altinity/clickhouse-operator/blob/0.23.0/docs/security_hardening.md#securing-clickhouse-server-settings
