### ISSUE TITLE
Different threads on Clickhouse replicas

### ISSUE THREAD

**Issue by Philippians413** [Altinity/clickhouse-operator#1266]
**Describe the unexpected behaviour**
We have 3 clickhouse replicas with completely the same hardware, but number of threads not equal on them during queries execution. One replica is very overloaded, but another 2 don't provide enough threads, with the same config.

**How to reproduce**
* Which ClickHouse server version to use 
Clickhouse version 23.3.8.22.altinitystable

* Which interface to use, if matters
We deploy clickhouse with 3 replicas with clickhouse-operator for Kubernetes.
Our config for profile and global settings:
```
    profiles:
      default/max_memory_usage: 68719476736
      default/max_memory_usage_for_all_queries: 68719476736
      default/max_bytes_before_external_group_by: 54760833024
      default/max_bytes_before_external_sort: 54760833024
      default/allow_experimental_live_view: 1
      default/allow_experimental_window_functions: 1
      default/allow_deprecated_database_ordinary: 1
      default/async_insert: 1
    settings:
      max_concurrent_queries: 4500
      max_thread_pool_size: 20000
      thread_pool_queue_size: 20000
```
During queries execution I see the next situation:
Replica 0-0 - 
```
chi-int-replcluster-0-0-0.chi-int-replcluster-0-0.integration.svc.cluster.local :) select * from system.metrics where metric like '%Global%'

SELECT *
FROM system.metrics
WHERE metric LIKE '%Global%'

Query id: 901cea3a-90a2-4679-8d9a-be7869f04727

┌─metric─────────────┬─value─┬─description─────────────────────────────────────────────┐
│ GlobalThread       │  4700 │ Number of threads in global thread pool.                │
│ GlobalThreadActive │  3890 │ Number of threads in global thread pool running a task. │
└────────────────────┴───────┴─────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.002 sec.
```
Replica 0-1 - 
```
chi-int-replcluster-0-1-0.chi-int-replcluster-0-1.integration.svc.cluster.local :) select * from system.metrics where metric like '%Global%'

SELECT *
FROM system.metrics
WHERE metric LIKE '%Global%'

Query id: d171ab18-b229-4674-b07a-d19224b57354

┌─metric─────────────┬─value─┬─description─────────────────────────────────────────────┐
│ GlobalThread       │  1341 │ Number of threads in global thread pool.                │
│ GlobalThreadActive │   343 │ Number of threads in global thread pool running a task. │
└────────────────────┴───────┴─────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.003 sec.
```
Replica 0-2 - 
```
chi-int-replcluster-0-2-0.chi-int-replcluster-0-2.integration.svc.cluster.local :) select * from system.metrics where metric like '%Global%'

SELECT *
FROM system.metrics
WHERE metric LIKE '%Global%'

Query id: bd8fa3ab-7855-4a8c-9910-b90c9f4172d8

┌─metric─────────────┬─value─┬─description─────────────────────────────────────────────┐
│ GlobalThread       │  1339 │ Number of threads in global thread pool.                │
│ GlobalThreadActive │   781 │ Number of threads in global thread pool running a task. │
└────────────────────┴───────┴─────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.004 sec. 
```
On Kubernetes pod level we can see next situation. Replica 0-0:
```
root@chi-int-replcluster-0-0-0:/# ps H -o 'tid comm' $(pidof -s clickhouse-server) |  tail -n +2 | awk '{ printf("%s\t%s\n", $1, $2) }' | clickhouse-local -S "threadid UInt16, name String" -q "SELECT name, count() FROM table GROUP BY name WITH TOTALS ORDER BY count() DESC FORMAT PrettyCompact"
┌─name────────────┬─count()─┐
│ ThreadPool      │    2045 │
│ QueryPipelineEx │    1917 │
│ HTTPHandler     │     289 │
│ BgSchPool       │     128 │
│ Collector       │     101 │
│ BgBufSchPool    │      16 │
│ BgDistSchPool   │      16 │
│ MergeMutate     │      16 │
│ BgMBSchPool     │      16 │
│ SystemLogFlush  │      10 │
│ Common          │       8 │
│ Move            │       8 │
│ Fetch           │       8 │
│ clickhouse-serv │       7 │
│ IntersrvHandler │       6 │
│ ExterLdrReload  │       2 │
│ ConfigReloader  │       2 │
│ TraceCollector  │       1 │
│ TCPHandler      │       1 │
│ DDLWorker       │       1 │
│ ZooKeeperRecv   │       1 │
│ BgBufSchPool/D  │       1 │
│ BgMBSchPool/D   │       1 │
│ DDLWorkerClnr   │       1 │
│ ZooKeeperSend   │       1 │
│ BgDistSchPool/D │       1 │
│ AsyncMetrics    │       1 │
│ BgSchPool/D     │       1 │
└─────────────────┴─────────┘

Totals:
┌─name─┬─count()─┐
│      │    4606 │
└──────┴─────────┘
```
Replica 0-1:
```
root@chi-int-replcluster-0-1-0:/# ps H -o 'tid comm' $(pidof -s clickhouse-server) |  tail -n +2 | awk '{ printf("%s\t%s\n", $1, $2) }' | clickhouse-local -S "threadid UInt16, name String" -q "SELECT name, count() FROM table GROUP BY name WITH TOTALS ORDER BY count() DESC FORMAT PrettyCompact"
┌─name────────────┬─count()─┐
│ ThreadPool      │    1094 │
│ HTTPHandler     │     244 │
│ BgSchPool       │     128 │
│ BgDistSchPool   │      16 │
│ MergeMutate     │      16 │
│ BgMBSchPool     │      16 │
│ BgBufSchPool    │      16 │
│ SystemLogFlush  │      10 │
│ IntersrvHandler │       9 │
│ Fetch           │       8 │
│ Move            │       8 │
│ Common          │       8 │
│ QueryPipelineEx │       7 │
│ clickhouse-serv │       7 │
│ ConfigReloader  │       2 │
│ ExterLdrReload  │       2 │
│ DDLWorker       │       1 │
│ TCPHandler      │       1 │
│ BgMBSchPool/D   │       1 │
│ TraceCollector  │       1 │
│ ZooKeeperRecv   │       1 │
│ BgBufSchPool/D  │       1 │
│ ZooKeeperSend   │       1 │
│ DDLWorkerClnr   │       1 │
│ BgDistSchPool/D │       1 │
│ AsyncMetrics    │       1 │
│ BgSchPool/D     │       1 │
└─────────────────┴─────────┘

Totals:
┌─name─┬─count()─┐
│      │    1602 │
└──────┴─────────┘
```
Replica 0-2:
```
root@chi-int-replcluster-0-2-0:/# ps H -o 'tid comm' $(pidof -s clickhouse-server) |  tail -n +2 | awk '{ printf("%s\t%s\n", $1, $2) }' | clickhouse-local -S "threadid UInt16, name String" -q "SELECT name, count() FROM table GROUP BY name WITH TOTALS ORDER BY count() DESC FORMAT PrettyCompact"
┌─name────────────┬─count()─┐
│ ThreadPool      │    1095 │
│ HTTPHandler     │     253 │
│ BgSchPool       │     128 │
│ BgDistSchPool   │      16 │
│ MergeMutate     │      16 │
│ BgBufSchPool    │      16 │
│ BgMBSchPool     │      16 │
│ SystemLogFlush  │      10 │
│ Common          │       8 │
│ Move            │       8 │
│ Fetch           │       8 │
│ clickhouse-serv │       7 │
│ IntersrvHandler │       7 │
│ QueryPipelineEx │       3 │
│ ExterLdrReload  │       2 │
│ ConfigReloader  │       2 │
│ ZooKeeperRecv   │       1 │
│ TraceCollector  │       1 │
│ TCPHandler      │       1 │
│ DDLWorker       │       1 │
│ BgBufSchPool/D  │       1 │
│ DDLWorkerClnr   │       1 │
│ BgMBSchPool/D   │       1 │
│ ZooKeeperSend   │       1 │
│ Collector       │       1 │
│ BgDistSchPool/D │       1 │
│ AsyncMetrics    │       1 │
│ BgSchPool/D     │       1 │
└─────────────────┴─────────┘

Totals:
┌─name─┬─count()─┐
│      │    1607 │
└──────┴─────────┘
```

**Expected behavior**
Have the same threads number on all replicas and have equal load on all replicas.

**Error message and/or stacktrace**
```
Error: calculateSubBlocks Error: getValueLosses LIN_A11 Error: Error: 500: Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=4827, jobs=4827). (CANNOT_SCHEDULE_TASK) (version 23.3.8.22.altinitystable (altinity build))

Error: calculateSubBlocks Error: getValueLosses LAN_4 Error: Error: 500: Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=14, jobs=14). (CANNOT_SCHEDULE_TASK) (version 23.3.8.22.altinitystable (altinity build))
```

**Comment by Slach** [comment]
Which hostname do you use to execute your queries?
Which client language and library?
Which protocol do you use?

**Comment by tanchik-curly** [comment]
Hi, I have the same issue, it doesn't matter how many concurrent queries I allocate for each replica (with an increased max_thread_pool_size to 30000) it always processes everything to the first replica, and as a result, it crashes and everything stops working because with 2 replicas performance goes down. As a balancer, we have a Zookeeper.
If I check system.processes, I always see running 200-300 processes on the first replica and 10-50 on the second and third one...

**Comment by Slach** [comment]
@tanchik-curly could you answer to questions above?

**Comment by Philippians413** [comment]
@Slach 
Which hostname do you use to execute your queries? - internal link to do a query inside cluster, we make requests to K8s Load Balancer
Which client language and library? - Typescript, we use axios requests and clickhouse library for Node.js
Which protocol do you use? - http

**Comment by Slach** [comment]
@Philippians413 

do you need access to clickhouse cluster outside from kubernetes cluster?

**Comment by Slach** [comment]
@Philippians413 which kind of kubernetes do you use managed or on-premise?

**Comment by Philippians413** [comment]
@Slach we use on-premise Kuberentes version 1.24. We don't need access to clickhouse cluster outside from kubernetes cluster. K8s Load Balancer created by clikhouse-operator

**Comment by Slach** [comment]
@Philippians413 

could you share
`kubectl get chi -n <your-clickhouse-namespace> <your-chi-name> -o yaml` ?

instead of `type: LoadBalancer` 
you could to try change it to `type: ClusterIP`

look details in 
```bash
kubectl explain chi.spec.templates.serviceTemplates
kubectl explain chi.spec.defaults.templates.serviceTemplate
```
and example in
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-03-service-template.yaml

**Comment by Philippians413** [comment]
We have `type: ClusterIP`, but I don't know why Load Balancer deploy.
Maybe this is something under the hood of clickhouse-operator

**Comment by Slach** [comment]
> We have type: ClusterIP, but I don't know why Load Balancer deployed.

Because you define `clusterServiceTemplate` instead of `serviceTemplate`, operator created default `serviceTemplate` and render service from it, which cover the WHOLE CHI, 
and one another service from your defined `clusterServiceTemplate` which cover only one cluster in the cluster and your chi have only one cluster

if you want to remove LoadBalancer, you can replace
```
      templates:
        clusterServiceTemplate: service-template
```

to 
```
      templates:
        serviceTemplate: service-template
```

Which endpoint do you use in your client applications? `clickhouse-int.integration.svc`? Or something else?

**Comment by Philippians413** [comment]
>Which endpoint do you use in your client applications? clickhouse-int.integration.svc? Or something else?

@Slach we also have ingress that points to the service that created by LoadBalancer. We use this ingress for tabix

**Comment by Philippians413** [comment]
@Slach I deleted LoadBalancer and changed `clusterServiceTemplate` to `serviceTemplate`, but I don't understand how to send client requests to clickhouse now? I have only 3 services for every replica
```
$ kubectl get svc -n integration | grep chi
chi-int-replcluster-0-0                  ClusterIP      None            <none>                             9000/TCP,8123/TCP,9009/TCP                       648d
chi-int-replcluster-0-1                  ClusterIP      None            <none>                             9000/TCP,8123/TCP,9009/TCP                       648d
chi-int-replcluster-0-2                  ClusterIP      None            <none>                             9000/TCP,8123/TCP,9009/TCP                       648d
```
Before we sent requests to the service that was pointed to LoadBalancer

**Comment by Philippians413** [comment]
I moved `serviceTemplate` block from `chi.spec.configuration.clusters.templates` to `chi.spec.defaults.templates` and I see the new service.
```
$ kubectl get svc -n integration | grep click
clickhouse-int                           ClusterIP      10.233.21.14    <none>                             8123/TCP,9000/TCP                                107s
```
We are going to test now

**Comment by tanchik-curly** [comment]
@Slach , Hi! balancing improved, but we still have a problem with thread allocation, we put a limit per replica of 6000 max_concurrent_queries, but we usually see such errors:

Code: 439. DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=10000, jobs=10000). (CANNOT_SCHEDULE_TASK) (version 22.8.13.21.altinitystable (altinity build))
Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=3, jobs=3). (CANNOT_SCHEDULE_TASK) (version 22.8.13.21.altinitystable (altinity build))
Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=18, jobs=18). (CANNOT_SCHEDULE_TASK) (version 22.8.13.21.altinitystable (altinity build))
Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=9, jobs=9). (CANNOT_SCHEDULE_TASK) (version 22.8.13.21.altinitystable (altinity build))
[9:44](https://windlogtwopointzero.slack.com/archives/D033VCLHBPZ/p1699429467093859)

Do you know why we usually see such a low number of threads, but we receive errors?

**Comment by Slach** [comment]
@tanchik-curly 

> we put a limit per replica of 6000 max_concurrent_queries

Which kind of queries is most frequent for your workload? INSERT? SELECT?
How many CPU cores do you have?

**Comment by tanchik-curly** [comment]
mainly select, and bulk insert ~ each 2 minutes
we have 384 cores for 3 replicas in total

**Comment by Slach** [comment]
@tanchik-curly look to
max_thread_pool_size=20000

**Comment by Slach** [comment]
@tanchik-curly what is your CPU utilization? 
do you have limits in your podTemplate?
could you share `top` output inside container?

**Comment by tanchik-curly** [comment]
we changed this:
+      max_thread_pool_size: 30000
+      thread_pool_queue_size: 30000
and also decreased this max_threads to 16, because I can see that we have 159 running queries on one replica, but at the same time the current number of global threads is 10700 right now, but because max_threads wasn't settled and used default value

**Comment by tanchik-curly** [comment]
@Slach 

1. do you have limits in your podTemplate?

No, we don't have

2. what is your CPU utilization?
we have 96 cores for all replicas and CPU usage from 20% to 84%, usually 80% always
