### ISSUE TITLE
Query Regarding Operator Update Plan and Data Verification in ClickHouse

### ISSUE THREAD

**Issue by emahdij** [Altinity/clickhouse-operator#1267]
I'm new to this community and currently working on understanding the ClickHouse operator for Kubernetes. I have a question regarding the update process managed by the operator: Does the operator check the existing data in the ClickHouse cluster before forming an update plan, or does it only consider the state of the pods and their configurations?

The context for my question is to ensure data consistency and integrity during operator-managed updates. I'm looking to understand if there are any checks or balances in place that prevent data loss or inconsistencies when an update is applied.

Any insights or documentation pointers on this would be greatly appreciated!

Best regards,
Mehdi

**Comment by Slach** [comment]
`clickhouse-operator` only consider the state of the statefulset, configmap, pods, pvc and their configurations related to clickhouse-server

`clickhouse-server` itself has eventually consistency

after upgrade applied
`clickhouse-operator` will roll-out schema for `Distributred + Dictionary + ReplicatedMegreTree` tables automatically for newly added pods

but will not to apply re-sharding exists data cause clickhouse-server itself currelty doesn't support it

**Comment by emahdij** [comment]
Thank you for the swift response and the valuable information provided.

I have a follow-up question regarding user management: If I were to modify the user secret in Kubernetes, would the clickhouse-operator update the ClickHouse user password accordingly? Additionally, what would be the expected behavior if a user is deleted from the secret? Does the operator handle the deletion of the user within ClickHouse as well?

Looking forward to your guidance on these aspects.

Best regards
