### ISSUE TITLE
User Management with ClickHouse Operator

### ISSUE THREAD

**Issue by emahdij** [Altinity/clickhouse-operator#1268]
Hello Altinity Team,

First of all, thank you for the work you do with the ClickHouse operator; it's a significant asset to the community.

I'm relatively new here and have some queries about managing user credentials within ClickHouse when using the operator.

1. If I update the user secret in Kubernetes, will the ClickHouse operator automatically detect this change and update the user password in ClickHouse accordingly?

2. In a similar vein, if I delete a user from the Kubernetes secret, does the operator take action to remove the corresponding user from ClickHouse, or is manual intervention required?

Understanding the lifecycle and management of user credentials is crucial for maintaining secure and seamless database operations. I would greatly appreciate some guidance on these points.

Thank you for your support!

Best regards,
Mehdi

**Comment by Slach** [comment]
> If I update the user secret in Kubernetes, will the ClickHouse operator automatically detect this change and update the user password in ClickHouse accordingly?

Do you mean upgrade secret name reference inside `kind: ClickHouse installation` resource?
Then answer will yes

Or upgrade secret content?
then answer will no

**Comment by Slach** [comment]
`clickhouse-operator` only watch and reconcile `kind: ClickHouseInstallation` resources
`kind: Secrets` resources is not watched

password generates in *usersd `ConfigMaps` as sha256 during reconciling cycle

you could manually trigger reconcile via changing `chi.spec.taskID`

**Comment by emahdij** [comment]
Could you tell me more about changing  ```chi.spec.taskID``` ?
After that I update secret content what I have to do?

**Comment by Slach** [comment]
look
```bash
kubectl explain chi
kubectl explain chi.spec
kubectl explain chi.spec.taskID
```

**Comment by emahdij** [comment]
Thanks alot
