### ISSUE TITLE
Release 0.23.0

### ISSUE THREAD

**Issue by morkalfon** [Altinity/clickhouse-operator#1274]
Hello,
Would it be possible for you to release the latest version of the operator 0.23.0 so it will be available to be installed as helm chart from https://docs.altinity.com/clickhouse-operator ? 
We're looking forward to test the integration to the ClickHouse Keeper.
Thanks!

**Comment by Slach** [comment]
0.23.0 still not ready, we continue to refactoring keeper manifests
just subscribe releases and watch
