### ISSUE TITLE
error: SchemaError(com.altinity.clickhouse.v1.ClickHouseInstallation.status.usedTemplates): array should have exactly one sub-item

### ISSUE THREAD

**Issue by jicki** [Altinity/clickhouse-operator#1279]
version 0.22.0

install operator 

error: SchemaError(com.altinity.clickhouse.v1.ClickHouseInstallation.status.usedTemplates): array should have exactly one sub-item

**Comment by jicki** [comment]
https://github.com/kubernetes/kubernetes/pull/96562

Is there a way to bypass this error?

**Comment by Slach** [comment]
Do you upgrade exists clickhouse-operator or install from scratch?
Do you use helm?

**Comment by Slach** [comment]
Which version of kubernetes do you use?

**Comment by jicki** [comment]
> Do you upgrade exists clickhouse-operator or install from scratch? Do you use helm?

install from scratch  

kubernetes version v1.19.3 

use  `kubectl apply -f crd.yaml`

**Comment by alex-zaitsev** [comment]
1.19 is too old, we suggest to upgrade to 1.21 or above.
