### ISSUE TITLE
Clarification request regarding default user password in the operator pod 

### ISSUE THREAD

**Issue by marblerun** [Altinity/clickhouse-operator#1281]
Hi,

We seem to have run into an issue in our kubernetes clusters where a connection from the clickhouse-operator pod to the clickhouse pods as the default user is being denied.

We create a simple 3 replica cluster and define the default users hashed password in our setup yaml file, and can access clickhouse without any issue. But as the logs on all 3 pods suggest an account issue, I thought I ought to resolve this.

I've looked through the documentation, and there appears to be an issue here. I thought it might be possible to shell across to the operator pod to make some changes, but most shell commands appear to be unavailable. I believe the config files should be available as mounted volumes, but a, can't see them from the shell, and b, they also don't appear if I try to open a maintenance pod to look at volumes at a node level.

In the operator docs, I found quite a bit of info in the security hardening guide. This suggests that the default user password isn't set in the operator pod. Working down a little, there is a section about changing the password of the clickhouse-operator account, so I looked at this to see if it might help with the default account.

> To change 'clickhouse_operator' user password you can modify etc-clickhouse-operator-files configmap or create ClickHouseOperatorConfiguration object.

> See [operator configuration](https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_configuration.md) for more information about operator configuration files.

> The operator protects access for the 'clickhouse_operator' user using an IP mask. When deploying a user into a ClickHouse server, access is restricted to the IP address of the pod where the operator is running, and nothing else. Therefore, the 'clickhouse_operator' user can not be used outside of this pod.

However, if I look at the configmap mentioned, it then says to only change the template file. If that is the case, where might that file be.

The pods are running on an alpine image, and the operator details are shown below.

So, in a nutshell, how do I best get the default user password to match across the operator and database pods ?

> install
> 
> curl -s https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator-web-installer/clickhouse-operator-install.sh | OPERATOR_NAMESPACE=clickhouse bash
> 
> root@kube-1:~# kubectl get pods -n clickhouse
> NAME                                   READY   STATUS    RESTARTS       AGE
> chi-deai-deai-0-0-0                    2/2     Running   2 (2d5h ago)   8d
> chi-deai-deai-0-1-0                    2/2     Running   0              2d9h
> chi-deai-deai-0-2-0                    2/2     Running   0              8d
> clickhouse-operator-5df6885f7c-zq5sd   2/2     Running   0              26h
> zookeeper-0                            1/1     Running   0              13d
> zookeeper-1                            1/1     Running   0              2d9h
> zookeeper-2                            1/1     Running   0              13d
> 
> root@kube-1:~# kubectl -n clickhouse describe pod clickhouse-operator-5df6885f7c-zq5sd
> Name:             clickhouse-operator-5df6885f7c-zq5sd
> Namespace:        clickhouse
> Priority:         0
> Service Account:  clickhouse-operator
> Node:             kube-4/[192.168.0.5](http://192.168.0.5/)
> Start Time:       Mon, 27 Nov 2023 18:16:47 +0200
> Labels:           app=clickhouse-operator
>                   [clickhouse.altinity.com/app=chop](http://clickhouse.altinity.com/app=chop)
>                   [clickhouse.altinity.com/chop=0.22.0](http://clickhouse.altinity.com/chop=0.22.0)
>                   [clickhouse.altinity.com/chop-commit=689d35c](http://clickhouse.altinity.com/chop-commit=689d35c)
>                   [clickhouse.altinity.com/chop-date=2023-11-06T09.03.18](http://clickhouse.altinity.com/chop-date=2023-11-06T09.03.18)
>                   pod-template-hash=5df6885f7c
> Annotations:      [cni.projectcalico.org/containerID](http://cni.projectcalico.org/containerID): ca6cf748b9934a5947633ea1bf943d3705190d81b985ffb62d3dc4fc5aeeb694
>                   [cni.projectcalico.org/podIP](http://cni.projectcalico.org/podIP): [10.233.122.26/32](http://10.233.122.26/32)
>                   [cni.projectcalico.org/podIPs](http://cni.projectcalico.org/podIPs): [10.233.122.26/32](http://10.233.122.26/32)
>                   [prometheus.io/port](http://prometheus.io/port): 8888
>                   [prometheus.io/scrape](http://prometheus.io/scrape): true
> Status:           Running
> IP:               10.233.122.26
> IPs:
>   IP:           10.233.122.26
> Controlled By:  ReplicaSet/clickhouse-operator-5df6885f7c
> Containers:
>   clickhouse-operator:
>     Container ID:   containerd://ea9bd74e35718abc5e1f4c702cc8c71428dfa5ee3285e303be83e9bd8973b6d8
>     Image:          altinity/clickhouse-operator:0.22.0
>     Image ID:       [docker.io/altinity/clickhouse-operator@sha256:e3b80713a06e5507495c17a078adcd526f8cd68d1c289fd72eed3ace5db2df2a](http://docker.io/altinity/clickhouse-operator@sha256:e3b80713a06e5507495c17a078adcd526f8cd68d1c289fd72eed3ace5db2df2a)
>     Port:           9999/TCP
>     Host Port:      0/TCP
>     State:          Running
>       Started:      Mon, 27 Nov 2023 18:16:48 +0200
>     Ready:          True
>     Restart Count:  0
>     Environment:
>       OPERATOR_POD_NODE_NAME:           (v1:spec.nodeName)
>       OPERATOR_POD_NAME:               clickhouse-operator-5df6885f7c-zq5sd (v1:[metadata.name](http://metadata.name/))
>       OPERATOR_POD_NAMESPACE:          clickhouse (v1:metadata.namespace)
>       OPERATOR_POD_IP:                  (v1:status.podIP)
>       OPERATOR_POD_SERVICE_ACCOUNT:     (v1:spec.serviceAccountName)
>       OPERATOR_CONTAINER_CPU_REQUEST:  0 (requests.cpu)
>       OPERATOR_CONTAINER_CPU_LIMIT:    node allocatable (limits.cpu)
>       OPERATOR_CONTAINER_MEM_REQUEST:  0 (requests.memory)
>       OPERATOR_CONTAINER_MEM_LIMIT:    node allocatable (limits.memory)
>     Mounts:
>       /etc/clickhouse-operator from etc-clickhouse-operator-folder (rw)
>       /etc/clickhouse-operator/conf.d from etc-clickhouse-operator-confd-folder (rw)
>       /etc/clickhouse-operator/config.d from etc-clickhouse-operator-configd-folder (rw)
>       /etc/clickhouse-operator/templates.d from etc-clickhouse-operator-templatesd-folder (rw)
>       /etc/clickhouse-operator/users.d from etc-clickhouse-operator-usersd-folder (rw)
>       /var/run/secrets/[kubernetes.io/serviceaccount](http://kubernetes.io/serviceaccount) from kube-api-access-kjz9n (ro)
>   metrics-exporter:
>     Container ID:   containerd://6ba5767d9178ab8182f6b7d4f06fa42505c6f13688f43670a93770d2dd3529d5
>     Image:          altinity/metrics-exporter:0.22.0
>     Image ID:       [docker.io/altinity/metrics-exporter@sha256:7c7b911e7be0a69e09f49b32fd836a8127d668215b71027b2e5bfab4a2381083](http://docker.io/altinity/metrics-exporter@sha256:7c7b911e7be0a69e09f49b32fd836a8127d668215b71027b2e5bfab4a2381083)
>     Port:           8888/TCP
>     Host Port:      0/TCP
>     State:          Running
>       Started:      Mon, 27 Nov 2023 18:16:49 +0200
>     Ready:          True
>     Restart Count:  0
>     Environment:
>       OPERATOR_POD_NODE_NAME:           (v1:spec.nodeName)
>       OPERATOR_POD_NAME:               clickhouse-operator-5df6885f7c-zq5sd (v1:[metadata.name](http://metadata.name/))
>       OPERATOR_POD_NAMESPACE:          clickhouse (v1:metadata.namespace)
>       OPERATOR_POD_IP:                  (v1:status.podIP)
>       OPERATOR_POD_SERVICE_ACCOUNT:     (v1:spec.serviceAccountName)
>       OPERATOR_CONTAINER_CPU_REQUEST:  0 (requests.cpu)
>       OPERATOR_CONTAINER_CPU_LIMIT:    node allocatable (limits.cpu)
>       OPERATOR_CONTAINER_MEM_REQUEST:  0 (requests.memory)
>       OPERATOR_CONTAINER_MEM_LIMIT:    node allocatable (limits.memory)
>     Mounts:
>       /etc/clickhouse-operator from etc-clickhouse-operator-folder (rw)
>       /etc/clickhouse-operator/conf.d from etc-clickhouse-operator-confd-folder (rw)
>       /etc/clickhouse-operator/config.d from etc-clickhouse-operator-configd-folder (rw)
>       /etc/clickhouse-operator/templates.d from etc-clickhouse-operator-templatesd-folder (rw)
>       /etc/clickhouse-operator/users.d from etc-clickhouse-operator-usersd-folder (rw)
>       /var/run/secrets/[kubernetes.io/serviceaccount](http://kubernetes.io/serviceaccount) from kube-api-access-kjz9n (ro)
> Conditions:
>   Type              Status
>   Initialized       True
>   Ready             True
>   ContainersReady   True
>   PodScheduled      True
> Volumes:
>   etc-clickhouse-operator-folder:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      etc-clickhouse-operator-files
>     Optional:  false
>   etc-clickhouse-operator-confd-folder:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      etc-clickhouse-operator-confd-files
>     Optional:  false
>   etc-clickhouse-operator-configd-folder:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      etc-clickhouse-operator-configd-files
>     Optional:  false
>   etc-clickhouse-operator-templatesd-folder:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      etc-clickhouse-operator-templatesd-files
>     Optional:  false
>   etc-clickhouse-operator-usersd-folder:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      etc-clickhouse-operator-usersd-files
>     Optional:  false
>   kube-api-access-kjz9n:
>     Type:                    Projected (a volume that contains injected data from multiple sources)
>     TokenExpirationSeconds:  3607
>     ConfigMapName:           kube-root-ca.crt
>     ConfigMapOptional:       <nil>
>     DownwardAPI:             true
> QoS Class:                   BestEffort
> Node-Selectors:              <none>
> Tolerations:                 [node.kubernetes.io/not-ready:NoExecute](http://node.kubernetes.io/not-ready:NoExecute) op=Exists for 300s
>                              [node.kubernetes.io/unreachable:NoExecute](http://node.kubernetes.io/unreachable:NoExecute) op=Exists for 300s
> Events:                      <none>
> 

Thanks,

Mike

**Comment by alex-zaitsev** [comment]
Hi @marblerun , sorry this has been unanswered. The operator does not use default user, it only uses clickhouse-operator user. You may change default user password in CHI configuration (spec.configuration.users), but by default it is protected by network rules so connections from outside are not permitted. See this more more detail: https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#the-default-user
