### ISSUE TITLE
A table becomes in read-only mode when trying to flush the buffer during the async insert

### ISSUE THREAD

**Issue by tanchik-curly** [Altinity/clickhouse-operator#1284]
Hi, I tried to switch to an async insert to avoid db overloading with many small inserts. Still, I faced a problem that I started to receive a lot of 408 errors (on query level I'm doing axios query inside a cluster with max execution time config from 9 to 15 seconds, depending on query).
I tried to increase async_insert_busy_timeout_ms to 5000/4000/2000, but it became even worse, I checked the asynchronous_insert_log table and saw that some queries take minutes to be executed, what should I improve then?

<img width="1297" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/67906338/ec448930-aeb0-46bd-8572-b7412e9402fb">
<img width="1019" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/67906338/abf7756e-5fd4-4b83-a89d-084ce8d671cf">
<img width="691" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/67906338/b9cde5d1-ecba-4b6b-ae68-75611cda6f7d">

**Comment by Slach** [comment]
How this issue related to `clickhouse-operator`?
Could you make question in https://github.com/CLickHouse/ClickHouse/?
