### ISSUE TITLE
Inconsistency in Service Monitor Endpoint Port Name after Recent Helm Chart 

### ISSUE THREAD

**Issue by thuban-arrakis** [Altinity/clickhouse-operator#1285]
I recently came across an issue in the Altinity/clickhouse-operator project, specifically related to the Helm chart for the ClickHouse operator. The problem is with the service monitor endpoint port name in the Helm chart.

**Issue Description:**
The recent release included a change in the service metric port naming. The service port name was updated from `clickhouse-operator-metrics` to `clickhouse-metrics`. This change is reflected in the following commit: [faa90c7](https://github.com/Altinity/clickhouse-operator/commit/faa90c781858169a509e9ad80c3abbebf1740a46#diff-24f1ff8e370cb5833c7bfebe8fa6e9f06e65c232642572219849f391120c2070L20).

However, the service-monitor.yaml file still references the old port name in its specification:

```
spec:
  endpoints:
  - port: clickhouse-operator-metrics
  
```
**Expected Behavior:**
The service-monitor.yaml file should reference the new port name clickhouse-metrics to stay consistent with the recent changes in the Helm chart.

**Suggested Solution:**
I will be submitting a pull request to update the service-monitor.yaml file to reflect the new port name. This should align the service monitor configuration with the recent changes and ensure proper functionality.

Please let me know if there are any additional steps or considerations I should be aware of in resolving this issue.

**Comment by Slach** [comment]
next release of helm chart 0.23.0 will contain fix https://github.com/Altinity/clickhouse-operator/commit/98a2f431084c86bdbd5a2be47876f5bd018c24b1
