### ISSUE TITLE
Generated ServiceMonitor is scraping non existent port 'clickhouse-operator-metrics'

### ISSUE THREAD

**Issue by ondrej-smola** [Altinity/clickhouse-operator#1287]
In generated service monitor spec there is  endpoint `clickhouse-operator-metrics`

https://github.com/Altinity/clickhouse-operator/blob/6e7a769a19cd40b68b507d4e77e0ddd5dfce98fa/deploy/helm/templates/servicemonitor.yaml#L14

But in generated service there is `clickhouse-metrics` and `operator-metrics`

https://github.com/Altinity/clickhouse-operator/blob/6e7a769a19cd40b68b507d4e77e0ddd5dfce98fa/deploy/helm/templates/generated/Service-clickhouse-operator-metrics.yaml#L22

**Comment by Slach** [comment]
@ondrej-smola will release in 0.22.2
