### ISSUE TITLE
all-shards cluster

### ISSUE THREAD

**Issue by tanner-bruce** [Altinity/clickhouse-operator#1291]
We have a use case where we would like to have multiple CH clusters, but allow querying all shards from each cluster from a single place, similar to `all-sharded`. The key difference being that we respect the replication of shards, instead of treating each replica as its own shard.

For example:

```yaml
clusters:
  prod_one:
    replicas: 2
    shards: 2
  prod_two:
    replicas: 2
    shards: 2
```

and have a resulting settings.conf cluster like

```xml
<clusters>
  <all-shards>
    <shard>
      <internal_replication>True</internal_replication>
      <replica>
        prod_one-0-0 // shorthand for brevity
      </replica>
      <replica>
        prod_one-0-1
      </replica>
    </shard>
    <shard>
      <internal_replication>True</internal_replication>
      <replica>
        prod_one-1-0
      </replica>
      <replica>
        prod_one-1-1
      </replica>
    </shard>
    <shard>
      <internal_replication>True</internal_replication>
      <replica>
        prod_two-0-0
      </replica>
      <replica>
        prod_two-0-1
      </replica>
    </shard>
    <shard>
      <internal_replication>True</internal_replication>
      <replica>
        prod_two-1-0
      </replica>
      <replica>
        prod_two-1-1
      </replica>
    </shard>
  </all-shards>
</clusters>
```

We could then create a distributed table on the `all-shards` cluster, which would fan out the query to each shard in all clusters.

I have a draft of the code required to do so already. If a PR for this is welcome, I will happily make one

**Comment by Slach** [comment]
We are welcome to PR
but please name this cluster as something like `chi-<chi_name>` 

`all-shards` like not mental name because `all-sharded` means entirely different behavior

Moreover, could you explain more detailed your use case?
Why do you need different clusters instead of just using:
```yaml
clusters:
  prod:
    layout:
      replicasCount: 2
      shardsCount: 4
```

**Comment by UnamedRus** [comment]
Actually, operator currently missing any way to customize remote_servers configuration, probably some templating option would be nice to have for it.

May be automatic cluster discovery feature can be used here(problem it's experimental, so potentially can be removed by ClickHouse team)

https://github.com/ClickHouse/ClickHouse/blob/4ff0eefe23f5209caa628b26f53f77790c761d0e/docs/en/operations/cluster-discovery.md?plain=1#L59

**Comment by Slach** [comment]
@UnamedRus yes, great suggestion

@tanner-bruce try to use

```yaml
spec:
 configuration:
   files:
     config.d/whole-chi-cluster.xml: |
       <remote_servers>
         <all-prods>
           <discovery>
              <path>/clickhouse/discovery/{all-prods}</path>
           </discovery>
        </all-prods>
       </remote_servers>
```

**Comment by UnamedRus** [comment]
IMO, it still make sense to have some templating options in operator, to generate such configuration.
For example, we need to populate shard value in config. (currently probably it can be done, if we populate value in config from ENV)
