### ISSUE TITLE
Does current clickhouse operator support clickhouse-keeper component?

### ISSUE THREAD

**Issue by hueiyuan** [Altinity/clickhouse-operator#1298]
Hi, everyone.

We want to setup clickhouse-cluster on AWS EKS. About replication we would like to apply clickhouse-keeper to process instead of Apache Zookeeper. I want to check whether this operator supports clickhouse-keeper? Because based on README.md, which just mention Apache Zookeeper settings.

**Comment by Slach** [comment]
this functionality is not released yet, and clickhouse-keeper is not well tested, watch https://github.com/Altinity/clickhouse-operator/tree/0.23.0 for progress

**Comment by hueiyuan** [comment]
@Slach Thanks for your reply.
Does have ETA about this version?

**Comment by Slach** [comment]
We don't provide any ETA
