### ISSUE TITLE
How can this operator support olm?

### ISSUE THREAD

**Issue by HuangQAQ** [Altinity/clickhouse-operator#1305]
I want to integrate this operator into the catalog in openshift. Is it supported now?

**Comment by Slach** [comment]
look https://artifacthub.io/packages/olm/community-operators/clickhouse

**Comment by HuangQAQ** [comment]
Thanks!




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Altinity/clickhouse-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月11日(星期四) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Altinity/clickhouse-operator] How can this operator support olm? (Issue #1305)





 
look https://artifacthub.io/packages/olm/community-operators/clickhouse
