### ISSUE TITLE
restart attribute in chi

### ISSUE THREAD

**Issue by UnamedRus** [Altinity/clickhouse-operator#1306]
attribute to make rolling restart/recreation for all pods of CHI
More gracefully analogue to do stop: "yes"/"no"

```
spec:
  stop: "yes"
```

```
spec:
   restart: "some version value"
```

If restart value is changed, operator does rolling restart.

**Comment by Slach** [comment]
this is have no sense

if you want to just restart clickhouse-server execute following command
```
kubectl get pods -n <your-namespace> -o name -l clickhouse.altinity.com/chi=<your-chi-name> | xargs -P 16 -I{} kubectl exec -n <your-namespace> {} -c clickhouse-pod -- clickhouse-client --echo -q "SYSTEM SHUTDOWN"
```

**Comment by UnamedRus** [comment]
> if you want to just restart clickhouse-server execute following command

It's not rolling

**Comment by Slach** [comment]
> It's not rolling

in this case just remove `xargs -P`  and add `kubectl wait`

something like that
```bash
kubectl get pods -n <your-namespace> -o name -l clickhouse.altinity.com/chi=<your-chi-name> | xargs -t -I{} bash -xe -c "kubectl exec -n <your-namespace> {} -c clickhouse-pod -- clickhouse-client --echo -q 'SYSTEM SHUTDOWN' && kubectl wait -n <your-namespace> --for=condition=Ready=true pod/{} || exit 255" 
```
