### ISSUE TITLE
Generating strong dhparam secret for enabling TLS

### ISSUE THREAD

**Issue by morkalfon** [Altinity/clickhouse-operator#1307]
Hello all,

Just wondering if you have an idea for a solution to this.

To enable TLS connections, we must create a Diffie-Hellman parameters file (dhparam). This process is pretty computationally expensive and requires openssl.

I wonder how do you recommend automating the creation of the secret while automating deployments of new environments in K8s using stack tools like Argo, Helm etc.

Thanks!

**Comment by UnamedRus** [comment]
BTW, Diffie-Hellman (DH) file is optional, if not specified or empty, the default parameters are used.
