### ISSUE TITLE
Does clickhouse support sso based user authentication

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1325]
Can we use providers like okta to login to clickhouse?

**Comment by UnamedRus** [comment]
This kind of question are related to ClickHouse itself, so it should go to https://github.com/ClickHouse/ClickHouse

But, there was attempt to introduce external http based auth. https://github.com/ClickHouse/ClickHouse/pull/55199
It was made to integrate with Cloud Auth providers.
