### ISSUE TITLE
Does cllckhouse-operator support clickhouse keeper

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1334]
I tried to apply this  https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/01-simple-1.yaml  but no resources were created.

 with the latest version of clickhouse server I was having issues with replication with zookeeper so i considered using the recommended clickhouse-keeper. I used the below 2 
 
 **zookeeper**: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/zookeeper/zookeeper-manually/quick-start-persistent-volume/zookeeper-1-node-create.sh

**clickhouse-cluster:**https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md

**Comment by Slach** [comment]
@manishtradebyte which clickhouse-operator version do you use?

**Comment by Slach** [comment]
CHIK resources supported from 0.23.0
