### ISSUE TITLE
Broken metrics in v0.23.0

### ISSUE THREAD

**Issue by Hexta** [Altinity/clickhouse-operator#1336]
After upgrading Operator to v0.23.0 ClickHouse Prometheus metrics disappeared.

In metrics-exporter logs
```plain
prometheus_writer.go:281] Error creating metric metric_RestartReplicaThreads: "kustomize.toolkit.fluxcd.io/name" is not a valid label name for metric "chi_clickhouse_metric_RestartReplicaThreads"
```

**Comment by alex-zaitsev** [comment]
@Hexta , thank you for reporting. We will get it fixed in 0.23.1 (this week).

**Comment by alex-zaitsev** [comment]
@Hexta , please try 0.23.1 -- it should fix your issue.

**Comment by Hexta** [comment]
@alex-zaitsev It works, thanks!

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.23.1
