### ISSUE TITLE
clickhouse keeper installation fails example

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1339]
I installes clickhouse-operator version 0.23.0 using below command
`
 k apply  -f https://github.com/Altinity/clickhouse-operator/raw/0.23.0/deploy/operator/clickhouse-operator-install-bundle.yaml
`

Then I tried to deploy the emample given https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/02-extended-3-nodes.yaml.

`
Error from server (BadRequest): error when creating "clickhouse-operator/docs/chk-examples/02-extended-3-nodes.yaml": ClickHouseKeeperInstallation in version "v1" cannot be handled as a ClickHouseKeeperInstallation: strict decoding error: unknown field "spec.podTemplate", unknown field "spec.settings", unknown field "spec.volumeClaimTemplates"
`

**Comment by hueiyuan** [comment]
I also have encountered this problem. And after check it, this example have some problems, which need to be fine-tuned.
* `podTemplate` --> `podTemplates`.

**Comment by alex-zaitsev** [comment]
@hueiyuan , we will fix examples ASAP. Those were left from the original PR and have not been corrected.

**Comment by alex-zaitsev** [comment]
Examples were corrected, please check them out

**Comment by hueiyuan** [comment]
@alex-zaitsev 
Could you assist to check #1329 this issue? because we have encountered the extend problems.
