### ISSUE TITLE
Annotations don't work

### ISSUE THREAD

**Issue by DTvGe45vc** [Altinity/clickhouse-operator#134]
Dear Sir or Madam

Could you help me?
I try to configure clickhouse-cluster without External_IP, but can't have this result.
I use this annotation:
      service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
but clickhouse-operator doesn't set it for LoadBalancer

How can I solve my problem?

**Comment by alex-zaitsev** [comment]
@DTvGe45vc please:
1) Confirm you are using latest version of Operator. Service templates have been added in 0.4.1. You can find it in labels, e.g.:

$ kubectl get deployment clickhouse-operator -L version -n kube-system

2) attach a example of your Yaml file for review.

**Comment by DTvGe45vc** [comment]
I use VERSION 0.4.0

YALM:

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "my-simple-02-pv1"
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  defaults:
    templates:
      serviceTemplate: chi-service-template
      volumeClaimTemplate: volumeclaim-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.test-clickhouse-operator
          port: 2181
        - host: zookeeper-1.zookeepers.test-clickhouse-operator
          port: 2181
        - host: zookeeper-2.zookeepers.test-clickhouse-operator
          port: 2181
    clusters:
      - name: "simple-pv"
        layout:
          type: Standard
          shardsCount: 2
          replicasCount: 1

  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: "service-{chi}"
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
          type: loadBalancer
      - name: replica-service-template
        # type ServiceSpec struct from k8s.io/core/v1
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None

    volumeClaimTemplates:
      - name: volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

**Comment by DTvGe45vc** [comment]
I updated clickhouse-operator. Problem stayed on.

**Comment by alex-zaitsev** [comment]
Confirmed. @sunsingerus, please take a look.

**Comment by sunsingerus** [comment]
Service Template Metadata update merged into 0.4.2 branch. Usage example is [available](https://github.com/Altinity/clickhouse-operator/blob/786c0e7b86337c0963596d525fb43d39f065e3fa/docs/examples/10-zones-03-advanced-03-pod-per-host-default-storage-class.yaml#L36)

**Comment by alex-zaitsev** [comment]
Released in 0.4.2
