### ISSUE TITLE
Custom Http Response Headers

### ISSUE THREAD

**Issue by ekatabavkar** [Altinity/clickhouse-operator#1348]
I need to set certain http response headers for security reasons. For example: 
"X-Frame-Options","SAMEORIGIN"
"X-Content-Type-Options","nosniff"

Can you share an example of http_handlers where i can set these properties?

**Comment by UnamedRus** [comment]
If you are talking about ClickHouse server, here is relevant feature request https://github.com/ClickHouse/ClickHouse/issues/59620

**Comment by Slach** [comment]
@ekatabavkar unfortunately `clickhouse-server` don't support returning custom HTTP Headers in HTTP response, so we can't configure headers via `clickhouse-operator`
