### ISSUE TITLE
Helm chart - allow adding additional pod labels to deployment

### ISSUE THREAD

**Issue by bruno-s-coelho** [Altinity/clickhouse-operator#1356]
Hi all 👋 

As I can see, we [can set](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/templates/generated/Deployment-clickhouse-operator.yaml#L26) pod annotations dynamically. However, we can't set labels. All labels are created with helpers, and we can't create additional new ones, as we can see [here](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/templates/generated/Deployment-clickhouse-operator.yaml#L17).

Would be possible to allow us to add new labels? As we can do with annotations?

Thanks,
Bruno

**Comment by Slach** [comment]
Which pod exactly do you mean? clickhouse-operator? or pod with clickhouse-server?

**Comment by bruno-s-coelho** [comment]
Hi 👋 

clickhouse-operator

**Comment by Slach** [comment]
feel free to make pull request look to
https://github.com/Altinity/clickhouse-operator/blob/master/dev/generate_helm_chart.sh and try to figure out

**Comment by bruno-s-coelho** [comment]
Hi @Slach,

I tried to push a branch, however I had the following error:
`dev git:(issue_1356_podlabels)     git push --set-upstream origin issue_1356_podlabels
ERROR: Permission to Altinity/clickhouse-operator.git denied to bruno-s-coelho.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Can you help here?

Thanks,
Bruno

**Comment by bruno-s-coelho** [comment]
Hi @Slach,

I tried to create a new PR however I had the following error:

```shell
➜  dev git:(master) ✗ git checkout 0.23.3
M       deploy/helm/README.md
M       deploy/helm/templates/_helpers.tpl
M       deploy/helm/templates/generated/Deployment-clickhouse-operator.yaml
M       deploy/helm/templates/generated/ServiceAccount-clickhouse-operator.yaml
M       dev/generate_helm_chart.sh
branch '0.23.3' set up to track 'origin/0.23.3'.
Switched to a new branch '0.23.3'

➜  dev git:(0.23.3) ✗ git checkout -b issue_1356
Switched to a new branch 'issue_1356'

➜  dev git:(issue_1356) ✗ git add -A && git commit -m "Issue 1356 Update helm chart to allow add pod labels" && git push
[issue_1356 8386c692] Issue 1356 Update helm chart to allow add pod labels
 5 files changed, 7 insertions(+), 3 deletions(-)
fatal: The current branch issue_1356 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin issue_1356

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.

➜  dev git:(issue_1356)     git push --set-upstream origin issue_1356
ERROR: Permission to Altinity/clickhouse-operator.git denied to bruno-s-coelho.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you help me here?
Thanks,
Bruno

**Comment by Slach** [comment]
@bruno-s-coelho create fork in your personal account
after that you can create pull request

**Comment by bruno-s-coelho** [comment]
Hi @Slach,
Just noticed that we already have a branch `0.23.4`. Could we add these modifications to that branch too?
Seems like 0.24.0 will take time to be released.

**Comment by Slach** [comment]
@bruno-s-coelho please create new PR to 0.23.4 i will merge it

**Comment by bruno-s-coelho** [comment]
Hi @Slach,

Done -> https://github.com/Altinity/clickhouse-operator/pull/1369

Thanks,
Bruno
