### ISSUE TITLE
The configuration that needs to be modified when replacing Zookeeper with clickhouse-keep in clickhouse-operator.

### ISSUE THREAD

**Issue by dxygit1** [Altinity/clickhouse-operator#1364]
How to replace Zookeeper with ClickHouse-keep in clickhouse-operator? What configurations need to be modified, and is there any related documentation?

**Comment by dxygit1** [comment]
So should I add ClickHouseKeeperInstallation or just remove the Zookeeper configuration?

**Comment by Slach** [comment]
You need to add `kind: ClickHouseKeeperInstallation` manifest
and convert 

you need to change `zookepeer` configuration section in `kind: ClickHouseInstallation` to reference to service which will created from `kind: ClickHouseKeeperInstallation`  and covered pods with `clickhouse-keeper`

If currently zookeeper works for you we don't recomennds to switch to clickhouse-keeper
Use it only for new projects

**Comment by dxygit1** [comment]
Do you have any documents?
I added CRD ，And the following files
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/02-extended-3-nodes.yaml

**Comment by dxygit1** [comment]
I don't know how to operate next
I am a new item
I want to know how volumeClaimTemplates are referenced

**Comment by dxygit1** [comment]
zookeper configuration section    How to modify it

**Comment by Slach** [comment]
Better use 1 keeper node, to avoid useless complexity

i updated comment https://github.com/Altinity/clickhouse-operator/issues/1364#issuecomment-1982496059
please read it

currently first `volumeClaimTemaplates` item
just mount inside keeper pod


> zookeper configuration section How to modify it

inside `kind: ClickHouseInstallation` manifest

modify existing
```yaml
spec:
 configuration:
  zookeeper:
    nodes:
      - host: clickhouse-keeper-service-name.namespace-name-where-keeper-installed
```  

> Is it just modifying the IP address？

use DNS service name

look
`kubectl get svc --all-namespaces` for service names

**Comment by dxygit1** [comment]
I understand, it's just a matter of changing the host of zookeeper to keep

About volumeClaimTemaplates

The document case is as follows

```   
volumeClaimTemplates:      
      - name: default
        spec:
          storageClassName: {{ .Values.global.acos.storageClass }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: snapshot-storage-path
        spec:
          storageClassName: {{ .Values.global.acos.storageClass }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi```
Will he quote himself if there is no reference in the document? Like in ClickHouseInstallation
Or do I still need to mount the volume myself using mountvolume?

**Comment by Slach** [comment]
i know nothing about   storageClassName: {{ .Values.global.acos.storageClass }}
looks like you use some custom helm chart on your side

AKAIK currently ClickHouseKeeperInstallation have only hardcoded mapping for volumeClaimTemplates

**Comment by dxygit1** [comment]
Okay, thank you very much
