### ISSUE TITLE
Can not add dictionary external csv to /var/lib/clickhouse/user_files/ path

### ISSUE THREAD

**Issue by hueiyuan** [Altinity/clickhouse-operator#1367]
We want to mount csv file to `/var/lib/clickhouse/user_files/ path` for dictionary can source from local. 
But is result in clickhouse pod can not start successfully. Does have any suggestion?

And if we volume mount to another path will have `Code: 481. DB::Exception: Received from localhost:9000. DB::Exception: File path /opt/clickhouse-dict/xxxx is not inside /var/lib/clickhouse/user_files/: While processing dictGet` Error

**Comment by Slach** [comment]
could you provide your current `kind: ClickHouseInstallation` manifest without sensitive data?

**Comment by alex-zaitsev** [comment]
@hueiyuan , the error message clearly says that you misconfugured the path. 

Also note, that paths with persistent data should be inside /var/lib/clickhouse.
