### ISSUE TITLE
Leader election for the operator

### ISSUE THREAD

**Issue by samof76** [Altinity/clickhouse-operator#1386]
Hi, Is anyone already working on leader election in the operator, otherwise could look at it? This is basically feature request.

**Comment by Slach** [comment]
Which kind of leader election do you mean?

clickhouse-operator is single binary which watch kubernetes api changes to reconcile cursom resources like `kind: ClickHouseInstallation`

**Comment by samof76** [comment]
I mean leader election on the Operator pods. So that I could run two instances of the operator pods so that one of them is the leader?

**Comment by Slach** [comment]
> I mean leader election on the Operator pods. So that I could run two instances of the operator pods so that one of them is the leader?

don't do it
by default Deployments contains `replicas: 1`

you can install

you can't install in common case different versions of clickhouse-operator if you will not have installed CRDs compatible with both operator version

if you have hundreds of clickhouse clusters in side one kubernetes cluster,
you can install two or more deployments of clickhouse-operator (better to different namespaces) but need to configure `clickhouse-operator` to watch separate namespaces, look to `etc-clickhouse-operator-files` configmap, `watch` section in `/etc/clickhouse-operator/config.yml`

default logic if `watch` not defined:

- if `clickhouse-operator` runs inside `kube-system` namespace, then will watch and reconcile all `chi,chit,chop,chk` custom resources in all namespaces
- if `clickhouse-operator` runs inside any other namespace, then will watch and reconcile all `chi,chit,chop,chk` custom resources only inside one namespace

**Comment by Kavinraja-G** [comment]
> if you install replicas: 2 it will race condition with each other

I think it's a best practice for operators to have implement `leaderElection`?

Also race condition won't occur during operator upgrades? Unless you have configured `recreate` in deployment strategy.

**Comment by Slach** [comment]
@Kavinraja-G you trying to add high availability in the case where high availability is not necessary

when a worker node will down, then deployment controller will try to reschedule pod to any available worker node

during upgrade clickhouse-operator, very short period when race condition is possible, but it will go away when the old version pod will destroy

when you have two replicas constantly
then both replicas attempt to watch the same custom resources and attempt to apply the same operations

clickhouse-operator is a stateless application, so you don't need multiple replicas

**Comment by gregakinman** [comment]
@Slach it's standard practice for k8s controllers to implement active-passive high availability via leader election: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/leaderelection. Notably, the newly released official ClickHouse operator is built with the standard controller-runtime library that supports leader election.

**Comment by Slach** [comment]
Unfortunately, our clickhouse operator began development before lot of modern libraries was present
