### ISSUE TITLE
how to solve clickhouse cluster aborted status?

### ISSUE THREAD

**Issue by hueiyuan** [Altinity/clickhouse-operator#1389]
## Description
We found that updating clickhouse cluster, it result in status is aborted. (it seems that cluster rolling update too long.)
And related logs are shown:
```
| clickhouse-operator I0410 02:30:45.990000       1 creator.go:233] onStatefulSetUpdateFailed():abort StatefulSet ipp-clickhouse-olap/chi-ck-cluster-ck-cluster-s1r0        │
│ clickhouse-operator I0410 02:30:45.990120       1 worker.go:1681] Update StatefulSet(ipp-clickhouse-olap/chi-ck-cluster-ck-cluster-s1r0) - got abort. Abort               │
│ clickhouse-operator W0410 02:30:46.126326       1 worker-chi-reconciler.go:697] reconcileHost():Reconcile Host interrupted with an error 3. Host: s1r0 Err: crud error -  │
│ should abort                                                                                                                                                              │
│ clickhouse-operator W0410 02:30:46.126436       1 worker-chi-reconciler.go:570] Skipping rest of shards due to an error: crud error - should abort                        │
│ clickhouse-operator E0410 02:30:46.126551       1 worker-chi-reconciler.go:108] reconcileCHI():ipp-clickhouse-olap/ck-cluster/5606947e-80da-4105-b343-db4691bb6bb7:FAILED │
│  to reconcile CHI err: crud error - should abort
| clickhouse-operator E0410 02:30:45.989888       1 creator.go:119] updateStatefulSet():StatefulSet update wait failed. err: poll(ipp-clickhouse-olap/chi-ck-cluster-ck-clu │
│ ster-s1r0) - wait timeout
```

How to solve it and convert status to `completed`?

clickhouse-operator version: `0.23.2`
clickhouse version: `24.1.5`

**Comment by Slach** [comment]
Check pods status and logs
could you share Without sensitive credentials?
```
kubectl get sts -n ipp-clickhouse-olap ck-cluster -o yaml
kubectl get pod -n ipp-clickhouse-olap chi-ck-cluster-ck-cluster-s1r0-0 -o yaml
kubectl describe pod -n ipp-clickhouse-olap chi-ck-cluster-ck-cluster-s1r0-0
```

**Comment by Slach** [comment]
`clickhouse-operator version: 0.24.2`
this is not official releases
look to
https://github.com/Altinity/clickhouse-operator/releases
do you mean 0.23.2?

**Comment by hueiyuan** [comment]
@Slach  Sorry, that is typo, right.

**Comment by hueiyuan** [comment]
@Slach 
We have solve this problem. Because we have added additional script in PostStart of K8s Lifecycle so that operator pull status of statefulset timeout. So we modified clickhouse operator `reconcile.statefulSet.update.timeout` settings.

**Comment by markandrus** [comment]
We just hit this ourselves. StatefulSet update took a long time (I guess because server startup takes a long time?). Is the answer to try another update and see if it takes/gets us out of the "Aborted" state?

**Comment by Slach** [comment]
@markandrus solution was provided here https://github.com/Altinity/clickhouse-operator/issues/1389#issuecomment-2046606639

edit ConfigMap etc-clickhouse-operator-files

increase timeout in reconcile section

Current timeout is 600 seconds in 0.23.5, it shall enough for 99% use cases

You need to figure out why your clickhouse started so long
