### ISSUE TITLE
ClickHouse Performance in Container(Docker).

### ISSUE THREAD

**Issue by GrigorievNick** [Altinity/clickhouse-operator#139]
Hi Altinity team,
Does your team make any performance benchmark over clickhouse on k8s/Docker?
In case, yes, What docker storage driver, CSI plugin, you use?
And what about CNI plugins?

**Comment by sunsingerus** [comment]
It would be an interesting quest to make performance comparison for different k8s setups. Would be nice to see results.

**Comment by Slach** [comment]
Maybe we need to think about automatization following benchmark instructions https://clickhouse.yandex/docs/en/operations/performance_test/ inside clickhouse-operator
