### ISSUE TITLE
ClickHouse pod update stuck when adjusting version or resource

### ISSUE THREAD

**Issue by hueiyuan** [Altinity/clickhouse-operator#1392]
### Description
Our clickhouse sever have 3 shard 2 replicas. When we update clickhouse version or modify resource of pods. The shard 0 and shard 1 can quickly update and recreate pod. But shard2 always hang and stuck... 

The log message of clickhouse-operator is always shown:
```
[cluster_schemer.go:281] IsHostInCluster():The host s2r0 is inside the cluster                                           │
│ clickhouse-operator I0411 07:59:01.700988       1 poller.go:170] Poll():xxx-clickhouse-olap/s2r0:WAIT:xxx-clickhouse-olap/s2r0
```
It seems that like waiting shard2 response.
For workaround, I manually restart statefulset to force update to avoid waiting to long so that timeout. 

Does anyone have idea about it and what is the root cause result in?

### version
clickhouse-operator: `0.23.2`
clickhouse: `24.1.8.22` (stable version)

**Comment by Slach** [comment]
Firstly, upgrade operator + CRD to 0.23.4

Second, could you please clarify, is CHI switched to status aborted or you just not wait and restart `StatefulSet` manually?
