### ISSUE TITLE
Change in user configuration leads to cluster restart

### ISSUE THREAD

**Issue by playdaddy** [Altinity/clickhouse-operator#1402]
We are testing clickhouse operator as a replacement for our cluster setup on EC2 instances.
We are managing users with xml file per user in users.d config folder.
Changes in users xml doesn't require server restart, but when we use `users` setting in CHI manifest, operator does restart the cluster. It looks like operator calculates config checksum and perform restart on any changes, but on my opinion it is incorrect. It should exclude configs which `can be changed in runtime`.
Also with lots of users it is not very convenient to manage them in CHI.
I understand that recommended way is sql, but it doesn't fit well into configuration as code (reason for operator existence) as we need db migration tool for that. Ideal scenario would be to allow custom configs (in addition to generated configmaps) to be mounted or added to generated with projection.

**Comment by Slach** [comment]
> setting in CHI manifest, operator does restart the cluster.

Which clickhouse-operator version do you use? latest releases should not restart clickhouse when you change `users`

Could you share your `kind: ClickHouseInstallation` manifest? without sensitive credentials?

**Comment by alex-zaitsev** [comment]
@playdaddy, change of users, both using users section and users.d files should not cause the restart. So if have an example when it does -- please share it.

**Comment by samof76** [comment]
We have noticed this in version 0.23.3.

**Comment by playdaddy** [comment]
we were using default operator install with bundle.
In this bundle in config section you have `settings/*: yes` as default value
I've commented out this, but didn't have a chance to test results

**Comment by Slach** [comment]
could you upgrade operator bundle to latest 0.23.5 release?
and look to
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-bundle.yaml#L3516-L3556
