### ISSUE TITLE
CHK example chk-examples/02-extended-3-nodes.yam doesn't work

### ISSUE THREAD

**Issue by orloffv** [Altinity/clickhouse-operator#1403]
https://github.com/Altinity/clickhouse-operator/blob/bbbf66a8e0fbbcf36b787a63eceeaca37e0ec272/docs/chk-examples/02-extended-3-nodes.yaml#L52-L66 with two persist storages
i see ```2024-04-22T22:15:49Z  Warning FailedScheduling  pod/clickhouse-keeper-0 0/34 nodes are available: persistentvolumeclaim "log-storage-path" not found. preemption: 0/34 nodes are available: 34 Preemption is not helpful for scheduling.  2024-04-22T21:57:47Z```
in logs

https://github.com/Altinity/clickhouse-operator/blob/bbbf66a8e0fbbcf36b787a63eceeaca37e0ec272/pkg/model/chk/creator.go#L104-L113

I don't think a set like this is expected.

**Comment by zeev1079** [comment]
change the `- name: default`  to `- name: log-storage-path`

**Comment by alex-zaitsev** [comment]
@Slach ^^

**Comment by Slach** [comment]
@alex-zaitsev already fixed in 0.24.0 in https://github.com/Altinity/clickhouse-operator/commit/93e7f6a99990b01561ea3e64e9a517e82bd2ccb1
