### ISSUE TITLE
Dashboard for ClickHouse Keeper

### ISSUE THREAD

**Issue by orloffv** [Altinity/clickhouse-operator#1405]
it's really dashboard for ClickHouse keeper? https://github.com/Altinity/clickhouse-operator/blob/master/grafana-dashboard/ClickHouseKeeper_dashboard.json

**Comment by Slach** [comment]
this dashboard is outdated
it prepared for early versions of `clickhuse-keeper` which not support prometheus metrics endpoint

we really open to contributions here

**Comment by Slach** [comment]
@ja14000 thans a lot for your PR, dashboard works as expected
