### ISSUE TITLE
Configure volumeClaimTemplates.reclaimPolicy in clickhouse keeper

### ISSUE THREAD

**Issue by orloffv** [Altinity/clickhouse-operator#1408]
in clickhouse - you can: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operatorhub/0.23.5/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml#L1144

in clickhouse keeper - it's not possible: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operatorhub/0.23.5/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml#L196

**Comment by Slach** [comment]
try clickhouse-operator 0.24.0
currently `kind:ClickHouseKeeperInstallation` in under deep refactoring, and will create new sets of `statefulset`, but `volumeClaimTemplates` will work in the same manner with `kind: ClickHouseInstallation`
