### ISSUE TITLE
Max Replica Delay after upgrade to 23.8

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1410]
After upgrade to the 23.8 version of clickhouse I've noticed max replica delay is steady growing in size to a huge numbers

what are the recommended methods to deal with it? This is 3 nodes replica and the table with this huge delay can be only seen on this pod only. I tried to OPTIMIZE FINAL, restarting pods etc, and nothing seems to be making any difference. The solution I tested working with other tables was to drop the table completely however since the altinity clickhouse-backup is not working as expected therefore restore from backup is not possible at this point.
Is there any way around it to fix it withough loosing data?  

```
chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) SELECT
table,
replica_name,
absolute_delay
FROM system.replicas
WHERE absolute_delay > 0

SELECT
    table,
    replica_name,
    absolute_delay
FROM system.replicas
WHERE absolute_delay > 0

Query id: 725f0626-1f40-469c-9965-07400dfaa329

┌─table──────────────────────┬─replica_name───────────┬─absolute_delay─┐
│ btc_all_activity_10_c_sell │ chi-ck3-replicated-0-0 │     1714560609 │
└──────────────
```──────────────┴────────────────────────┴────────────────┘

```
```
SELECT
    database,
    table,
    count() AS queue_size,
    sum(num_tries) AS total_tries,
    min(create_time) AS oldest_entry,
    max(last_attempt_time) AS last_attempt
FROM system.replication_queue
WHERE type != 'GET_PART'
GROUP BY
    database,
    table
ORDER BY queue_size DESC

Query id: 5bff4dfb-4baf-4b15-b798-26314cd3f3b5

Ok.

0 rows in set. Elapsed: 0.007 sec. 

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) 
```
```

**Comment by Slach** [comment]
issue is not related to clickouse-operator itself

look to 
```
SELECT hostName(), * 
FROM cluster('all-sharded',system.replication_queue)
WHERE table='btc_all_activity_10_c_sell'
FORMAT Vertical
```

**Comment by darioneto** [comment]
that seems to return no values when run on the pod with max delay 

```
SELECT hostName(), * 
FROM cluster('all-sharded',system.replication_queue)
WHERE table='btc_all_activity_10_c_sell'
FORMAT Vertical

SELECT
    hostName(),
    *
FROM cluster('all-sharded', system.replication_queue)
WHERE table = 'btc_all_activity_10_c_sell'
FORMAT Vertical

Query id: c0954731-c177-4734-ba28-c8be23945cef

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.8.12 revision 54465.

Ok.

0 rows in set. Elapsed: 0.021 sec. 
```

I'd imagine if I run 3 replicas (no shards) I should be able to just drop table from one pod and let the clickhouse resync? Is that possible ? Thsi in theory should be better then drop ON CLUSTER and restore from backup? What are the options I should look for to solve this issues? 

would something like this work with ReplicatedAggregatingMergeTree 

Tables are being created as such:

CREATE TABLE discord_alert.btc_all_activity_10_c_sell ON CLUSTER replicated
...
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/discord_alert.btc_all_activity_10_c_sell', '{replica}')

**Comment by Slach** [comment]
yes, you can DROP / CREATE table on each replica separatelly

and use `SYSTEM RESTART REPLICA db.table`

could you share?
```sql
SELECT hostName(), * FROM cluster('all-sharded',system.replicas) WHERE absolute_delay > 3600 FORMAT Vertical
```

**Comment by darioneto** [comment]
I'm concerned (from memory) that if I do that then I will run into issue where for some unknown reason I won't be able to recreate the table neither query it. In both cases there will be warning that either table doesn't exist when I try to fetch data or table already exist when I try to recreate after dropping. Have you come across of this issue before? 

```
SELECT
    hostName(),
    *
FROM cluster('all-sharded', system.replicas)
WHERE absolute_delay > 3600
FORMAT Vertical

Query id: 223d52ab-5b46-4bb8-a881-031fe1ffe782

Row 1:
──────
hostName():                  chi-ck3-replicated-0-0-0
database:                    discord_alert
table:                       btc_all_activity_10_c_sell
engine:                      ReplicatedAggregatingMergeTree
is_leader:                   0
can_become_leader:           1
is_readonly:                 1
is_session_expired:          1
future_parts:                0
parts_to_check:              0
zookeeper_name:              default
zookeeper_path:              /clickhouse/tables/0/discord_alert.btc_all_activity_10_c_sell
replica_name:                chi-ck3-replicated-0-0
replica_path:                /clickhouse/tables/0/discord_alert.btc_all_activity_10_c_sell/replicas/chi-ck3-replicated-0-0
columns_version:             -1
queue_size:                  0
inserts_in_queue:            0
merges_in_queue:             0
part_mutations_in_queue:     0
queue_oldest_time:           1970-01-01 00:00:00
inserts_oldest_time:         1970-01-01 00:00:00
merges_oldest_time:          1970-01-01 00:00:00
part_mutations_oldest_time:  1970-01-01 00:00:00
oldest_part_to_get:          
oldest_part_to_merge_to:     
oldest_part_to_mutate_to:    
log_max_index:               0
log_pointer:                 0
last_queue_update:           1970-01-01 00:00:00
absolute_delay:              1714570170
total_replicas:              0
active_replicas:             0
lost_part_count:             0
last_queue_update_exception: 
zookeeper_exception:         
replica_is_active:           {}

1 row in set. Elapsed: 0.355 sec. 

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) 
```

**Comment by darioneto** [comment]
yes so as I expected I've see this before on some other tables 

```
select count(*) from discord_alert.btc_all_activity_10_c_sell

SELECT count(*)
FROM discord_alert.btc_all_activity_10_c_sell

Query id: 8d19e2bc-06ff-4e8e-bf6b-6f83538bec9a

┌─count()─┐
│      97 │
└─────────┘

1 row in set. Elapsed: 0.004 sec. 

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) drop table discord_alert.btc_all_activity_10_c_sell

DROP TABLE discord_alert.btc_all_activity_10_c_sell

Query id: 008032a6-9220-4a27-acdd-6cb831b96b6f

Ok.

0 rows in set. Elapsed: 0.004 sec. 

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) select count(*) from discord_alert.btc_all_activity_10_c_sell

SELECT count(*)
FROM discord_alert.btc_all_activity_10_c_sell

Query id: d06276ee-2cc2-4e7e-9576-449a4d83775c


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 23.8.12):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table discord_alert.btc_all_activity_10_c_sell does not exist. Maybe you meant btc_all_activity_10_p_sell?. (UNKNOWN_TABLE)

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) 

on Another instance 
SELECT count(*)
FROM discord_alert.btc_all_activity_10_c_sell

Query id: 9a4a92da-be31-4cd8-9bb5-8fc86bfa52b9

┌─count()─┐
│     100 │
└─────────┘

1 row in set. Elapsed: 0.002 sec. 

chi-ck3-replicated-0-1-0.chi-ck3-replicated-0-1.ck.svc.cluster.local :) 


when I try to recreate the table on this node 

Received exception from server (version 23.8.12):
Code: 253. DB::Exception: Received from localhost:9000. DB::Exception: Replica /clickhouse/tables/0/discord_alert.btc_all_activity_10_c_sell/replicas/chi-ck3-replicated-0-0 already exists. (REPLICA_ALREADY_EXISTS)
```

and stuck, do you know how to fix this issue? This is very strange, in the past I just use different names of tables but in this way I loose past data when this issue happens all the time

**Comment by Slach** [comment]
> Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table discord_alert.btc_all_activity_10_c_sell does not exist. Maybe you meant btc_all_activity_10_p_sell?. (UNKNOWN_TABLE)

next time use `DROP TABLE db.table SYNC` or wait 480 seconds

look details in 
https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#old-parts-lifetime

this approach allows atomic non blocking DDL schema queries

**Comment by Slach** [comment]
`SELECT hostName(), count() FROM cluster('all-sharded',  discord_alert.btc_all_activity_10_c_sell)`

**Comment by darioneto** [comment]
here is what I get 

SELECT
    hostName(),
    count()
FROM cluster('all-sharded', discord_alert.btc_all_activity_10_c_sell)

Query id: 071557f2-75a5-49cf-adfa-5ed7f199d44e


0 rows in set. Elapsed: 0.017 sec. 

Received exception from server (version 23.8.12):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table discord_alert.btc_all_activity_10_c_sell does not exist. Maybe you meant btc_all_activity_10_p_sell?. (UNKNOWN_TABLE)

chi-ck3-replicated-0-0-0.chi-ck3-replicated-0-0.ck.svc.cluster.local :) 

How do I restore this replica on this pod now?

**Comment by Slach** [comment]
```sql
SYSTEM DROP REPLICA '{replica}' FROM ZKPATH '/clickhouse/tables/{shard}/discord_alert.btc_all_activity_10_c_sell'`

CREATE TABLE IF NOT EXISTS discord_alert.btc_all_activity_10_c_sell ON CLUSTER '{cluster}' (field1 ... fieldN) ENGINE=...ReplicatedMergeTree(''/clickhouse/tables/{shard}/{database}.{table}','{replica}');
```

**Comment by darioneto** [comment]
ah ok, this worked, thank you. 
Also this way I can recreate table of the same name in the future :-). Didn't know I have to also drop the ZKPATH to make it work.

**Comment by Slach** [comment]
use `DROP TABLE | DATABASE ... SYNC` to avoid problems in future

**Comment by darioneto** [comment]
ok thanks , will do , there should be no need to mess around with backup/restore then. With 3 replicas and no shards there should be fairly good level of redundancy I assume. 
However if I ever want to migrate the metadata/data to a new cluster what do you recommend doing?
