### ISSUE TITLE
Buggy manual keeper setup config

### ISSUE THREAD

**Issue by rauanmayemir** [Altinity/clickhouse-operator#1421]
I was trying to setup a clickhouse-keeper based on `deploy/clickhouse-keeper/clickhouse-keeper-manually` with both 3 nodes and 1 node.

Setup fails 100% of the times for `latest:alpine` (currently, `v24.4`).

```
+ NAME=clickhouse-keeper
+ ORD=0
+ MY_ID=1
++ clickhouse-keeper-client --history-file=/dev/null -h clickhouse-keeper.default.svc.cluster.local -p 2181 -q 'get /keeper/config'
Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: 172.32.30.172:2181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.4.1.2088 (official build)), 172.32.30.172:2181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.4.1.2088 (official build)), 172.32.30.172:2181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.4.1.2088 (official build)), 172.32.30.172:2181
```

I tried downgrading to `v23.12`, it will keep crashing one by one for 3 nodes.
What is currently the proper config?

**Comment by rauanmayemir** [comment]
`v23.9` seems to work, at least peers aren't crashing constantly.

**Comment by rauanmayemir** [comment]
So I tried scaling STS down to 0 replicas and then scaling it back up to 3 replicas, it will fail to boot itself because `peer-0` will fail to connect to `peer-1` and `peer-2`.

It's unreasonable to expect the cluster to be always alive, I think `keeperTeardown.sh` is not working properly?

**Comment by Slach** [comment]
We are open to pull requests, this is hard to debug keeperTeardown.sh

**Comment by rauanmayemir** [comment]
I mean, I’m using the exact same setup from the examples.

I’ll try to debug more some other time, but this setup is not even functioning properly, so I’m filing the issue for others lest they waste their weekend for nought.

**Comment by rauanmayemir** [comment]
Apparently, this setup does work, but takes _**a lot of time**_ to reach consensus.
E.g: 3 node cluster with OrderedReady policy will take about 3-4 minutes for the first 2 peers to boot and agree on the ring membership before the third pod can start, so all in all about 6 minutes for the cluster to become alive.
