### ISSUE TITLE
How to run an operator only in namespace mode?

### ISSUE THREAD

**Issue by tropnikovvl** [Altinity/clickhouse-operator#1422]
Hello!

How to run a clickhouse operator in only one namespace mode?
By this I mean not only restrictions on working in specific namespaces, but also a change in clusterwide access to the namespace level.

For example:

- use `Role` instead of `ClusterRole`
- use `RoleBinding` instead if `ClusterRoleBinding`

**Comment by Slach** [comment]
try to use 
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-ansible.yaml
as template
and use something as jinja2 for replace {{ namespace }}

**Comment by tropnikovvl** [comment]
@Slach 
I forgot to clarify that the question concerns the helm chart.
I want to deploy the helm chart operator to work only in one dedicated namespace without cluster-level rights.

**Comment by Slach** [comment]
by default helm chart install operator which watch only one namespace
but with cluster wide access limited access

in this case, you need to modify `templates` folder in helm chart
and replace `ClusterRole` to `Role` and `ClusterRoleBinding` to `RoleBinding`


look
https://github.com/Altinity/clickhouse-operator/tree/master/deploy/helm/clickhouse-operator/templates/generated
for details
