### ISSUE TITLE
clickhouse cluster not deployed with dedicated tolerations and affinity

### ISSUE THREAD

**Issue by aauer-powens** [Altinity/clickhouse-operator#1427]
Hello,
I have succeeded deployed a clickhouse-operator with the dedicated taints & tolerations.
I want now deploy a clickhouse cluster but i'm struggling to make it works. We user Karpenter in our k8s cluster and it's like my `ClickhouseInstallation` never have the corresponding tolerations.

I used [99-clickhouseinstallation-max.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml) to deploy clickhouse-operator with the corresponding `tolerations` i would want to add. Now i don't know how my clickhouse instance could have it.

If you could provide any help on how to achieve it, 

Many thanks

**Comment by hostmaster** [comment]
@aauer-powens Was a solution to the problem found?
