### ISSUE TITLE
Helm deployment: Clickhouse cluster

### ISSUE THREAD

**Issue by aauer-powens** [Altinity/clickhouse-operator#1428]
Hello,

The helm support for clickhouse operator is great. I would like to know how to deploy CHI with helm as well.
As we are using ArgoCD, it would be more convenient to use helm chart to deploy clickhouse cluster along the operator and i can't find any valuable documentation regarding this topic.

Many thanks

**Comment by Slach** [comment]
look to `additionalResources` in values.yaml

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/clickhouse-operator/values.yaml#L635-L661

**Comment by clemcvlcs** [comment]
@Slach 
Indeed `additionalResources` can do the job, but it's not very convenient. 
I think it would be much better to deploy a CH cluster from a separated release than the operator itself, to be allowed to create a cluster without touching the operator values.

So having a dedicated chart for the cluster deployment would be super helpful. 

As an example, [minio operator](https://github.com/minio/operator/tree/v6.0.4/helm) has two distinct charts, one for the operator, and one for the tenants.

**Comment by Slach** [comment]
@clemcvlcs we are welcome to PR
