### ISSUE TITLE
Examples to expose secure ports 8123 and 9000 9004

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1431]
I want to add tls encryption on the ports. I am exposing them by using ingress in an EKS cluster.

**Comment by ilkarataev** [comment]
In kind: ClickHouseInstallation, in files section you need 
```
   files:
      openssl.xml: |
        <clickhouse>
          <openSSL>
            <server>
              <certificateFile>/etc/clickhouse-server/secrets.d/servercrt/tls/tls.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-server/secrets.d/serverkey/tls/tls.key</privateKeyFile>
              <dhParamsFile></dhParamsFile>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
            </server>
          </openSSL>
        </clickhouse>
      servercrt:
        valueFrom:
          secretKeyRef:
            name: tls
            key: tls.crt
      serverkey:
        valueFrom:
          secretKeyRef:
            name: tls
            key: tls.key
```
and create secret with cert and key
```
apiVersion: v1
kind: Secret
data:
  tls.crt: your_cert
  tls.key: your_key
metadata:
  name: tls
  namespace: clickhouse
```
You can see[ examples ](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/22-secure-ssl-02-files-secret-ref.yaml)

**Comment by manishtradebyte** [comment]
What if i want to achieve it at ingress level. ??
which ports do I need to expose in the clickhouse ?

Because if i try to expose the 8123 port with tls i get 400 error

**Comment by Slach** [comment]
8123 is not secure port
if you expose it to ingress you need to terminate TLS session on the ingress level and pass unecrypted traffic to clickhouse services

**Comment by alex-zaitsev** [comment]
https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#securing-the-network
