### ISSUE TITLE
Missed Disk* metrics with ClickHouse 24.3

### ISSUE THREAD

**Issue by Hexta** [Altinity/clickhouse-operator#1440]
`Disk*` metrics are missing for ClickHouse v24.3.
The root cause is renamed value for `type` column in `system.disks` table.
CH now has `Local` as `type` value when query in the exporter uses `local`.

```sql
SELECT DISTINCT type
FROM system.disks
```

```plain
   ┌─type──┐
1. │ Local │
   └───────┘
```

https://github.com/Altinity/clickhouse-operator/blob/ed8f7f0086b0ee60241248be0a6cfc7a6b8d9b2a/pkg/apis/metrics/clickhouse_metrics_fetcher.go#L113-L120

**Comment by Slach** [comment]
thanks for reporting
already fixed in next release 0.24.4
https://github.com/Altinity/clickhouse-operator/blob/0.24.0/pkg/metrics/clickhouse/clickhouse_metrics_fetcher.go#L113-L119
