### ISSUE TITLE
table in read only state on all replicas

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1441]
For whatever reason, I see the table state in read-only mode across all three replicas. I tried to drop it and resynchronize it, but due to its read-only status, these operations were unsuccessful. Additionally, I deleted the ZooKeeper references for this table from all instances, but this did not make any difference. I am wondering if there is any alternative method or recovery procedure available to resolve this issue?

**Comment by Slach** [comment]
zookeeper is a critical component for replication
did you remove zookeeper section from your `kind: ClickHouseInstallation` manifest? why?

did you install zookeeper / clickhouse-keeper ?

**Comment by darioneto** [comment]
I haven't removed the zookeeper from ClickHouseInstallation, only the reference for the problematic table.
What I did was deleting the table from zookeeper pod with this command:
zkCli.sh
deleteall /clickhouse/tables/0/db.tablex

typically what worked in the past to resolve similar issues was this method below:

DROP TABLE db.tablex SYNC;
SYSTEM DROP REPLICA 'chi-ck3-replicated-0-0' FROM ZKPATH '/clickhouse/tables/0/db.tablex';

recreate table and data was back

However in this case all the replicas indicated that a table was in the RO mode so the data wasn't replicated from last datapoint inserted

**Comment by Slach** [comment]
`SELECT engine_full FROM system.tables WHERE database='db' AND table='tablex'`

**Comment by darioneto** [comment]
The result indicates that the table is configured as expected and is using the ReplicatedAggregatingMergeTree engine correctly.

┌─engine_full────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
`│ ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/db.tablex', '{replica}') PARTITION BY toMonday(timestamp) ORDER BY (timestamp, creation_timestamp, instrument_name, index, type, settlement, price, id) TTL timestamp + toIntervalYear(3) SETTINGS index_granularity = 8192 │`

**Comment by darioneto** [comment]
It appears something occurred overnight, as the replicas on one of our pods are no longer in read-only mode. I was able to resolve the issue and fix the data. This is quite bizarre as it’s the first time we’ve experienced this. Thank you very much for your quick support.

**Comment by Slach** [comment]
Looks like issue not related to `clickhouse-operator`
