### ISSUE TITLE
How to pass external disk config to keeper using the operator

### ISSUE THREAD

**Issue by sigtriggr** [Altinity/clickhouse-operator#1442]
How do I pass this configuration below to keeper when using the clickhouse operator ? 

```
<clickhouse>
    <keeper_server>
        <log_storage_disk>log_s3_plain</log_storage_disk>
        <latest_log_storage_disk>log_local</latest_log_storage_disk>

        <snapshot_storage_disk>snapshot_s3_plain</snapshot_storage_disk>
        <latest_snapshot_storage_disk>snapshot_local</latest_snapshot_storage_disk>
    </keeper_server>
</clickhouse>
```

I tried passing it in as a configuration file the same way clickhouse configs are passed in and operator errors out with: 

```strict decoding error: unknown field "spec.configuration.files"```

**Comment by ondrej-smola** [comment]
This field is part of `ClickhouseInstallation` spec but not `ClickHouseKeeperInstallation` yet as of `0.23.5`.
You can pass them as shown [here](https://github.com/Altinity/clickhouse-operator/blob/0.23.0/docs/chk-examples/02-extended-1-node.yaml). E.g. under `spec.configuration.settings.log_storage_disk: "log_s3_plain"`

**Comment by sigtriggr** [comment]
Thank you that worked
