### ISSUE TITLE
Operator restart during upgrade causes extremely slow reconciliation on already upgraded pods

### ISSUE THREAD

**Issue by tanner-bruce** [Altinity/clickhouse-operator#1443]
Why:
Operator will start back at first pod. It will check [excludeHost](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/controller/chi/worker-chi-reconciler.go#L696-L704), but will not exclude the host because of [this condition](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/controller/chi/worker.go#L1167)

It will then enter [completeQueries](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/controller/chi/worker.go#L1019). Since the host is being actively written to, there will always be queries running (`select count() from system.processes > 1`). It will wait until the `chop.Timeout` has elapsed, and then return an error. The error returned from [completeQueries](https://github.com/Altinity/clickhouse-operator/blob/master/pkg/controller/chi/worker-chi-reconciler.go#L704) is not checked, so it will continue on with the reconciliation process, eventually finishing. This effectively adds whatever `chop.Timeout` is set to to each pods reconciliation loop

**Comment by tanner-bruce** [comment]
fixed in 0.24.0

**Comment by chenlujjj** [comment]
@tanner-bruce there is not a release 0.24.0
