### ISSUE TITLE
Override image altinity/clickhouse-operator

### ISSUE THREAD

**Issue by patsevanton** [Altinity/clickhouse-operator#1447]
Hello! Thanks for clickhouse-operator.
I try install:
```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.22.1/deploy/operator/clickhouse-operator-install-bundle.yaml
```
I get error:
```
Back-off pulling image "altinity/clickhouse-operator:0.22.1"
```
How Override image altinity/clickhouse-operator ?

**Comment by ondrej-smola** [comment]
Hello, image can be changed [here](https://github.com/Altinity/clickhouse-operator/blob/6e7a769a19cd40b68b507d4e77e0ddd5dfce98fa/deploy/operator/clickhouse-operator-install-bundle.yaml#L3715). It seems like Docker Hub rate-limited or blocked you pull request (there should be more info in pull attempt events) - you can setup registry mirror or transfer pre-pulled images beforehand.

**Comment by patsevanton** [comment]
is the usage correct ?
```
OPERATOR_NAMESPACE="${OPERATOR_NAMESPACE:-clickhouse-operator}"
METRICS_EXPORTER_NAMESPACE="${OPERATOR_NAMESPACE}"
OPERATOR_IMAGE="${OPERATOR_IMAGE:-dockerhub.timeweb.cloud/altinity/clickhouse-operator:0.22.1}"
METRICS_EXPORTER_IMAGE="${METRICS_EXPORTER_IMAGE:-dockerhub.timeweb.cloud/metrics-exporter:latest}"

kubectl create namespace "${OPERATOR_NAMESPACE}"
kubectl apply --namespace="${OPERATOR_NAMESPACE}" -f <( \
    curl -s https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.22.1/deploy/operator/clickhouse-operator-install-template.yaml | \
        OPERATOR_IMAGE="${OPERATOR_IMAGE}" \
        OPERATOR_NAMESPACE="${OPERATOR_NAMESPACE}" \
        METRICS_EXPORTER_IMAGE="${METRICS_EXPORTER_IMAGE}" \
        METRICS_EXPORTER_NAMESPACE="${METRICS_EXPORTER_NAMESPACE}" \
        envsubst \
)

kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.22.1/deploy/operator/clickhouse-operator-install-bundle.yaml
```

**Comment by Slach** [comment]
Better use 0.23.5 version, syntax is correct

Better use `OPERATOR_NAMESPACE` with the same namespace where `kind: ClickHouseInstallation` will apply
by default, if operator run not in `kube-system`, then it watches `chi` resources only namespace where installed
