### ISSUE TITLE
Insert & Load Data inside Clickhouse a cluster 

### ISSUE THREAD

**Issue by DelaunayAntoine** [Altinity/clickhouse-operator#1450]
Hello, I'd like to ask you a question because I don't really understand how clickhouse works or how to connect to its cluster. 

I have a clickhouse cluster deployed using operator and orchestrated behind by zookeeper. I'm currently on kubernetes. My cluster is deployed in a namespace with the operator

I currently have a cluster with 3 shards and 3 replicas, making a total of 9 pods.

I've exposed the clickhouse service with a loadbalancer so that I can access it with the command :
`clickhouse-client -h 192.168.1.15 -u user --password password`

When I place this order, I'm connected to a replica of a shard. Let's say I'm connected to `pod-0-1` (so shards 0 replicated 1) 

When I perform simple requests like `CREATE DATABASE TEST`, it creates a database on` pod-0-1`, but not on the rest of the pods. This seems normal as I'm only connected to this pod. 

So in order to create my tables and databases I use `CREATE DATABASE TEST ON CLUSTER replicated ;`(name of my cluster). My databases and tables are now created on my entire cluster. This allows me to propagate the creation of my tables, views and databases across the cluster by connecting to an endpoint

But the problem is when I want to load or INSERT data and it only adds it to pod-0-1. 

Here's an example of the requests I execute:

`INSERT INTO test.test_table (1, 3, test ....) `

```
INSERT INTO test.test_table
    SELECT * 
    FROM s3()
```

`clickhouse-client -q "INSERT INTO test.test_table FORMAT Parquet" < file.parq -h 192.168.1.15 -u user --password password`

How can I get my `inserts `and `loads `to propagate to the cluster because the `ON CLUSTER` parameter doesn't work with inserts?
Should I use another method so that my data is distributed across the entire cluster? 

Thank you very much, I look forward to hearing from you.

**Comment by Slach** [comment]
> When I perform simple requests like CREATE DATABASE TEST, it creates a database on pod-0-1, but not on the rest of the pods.

yes this is expected behavior


To insert your parquet file
you need to create two tables on cluster

first local replicated table
```sql
CREATE TABLE test.test_table_local ON CLUSTER '{cluster}' (
... columns definitions here...
) ENGINE=ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/{table}','{repllica}')
ORDER BY ...
```

second distributed table which need use to INSERT and SELECT from the whole cluster regardless of which replica you connected via LoadBalancer

```sql
CREATE TABLE test.test_table_distributed ON CLUSTER '{cluster}' AS test.test_table_local 
ENGINE=Distributed('{cluster}', test.test_table_local)
```

look details in 
https://clickhouse.com/docs/en/engines/table-engines/special/distributed
and
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication

**Comment by DelaunayAntoine** [comment]
@Slach 
Thank you very much for your reply. 

I would like to ask you another question about sharding_key. In fact, in the documentation when '`Engine=Distributed('{cluster}', test.test_table_local)`' 

This allows me to create a distributed table, but my problem comes with the` clickhouse-client -q command "INSERT INTO test.test_table_distributed FORMAT Parquet" < file.parq -h 192.168.1.15 -u user --password password`

The response is "`Method write is not supported by storage Distributed with more than one shard and no sharding key provided`".

So I looked at the doc and understood that I need to specify the sharding_key to the distributed base this way:
`'Engine=Distributed('{cluster}', test.test_table_local[sharding_key])`'

But no sharding value seems to match. This is probably because I don't understand the concept of sharding_key.

**So how can I retrieve this sharding_key or create one?**

Below is my deployment :

[clickhouse-cluster-deploy.txt](https://github.com/user-attachments/files/16177231/clickhouse-cluster-deploy.txt)

**Comment by Slach** [comment]
sharding key 
this is expression 
which calculated for each row during insert
and according calculated values it divided by number of shards from <remote_servers> config section
and write splitted data to .bin files in RawBinary format for each destination shard separatelly

for example if you want data for same `customer_id` store on the same shard
then use `customer_id` as sharding key

**Comment by DelaunayAntoine** [comment]
Ohhh I understand better why it's used and the interest it matters.

But let's imagine that in one case I still want to use this way of doing things (replicatedMergeTree & Distributed ) but I don't want to bother with storing for same customer_id store on the same shard.

Why it is not possible to just use this command : 

`clickhouse-client -q command "INSERT INTO test.test_table_distributed FORMAT Parquet" < file.parq -h 192.168.1.15 -u user --password password` 
and it's giving me back :
`Method write is not supported by storage Distributed with more than one shard and no sharding key provided`

Do i still need to do this :
`CREATE TABLE test.test_table_distributed ON CLUSTER '{cluster}' AS test.test_table_local 
ENGINE=Distributed('{cluster}', test , test.test_table_local[, customer_id] )` 

For this command `clickhouse-client -q command "INSERT INTO test.test_table_distributed....`  to work ?

**Comment by Slach** [comment]
`[... ]` means optional in documentations

use
```sql
CREATE TABLE test.test_table_distributed ON CLUSTER '{cluster}' AS test.test_table_local
ENGINE=Distributed('{cluster}', test, test_table_local, customer_id)
```

**Comment by DelaunayAntoine** [comment]
Thank you very much for your answer and expertise
