### ISSUE TITLE
 DB::Exception: Too many simultaneous queries. Maximum: 1000. (TOO_MANY_SIMULTANEOUS_QUERIES)

### ISSUE THREAD

**Issue by nnaik25** [Altinity/clickhouse-operator#1461]
Hello ,

We are seeing below exception is clickhouse server log

2024.07.22 06:20:07.987964 [ 15813 ] {aaa59f3c-cf58-4e91-809b-e9db05851a56} <Error> DynamicQueryHandler: Code: 202. DB::Exception: Too many simultaneous queries. Maximum: 1000. (TOO_MANY_SIMULTANEOUS_QUERIES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cf5565b
1. DB::Exception::Exception<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x00000000079aae30
2. DB::ProcessList::insert(String const&, DB::IAST const*, std::shared_ptr<DB::Context>, unsigned long) @ 0x0000000011c52fa2
3. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011f64875
4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x0000000011f6b9a9
5. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f5ca15
6. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f61350
7. DB::HTTPServerConnection::run() @ 0x0000000012fdb73a
8. Poco::Net::TCPServerConnection::start() @ 0x00000000158af152
9. Poco::Net::TCPServerDispatcher::run() @ 0x00000000158aff51
10. Poco::PooledThread::run() @ 0x00000000159a85e7
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000159a6c1d
12. ? @ 0x00007f0f8e3ae609
13. ? @ 0x00007f0f8e2d3353
 (version 24.2.1.2248 (official build))

We are using clickhouse-default-profile for creating users in clickhouse https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/clickhouse-operator/values.yaml#L612 and using the same user to ingest data in clickhouse on a large scale

Question:
If we set <max_concurrent_queries_for_all_users>0</max_concurrent_queries_for_all_users> in clickhouse-default-profile , will that resolve the issue?

**Comment by Slach** [comment]
issue is not related to `clickhouse-operator` itself, issue is related to `clickhouse-server`

are you sure you need to run 1000 simultaneous queries?

could you share

```clickhouse-client -q "SELECT normalizedQuery(query), count() FROM system.processes GROUP BY ALL"``` 
?

**Comment by nnaik25** [comment]
Output:-

CREATE DATABASE IF NOT EXISTS `?` ON CLUSTER htel       989
SELECT normalizeQuery(query), count() FROM system.processes GROUP BY ALL        1
KILL QUERY on cluster htel where user=?         11

**Comment by Slach** [comment]
`CREATE DATABASE IF NOT EXISTS ? ON CLUSTER x123` - 989 times

looks like this is root reason 
why you try to create database so often
something wrong with your application


better run
SYSTEM SHUTDOWN

and restart replica
after that look to your application code

**Comment by nnaik25** [comment]
Yes. we have fixed this. 

But we cannot push the fix to the stack for atleast 2 weeks

Hence need your expert help in answering below question

If we set <max_concurrent_queries_for_all_users>0</max_concurrent_queries_for_all_users> in clickhouse-default-profile , will that resolve the issue?

**Comment by nnaik25** [comment]
Hi @Slach 

Would you be able to help here?

**Comment by ondrej-smola** [comment]
Look on `max_concurrent_queries`  as gate that protects your cluster from more problems that would be harder to debug and would cause much more problems. If you disable it you will cause more problems and mitigate none - it looks like your DDL is run in some kind of busy loop - if you let it loose it will exhaust some other resource in the system.

**Comment by Slach** [comment]
> If we set <max_concurrent_queries_for_all_users>0</max_concurrent_queries_for_all_users> in clickhouse-default-profile , will that resolve the issue?

no, you will just overload clickhouse
and after 5000 qps you will get liveness probe failure

first of all fix your application

**Comment by Slach** [comment]
also read

https://altinity.com/blog/clickhouse-in-the-storm-part-1
https://altinity.com/blog/clickhouse-in-the-storm-part-2
