### ISSUE TITLE
 Pod is not coming up after applying chi [ClickHouseInstallation]

### ISSUE THREAD

**Issue by sanjeev3d** [Altinity/clickhouse-operator#1463]
After applying the ClickHouseInstallation (chi) configuration, the pod is not coming up as expected. This issue is preventing the ClickHouse instance from being operational.

```
 kubectl get chi -n ns-rm-yb-clicktt --kubeconfig=kubeconfig.txt
NAME        CLUSTERS   HOSTS   STATUS
cliff-rmi
```

**Comment by Slach** [comment]
coul you share

`kubectl get pod --all-namespaces -l app=clickhouse-operator --kubeconfig=kubeconfig.txt` ?

**Comment by alex-zaitsev** [comment]
no repro
