### ISSUE TITLE
Support for disabling installation of CRDs

### ISSUE THREAD

**Issue by shivtej-opsverse** [Altinity/clickhouse-operator#1486]
## Issue
- I am using this chart as a dependency in one of my chart let's name it `ALPHA` for now.
- The `ALPHA` Chart has a template of `kind` `ClickHouseInstallation`.
- If I package the `ALPHA` chart and do a `helm install` it errors saying the `crds` for the template having `kind: ClickHouseInstallation` must be installed beforehand.
- Helm provides two solutions for this: put all the `crds` in a file called `crds` which will install it beforehand or install using two separate charts.
- However since this chart is in the dependency of the `ALPHA` chart I cannot control the `crd` installation of this chart via helm as it a sub-chart. (Installation with `--skip-crds` only skips installation of charts from the main chart and the sub-charts)
- I propose adding a key `installCrds: true` in the `values.yaml` file which controls the installation of `crds`, similar example [here](https://github.com/VictoriaMetrics/helm-charts/blob/47d44a16747aa1d9d5cbcf08848488194abcc12c/charts/victoria-metrics-operator/values.yaml#L18).
- As i want to do the installation using only one chart let me know if there is something i am missing. If the solution i propose seems acceptable, please let me know i can raise a PR for the same

Thanks

**Comment by Slach** [comment]
feel free to make PR

**Comment by Slach** [comment]
Actually helm chart crds management is ugly

as workaround you could  use clickhouse-operator helm chart

with values
```yaml
additionalResources:
  - |
  kind: ClickHouseInstallation
  spec:
   ...
```   
look details
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/clickhouse-operator/values.yaml#L635

**Comment by tropnikovvl** [comment]
+1

**Comment by Slach** [comment]
@tropnikovvl don't be shy to make pull request

**Comment by shivtej-opsverse** [comment]
@Slach I think what you said makes sense. According to Helm there is no way to use templating in `crds` folder.
Reference here : https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

The only way I see this can work is bringing in the `kind: ClickHouseInstallation` resource under this chart or creating a `crds` folder in the main chart and helm will install those and just throw a warning.

Hence closing this.

Thanks
