### ISSUE TITLE
Templates in ClickHouseKeeperInstallation are not used

### ISSUE THREAD

**Issue by ShuaiShao93** [Altinity/clickhouse-operator#1504]
It looks like there is no way to use the templates in https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/02-extended-3-nodes.yaml#L26-L66, so specifying them is not useful.

I tried to add `defaults` but got 

```
error validating data: ValidationError(ClickHouseKeeperInstallation.spec): unknown field "defaults" in com.altinity.clickhouse-keeper.v1.ClickHouseKeeperInstallation.spec
```

**Comment by Slach** [comment]
could you check prepelease clickhouse-operator:0.24.0?

look 
https://github.com/Altinity/clickhouse-operator/blob/0.24.0/docs/chk-examples/02-extended-3-nodes.yaml

and 
https://github.com/Altinity/clickhouse-operator/tree/0.24.0/deploy/operator

**Comment by ShuaiShao93** [comment]
This works, thank you! When will 0.24 go out formally?

**Comment by Slach** [comment]
we don't provide any ETA
kind: ClickHouseInstallationKeeper now in deep refactoring

**Comment by ShuaiShao93** [comment]
@Slach the ClickHouseInstallationKeeper works for some cluster, but exactly the same manifest doesn't work for another cluster for some reason. Looks like the defaults didn't take effect. I'm testing different kubernetes versions to figure out why, but do you have any thoughts why this may happen?

```
$ kubectl gdescribe sts clickhouse-keeper
Name:               clickhouse-keeper
Namespace:          galileo
CreationTimestamp:  Wed, 18 Sep 2024 18:21:58 -0700
Selector:           app=clickhouse-keeper,uid=ce5c0680-c64e-43db-8b6a-e7416642b1f2
Labels:             app=clickhouse-keeper
                    uid=ce5c0680-c64e-43db-8b6a-e7416642b1f2
Annotations:        <none>
Replicas:           3 desired | 0 total
Update Strategy:    RollingUpdate
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=clickhouse-keeper
           uid=ce5c0680-c64e-43db-8b6a-e7416642b1f2
  Containers: <none>
  Volumes:      <none>
Volume Claims:  <none>
Events:
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  31s (x17 over 5m58s)  statefulset-controller  create Pod clickhouse-keeper-0 in StatefulSet clickhouse-keeper failed error: Pod "clickhouse-keeper-0" is invalid: spec.containers: Required value
```

**Comment by Slach** [comment]
@ShuaiShao93 which is your kubernetes version?

**Comment by ShuaiShao93** [comment]
> @ShuaiShao93 which is your kubernetes version?

Yeah I figured this out. The keeper 0.24.0 requires at least kubernetes 1.29. After upgrading, it works now. Thanks!

**Comment by zz913922** [comment]
I encountered the same issue, and our cluster can't be upgraded to v1.29 easily.

After I modified the generated statefulset, the `chi` CRD object won't reconcile successfully

**Comment by zz913922** [comment]
Sorry my mistake, didn't fill in the `spec.defaults.templates.podTemplate` name correctly
