### ISSUE TITLE
Not able to expose port for TimeSeries engine using operator

### ISSUE THREAD

**Issue by sachidananda007** [Altinity/clickhouse-operator#1506]
With 24.8 release clickhosue supports TImeSeries Engine. 
I am trying to deploy the same set up on k8s using altinity-operator.
However I am not able to open port for prometheus port 9363 for remote_read and remote_write in the shard and replica pods.

**Comment by sachidananda007** [comment]
slack thread  for this issue - https://altinitydbworkspace.slack.com/archives/C02K1MWEK2L/p1725972384941389

**Comment by Slach** [comment]
look to https://github.com/Altinity/clickhouse-operator/pull/1508
