### ISSUE TITLE
User management in clickhouse

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1507]
I am using altinity operator to deploy my own clickhouse cluster.
Since we have multiple projects  . I need a clean method for handling users.

Is there a terraform provider of vault secret engine for clickhouse?

**Comment by Slach** [comment]
look 
https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationusers
https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationprofiles

and https://github.com/ContentSquare/vault-plugin-database-clickhouse
