### ISSUE TITLE
ClickHouseKeeperInstallation CrashLoopBackOff with exit code 233

### ISSUE THREAD

**Issue by ShuaiShao93** [Altinity/clickhouse-operator#1520]
The logs are just like this, so nothing useful
```
Processing configuration file '/etc/clickhouse-keeper/keeper_config.xml'.
Merging configuration file '/etc/clickhouse-keeper/conf.d/chop-generated-raft.xml'.
Logging trace to /var/log/clickhouse-keeper/clickhouse-keeper.log
Logging errors to /var/log/clickhouse-keeper/clickhouse-keeper.err.log
```

**Comment by Slach** [comment]
Looks similar with https://github.com/Altinity/clickhouse-operator/issues/1519
Which clickhouse-operator version do you use?

**Comment by ShuaiShao93** [comment]
Both clickhouse operator and clickhouse keeper images are 0.24.0.

I don't think it's the same issue as https://github.com/Altinity/clickhouse-operator/issues/1519, because they can see error logs, but my pods crash immediately without any logs.

**Comment by Slach** [comment]
provide
clickhouse keeper can't have 0.24.0 version
only clickhouse-operator

could you provide
`kubectl get chk --all-namespaces`

**Comment by ShuaiShao93** [comment]
Oh sorry, the clickhouse keeper version is `clickhouse/clickhouse-keeper:24.8-alpine`. The 0.24.0 is the crd version.

> kubectl get chk --all-namespaces

This happens on one of our customers' clusters downstream. I'll ask them to provide but it may take a while

**Comment by alex-zaitsev** [comment]
@ShuaiShao93 , looks like you are using 0.24.0 until it is released. There were changes around configuration files recently. So if new image has been pulled without updating other things, it may break. Please re-deploy operator.

**Comment by Slach** [comment]
@ShuaiShao93 could you check latest 0.24.0 clickhouse-operator full installation with https://github.com/Altinity/clickhouse-operator/blob/0.24.0/deploy/operator/clickhouse-operator-install.sh or https://github.com/Altinity/clickhouse-operator/tree/0.24.0/deploy/operator-web-installer ?

**Comment by ShuaiShao93** [comment]
Thanks! I have fixed this by pinning the operator binary version to an older sha.

But we will upgrade both the operator and the crd to the latest 0.24.0 later for sure
