### ISSUE TITLE
Checking the number of replicas

### ISSUE THREAD

**Issue by tropnikovvl** [Altinity/clickhouse-operator#1535]
Hi!

I noticed that the operator does not restore (doesn't scale back to 1) the replica if `StatefulSet` was scaled to 0 for some reason.
Is this expected behavior?

**Comment by Slach** [comment]
could you provide more context?
what exactly your action sequence?

did you change `kind: ClickHouseInstallation` resource or change `kind: StatefulSet`?

**Comment by tropnikovvl** [comment]
I manually changed the number of replicas to `kind: StatefulSet` and watched how the provider would react to the changes.

**Comment by Slach** [comment]
operator watch `kind: ClickHouseInstallation`, and if it changed then change `kind: Statefulset` and other resources like `ConfigMap` and `StatefulSet`

**Comment by tropnikovvl** [comment]
Thanks for the information
