### ISSUE TITLE
Clickhouse Keeper config examples missing volume claim usage

### ISSUE THREAD

**Issue by SergeBakharev** [Altinity/clickhouse-operator#1542]
The extended Clickhouse Keeper config examples that have a `volumeClaimTemplate` do not have a `.spec.default.templates.dataVolumeClaimTemplate` definition that consumes that template. 

This can leave someone using these examples with keepers deployments that they might think are storing their data persistently, but are not! Not a good surprise.

The following templates are affected:
docs/chk-examples/02-extended-1-node.yaml
docs/chk-examples/02-extended-3-nodes.yaml

just needs a `dataVolumeClaimTemplate: default` added

**Comment by alex-zaitsev** [comment]
Fixed in 0.24.1
