### ISSUE TITLE
Options to Update PVC through CHI

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [Altinity/clickhouse-operator#1557]
Currently once the statefulset is created with a PVC size of 100Gi (just an example), its not possible to update the statefulset to increase the pvc size from 100Gi to 200Gi as the size field is an immutable field. Thus we end up patching the PVC dynamically and directly to increase the PVC size. Now this leads to inconsistent pvc size between CHI, STS and PVC. Please provide an option to update the PVC ( if there is an update only to pvc) to delete and recreate the STS on updating the CHI so as to make it consistent.

**Comment by Slach** [comment]
is your storage class contains `AllowVolumeExpansion: true`
kubectl get pvc
check storage class

kubectl get storageclass <name>

check `AllowVolumeExpansion: true` present

**Comment by karthik-thiyagarajan** [comment]
Yes its already set to true

**Comment by Slach** [comment]
could you share
`kubeclt get storageclass` ?

**Comment by karthik-thiyagarajan** [comment]
NAME                                              PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
clickhouse-storage                                ebs.csi.aws.com   Retain          WaitForFirstConsumer   true                   73d

**Comment by karthik-thiyagarajan** [comment]
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    artifact.spinnaker.io/location: ""
    artifact.spinnaker.io/name: clickhouse-storage
    artifact.spinnaker.io/type: kubernetes/storageClass
    artifact.spinnaker.io/version: ""
    moniker.spinnaker.io/application: cloudoperations
    moniker.spinnaker.io/cluster: storageClass clickhouse-storage
  creationTimestamp: "2024-08-30T07:14:20Z"
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: cloudoperations
  name: clickhouse-storage
  resourceVersion: "9173767"
  uid: 79eb31ac-6e1a-44a7-a645-861cb72a3c4a
parameters:
  iops: "16000"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

kubectl get chi --all-namespaces

NAMESPACE    NAME                CLUSTERS   HOSTS   STATUS
clickhouse   clickhouse-server   1          24      Completed

**Comment by Slach** [comment]
could you share following command without sensitive information?
```kubectl get chi -n clickhouse clickhouse-server -o yaml```
