### ISSUE TITLE
How to regenerate crd

### ISSUE THREAD

**Issue by liuxianXX** [Altinity/clickhouse-operator#1581]
hi，I want to modify the api and add a field. How can I regenerate the crd file after modifying the source code?

**Comment by chengjoey** [comment]
./dev/run_code_generator.sh

**Comment by liuxianXX** [comment]
> ./dev/run_code_generator.sh

Thanks for your reply，but after I executed this script, crd was not updated. 
this is output:
![Uploading 20241205-111430.jpeg…]()

**Comment by sunsingerus** [comment]
Check this out https://github.com/Altinity/clickhouse-operator/pull/1580#issuecomment-2518016900

**Comment by Slach** [comment]
@liuxianXX you need manually change CRD in `deploy/builder`
