### ISSUE TITLE
Build new Docker images

### ISSUE THREAD

**Issue by falfaro** [Altinity/clickhouse-operator#190]
Could you please build new Docker images, for the Operator and Metrics Exporter from "master"?

**Comment by alex-zaitsev** [comment]
We have 0.7.0 release coming soon, that will update :latest tag. You can take clickhouse-operator:dev for dev version that is built from 0.7.0 branch, if you need a development version.

**Comment by falfaro** [comment]
@alex-zaitsev or alternatively what's the frequency for new releases? Any chance of getting Docker images built automatically for every commit and tagged accordingly in Docker Hub?

**Comment by falfaro** [comment]
@alex-zaitsev thanks for the information. Great to know about the "dev" tag.
