### ISSUE TITLE
Support zookeeper configuration on clickhouse cluster level

### ISSUE THREAD

**Issue by qixiaogang** [Altinity/clickhouse-operator#209]
Hi Team

Does your team have a plan to support zookeeper configuration on clickhouse cluster level. 
For the case, there are thousands tables, and join queries are supported on these tables. We want to create these tables into different clickhouse cluster and each clickhouse cluster use different zookeeper cluster.

Thanks

**Comment by alex-zaitsev** [comment]
Hi @qixiaogang ,

Operator automatically generates 'all-sharded' and 'all-replicated' clusters in ClickHouse sense (sections of remote_servers). 'all-replicated' should be used for dimension tables that appear on the right side of the join.

I am not sure why you need a separate Zookeeper for that? Zookeeper is rarely a bottleneck in ClickHouse, and having multiple Zookeeper clusters per ClickHouse installation can make things quite hard to manage properly.

**Comment by qixiaogang** [comment]
Hi @alex-zaitsev  

Our clickhouse clusters are going to support a big volume traffic and thousands of tables. Let's say we have 2000 tables, and we have 4 clickhouse clusters. Then each clickhouse will serve 500  tables. We want the feature that each clickhouse cluster use different zookeeper cluster

**Comment by alex-zaitsev** [comment]
@qixiaogang , I understand. But if those are 4 different clusters, you can use 4 different ClickHouseInstallations for them. Why do you want to manage them as a whole? Do you need to access them from a single distributed query?

**Comment by qixiaogang** [comment]
Here is the case, table1 in cluster 1 and table 501 in cluster 2, and we want to support join queries over table1 and table501 by distributed tables. 
When clickhouse clusters in one chi, join queries are supported. When clickhouse clusters in different chi instance, join queries will not.

**Comment by qixiaogang** [comment]
@alex-zaitsev can I file a PR for this case to support zookeeper cluster on clickhouse cluster, at the same time keep zookeeper cluster on CHI level. If zookeeper cluster is configured on clickhouse cluster, then use it, otherwise use zookeeper cluster on CHI level.

**Comment by alex-zaitsev** [comment]
Sure, we welcome all PRs.

**Comment by qixiaogang** [comment]
@alex-zaitsev  I want to file a PR to support zk support on clickhouse cluster level, which branch can I file a PR to?

**Comment by alex-zaitsev** [comment]
@qixiaogang , please use master for PR

**Comment by qixiaogang** [comment]
Create PR for review https://github.com/Altinity/clickhouse-operator/pull/288, support Zookeeper configuration in cluster level

**Comment by alex-zaitsev** [comment]
Released in 0.9.4
