### ISSUE TITLE
Operator drops previous monitoring 

### ISSUE THREAD

**Issue by logart** [Altinity/clickhouse-operator#225]
When deploying new clickhouse installation information about old chi monitoring is dorpped.

How to reproduce:
1. Deploy clickhouse-operator to k8s.
2. Map port for monitoring `kubectl port-forward svc/clickhouse-operator-metrics 8888`
3. Visit http://localhost:8888/chi
4. There should be empty array as expected.
5. Deploy dev chi to dev namespace.
6. Visit http://localhost:8888/chi
7. There will be something like ```[{"namespace":"dev","name":"dev","hostnames":["chi-dev-0-0.dev.svc.cluster.local","chi-dev-0-1.dev.svc.cluster.local","chi-dev-1-0.dev.svc.cluster.local","chi-dev-1-1.dev.svc.cluster.local"]}]```
8. Deploy prod chi to prod namespace.
9. Visit http://localhost:8888/chi
10. I expect to see second element in the array, but instead there are something like ```[{"namespace":"dev","name":"dev","hostnames":["chi-prod-0-0.prod.svc.cluster.local","chi-prod-0-1.prod.svc.cluster.local","chi-prod-1-0.prod.svc.cluster.local","chi-prod-1-1.prod.svc.cluster.local"]}]```

k8s version :
```Client Version: version.Info{Major:"1", Minor:"17", 
GitVersion:"v1.17.0", 
GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean",
BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", 
Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"16",
GitVersion:"v1.16.3", 
GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean",
BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12",
Compiler:"gc", Platform:"linux/amd64"}
```
clickhouse-operator version :
```altinity/clickhouse-operator:0.7.0```

**Comment by alex-zaitsev** [comment]
@logart , thanks, the bug is fixed in upcoming 0.8.0 release. We are going to release it soon.

**Comment by logart** [comment]
@alex-zaitsev thank you so much!

**Comment by alex-zaitsev** [comment]
@logart https://github.com/Altinity/clickhouse-operator/releases/tag/0.8.0
