### ISSUE TITLE
Cluster scale up/down - moving data

### ISSUE THREAD

**Issue by ikosyanenko** [Altinity/clickhouse-operator#234]
https://github.com/Altinity/clickhouse-operator/blob/master/docs/schema_migration.md

Is it possible to scale up cluster without losing data?

**Comment by alex-zaitsev** [comment]
@ikosyanenko , Scaling up does not loose any data. The data loss is only possible if you scale cluster down and remove shards.

**Comment by ikosyanenko** [comment]
@alex-zaitsev one more question. How do you move shard? Copying?

**Comment by alex-zaitsev** [comment]
@ikosyanenko , what do you mean by 'move shard', could you elaborate your use case?

**Comment by ikosyanenko** [comment]
If I am scaling up a cluster. Do you move existed shards?

**Comment by alex-zaitsev** [comment]
No, we don't. New shards are empty. You can manually move data with 'insert select' or using https://clickhouse.yandex/docs/en/operations/utils/clickhouse-copier/

**Comment by ikosyanenko** [comment]
Ok, thanks
