### ISSUE TITLE
"latest" tag used in the installation template

### ISSUE THREAD

**Issue by ilyshav** [Altinity/clickhouse-operator#237]
Hi! 
"latest" tag is used in for clickhouse-operator in default yaml (https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install.yaml)

This could be a problem, because operator version could be updated unexpectedly, and it could break some installations (0.8.0 requires installation name shorter, that 15 symbols).
Should we replace it with the current release versions?

**Comment by alex-zaitsev** [comment]
Yes, you can change it in your environment with the following command:

```
kubectl set image deployment.v1.apps/clickhouse-operator clickhouse-operator=altinity/clickhouse-operator:0.6.0 -n <your_namespace>

kubectl rollout status deployment.v1.apps/clickhouse-operator -n <your_namespace>
```
Do you suggest to change default installation templates as well?

**Comment by ilyshav** [comment]
Yes, I'm talking about the default template. I could make a PR, if there is no concerns about it.

**Comment by alex-zaitsev** [comment]
@ilyshav , PR is welcomed, but bear in mind two things:
1) Templates are generated by a shell script in 'deploy/operator' folder. So you need to change the version tag in the script and build the operator -- templates will be updated accordingly.
2) The current version is in 'release' file in the root project folder

Thanks!

**Comment by alex-zaitsev** [comment]
'latest' have been removed from the template. 

The current tagging logic has been modified as follows:
1. Master branch is tagged as 'latest'
2. Release branches are tagged with release tag.

**Comment by ilyshav** [comment]
Thank you!
