### ISSUE TITLE
clickhouse cluster create database error

### ISSUE THREAD

**Issue by 4ss3g4f** [Altinity/clickhouse-operator#240]
we create clickhouse cluster with attached yaml file 
[cluster-latest.txt](https://github.com/Altinity/clickhouse-operator/files/4107351/cluster-latest.txt)

status from kubernetes:
![image](https://user-images.githubusercontent.com/22811935/73054437-03b29e00-3ebd-11ea-91f3-73cd17db255b.png)

We are using apache superset as our clickhouse IDE, we had error to create database on cluster, the database is created but there is error:

![image](https://user-images.githubusercontent.com/22811935/73054799-e9c58b00-3ebd-11ea-88be-a852a7ef2383.png)

We have error when create database on cluster,
![image](https://user-images.githubusercontent.com/22811935/73054856-0366d280-3ebe-11ea-97b8-e02d991a6d14.png)

but the database was created,
![image](https://user-images.githubusercontent.com/22811935/73054921-2d1ff980-3ebe-11ea-8d2c-c21b0f558d3f.png)

Is this behaviour correct ?
Is our create database command on cluster correct ?
we also see the error from kubectl exec -it , how to resolve this issue ??

**Comment by Slach** [comment]
hmm... look like clickhouse-latest.txt contains "deployment-pv" cluster instead "all-replicated" 
try run following command
```
CREATE DATABASE IF NOT EXISTS test ON CLUSER all-replicated
```

**Comment by 4ss3g4f** [comment]
error:
![image](https://user-images.githubusercontent.com/22811935/73057396-f4831e80-3ec3-11ea-818d-88cadb2d70e9.png)

error:
![image](https://user-images.githubusercontent.com/22811935/73057427-0c5aa280-3ec4-11ea-9b2b-d1a5c9a74437.png)

**Comment by 4ss3g4f** [comment]
I think this is minor issue with apache superset,

Thank you
