### ISSUE TITLE
Recreate from backup strategy

### ISSUE THREAD

**Issue by chrisprobst** [Altinity/clickhouse-operator#258]
I could not find any strategy for reusing a PVC/PV.

Imagine a cloud provider like DigitalOcean or GCE where you have snapshots and you are able to mount a disk from snapshot as PV.

How could I specify in the *ClickhouseInstallation* resource to reuse an existing data source?
As far as I understand, this is not supported currently, correct?

**Comment by alex-zaitsev** [comment]
@chrisprobst , you can do it only manually plugging volume to the podTemplate now. We have TODO item to make it easier. Expect it in March.

**Comment by chrisprobst** [comment]
@alex-zaitsev Thank you so much for your fast response. Understood. We are currently evaluating different strategies of hosting ClickHouse using Kubernetes. This operator really is a game changer. That would be the final piece for us to migrate from our giant bare metal setup.

**Comment by chrisprobst** [comment]
@alex-zaitsev Just filled out your contact form. Very interested to learn more about Altinity.

**Comment by chicofranchico** [comment]
It's march 2021 ;-) Any news on this feature?

**Comment by ilyakuchaev** [comment]
It's even 2022 )))

**Comment by alex-zaitsev** [comment]
@ilyakuchaev , Our current approach is to use clickhouse-backup utility that is deployed as a sidecar.

See example here:
https://github.com/Altinity/clickhouse-operator/blob/master/tests/e2e/manifests/chi/test-005-acm.yaml

This is much more portable and easier to manage than volume snapshots.
