### ISSUE TITLE
Dropping tables on installation deletion

### ISSUE THREAD

**Issue by lukatera** [Altinity/clickhouse-operator#275]
Recently we had an issue with tables being dropped after we accidentally deleted the ClickHouse installation object. Normally, we guard against any accidental deletion of in-cluster objects with PersistentVolumes reclaim policy set to "Retain" and the fact that ClickHouse doesn't delete stuff by itself but rather puts it in detached state. 

I found out that the issue we had is caused by this function: https://github.com/Altinity/clickhouse-operator/blob/b7c71f8c5d4ea615c716aa16301ff29f1906951b/pkg/model/schemer.go#L223

What is the use-case for dropping the actual tables from ClickHouse in this case?
If you'd want to release storage, could the same be achieved with just deleting associated PersistentVolumeClaim and leave the underlying data cleaning mechanism to PV (i.e. Retain, Recycle, Delete)?

**Comment by alex-zaitsev** [comment]
Hi @lukatera , the main reason of deleting the tables is replication. If you drop the replica and do not delete Replicated tables they are stuck in ZooKeeper.

We can add an option to retain data or even protect installations from incidental deletes. E.g. require to set some property first. If you have other proposals let us know.

**Comment by phatak-dev** [comment]
@alex-zaitsev it will be useful to have this property. It will help us to avoid the same situations as above.

**Comment by alex-zaitsev** [comment]
@phatak-dev , our plan is to introduce 'two-phase' delete.

Phase 1. Add a property to CHI that allows to delete:

* allowDeleteShard
* allowDeleteReplica
* allowDeleteCluster
* allowDeleteInstallation

Phase 2. Delete the object.

So user will have to do kubectl patch first, and only then apply the manifest that removes shards/replicas/clusters.

With installation it is a bit more complicated. We need to understand how we can tell k8s that installation can not be removed, or, recreate it back to the previous state if flag is not set.
