### ISSUE TITLE
Zookeeper authorization problem

### ISSUE THREAD

**Issue by Nklya** [Altinity/clickhouse-operator#276]
Hello.

I think that there is a problem with Zookeeper authorization in clickhouse configured with clickhouse-operator.
I deployed Zookeeper with the latest chart from bitnami  https://github.com/bitnami/charts/tree/master/bitnami/zookeeper

Without auth enabled in Zookeeper, everything works fine, but when I tried to enable it, I got an error during table creation
```
Received exception from server:
Code: 999, e.displayText() = Coordination::Exception: Not authenticated, path: /clickhouse (version 19.16.10.44 (official build))


2020.02.27 12:50:04.027507 [ 35 ] {ebc7c680-14d4-416e-8a9d-83743ed7087e} <Error> executeQuery: Code: 999, e.displayText() = Coordination::Exception: Not authenti │
│ cated, path: /clickhouse (version 19.16.10.44 (official build)) (from 10.2.15.119:63674) (in query: CREATE TABLE events_local on cluster '{cluster}' (     event_ │
│ date  Date,     event_type  Int32,     article_id  Int32,     title       String ) engine=ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard │
│ }/{database}/{table}', '{replica}', event_date, (event_type, article_id), 8192) ), Stack trace:                                                                   │
│ 2020.02.27 12:50:04.027694 [ 35 ] {ebc7c680-14d4-416e-8a9d-83743ed7087e} <Error> HTTPHandler: Code: 999, e.displayText() = Coordination::Exception: Not authentic │
│ ated, path: /clickhouse, Stack trace:
```

While zkcli is able to connect without any problem

```
$ brew install zookeeper
$ cat /Users/user/.jaas.conf
Client{
      org.apache.zookeeper.server.auth.DigestLoginModule required
      username="zk_user"
      password="password";
};

JVMFLAGS="-Djava.security.auth.login.config=/Users/user/.jaas.conf" zkcli
```

Part of ClickHouseInstallation:
```yaml
kind: 'ClickHouseInstallation'

metadata:
  name: 'demo'

spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-host
      identity: "zk_user:password"
```

I tried a couple of times with the same result.
Versions:
k8s: 1.14.9
clickhouse: 19.16.10.44
clickhouse-operator: 0.9.1
zookeeper chart: 5.4.2

**Comment by sunsingerus** [comment]
Operator does not communicate with ZK directly, ClickHouse does it.
There may be issues somewhere in between operator <-> clickhouse ZK credentials interpretation, or between clickhouse <-> ZK credentials exchange.

**Comment by Nklya** [comment]
Yeah, you are right, fixed description.

Checked the running containers. Looks like zookeeper is configured properly. 

```
cat /etc/clickhouse-server/config.d/..2020_02_27_15_39_57.000342497/zookeeper.xml
<yandex>
    <zookeeper>
        <node>
            <host>zookeeper-host</host>
            <port>2181</port>
        </node>
        <identity> zk_user:password</identity>
    </zookeeper>
    <distributed_ddl>
        <path>/clickhouse/demo/task_queue/ddl</path>
    </distributed_ddl>
</yandex>
```

**Comment by Slach** [comment]
maybe it should be
` <identity>zk_user:password</identity>`
instead of
` <identity> zk_user:password</identity>`
               ^^^^ space here?

**Comment by Nklya** [comment]
My bad, that was the wrong copypaste.
```
root@chi-demo-replicated-0-0-0:/# cat /etc/clickhouse-server/config.d/..2020_02_27_15_39_57.000342497/zookeeper.xml
<yandex>
    <zookeeper>
        <node>
            <host>clickhouse-demo-zookeeper.clickhouse-demo.svc.cluster.local</host>
            <port>2181</port>
        </node>
        <identity>zk_user:password</identity>
    </zookeeper>
    <distributed_ddl>
        <path>/clickhouse/demo/task_queue/ddl</path>
    </distributed_ddl>
</yandex>
```

**Comment by Slach** [comment]
could you try https://github.com/eldadru/ksniff or https://github.com/twitter/zktraffic for capture traffic inside pod and compare differences between zkcli and clickhouse-server communications?

**Comment by Nklya** [comment]
Sure. Created dump with filtered packets to zookeeper only for zkCli.sh and ClickHouse
[ch-zk.zip](https://github.com/Altinity/clickhouse-operator/files/4263009/ch-zk.zip)

**Comment by Slach** [comment]
could you look to zookeeper pod logs, about authentification errors?
look like clickhouse still try create entries in zookeeper without authentification credentials

![image](https://user-images.githubusercontent.com/105560/75471054-78449500-59b3-11ea-935a-093be5f3278d.png)

**Comment by Slach** [comment]
please look at https://github.com/ClickHouse/ClickHouse/blob/master/dbms/tests/integration/test_zookeeper_config/test.py#L84

clickhouse have integration test for your case and it passed

i think we should look to zookeeper pod logs for investigate problem

**Comment by Slach** [comment]
also maybe you create /clickhouse path in zookeeper with another user:password
and after that old ACL still applied to this path ?
https://groups.google.com/forum/#!topic/clickhouse/Jn6FNb8WPHA

**Comment by Slach** [comment]
@Nklya look https://github.com/ClickHouse/ClickHouse/pull/9418

**Comment by Nklya** [comment]
Oh, that’s great 😊
But what type of auth is supported now?

**Comment by alexey-milovidov** [comment]
`digest`, at most.

**Comment by alexey-milovidov** [comment]
@Slach it should work already.

According to the ZooKeeper Programmers Guide:

> **auth** is a special scheme which ignores any provided expression and instead uses the current user, credentials, and scheme. Any expression (whether user like with SASL authentication or user:password like with DIGEST authentication) provided is ignored by the ZooKeeper server when persisting the ACL. However, the expression must still be provided in the ACL because the ACL must match the form scheme:expression:perms. This scheme is provided as a convenience as it is a common use-case for a user to create a znode and then restrict access to that znode to only that user. If there is no authenticated user, setting an ACL with the auth scheme will fail.

We use the same code as in original ZooKeeper C library.

Need step by step guide to reproduce (without Kubernetes).

**Comment by Slach** [comment]
@Nklya could you check it again with change to zookeeper settings to digest authorization?

**Comment by Nklya** [comment]
I use zookeeper from Bitnami chart and it supports only `SASL/Digest-MD5` auth as stated here
https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml#L128. I still don't understand what's the difference.

Looks like I could just close this issue, but I think that in this case option `identity` in operator is pointless, as there is no working example with zookeeper auth enabled.
