### ISSUE TITLE
Support defining pod templates instead of pod specs

### ISSUE THREAD

**Issue by vjsamuel** [Altinity/clickhouse-operator#281]
In the Clickhouse installation CRD currently we see that the `ChiPodTemplate` has a spec which is `v1.PodSpec`. this prohibits defining custom labels when the resources are created. allowing to define custom labels allows selecting resources of an installation with the same selector. To do so, it needs to be `v1.PodTemplateSpec` instead.

Could this be considered?

**Comment by sunsingerus** [comment]
@vjsamuel there is another issue #269 with the same question about custom labels. Please, take a look on temp solution available ATM in [this reply](https://github.com/Altinity/clickhouse-operator/issues/269#issuecomment-593846406). Probably it will help you ATM, while we'll reconcile about `PodSpecTemplate`

**Comment by vjsamuel** [comment]
@sunsingerus , thanks for the prompt reply. I see that this only covers labels? what about annotations?

**Comment by sunsingerus** [comment]
> I see that this only covers labels? what about annotations?
Yes, operator copies labels only at the moment. We can implement the same functionality with annotations as well.
Thanks for suggestion.

**Comment by qixiaogang** [comment]
@sunsingerus  This is the PR https://github.com/Altinity/clickhouse-operator/pull/289 to support annotations and test works for us. Can you help to review.

**Comment by sunsingerus** [comment]
Done via https://github.com/Altinity/clickhouse-operator/pull/289
