### ISSUE TITLE
Make it possible to watch all namespaces from non kube-system namespace

### ISSUE THREAD

**Issue by wilmardo** [Altinity/clickhouse-operator#294]
Currently deploying the operator in another namespace then `kube-system` implicitly disallows global watching:
https://github.com/Altinity/clickhouse-operator/blob/aaee541b6d2b1ae79aa2d11088ec9c7f377a1dc3/pkg/apis/clickhouse.altinity.com/v1/type_config.go#L323-L329

It would be nice to have a parameter for this behavior, we deploy all operators in the `operator` namespace and they are cluster global.

I am open to implement this but what is a nice approach to this? A `WATCH_ALL_NAMESPACES` boolean? When `WATCH_NAMESPACES` or `WATCH_NAMESPACE` is defined it will be ignored.

PS why not consolidate `WATCH_NAMESPACE` and `WATCH_NAMESPACES` into just `WATCH_NAMESPACES`? Nothing wrong with a list with one entry or am I missing something? Feels weird as enduser :)

**Comment by anxolerd** [comment]
I'd also like to have operator installed in its own namespace, but watching all namespaces.

By the way, I've heard, it is common practice for users of operator-framework to watch all namespaces if `WATCH_NAMESPACE` environment variable is empty.

**Comment by TCeason** [comment]
> I'd also like to have operator installed in its own namespace, but watching all namespaces.
> 
> By the way, I've heard, it is common practice for users of operator-framework to watch all namespaces if `WATCH_NAMESPACE` environment variable is empty.

If set empty just only watch the ns where operator was installed.

https://github.com/Altinity/clickhouse-operator/issues/686

**Comment by Slach** [comment]
sorry for late response, solution here
https://github.com/Altinity/clickhouse-operator/issues/1418#issuecomment-2111986205
