### ISSUE TITLE
Apply two yaml files successively using operator. Why not create the next chi cluster if one chi cluster is not created successfully

### ISSUE THREAD

**Issue by xiedeyantu** [Altinity/clickhouse-operator#300]

**Comment by sunsingerus** [comment]
Can you, please, provide more details?

**Comment by xiedeyantu** [comment]
such as
kubectl apply -f chexample.yaml(2shard,2replica)
we will see such as
NAMESPACE     NAME                                    READY   STATUS              RESTARTS   AGE   IP          
default       chi-chexample-xxx-0-0-0                 0/1     Pending         0          x   <none>      

Next
kubectl apply -f chexample2.yaml(2shard,1replica)

Five minutes later
we wil see such as
NAMESPACE     NAME                                    READY   STATUS              RESTARTS   AGE   IP               
default       chi-chexample-xxx-0-0-0                 0/1     ContainerCreating   0          x   <none>           
default       chi-chexample-xxx-0-1-0                 0/1     Pending         0          x   <none>           

But we can't see chi-chexample2-xxx-0-0-0 in this list until chexample finished
