### ISSUE TITLE
Using ODBC drivers

### ISSUE THREAD

**Issue by aksenk** [Altinity/clickhouse-operator#305]
Hello.

We need an odbc driver in our cluster. How can we do this now?

We can add Unix-packages to the docker image, but how do we add ODBC configuration files via operator?

Thanks.

**Comment by sunsingerus** [comment]
Some clarification is needed. Would you like to add driver on every cluster's node? Why not to add driver on the client's side?

**Comment by lazjake** [comment]
maybe related -- i'm not sure what the best way to create an external dictionary with a postgres source would be. the files section of the installation config defaults to putting files in `config.d`, which isn't the default path for unixODBC, so i'm not seeing a convenient way to include an `odbc.ini` file for the driver to reference. 

how would you suggest creating a dictionary with an odbc source via the operator?

**Comment by filimonov** [comment]
@sunsingerus we need to have reciepe for that.

Most probably can be done as
A) install unixODBC package
B) install needed odbc driver via package/archive (we can pick one as a sample) 
C) register odbc DSN using a template provided by user and using odbcint tool

**Comment by a-dot** [comment]
+1 for this..

Can you post some information on how to add the shared library for the ODBC driver and the odbc.ini file in the right spot so the ODBC table engine can pick it up?

Thanks!

**Comment by Slach** [comment]
@a-dot you need custom image which contains required
look Docker file examples on https://gist.github.com/9f9449a722091a13a9069b79f8dc7da7
build and publish custom image with installed ODBC drivers

after that
look `kubectl explain chi.spec.configuration.templates.podTemlates` and `kubectl explain chi.spec.configuration.clusters.templates` and try to figure out how to create podTemplate and link it to cluster pods
