### ISSUE TITLE
Support mount existing pv?

### ISSUE THREAD

**Issue by yuzhichang** [Altinity/clickhouse-operator#309]
Some cloud vendor doesn't support "Dynamic Volume Provisioning". Does clickhouse-operator support mounting existing pv to each ChiHost? I don't see how to customize templates to do that.

**Comment by hodgesrm** [comment]
If you define a volumeClaimTemplate with storageClass set to '' (empty string) the operator should use existing PVs.  

This is described in the docs.  Have a look at https://github.com/Altinity/clickhouse-operator/blob/master/docs/storage.md.

**Comment by yuzhichang** [comment]
Which existing PV does the template use if `define a volumeClaimTemplate with storageClass set to '' (empty string)`? I need each ck instance mount an unique existing PV.

**Comment by hodgesrm** [comment]
It should pick up a PV that is large enough to meet your request and keep it even when pods restart or are upgraded. Try it out and post your results.  We've mostly been working with dynamic provisioning in our tests.

**Comment by hodgesrm** [comment]
p.s., Which Kubernetes distro are you using?

**Comment by yuzhichang** [comment]
@hodgesrm You are right. I'v managed to bound existing pv. Thanks!
