### ISSUE TITLE
Default value for spec.configuration.zookeeper.nodes.port does not work

### ISSUE THREAD

**Issue by djmarcin** [Altinity/clickhouse-operator#310]
A new setup started throwing this error from the clickhouse-operator pod & container.

`I0316 22:07:13.485320       1 controller.go:498] ERROR update CHI (datans/example): "ClickHouseInstallation.clickhouse.altinity.com \"example\" is invalid: spec.configuration.zookeeper.nodes.port: Invalid value: 1: spec.configuration.zookeeper.nodes.port in body should be greater than or equal to 1"`

It appears to be resolved by explicitly setting the port to 2181 (the default zookeeper port) but the operator should just use this default if port is unspecified.

The exact same config file has worked in the past (I think last tested at 0.9.0, but not 100% sure of the version).

**Comment by alex-zaitsev** [comment]
Thank you, @djmarcin . We will fix it shortly.

**Comment by xiaozzz** [comment]
@alex-zaitsev same problem for 0.9.3. I try to change the `configuration.zookeeper.nodes.port.minimum` to `0`, it throw this error when starting up
`spec.configuration.zookeeper.nodes.host in body is required`.

I changed `configuration.zookeeper.nodes.port.minimum` to `0` and deleted `configuration.zookeeper.nodes.items.required` as a workaround.

**Comment by alex-zaitsev** [comment]
@xiaozzz , stay tuned. We are going to release 0.9.4 today that addresses this issue and few others.

**Comment by sunsingerus** [comment]
Fix proposed in #311

**Comment by alex-zaitsev** [comment]
Released in 0.9.4
