### ISSUE TITLE
Question about config of networks for users.xml

### ISSUE THREAD

**Issue by xiaozzz** [Altinity/clickhouse-operator#312]
Hi, i am using 0.9.3 , and when i set a new user, it auto generates network config like this:
``` xml
<networks>
    <host_regexp>(chi-[^.]+\d+-\d+|clickhouse\)\.default\.svc\.cluster\.local$</host_regexp>
    <ip>::1</ip>
    <ip>127.0.0.1</ip>
</networks>
```
i have two questions
1. according to the [official website](https://clickhouse.tech/docs/en/operations/access_rights/), `For use in production, only specify ip elements (IP addresses and their masks), since using host and hoost_regexp might cause extra latency.` Is it a must to use this `host_regexp` in production?
2. i am using in Intranet, and i do not want any ip filters. the default setting is a whitelist so it blocks connection from other pods (e.g. `User default is not allowed to connect from address 10.240.0.166`), and the network segment is dynamic so `admin/networks/ip: "10.0.0.1/8"` does not work for me. Is there any method to avoid the network filtering?

Thank you!

----------------
update:
For the second question, it seems work if i change this, is that right? i am not familiar with ip rules
```xml
chConfigUserDefaultNetworksIP:
      - "::/0"
```

**Comment by alex-zaitsev** [comment]
@xiaozzz, 
1) there is no or very little performance penalty when hostRegexp is used, since ClickHouse cashes DNS resolution.
2) You can enable connections from everywhere by adding a line to your ClickHouseInstallation CRD:
{code}
spec:
  configuration:
    users:
      default/networks/ip: "::/0"
{code}
