### ISSUE TITLE
Support configuration for name pattern

### ISSUE THREAD

**Issue by qixiaogang** [Altinity/clickhouse-operator#315]
In our company, namespaceDomainPattern  is different from "%s.svc.cluster.local" in
https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/namer.go#L125

we also want to keep the sts and pod name shorter, so remove "chi-" from statefulSetNamePattern , I am wondering can you support the name pattern configurable, so we don't need to maintain code change in our company.  This feature seems helpful for most company running their own k8s.

**Comment by sunsingerus** [comment]
@qixiaogang we'll take a look on how to extract the predefined values into configuration.
Added to features list, however, no exact dates...

**Comment by qixiaogang** [comment]
@sunsingerus  Cool, thanks

**Comment by qixiaogang** [comment]
@sunsingerus  Can a file a PR to make statefulSetNamePattern configurable just as shardServiceNamePattern do in https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/namer.go#L527-L539

**Comment by sunsingerus** [comment]
Yes, sure any PRs are very welcome!
Please make your PR towards dev branch for next release [0.9.7](https://github.com/Altinity/clickhouse-operator/tree/0.9.7)

**Comment by sunsingerus** [comment]
We keep `master` as a clean `latest release` branch, so all PR has to be made into dev branches

**Comment by qixiaogang** [comment]
sure

**Comment by qixiaogang** [comment]
@sunsingerus  File PR to dev branch, could you please help to review and merge https://github.com/Altinity/clickhouse-operator/pull/360

**Comment by alex-zaitsev** [comment]
Fixed in #360
