### ISSUE TITLE
ingesting high volume data with clickhouse-operator on AWS (bypassing ELB costs)

### ISSUE THREAD

**Issue by kushagra391** [Altinity/clickhouse-operator#326]
Is there a recommended way to ingest high volume data into clickhouse, using clickhouse-operator setup on EKS ? 

We are evaluating clickhouse-operator and hope to upload 100x GBs of data everyday. 
clickhouse-operator (kubernetes) exposes an ALB / ELB by default that costs around 0.008$/GB hour. Was wondering if there is any other way to ingest bypassing load-balancer ? 

The only workaround that comes to my mind is to upload data to s3, and then download into a node inside EKS (through s3 vpc-endpoint) which is free. Though this makes ingestion a two step process and we need to deal with s3 sensors, etc

Thanks !

**Comment by kushagra391** [comment]
I guess we'll just connect to EKS with kubectl, and download s3 logs and push into CH.
Rather than trying to use ELB.

**Comment by kushagra391** [comment]
I guess we'll just connect to EKS with kubectl, and download s3 logs and push into CH.
Rather than trying to use ELB.

**Comment by alex-zaitsev** [comment]
Yes, that is a possible option. Thank you for an update.
