### ISSUE TITLE
How to apply different settings on different hosts?

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#380]
I want to apply different settings on different shards/replicas/hosts.
Is there a way to do that?

**Comment by winter7** [comment]
My chop version is 0.9.9. There are configmaps for all host in elder version. 
Why is the newer version configmap more limited?

**Comment by winter7** [comment]
Can I use `{shardIndex}` in configuration?

**Comment by alex-zaitsev** [comment]
@winter7 , settings are only global now. We can add a feature to enable settings on different levels (as we do with templates), it will take some time. Could you describe your use case, why do you need it?

**Comment by winter7** [comment]
@alex-zaitsev It is related with https://github.com/Altinity/clickhouse-operator/issues/355
I want to customize different `macros` like `shard` and `replcia` on different shards and replicas.

And for more, my clickhouse cluster is split into a read replica and a write replica with different ec2 type and ebs type, so that some of their configurations are different accordingly.

For now, Can I do this by modifying the configmap for each host?

**Comment by alex-zaitsev** [comment]
Hi @winter7 , 
You can define custom podTemplate and volumeClaimTemplate for replicas right now. Here is an example with different podTemplates. volumeClaimTemplates can be configured the same:
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/06-advanced-layout-02-replicas.yaml

Also, take a look at this example: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/14-zones-distribution-01.yaml

It demonstrates how you can balance replicas between different zones/AZs.

**Comment by winter7** [comment]
@alex-zaitsev  Thanks! 
I did refer to these examples to configure different hard disks and AZ.
What I have not yet solved is the `configuration/settings". Now I have achieved the purpose by modifying ConfigMap for every host. I wonder if there is any hidden danger?

**Comment by alex-zaitsev** [comment]
No danger adding custom config maps if you can control it.  See this example:
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-05-sidecar.yaml

We will add a support for 'settings' at different levels, but it requires quite a lot of re-factoring that may take several weeks.
