### ISSUE TITLE
Support RAID 0

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#384]
I want to improve the throughput of ClickHouse by building a RAID 0.
Is there a way to do that in operator?

**Comment by alex-zaitsev** [comment]
@winter7 , RAID is typically build on storage side. ClickHouse itself support RAID-like structures if you add multiple disks to a volume. See this for details:
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes

You can configure it via operator as in this example:
https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-020-multi-volume.yaml

**Comment by winter7** [comment]
@alex-zaitsev Thanks! But my prd env clickhouse server version is lower than which supports multiple storage.
Do you have any idea about just building RAID 0 in operator?

**Comment by alex-zaitsev** [comment]
@winter7, operator can not build the RAID. Please consider an upgrade to latest Altinity Stable release: https://www.altinity.com/blog/tag/Releases
