### ISSUE TITLE
adding new replica does not create materialized views and normal views

### ISSUE THREAD

**Issue by samene** [Altinity/clickhouse-operator#385]
Latest release, I have a deployment with 3 shards and 1 replica. I increased to 2 replicas and expected that the schema propagate to the new replica. All distributed and replicated tables were created but the materialized views and normal views were not created on the new replica.

I see in schemer.go you are only querying tables where engine like 'Replciated%' or 'Distributed'. This does not include materialized views and normal views. Is this on purposed and what is the reason behind this?

This is more of a question rather than a issue.

**Comment by alex-zaitsev** [comment]
Hi @samene , we were mostly focused on replicated and distrubuted objects and dependencies. Looks like we overlooked over objects. This needs to be fixed, and we have a task already scheduled to re-write schemer completely.

Note, operator will create objects for the same shard only, i.e. if you happen to have different views and MVs on different shards, those will be populated to corresponding replicas respectively.

**Comment by alex-zaitsev** [comment]
Hi @samene ,
We have patched 0.9.9 version, so it should create all schema objects on new replica now. Please test if it fixes the issue for you.
Thanks

**Comment by alex-zaitsev** [comment]
Fixed in 0.10.0
