### ISSUE TITLE
Use k8s secrets  for passwords

### ISSUE THREAD

**Issue by R-omk** [Altinity/clickhouse-operator#386]
Why don't you use k8s secrets to store passwords?

As a user of a product, I would like to connect the same k8s secret to an application and to an clickhouse cluster

**Comment by sunsingerus** [comment]
These items are already in TODO list, however, with no specific implementation dates so far.

**Comment by sunsingerus** [comment]
implemented in 0.14.0

**Comment by Slach** [comment]
@sunsingerus could you share some links with CHI examples how to use this feature?

**Comment by sunsingerus** [comment]
In CHOP config file one [can specify not only plan username/password, but also namespace/name of the secret](https://github.com/Altinity/clickhouse-operator/blob/a60317bfcbfc39604559573e2433049b34c90769/config/config.yaml#L94) where passwords are located. Credentials from the secret takes precedence in case both options provided. In case no secret provied, operator fallback to old approcah with plaintest credentials.

**Comment by sunsingerus** [comment]
One more note - operator configuration can be presented as ConfigMap, there is no need to modify files backed in Docker image

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/0.14.0
