### ISSUE TITLE
i want to create operator in other namespace, what should i do? and all the releases could be watched

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#388]

**Comment by SalleryWang** [comment]
not be kube-system

**Comment by Slach** [comment]
You can use following solution:

```bash
git clone https://github.com/Altinity/clickhouse-operator.git
cd clickhouse-operator/deploy/operator/
OPERATOR_NAMESPACE=your_namespace bash -x clickhouse-operator-install.sh 
```

**Comment by Slach** [comment]
by default operator watch all namespaces

**Comment by SalleryWang** [comment]
the default operator means kube-system namespace? if i set the other namespace, the operator whether watch all namespaces?

**Comment by SalleryWang** [comment]
> by default operator watch all namespaces
the default operator means kube-system namespace? if i set the other namespace, the operator whether watch all namespaces?
