### ISSUE TITLE
the default operator means kube-system namespace? if i set the other namespace, the operator whether watch all namespaces?

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#389]
the default operator means kube-system namespace? if i set the other namespace, the operator whether watch all namespaces?

_Originally posted by @SalleryWang in https://github.com/Altinity/clickhouse-operator/issues/388#issuecomment-630765143_

**Comment by SalleryWang** [comment]
@Slach

**Comment by Slach** [comment]
by default operator watch all namespaces
