### ISSUE TITLE
Ask a question, restart the all zookeerper pods, the data cannot be written in

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#410]
![image](https://user-images.githubusercontent.com/45587738/83391723-77922380-a426-11ea-9803-f8926efd865c.png)

**Comment by Slach** [comment]
if you restart zookeeper, *ReplicatedMergeTree table switch to read-only mode until zookeeper back to online, cause we need save new replicated parts name to Zookeeper for each INSERT INTO *ReplicatedMergeTree, tables with not replicated engines still work
