### ISSUE TITLE
the problem is the zookeeper pod has been running, tha data cannot be written in.

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#413]
if you restart zookeeper, *ReplicatedMergeTree table switch to read-only mode until zookeeper back to online, cause we need save new replicated parts name to Zookeeper for each INSERT INTO *ReplicatedMergeTree, tables with not replicated engines still work

_Originally posted by @Slach in https://github.com/Altinity/clickhouse-operator/issues/410#issuecomment-636737319_

**Comment by Slach** [comment]
could you run?
```
kubectl --all-namespaces get pods | grep zookeeper
```

**Comment by SalleryWang** [comment]
i am sure the all zookeeper pods are running，all zookeeper pods has been restarted， but tha data cannot be written in.

**Comment by Slach** [comment]
could you provide zookeeper manifest which you use for install zookeeper?

**Comment by SalleryWang** [comment]
docker.io/zookeeper 3.5.6




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 06/01/2020 20:43, Eugene Klimov wrote:

could you provide zookeeper manifest which you use for install zookeeper?

**Comment by Slach** [comment]
could you provide whole YAML which you use for install zookeeper instead of just say zookeeper image version ?

**Comment by SalleryWang** [comment]
![image](https://user-images.githubusercontent.com/45587738/83602846-ea75d880-a5a5-11ea-875a-c54236ce0061.png)
i restart clickhouse error

**Comment by Slach** [comment]
look like you lost your zookeeper data
could you provide what exactly happens with Zookeeper on your side?
which actions you apply for your Zookeeper installation?

**Comment by SalleryWang** [comment]
the new operator is ok
