### ISSUE TITLE
Ask a question,   What are the limitations of the clickhouse user name format

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#418]

**Comment by Slach** [comment]
according to https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-user-statement
username can be utf-8 string
`CREATE USER "utf-8-user-name"` 
should works

**Comment by SalleryWang** [comment]
i mean the regex




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 06/02/2020 21:19, Eugene Klimov wrote:

according to https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-user-statement
username can be utf-8 string
CREATE USER "utf-8-user-name"
should works

**Comment by Slach** [comment]
it same as XML tag name
https://stackoverflow.com/a/3158299/1204665
