### ISSUE TITLE
Ask a question,  directly modify the configuration file, whether it supports hot loading？

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#426]

**Comment by Slach** [comment]
@SalleryWang could you explain what exactly you mean?
Do you need apply settings without POD restart?

You can define clickhouse settings inside Kubernetes custorm resource `ClickhouseInstallation`
please look at https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationsettings

some parts of settings can be changed without restart pods:
https://clickhouse.tech/docs/en/operations/settings/

some kind of server settings require to restart a pod:
https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/

**Comment by alex-zaitsev** [comment]
Operator does not reload configuration file without restart.
