### ISSUE TITLE
Authentication problem when querying a Distributed Table

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#456]
Code: 194. DB::Exception: Received from service-ck-svhhp1sop1.ck-svhhp1sop1-hb.jvessel2.local:9000. DB::Exception: Received from chi-ck-svhhp1sop1-0-0:9000. DB::Exception: Password required for user default.

0 rows in set. Elapsed: 0.005 sec.

**Comment by Slach** [comment]
please check <remote_servers> section in your config file 
and read https://clickhouse.tech/docs/en/engines/table-engines/special/distributed/

**Comment by SalleryWang** [comment]
I set a password for the default user，cause Authentication problem when querying a Distributed Table，what should i do？

**Comment by Slach** [comment]
could you share your YAML clickhouse-operator manifest for `kind: ClickhouseInstallation`

**Comment by SalleryWang** [comment]
![image](https://user-images.githubusercontent.com/45587738/86894177-4d263b00-c135-11ea-9a3a-d5b73f85f389.png)
if i set like this,select the distributed table, error
Code: 195. DB::Exception: Received from localhost:9000. DB::Exception: Received from chi-ck-06i66lmm9h-0-1:9000. DB::Exception: User default is not allowed to connect from address

**Comment by SalleryWang** [comment]
so i have to add -"::/0"
and i want to add password for the default user, what should i do?

**Comment by SalleryWang** [comment]
@alex-zaitsev @Slach

**Comment by alex-zaitsev** [comment]
@SalleryWang , see discussion in there https://github.com/Altinity/clickhouse-operator/issues/265

We recommend you to keep default user w/o password. Operator generates host_regexp user setting that restricts default user to the cluster nodes only, so even without a password you can not connect from the outside.

**Comment by SalleryWang** [comment]
i found the host_regexp user setting not works,i cat connect from the outside.like this
    chConfigNetworksHostRegexpTemplate: "(chi-{chi}-[^.]+\\d+-\\d+|clickhouse\\-{chi})\\.{namespace}\\.svc\\.cluster\\.local$"

**Comment by alex-zaitsev** [comment]
One more thing, the default host_regexp is stored in operator configuration:

```
chConfigNetworksHostRegexpTemplate: "(chi-{chi}-[^.]+\\d+-\\d+|clickhouse\\-{chi})\\.{namespace}\\.svc\\.cluster\\.local$"
```

During deployment {chi} is replaced by ClickHouseInstallation name. Since you are using custom pod naming, you need to change it. You can change it globally in operator configuration, but it only applies to new installations. Or you could change it in the installation manifest as follows:

```
  configuration:
    users:
      default/networks/host_regexp: \.ck-svhhp\\d+sop\\d+-hb.jvessel\\d+.local$
```

That should match your host name 'service-ck-svhhp1sop1.ck-svhhp1sop1-hb.jvessel2.local' and the similar ones.

**Comment by Slach** [comment]
@SalleryWang I'm sorry I didn't figure out into the context of your question

**Comment by SalleryWang** [comment]
the generated host_regexp:
(chi-ck-cudgi92oyh-[^.]+\d+-\d+|clickhouse\-ck-cudgi92oyh)\.ck-cudgi92oyh\.svc\.cluster\.local$
the real host:  chi-ck-cudgi92oyh-default-0-0-0.chi-ck-cudgi92oyh-0-0.ck-cudgi92oyh.svc.cluster.local
the     chConfigNetworksHostRegexpTemplate: 
"(chi-{chi}-[^.]+\\d+-\\d+|clickhouse\\-{chi})\\.{namespace}\\.svc\\.cluster\\.local$"

how should i change the chConfigNetworksHostRegexpTemplate or  default/networks/host_regexp?

**Comment by SalleryWang** [comment]
@alex-zaitsev @Slach

**Comment by alex-zaitsev** [comment]
@SalleryWang 

Please remove '[^.]+' part. Probably we should change the defaults as well.

'(chi-ck-cudgi92oyh-\d+-\d+|clickhouse-ck-cudgi92oyh).ck-cudgi92oyh.svc.cluster.local$' should match your host perfectly: chi-ck-cudgi92oyh-default-0-0-0.**chi-ck-cudgi92oyh-0-0.ck-cudgi92oyh.svc.cluster.local**

**Comment by SalleryWang** [comment]
thx

**Comment by SalleryWang** [comment]
the host_regexp is alright, I created a cluster with two shards and two replicas，and did like this on the one relica：
CREATE TABLE local_l ON CLUSTER default (nodeName String,FlightDate Date,Year UInt16) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/local_l','{replica}',FlightDate,(Year, FlightDate),8192);

 CREATE TABLE test_a on CLUSTER default  (nodeName String, FlightDate Date,Year UInt16) ENGINE= Distributed("default", default, local_l, rand()); 

insert into test_a (nodeName,FlightDate,Year)values('BcB','2001-10-12',2001);
last i did: 
![image](https://user-images.githubusercontent.com/45587738/87015089-85924b80-c1ff-11ea-8a1e-6b3b143f2677.png)
when i change a shard
![image](https://user-images.githubusercontent.com/45587738/87015215-b2466300-c1ff-11ea-97af-204ee09f8bbd.png)
i both use the clickhouse-server 19.17.4.11and 19.17.6.36 same error.
I'm sure the host_regexp  it's okay.

Looking forward to your reply @alex-zaitsev @Slach

**Comment by SalleryWang** [comment]
one shard and two replicas have not problem.

**Comment by Slach** [comment]
@SalleryWang when you use 1 shard + 2 replicas, then only one replica will be selected 
look like your clickhouse server can't resolve IP addresses for remote connection from other clickhouse instances

could you run 
```
kubectl  -n your_clickhouse_namespace <your clickhouse pod id> exec bash -c "apt-get update -y && apt install -y --no-install-recommends dnsutils && nslookup 192.168.73.18" 
``` 

also, as a workaround, you can add to your CHI manifests following part:
```
  configuration:
    users:
      default/networks/ip: 192.168.0.0/24
```

**Comment by SalleryWang** [comment]
use 1 shard + 2 replicas  no problem, more than 1 shard bring the prolem

**Comment by SalleryWang** [comment]
i try add  
configuration:
    users:
      default/networks/ip: 192.168.0.0/24

the same error

**Comment by SalleryWang** [comment]
![image](https://user-images.githubusercontent.com/45587738/87027473-cb571000-c20f-11ea-8a6e-c734f9282568.png)
![image](https://user-images.githubusercontent.com/45587738/87027498-d4e07800-c20f-11ea-88bf-d480a623ee99.png)

**Comment by SalleryWang** [comment]
i remove host_regexp,it works!
i can not figure out 1 shard 2 replica, it works normally.but more than 2 shard have problem

**Comment by SalleryWang** [comment]
i remove host_regexp,it works!
i can not figure out that when i control by host_regexp create 1 shard 2 replica, it works normally.but more than 2 shard have problem

**Comment by Slach** [comment]
SalleryWang

look like clickhouse can't resolve your IP address
could you run `kubectl exec -n <your_clickhouse_namespace> <your-clickhouse-pod-id> bash` and try to run `apt-get update -y && apt install -y  --no-install-recommends dnsutils && nslookup 192.168.70.132`

you can try to add 

```
  configuration:
    users:
      default/networks/ip: 192.168.0.0/16
```

instead of 192.168.0.0/24

you don't have any error for 1 shared + 2 replica, cause for Distributed query clickhouse select only one replica from shard, look to https://clickhouse.tech/docs/en/operations/settings/settings/#settings-load_balancing and possible it always was your local server where you run clickhouse-client

**Comment by SalleryWang** [comment]
disable_internal_dns_cache? why set 1?

**Comment by treksler** [comment]
this issue looks to be still a problem

clickhouse installation generates the following remote servers file, which does not have 
`
                    <password>whateverpassword</password>` even if you set a password for the default user. this results in failed distributed queries

```
root@chi-deps-clickhouse-0-0-0:/etc/clickhouse-server# cat ./config.d/..2022_03_16_03_32_17.293799128/chop-generated-remote_servers.xml
<yandex>
    <remote_servers>
        <!-- User-specified clusters -->
        <clickhouse>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-deps-clickhouse-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-deps-clickhouse-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </clickhouse>
        <!-- Autogenerated clusters -->
        <all-replicated>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-deps-clickhouse-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-deps-clickhouse-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-replicated>
        <all-sharded>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-deps-clickhouse-0-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-deps-clickhouse-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-sharded>
    </remote_servers>
</yandex>
```

**Comment by Slach** [comment]
@treksler 
Unfortunately, no way to set password with `clickhouse-operator` inside generated `remote_servers`

but you could setup `secret` (look https://clickhouse.com/docs/en/engines/table-engines/special/distributed/#distributed-clusters for details)
```yaml
spec:
 configuration:
   settings:
     remote_servers/all-sharded/secret: any_secret_word
     remote_servers/all-replicated/secret: any_secret_word
     remote_servers/clickhouse/secret: any_secret_word
```

moreover, `default` user connection should restrict by `host_regexp` and `ip` 
so, you don't require change `default` user password, you can't connect with default user outside from cluster

instead of it, just add your application related user with default profile inside `chi.spec.configuration.users`
https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationusers
