### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#461]
I0710 08:34:02.145372       1 creator.go:199] verifyServiceTemplatePorts(default-service-template) INCORRECT PORT: 0 E0710 08:34:02.145428       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

**Comment by alex-zaitsev** [comment]
@SalleryWang , please provide the cluster manifest.
