### ISSUE TITLE
Easy way to bootstrap Schema for new Clusters?

### ISSUE THREAD

**Issue by fmotrifork** [Altinity/clickhouse-operator#463]
Hi,

First of, great project and very nice operator!

I am currently maintaining a project that has ephemeral Kubernetes clusters/environments, that are created and destroyed automatically.

But I cannot seem to find a nice and easy way to do the initial bootstrapping of the schema for the Clickhouse Cluster, that both works on the first node and that does not interfere with the operator when the next nodes are joining the cluster.

Does this bootstrapping option exist? And do you have an example where it works?

**Comment by MisterTimn** [comment]
We are also looking into this, so far cant seem to find anything. Using docker images we can mount our initdb script to `/docker-entrypoint-initdb.d` and go from there.

Can we add this script as a configmap/secret and refer to it somehow through `clickhouseoperatorconfigurations`?
I've seen there's a `files` entry in it.

**Comment by alex-zaitsev** [comment]
@fmotrifork , @MisterTimn  see this example: https://github.com/Altinity/clickhouse-operator/blob/0.15.0/docs/chi-examples/02-templates-07-bootstrap-schema.yaml
