### ISSUE TITLE
Setting logger level for clickhouse-operator itself

### ISSUE THREAD

**Issue by wiktor2200** [Altinity/clickhouse-operator#468]
Hello, I'm trying to set proper logger level for clickhouse-operator. 
By default it emits thousands of logs and in GCP Stackdriver it makes a lot of mess as well as costs. Logs which are emitted by operator look like DEBUG level. I've found setting log parameters in `clickhouse-operator-install.yaml` by modifying verbosity level: `v: "1"`. It's set to `1` by default and it's overwritten every time `build-clickhouse-operator-install-yaml.sh` is run.
It has no documentation in clickhouse-operator . I've found also in code that logs are maintained by https://github.com/golang/glog library but it also has limited documentation. 

I've tried modifying it on my own but when I changed it to `v: "0"` I resulted with a few log entries only emitted while creating new operator pods. It create no logs while changing clickhouse-server version, deleting pod of one clickhouse-server etc.

So my question is as follows, is there any possibility to change log level to for example INFO (to get only relevant information)?

**Comment by sunsingerus** [comment]
> ...is there any possibility to change log level...

As you've specified earlier, there is `v` parameter in operator's configuration. It exposes the same `v` parameter from https://github.com/golang/glog library, which is used by the operator for logging.

>...to for example INFO (to get only relevant information)?...

There is not such notion as `INFO` log level, just numbered ones. There is no direct mapping between numbers and named logging levels, but it roughly can be presented as:

v=0: display important messages only
v=1: display general workflow. Can be used for tracing operator's actions in general. No detailed info, though. Typical log level
v=2: display more detailed workflow. Can be used for detailed tracing operator's actions. Used for development
v=3: display everything. Used for debugging and development (but it is excessive even for day-to-day development)

Also, please note, you need to restart operator (manually) after operator's configuration changed (at least now) in order operator to adopt updated configuration. (Yes, we already have in backlog task to reload configuration on-the-fly)

**Comment by wiktor2200** [comment]
Ok, thanks for your answer.
