### ISSUE TITLE
Wrong chi status: delete then recreate

### ISSUE THREAD

**Issue by slimtom95** [Altinity/clickhouse-operator#472]
Delete a completed chi and then recreate it:

The chi status changes like:

Completed(before delete) -> (removed) -> empty (recreate) -> Completed ( chop handling delete event) -> InProgress (chop handling add event) -> Completed (done)

I think the expected status chain should be:

Completed(before delete) -> (removed) -> empty (recreate) -> **InProgress ( chop handling delete event)** -> InProgress (chop handling add event) -> Completed (done)

**Comment by alex-zaitsev** [comment]
The current behavior is correct. It waits until the previous operation to complete before going to the next one.

**Comment by slimtom95** [comment]
@alex-zaitsev Perhaps I didn't make it clear, I think the problem is that `delete` keep previous status. So when you delete chi and recreate it immediately, chi is at Completed status during delete event handling, but it shouldn't be.

Delete should set status as InProgress, in case it may be created very soon.

**Comment by alex-zaitsev** [comment]
Could you check with 0.11 version? The delete logic has been completely changed in there.

**Comment by slimtom95** [comment]
Indeed, the new mechanism in 0.11.0 doesn't have this issue. Thanks.
