### ISSUE TITLE
Crashes during delete handling may cause unbound pods

### ISSUE THREAD

**Issue by slimtom95** [Altinity/clickhouse-operator#473]
If chop crashes when handling delete event, the remaining pods will hang there (util someone comes to save them :)

To avoid this situation, for example, would we consider to add a step in chop's boot to check and remove those unbound resources..

**Comment by alex-zaitsev** [comment]
Deletion process has been refactored in 0.11.0 (to be released this week). In any case, I would not delete pods if not asked. If CHI with the same name gets re-created, pods will be re-created as well.
