### ISSUE TITLE
Lost connection with CHI after upgrade image

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#482]
I've manually built a metrics-exporter's image, and I want to replace it in the clickhouse-perator pod.
No matter which way I upgrade, deleting and reinstalling operator or setting image as [operator_upgrade.md](https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_upgrade.md) said, I cannot get any metrics in my new metrics-exporter.
Why is that?
Is there a way you can update image without reinstalling CHI which is in production environment and without losing the connection?
My clickhouse-operator version is `0.9.9`.

**Comment by winter7** [comment]
@alex-zaitsev Can you help it my friend?

**Comment by alex-zaitsev** [comment]
You may alter your clickhouse-operator deployment object as follows:

1. kubectl get deployment clickhouse-operator -n <your-namespace> -o yaml > deployment.yaml
2. Find the line with  'image: altinity/metrics-exporter:0.11.0'
3. Modify the image to the new one.
4. Apply deployment back with 'kubectl apply -f deployment.yaml'

I am not sure it would not cause CHI restart though. We are working on 0.11 version now that would not restart CHI on operator restarts/upgrades.

**Comment by winter7** [comment]
@alex-zaitsev I mean, doesn't
```
kubectl set image deployment.v1.apps/clickhouse-operator metrics-exporter=my-image -n kube-system
```
achieve what you described above? 
Although I'll try it.

**Comment by winter7** [comment]
@alex-zaitsev It seems doesn't work, man.
And when I tried to upgrade my EKS version, here is another scene, clickhouse-operator reassignment caused all clickhouse pods reassignment., even not scrolling.
Can any other methods solve it?

**Comment by alex-zaitsev** [comment]
@winter7 , have you figured it out?

**Comment by winter7** [comment]
@alex-zaitsev For now every time the clickhouse-operator pod changes ( updates image or migrates to another node), the CHI would scroll to reassign (restart). I take that as normal.

**Comment by alex-zaitsev** [comment]
ok, I will close it then
