### ISSUE TITLE
Need a way to limit what labels get copied to child resources.

### ISSUE THREAD

**Issue by denniswebb** [Altinity/clickhouse-operator#487]
## Issue and Background

We use [ArgoCD](https://github.com/argoproj/argo-cd) for our GitOps operator. Our ClickHouseInstallation is `kubectl apply` itself with Argo. If we remove the YAML for an object from our git repo, the ArgoCD will see this has been removed and will remove the old resource.

ArgoCD is able to handle this buy adding a label `argocd.argoproj.io/instance` to all Kubernetes resources it has created so it knows if the YAML for that resource is removed from github, that it was originally managed by ArgoCD and should be pruned(deleted).

The issue with ClickhouseOperator is that it copies all the labels from the ClickHouseInstallation resource and adds it to the child resources such as configmaps, services, pods, etc. This also copies the `argocd.argoproj.io/instance` and triggers ArgoCD to believe that the resource has been abandoned and it wants to prune those configmaps, statefulsets, etc.

This can be avoided if an object has the annotation `argocd.argoproj.io/sync-options: Prune=false` attached to it, but unfortunately ClickHouseOperator does not copy the annotations to all resources.

## Proposed Solution

I believe the best solution to this would be to add a configuration option to any ClickHouseInstallation for a list of `IgnoreLabels`. We could configure any non-clickhouse related labels that shouldn't be copied here. This will prevent the `argocd.argoproj.io/instance` label or any other label we choose from being copied to all resources managed and owned by the ClickHouseOperator process.

**Comment by alex-zaitsev** [comment]
@denniswebb , this is an interesting use case. Maybe it is easier to add a flag that would prevent copying user labels from CHI to dependent resources at all?

**Comment by denniswebb** [comment]
That works for me.

**Comment by sunsingerus** [comment]
Implemented in #676 
PR merged. 
To be released in 0.14.0
