### ISSUE TITLE
Whether to support the expansion of replicas and shards with existing data？

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#492]
https://github.com/Altinity/clickhouse-operator/commit/76c20700014916807a649d5419ede74434efe371
i think the expansion not work

**Comment by alex-zaitsev** [comment]
Operator creates schema on shards and replicas. When replicated tables are created on new replicas, it gets automatically replicated. Rebalance to new shards is not supported by ClickHouse now. We plan to work on that later this year.
