### ISSUE TITLE
Can't add satefulsets / container resources (limits/requests)

### ISSUE THREAD

**Issue by mohamedelbahr** [Altinity/clickhouse-operator#520]
This is my pod template configurations copied from example in repo:

` podTemplates:
      - name: clickhouse:20.5.3.27
        zone:
          key: "lifecycle"
          values:
            - "stable"
        podDistribution:
          - type: ShardAntiAffinity
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.6.2.11
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"`
#########################################################
 podTemplates:
      - name: clickhouse:20.5.3.27
        zone:
          key: "lifecycle"
          values:
            - "stable"
        podDistribution:
          - type: ShardAntiAffinity
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.6.2.11
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
#########################################################

The resources is not updated / no error logs in operator 

I notice this at the Output of `kubectl describe  ClickHouseInstallation/clickhouse`

invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

Can you please help !

**Comment by alex-zaitsev** [comment]
@mohamedelbahr , could you explain what you are trying to do, step by step, please?
