### ISSUE TITLE
Clickhouse configuration update

### ISSUE THREAD

**Issue by billstark** [Altinity/clickhouse-operator#528]
Hi there, I found this fantastic solution for clickhouse + k8s deployment but I am quite new to clickhouse as well as this clickhouse operator so I want to clarify something. 

**Our Clickhouse usage:**
We will be using clickhouse in a way that changes the `external dictionary` configuration quite often; we might need to add new connections frequently.

**Our concerns**
We are not really sure about what would be the best practice for configuration update. 
1. As clickhouse servers are deployed using custom resource, should we directly patch the custom resource with new dictionary configuration? 
2. From our point of view, this might result in restart of the clickhouse service is that correct?
3. Just in case if we do not want to experience down time of the clickhouse, what would you suggest us to do in this case?

Thank you very much!

**Comment by alex-zaitsev** [comment]
Hi @billstark , ClickHouse from versions 20.1 and above supports [CREATE DICTIONARY](https://clickhouse.tech/docs/en/sql-reference/statements/create/dictionary/) syntax. We recommend using it instead of external dictionaries configuration in XML.

**Comment by billstark** [comment]
@alex-zaitsev Get it and thanks for your reply.
