### ISSUE TITLE
error when creating  yaml

### ISSUE THREAD

**Issue by xinxinzxc** [Altinity/clickhouse-operator#550]
when i exec
kubectl apply -f 01-simple-layout-02-1shard-2repl.yaml
i get
Error from server (NotFound): error when creating "01-simple-layout-02-1shard-2repl.yaml": the server could not find the requested resource (post clickhouseinstallations.clickhouse.altinity.com)

**Comment by Slach** [comment]
look like you didn't install `clickhouse-operator` itself and related CRDs
you can install operator with follow instructions
here
https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md#clickhouse-operator-installation

**Comment by xinxinzxc** [comment]
thanks 
i didn't exec kubectl apply -f 01-simple-layout-02-1shard-2repl.yaml in the namespace where clickhouse-operator in
