### ISSUE TITLE
ch-cluster connecting problem

### ISSUE THREAD

**Issue by xinxinzxc** [Altinity/clickhouse-operator#552]
hi 
here is my svc
 kubectl get svc -n test-clickhouse-operator
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
chi-pv-simple-simple-0-0   ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP      28m
chi-pv-simple-simple-0-1   ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP      28m
chi-pv-simple-simple-1-0   ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP      27m
chi-pv-simple-simple-1-1   ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP      27m
clickhouse-pv-simple       LoadBalancer   10.100.65.42    <pending>     8123:32488/TCP,9000:31318/TCP   29m
zookeeper                  ClusterIP      10.109.86.202   <none>        2181/TCP,7000/TCP               43m
zookeepers                 ClusterIP      None            <none>        2888/TCP,3888/TCP               43m

when i use tool to connect clickhouse clusters

jdbc:clickhouse://10.30.80.85:32488 
(NOTE: 10.30.80.85 is my real machine's ip which my kubernetes running on )
user :default
but when i test connetction i received
java.net.SocketTimeoutException: connect timed out.
what should i do.

**Comment by Slach** [comment]
@xinxinzxc how you exactly install your kubernetes cluster which installation method did you use?
LoadBalancer doesn't guaranteed access outside `kubernetes` cluster by default, it allows outside connection for cloud providers, but not for minikube for example
https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

you should install Ingress and IngressController to pass outside connection into cluster
https://kubernetes.io/docs/concepts/services-networking/ingress/

or only for dev environment you can try to run `kubectl port-forward service/clickhouse-pv-simplte 8123:8123 &` on your `10.30.80.85`
