### ISSUE TITLE
Question - New Grafana operator version and alerting support

### ISSUE THREAD

**Issue by wiktor2200** [Altinity/clickhouse-operator#556]
Hello, I'm following new info about updating Grafana version with alerting support.
In this line there was a comment about plugin update.
https://github.com/Altinity/clickhouse-operator/blob/26f65d0f30e6ac83fa5fcb2d48a22086f6ad35c8/deploy/grafana/grafana-with-grafana-operator/grafana-dashboard-operator-cr-template.yaml#L16
It's merged long time ago and current version is here:
https://github.com/Altinity/grafana-plugin-repository/blob/ebd76585b7f8dea7b048e06da0718efb13877755/repo.json#L2173

So what's the status of this change? Is it still blocked by something else?
Thanks in advance for your reply.

**Comment by Slach** [comment]
yep, currently, we wait when `grafana-operator` will publish the next stable release which will contain https://github.com/integr8ly/grafana_plugins_init/pull/2 and grafana plugins init side container 0.0.3 version
you can try to install 

```
GRAFANA_OPERATOR_VERSION=latest ./deploy/grafana/grafana-with-operator/install-grafana-operator.sh
```

change ./deploy/grafana/grafana-with-operator/grafana-dashboard-operator-cr-template.yaml, and run
```
./deploy/grafana/grafana-with-operator/install-grafana-with-operator.sh
```

**Comment by wiktor2200** [comment]
Thanks for info. :+1:  
I look forward to new `grafana_plugins_init` new stable version.
