### ISSUE TITLE
pod restarting when replica is added

### ISSUE THREAD

**Issue by yanalavishnu** [Altinity/clickhouse-operator#563]
Versions

1. eksctl 0.28.1
2. kubectl v1.17.9-eks-4c6976
3. Clickhouse operator 0.12.0

I have been trying to add a replica to the existing cluster. After increasing the replica count. shard1 replica 0 is restarting(terminating and creating freshly)

Below is the spec of the installation

    apiVersion: "clickhouse.altinity.com/v1"
    kind: "ClickHouseInstallation"
    metadata:
      name: "clickhouse-xxxx"
    
    spec:
      stop: "no"
      defaults:
        replicasUseFQDN: "no"
        distributedDDL:
          profile: default
        templates:
          podTemplate: clickhouse-replica-v20.3
          dataVolumeClaimTemplate: volume-claim-delete-pvc
          logVolumeClaimTemplate: default-volume-claim
          serviceTemplate: chi-service-template
    
      configuration:
        zookeeper:
          nodes:
            - host: zookeeper-0.zookeepers.zoons.svc.cluster.local
              port: 2181
            - host: zookeeper-1.zookeepers.zoons.svc.cluster.local
              port: 2181
            - host: zookeeper-2.zookeepers.zoons.svc.cluster.local
              port: 2181
          session_timeout_ms: 30000
          operation_timeout_ms: 10000
        users:
          default/profile: default
          readonly/profile: readonly
          default/networks/ip:
            - "127.0.0.1"
            - "::1"
            - "::/0"
          xxxx/networks/ip:
            - "127.0.0.1"
            - "::/0"
          xxxx/profile: default
          xxxx/quotas: default
        profiles:
          readonly/readonly: "1"
          default/max_memory_usage: "25000000000"
          default/max_bytes_before_external_group_by: "10000000000"
          default/max_memory_usage_for_all_queries: "25000000000"
        quotas:
          default/interval/duration: "3600"
        settings:
          compression/case/method: zstd
          disable_internal_dns_cache: "1"
    
        clusters:
          - name: production
            layout:
              shards:
                - name: "0"
                  replicasCount: 1
                  internalReplication: Enabled
                  replicas:
                    - name: 0-replica0
                      templates:
                        podTemplate: clickhouse-v20.3
                        dataVolumeClaimTemplate: volume-claim-retain-pvc
                        logVolumeClaimTemplate: default-volume-claim
                - name: "1"
                  replicasCount: 1 
                  internalReplication: Enabled
                  replicas:
                    - name: 1-replica0
                      templates:
                        podTemplate: clickhouse-v20.3
                        dataVolumeClaimTemplate: volume-claim-retain-pvc
                        logVolumeClaimTemplate: default-volume-claim
      templates:
        serviceTemplates:
          - name: chi-service-template
            generateName: "service-{chi}"
            metadata:
              annotations:
                # For more details on Internal Load Balancer check
                # https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
                cloud.google.com/load-balancer-type: "Internal"
                service.beta.kubernetes.io/aws-load-balancer-internal: "true"
                service.beta.kubernetes.io/azure-load-balancer-internal: "true"
                service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
                service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
                service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-xxxxxxxxxxxx"
                # NLB Load Balancer
                service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            spec:
              ports:
                - name: http
                  port: 8123
                  targetPort: 0
                - name: tcp
                  port: 9000
                  targetPort: 0
              type: LoadBalancer
    
        volumeClaimTemplates:
          - name: default-volume-claim
            reclaimPolicy: ""
            spec:
              storageClassName: gp2-delete
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          - name: volume-claim-delete-pvc
            reclaimPolicy: Delete
            spec:
              storageClassName: gp2-delete
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Gi
          - name: volume-claim-retain-pvc
            reclaimPolicy: Retain
            spec:
              storageClassName: gp2-persistent
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Gi
    
        podTemplates:
          - distribution: ""
            name: clickhouse-v20.3
            zone:
              key: "server"
              values:
                - "clickhouseOnDemand"
            podDistribution:
              - type: ClickHouseAntiAffinity
    
            spec:
              containers:
                - name: clickhouse
                  image: yandex/clickhouse-server:20.3
                  volumeMounts:
                    - name: volume-claim-retain-pvc
                      mountPath: /var/lib/clickhouse
                  resources:
                    requests:
                      memory: "20Gi"
                      cpu: "4"
                    limits:
                      memory: "30Gi"
                      cpu: "8"
          - distribution: ""
            name: clickhouse-replica-v20.3
            zone:
              key: "server"
              values:
                - "clickhouseEC2Spot"
            podDistribution:
              - type: ClickHouseAntiAffinity
            spec:
              containers:
                - name: clickhouse
                  image: yandex/clickhouse-server:20.3
                  volumeMounts:
                    - name: volume-claim-delete-pvc
                      mountPath: /var/lib/clickhouse
                  resources:
                    requests:
                      memory: "20Gi"
                      cpu: "4"
                    limits:
                      memory: "30Gi"
                      cpu: "8"

**Comment by yanalavishnu** [comment]
If the replica count is changed to 2, the pod chi-clickhouse-xxxx-production-1-replica0-0 is terminating and starting again. May I know what is the issue?

**Comment by alex-zaitsev** [comment]
Should be not an issue from 0.13.5 and above.
