### ISSUE TITLE
Configmap chi-{CRD_NAME}-common-configd hold 2 file instead of 6 file

### ISSUE THREAD

**Issue by Boston01** [Altinity/clickhouse-operator#573]
I'm using the the operator of clickhouse, and i have statefulset name for my CRD shown here
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "statefulset"
  namespace: ${NAMESPACE_INSTALL}
spec:
....
when i instal this CRD the configMap chi-statefulset-common-configd did not hold the all xml file what are going to be mounted in /etc/clickhouse-server/config.d/.
Only two xml files are mounted chop-generated-remote_servers.xml  chop-generated-settings.xml.
I did not find the root cause if the issue.
For information im fworking for [www.the-ica.com](url)

**Comment by Slach** [comment]
@Boston01 could you share your `spec.configuration.files` section of ClickHouseInstallation CR?
https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationfiles

**Comment by Boston01** [comment]
Hi Slach the probleme was not in spec.configuration.files, it was about the clickhouse-operator-install-template.yaml file,  when another way of installing this file like echo "$MANIFESTS" | kubectl apply -f -, MANIFESTS can be seen as MANIFESTS=`eval "cat <<EOF
$(cat $1)
EOF
"` 
In MANIFESTS there are some customed variables that are going to be substituted. 
This kind of doing just create two configmap as i discribed before.
And when  juste use kubectl apply -f clickhouse-operator-install-template.yaml it work fine !!!
