### ISSUE TITLE
Configure annotations of PVC

### ISSUE THREAD

**Issue by qixiaogang** [Altinity/clickhouse-operator#578]
In our environment, we used annotations in PVC for some automation work. Now the annotations of PVC is not configurable, it will be great to support annotation in ChiVolumeClaimTemplate.

**Comment by alex-zaitsev** [comment]
Scheduled for 0.14

**Comment by sunsingerus** [comment]
implemented

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/0.14.0
