### ISSUE TITLE
Bump operator in upstream-community-operators to 0.12.0

### ISSUE THREAD

**Issue by made-with-care** [Altinity/clickhouse-operator#579]
Current version of operator in [upstream-community-operators](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/clickhouse) is 0.10.0.
Please bump it to 0.12.0.

**Comment by alex-zaitsev** [comment]
Yes, will do

**Comment by kirushkame** [comment]
I would like to use this version too! Many thanks.

**Comment by alex-zaitsev** [comment]
Version has been updated to 0.12.0. cc @kirushkame @made-with-care
