### ISSUE TITLE
How to deal with DNS caching when Pod IPs can/will change

### ISSUE THREAD

**Issue by agelwarg** [Altinity/clickhouse-operator#58]
It looks like you are deploying each "node" as a single instance `StatefulSet`, and relying on the DNS name of each Pod under a headless `Service` for replication (since the default interserver_http_host is `hostname -f`) as well as cluster definitions in `<yandex><remote_server>....</remote_servers></yandex>`.  This works fine on initial deployment.  However, in the event that a `Pod` is restarted (planned or unplanned), the DNS caching on each node creates a problem.  Is the intention to trigger something like `SYSTEM DROP DNS CACHE` on each node after the restarted `Pod` is ready?

On another note, in our own deployment using a Helm chart, we tried dealing with this in another way.  We placed a regular `Service` in front of each `StatefulSet`, knowing that it's `ClusterIP` would be static (unless we remove that `Service`, which is much less likely).  We then explicitly set the `<interserver_http_host>` to that `Service` name, and used it in `<remote_servers>` as well.  This seems to work for everything EXCEPT any `ON CLUSTER` queries.  We have no idea WHY those queries seem to be blocked at a network layer -- they're just timing out.  We haven't traced that yet, but were wondering if you maybe know why these queries fail.

**Comment by sunsingerus** [comment]
Hello and thanks for the note!
> It looks like you are deploying each "node" as a single instance `StatefulSet`, 

Yes  - each ClickHouse instance is running in personal 1-pod-size StatefulSet
> and relying on the DNS name of each Pod under a headless `Service` for replication

Yes - DNS names based on headless `Service` are used for inter-server communication - such as replication
> This works fine on initial deployment. However, in the event that a `Pod` is restarted (planned or unplanned), the DNS caching on each node creates a problem. 

Thanks for pointing this out! We need to investigate further for details
>Is the intention to trigger something like `SYSTEM DROP DNS CACHE` on each node after the restarted `Pod` is ready?

Of course, we need to deal with DNS caching some way or another. I can't say right now what steps exactly would be make, though.
> On another note, in our own deployment using a Helm chart, we tried dealing with this in another way. We placed a regular `Service` in front of each `StatefulSet`, knowing that it's `ClusterIP` would be static (unless we remove that `Service`, which is much less likely). We then explicitly set the `<interserver_http_host>` to that `Service` name, and used it in `<remote_servers>` as well. 

Thanks for the idea! Yes indeed, each ClickHouse instance can be shielded by personal `Service` with `ClusterIP`
>This seems to work for everything EXCEPT any `ON CLUSTER` queries. We have no idea WHY those queries seem to be blocked at a network layer -- they're just timing out. We haven't traced that yet, but were wondering if you maybe know why these queries fail.

Thanks for notification, sure we'll need to investigate in more details

So, we definitely need to review DNS subsystem within ClickHouse installation

**Comment by agelwarg** [comment]
I misread how you were using the headless `Service` at first.  Originally I thought you were referencing the actual Pod name (i.e., `XXX-0-0-0`) in `<remote_servers>` and letting DNS resolve that, but now I see you are referencing the headless `Service` name (i.e., `XXX-0-0`), which I didn't know could also resolve the `Pod` IP as well.  I imagine that's kube dns is doing round-robin DNS against any Pods that match the headless `Service` selector, which is only 1 in this case.  Neat trick -- the removes the need to further qualify the full Pod name.  We had previously needed to use something like this:

```XXX-0-0-0.XXX-0-0`

**Comment by bzon** [comment]
This is also related to this issue https://github.com/yandex/ClickHouse/issues/4970

**Comment by bzon** [comment]
This is actually a serious issue as it stops replication where replica host 1 couldn't reach replica host 2 because of outdated IP address in **system.clusters**. If you are not monitoring **merge_in_queues**, it could pile up and eventually stress the replica host CPU once it's fixed.

**Comment by alex-zaitsev** [comment]
I confirm, operator does not handle pod re-provisioning properly. IP address is cached.  SYSTEM DROP DNS CACHE helps. We will discuss internally and implement a fix.

**Comment by bzon** [comment]
One thing I noticed the other day is even after running **SYSTEM DROP DNS CACHE** and seeing that the **host_address** has changed in **system.clusters**, I still keep seeing errors in the console logs about Clickhouse using the outdated host address.

```
        <logger>
            <level>trace</level>
            <console>1</console>
        </logger>
```

The solution was to restart Clickhouse Pod again and then run **SYSTEM DROP DNS CACHE** on the other replica pod.

I'm running Clickhouse docker image **19.4.1.3**.

**Comment by alex-zaitsev** [comment]
In 0.2.1 release we have added 'SYSTEM DROP DNS CACHE' on pod restarts (actually, on all endpoint IP address changes) -- it solves the issue. There could be some delay before it takes an effect though.

We have also confirmed that it only affects distributed tables, replication continues to work properly when pod is re-provisioned.
