### ISSUE TITLE
clickhouse-operator "schemer" doesn't apply changes if replicasCount has been changed together with operator restart

### ISSUE THREAD

**Issue by ivanblack19** [Altinity/clickhouse-operator#594]
Hello, 
After changing YAML manifest and adding an additional replica, the CH operator doesn't create empty tables on new pods, and therefore ClickHouse not replicate all data via zookeeper queue
CH operator verion is 0.12.0

BEFORE
```
layout:
shards:
- name: "0"
replicasCount: 3
templates:
podTemplate: clickhouse-v20.4.4.18
```

AFTER

```
layout:
shards:
- name: "0"
replicasCount: 4
templates:
podTemplate: clickhouse-v20.4.4.18
```

**Comment by alex-zaitsev** [comment]
As discussed in another thread the problem was in Helm chart that restarted an operator together with replicasCount change. When restarted -- operator reconciles the objects properly but do not apply schema changes. This can be probably fixed so let's keep it open.

**Comment by alex-zaitsev** [comment]
0.13.0 version should fix this issue. It tries to re-create schema on every reconcile attempt, and therefore should handle this scenario properly as well.
