### ISSUE TITLE
What is the use of Autogenerated Clusters and how to colse Autogenerated Clusters

### ISSUE THREAD

**Issue by wfxxh** [Altinity/clickhouse-operator#616]
I create a cluster like the 'replication_setup.md' described , but there create a Autogenerated cluster, I do not know the use of the cluster,and how to close it
![图片](https://user-images.githubusercontent.com/22764286/101316337-48f27b00-3897-11eb-92e3-3414f4887ec0.png)
![图片](https://user-images.githubusercontent.com/22764286/101316371-5a3b8780-3897-11eb-9baa-b7f1b90e1552.png)

**Comment by alex-zaitsev** [comment]
Single ClickHouse installation allows users to define different data distribution layouts, that are sometimes confusingly referred as clusters. In your example
* 'test_' clusters are default ClickHouse, used in unit tests. Those can be ignored
* 'all-replicated' cluster is 1 shard N replicas, useful for tables that should be replicated across all nodes.
* 'all-sharded' cluste is N shards, 1 replica, useful for tables that should be distributed across all nodes.
* 'med' -- this is your cluster that corresponds to CHI definition (3 shards and 2 replicas). It should be used in a general case for replicated and distributed tables.
