### ISSUE TITLE
Prevent ClickHouse operator from creating a load balancer

### ISSUE THREAD

**Issue by dav1d992** [Altinity/clickhouse-operator#631]
I have a cluster wherein I have loaded a ClickHouse operator. When I'm applying the installation here: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/04-replication-zookeeper-03-minimal-AWS-persistent-volume.yaml
A load balancer will be created. I would like to NOT have that load balancer created. 

**Is there anything that I can change in the _04-replication-zookeeper-03-minimal-AWS-persistent-volume.yaml_ file so that the load balancer isn't created?**

**Comment by alex-zaitsev** [comment]
@dav1d992 , you need to add serviceTemplate with ClusterIP type in order to override the default one. See examples of serviceTemplate:

https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-03-service-template.yaml

https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-012-service-template.yaml

**Comment by jessezax** [comment]
> @dav1d992，您需要添加具有 ClusterIP 类型的 serviceTemplate 以覆盖默认类型。查看 serviceTemplate 的例子：
> 
> https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-03-service-template.yaml
> 
> https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-012-service-template.yaml

it seems like not works

**Comment by Slach** [comment]
@jessezax could you share your `kind: ClickHouseInstallation` manifest?

**Comment by jessezax** [comment]
> @jessezax could you share your `kind: ClickHouseInstallation` manifest?
sorry.forget add :
```
defaults:
    templates:
      serviceTemplate: clickhouse-lb
```
and did 
serviceTemplate -- >LoadBalancer
clusterServiceTemplate --> ClusterIP
?

**Comment by Slach** [comment]
@jessezax if you have

```yaml
templates:
  serviceTemplates:
    - name: clickhouse-lb
       type: LoadBalancer
defaults:
   templates:
      serviceTemplate: clickhouse-lb       
```       

it will create service with `type: LoadBalancer`
change type: LoadBalancer to `type: ClusterIP` and you will get another service type

if you not define  serviceTemplate, clusterServiceTemplate, shardServiceTemplate, replicaServiceTemplate in defaults.templates, for example
```
defaults:
  clusterServiceTemplate: another-temlate-name
```

then default serviceTemplates (defined in golang code) will applied for creating services

**Comment by jessezax** [comment]
> @jessezax if you have
> 
> ```yaml
> templates:
>   serviceTemplates:
>     - name: clickhouse-lb
>        type: LoadBalancer
> defaults:
>    templates:
>       serviceTemplate: clickhouse-lb       
> ```
> 
> it will create service with `type: LoadBalancer` change type: LoadBalancer to `type: ClusterIP` and you will get another service type
> 
> if you not define serviceTemplate, clusterServiceTemplate, shardServiceTemplate, replicaServiceTemplate in defaults.templates, for example
> 
> ```
> defaults:
>   clusterServiceTemplate: another-temlate-name
> ```
> 
> then default serviceTemplates (defined in golang code) will applied for creating services

thanks
