### ISSUE TITLE
How to prevent access of unauthenticated users 

### ISSUE THREAD

**Issue by dav1d992** [Altinity/clickhouse-operator#632]
The clickhouse-operator is deployed to my cluster and in my installation file I have 
`users: `
   `        user2/networks/ip: "::/0"`
  `user2/password: qwerty`      
       ` user2/profile: default`
borrowed from your example [here]( https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-03-2-user2.yaml)

I'm expecting that I can't simply connect to that pod and use `clickhouse-client ` but that is not the case. The pod has no restrictions. There is probably something I've missed out or misunderstood. Can you enlighten me on what to do to achieve what i'm expecting?

**Comment by Slach** [comment]
just add
```
 users:
   default/password: some_random_password 
```
