### ISSUE TITLE
> define custom remote_servers section

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#641]
> define custom remote_servers section

I mean to define custom remote_servers section

_Originally posted by @Sallery-X in https://github.com/Altinity/clickhouse-operator/issues/640#issuecomment-768875627_

**Comment by alex-zaitsev** [comment]
You can do it, see this example:
https://github.com/Altinity/clickhouse-operator/blob/0282ca198ecbde670f919aa8d0438a00d4ffd97f/tests/configs/test-016-settings-01.yaml#L43
