### ISSUE TITLE
events, events_local tables lost once pod is drifted to another node.

### ISSUE THREAD

**Issue by leoxhj** [Altinity/clickhouse-operator#645]
Hi folks,

Today we have tested below scenario:

* create a new clickhouse with 2shards, 2replicas using persistent volumes, list out correspodings nodes shown as follows:
```bash
0-0-0 node1
0-1-0 node1
1-0-0 node1
1-1-0 node2
```
* cordon node2 
> let assume this node is permenant damaged, and data is unrecoverable
```bash
kubectl cordon node2
```
* delete pvc 1-1-0 
> have to delete pvc, then delete pod, otherwise, the pod will never reschedule to a new node due to k8s statefulset restriction (sticky to the node has pvc)
* delete pod 1-1-0
* the pod 1-1-0 is rescheduled to another new node, let's say node3
* check events, events_local tables on instance 1-1-0, there are missing. (another 3 instances, those two tables just fine)
Would you kindly please confirm this? 

Thanks

**Comment by alex-zaitsev** [comment]
If you delete PVC, you delete the data. Operator can recover the schema, and ClickHouse may replicate from another replica, but it does not do it automatically now, only when some changes needs to be done to CHI. This is a good use case for a local storage, though, we will add FR to one of next releases.

**Comment by leoxhj** [comment]
as per current operator, we have workaround steps like below:
1. the pod is rescheduled to the new node with lossing schema and data
2. scale down one replica from chi yaml manifests
3. scale up back one replica

**Comment by alex-zaitsev** [comment]
@leoxhj , We've made some changes over 2022 that makes it easier. If you need to re-provision the volume (because volume is broken, or node with local storage is gone), just delete PVC and trigger CHI update. That will re-create PVC, and sync schema from other replicas. For replicated tables it will do ATTACH that creates a table and starts replication
