### ISSUE TITLE
inquiry regarding RBAC permission on service account:  clickhouse-operator

### ISSUE THREAD

**Issue by leoxhj** [Altinity/clickhouse-operator#646]
Dear team, 

   we noticed the rbac for clickhouse-operator is binding to highest cluster role user: cluster-admin, this is not allowed for our production environment since we need to specify detail cluster resources and give out as minimum permission as possible to prevent security issues, would you kindly please advice on those specific resouces permission for the sa? e.g. pvc, pod, ...

Thanks.

**Comment by sunsingerus** [comment]
`clickhouse-operator` role is restricted with PR #675
PR is merged into 0.14.0 branch
Feel free to provide any feedback

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/0.14.0
