### ISSUE TITLE
Add prometheus metrics config by default

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-operator#649]
Currently the prometheus config has to be added separately.
Since a lot of people will want to have metrics, perhaps it's useful to add it in the default config layout?

https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus

**Comment by alex-zaitsev** [comment]
operator uses its own metrics-exporter that provides more data compared to the built-in ClickHouse Prometheus exporter. There is also a dedicated Grafana dashboard that is integrated with it: https://github.com/Altinity/clickhouse-operator/tree/master/grafana-dashboard

The operator's metrics-exporter has been designed before ClickHouse endpoint was available, and it is easier to adopt. Nevertheless, we are in a process of designing a solution that would allow operator to use ClickHouse endpoint that will require some extension and configurable tagging.

**Comment by electrical** [comment]
Ah perfect, thank you. I must have missed that. I'll have a look at the metrics and dashboard :-) Thanks!

**Comment by electrical** [comment]
Closing as there are existing metrics indeed and added the dashboard. Thank you for pointing me to it.
