### ISSUE TITLE
Unexpected metrics-exporter behavior

### ISSUE THREAD

**Issue by MisterTimn** [Altinity/clickhouse-operator#653]
I have set up the clickhouse operator and wanted to collect metrics from it. I use the prometheus operator as well so I just defined a service monitor to start scraping.

![2021-02-19-100032_1088x196_scrot](https://user-images.githubusercontent.com/4209558/108491799-a8f89b00-72a4-11eb-8529-6a6a3876acdd.png)
The job is up and running and I can see the scrapes coming in on the metrics-exporter through logs:
```
I0219 10:03:23.822198       1 exporter.go:98] Finished Collect
I0219 10:03:33.822924       1 exporter.go:88] Starting Collect
I0219 10:03:33.822945       1 exporter.go:98] Finished Collect
I0219 10:03:43.822285       1 exporter.go:88] Starting Collect
I0219 10:03:43.822303       1 exporter.go:98] Finished Collect
I0219 10:03:53.822311       1 exporter.go:88] Starting Collect
I0219 10:03:53.822333       1 exporter.go:98] Finished Collect
```

Yet when I go to inspect my metrics, I can see a list of all available metrics yet there is only 1 entry for each of these
![2021-02-19-102340_1826x541_scrot](https://user-images.githubusercontent.com/4209558/108492013-eeb56380-72a4-11eb-96cd-50f2f51a2543.png)

This is the case for all metrics... I tried to find similar issues but to no avail.
Prometheus isn't showing any errors whatsoever, weird thing is, I even saw the appended samples/scrape targets go up when I deployed the service monitor object.

Querying yields the same result in the Prometheus built in graph tool. All my other metrics (custom instrumentation, dependencies and kubernetes metrics) are running normally.

**Comment by Slach** [comment]
when you run repeatedly

```
kubectl exec -n kube-system $(kubectl get pods -n kube-system -o name | grep clickhouse-operator) -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/metrics
```

is `chi_clickhouse_events_InstertedRows` metric changed?

**Comment by MisterTimn** [comment]
This is what I get as response:
```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 8.933e-06
go_gc_duration_seconds{quantile="0.25"} 1.6137e-05
go_gc_duration_seconds{quantile="0.5"} 2.8216e-05
go_gc_duration_seconds{quantile="0.75"} 6.1345e-05
go_gc_duration_seconds{quantile="1"} 0.930618196
go_gc_duration_seconds_sum 1.058141375
go_gc_duration_seconds_count 2161
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 19
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.12.7"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.785232e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.031622656e+09
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.466558e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1.524692e+06
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 6.11705002344067e-06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 2.38592e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 3.785232e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.0301312e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 6.119424e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 20850
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 5.890048e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.6420736e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6137468738307302e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 1.545542e+06
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 3472
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 73728
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 98304
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 5.03464e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 686138
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 688128
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 688128
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 7.1762168e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 11
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 12.73
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.636352e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.61347180583e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.33189632e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1873
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

So apparently no clickhouse metrics are exported, only standard prometheus ones.

**Comment by MisterTimn** [comment]
Your question made me look at the metrics-exporter version. I update the clickhouse operator image to stay with the latest stable release but i have never updated the metrics-exporter image version. Just bumped it to 0.9.9 and now I get the clickhouse metrics.

So I guess I can close this issue now? Might be good to add an entry to https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_upgrade.md about the metrics exporter?

**Comment by bilalbayasut** [comment]
I have the same problem , and yet my metrics-exporter version is `0.13.5`. any idea ?

**Comment by Slach** [comment]
@bilalbayasut 
which namespace did you use to install clickhouse-operator deployment?

could you run 
`kubectl -n <your_clickhouse_operator> -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/chi` ?
it return something or just return empty `chi` list?

**Comment by bilalbayasut** [comment]
@Slach ```
[{"namespace":"default","name":"myapp","hostnames":["chi-myapp-clickhouse-0-0.default.svc.cluster.local","chi-myapp-clickhouse-0-1.default.svc.cluster.local"]}]
```

**Comment by Slach** [comment]
@bilalbayasut ok. look like metrics-exporter monitor 2 nodes from 1 cluster

you can ensure to metrcis collected 

`kubectl -n <your_clickhouse_operator> <your_clickhouse_operator_pod> -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/metrics`

after it
how you deploy prometheus inside your kubernetes cluster?
if you use prometheus-operator
you also shall define custom resource `ServiceMonitor` which will scrape all endpoins of selected services
or create custom scraping config

look to https://github.com/Altinity/clickhouse-operator/tree/master/deploy/prometheus for details

**Comment by bilalbayasut** [comment]
@Slach regarding metrics ,I only get this :
> This is what I get as response:
> 
> ```
> 
> # HELP go_gc_duration_seconds A summary of the GC invocation durations.
> 
> # TYPE go_gc_duration_seconds summary
> 
> go_gc_duration_seconds{quantile="0"} 8.933e-06
> 
> go_gc_duration_seconds{quantile="0.25"} 1.6137e-05
> 
> go_gc_duration_seconds{quantile="0.5"} 2.8216e-05
> 
> go_gc_duration_seconds{quantile="0.75"} 6.1345e-05
> 
> go_gc_duration_seconds{quantile="1"} 0.930618196
> 
> go_gc_duration_seconds_sum 1.058141375
> 
> go_gc_duration_seconds_count 2161
> 
> # HELP go_goroutines Number of goroutines that currently exist.
> 
> # TYPE go_goroutines gauge
> 
> go_goroutines 19
> 
> # HELP go_info Information about the Go environment.
> 
> # TYPE go_info gauge
> 
> go_info{version="go1.12.7"} 1
> 
> # HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
> 
> # TYPE go_memstats_alloc_bytes gauge
> 
> go_memstats_alloc_bytes 3.785232e+06
> 
> # HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
> 
> # TYPE go_memstats_alloc_bytes_total counter
> 
> go_memstats_alloc_bytes_total 1.031622656e+09
> 
> # HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
> 
> # TYPE go_memstats_buck_hash_sys_bytes gauge
> 
> go_memstats_buck_hash_sys_bytes 1.466558e+06
> 
> # HELP go_memstats_frees_total Total number of frees.
> 
> # TYPE go_memstats_frees_total counter
> 
> go_memstats_frees_total 1.524692e+06
> 
> # HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
> 
> # TYPE go_memstats_gc_cpu_fraction gauge
> 
> go_memstats_gc_cpu_fraction 6.11705002344067e-06
> 
> # HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
> 
> # TYPE go_memstats_gc_sys_bytes gauge
> 
> go_memstats_gc_sys_bytes 2.38592e+06
> 
> # HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
> 
> # TYPE go_memstats_heap_alloc_bytes gauge
> 
> go_memstats_heap_alloc_bytes 3.785232e+06
> 
> # HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
> 
> # TYPE go_memstats_heap_idle_bytes gauge
> 
> go_memstats_heap_idle_bytes 6.0301312e+07
> 
> # HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
> 
> # TYPE go_memstats_heap_inuse_bytes gauge
> 
> go_memstats_heap_inuse_bytes 6.119424e+06
> 
> # HELP go_memstats_heap_objects Number of allocated objects.
> 
> # TYPE go_memstats_heap_objects gauge
> 
> go_memstats_heap_objects 20850
> 
> # HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
> 
> # TYPE go_memstats_heap_released_bytes gauge
> 
> go_memstats_heap_released_bytes 5.890048e+07
> 
> # HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
> 
> # TYPE go_memstats_heap_sys_bytes gauge
> 
> go_memstats_heap_sys_bytes 6.6420736e+07
> 
> # HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
> 
> # TYPE go_memstats_last_gc_time_seconds gauge
> 
> go_memstats_last_gc_time_seconds 1.6137468738307302e+09
> 
> # HELP go_memstats_lookups_total Total number of pointer lookups.
> 
> # TYPE go_memstats_lookups_total counter
> 
> go_memstats_lookups_total 0
> 
> # HELP go_memstats_mallocs_total Total number of mallocs.
> 
> # TYPE go_memstats_mallocs_total counter
> 
> go_memstats_mallocs_total 1.545542e+06
> 
> # HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
> 
> # TYPE go_memstats_mcache_inuse_bytes gauge
> 
> go_memstats_mcache_inuse_bytes 3472
> 
> # HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
> 
> # TYPE go_memstats_mcache_sys_bytes gauge
> 
> go_memstats_mcache_sys_bytes 16384
> 
> # HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
> 
> # TYPE go_memstats_mspan_inuse_bytes gauge
> 
> go_memstats_mspan_inuse_bytes 73728
> 
> # HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
> 
> # TYPE go_memstats_mspan_sys_bytes gauge
> 
> go_memstats_mspan_sys_bytes 98304
> 
> # HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
> 
> # TYPE go_memstats_next_gc_bytes gauge
> 
> go_memstats_next_gc_bytes 5.03464e+06
> 
> # HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
> 
> # TYPE go_memstats_other_sys_bytes gauge
> 
> go_memstats_other_sys_bytes 686138
> 
> # HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
> 
> # TYPE go_memstats_stack_inuse_bytes gauge
> 
> go_memstats_stack_inuse_bytes 688128
> 
> # HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
> 
> # TYPE go_memstats_stack_sys_bytes gauge
> 
> go_memstats_stack_sys_bytes 688128
> 
> # HELP go_memstats_sys_bytes Number of bytes obtained from system.
> 
> # TYPE go_memstats_sys_bytes gauge
> 
> go_memstats_sys_bytes 7.1762168e+07
> 
> # HELP go_threads Number of OS threads created.
> 
> # TYPE go_threads gauge
> 
> go_threads 11
> 
> # HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
> 
> # TYPE process_cpu_seconds_total counter
> 
> process_cpu_seconds_total 12.73
> 
> # HELP process_max_fds Maximum number of open file descriptors.
> 
> # TYPE process_max_fds gauge
> 
> process_max_fds 1.048576e+06
> 
> # HELP process_open_fds Number of open file descriptors.
> 
> # TYPE process_open_fds gauge
> 
> process_open_fds 9
> 
> # HELP process_resident_memory_bytes Resident memory size in bytes.
> 
> # TYPE process_resident_memory_bytes gauge
> 
> process_resident_memory_bytes 1.636352e+07
> 
> # HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
> 
> # TYPE process_start_time_seconds gauge
> 
> process_start_time_seconds 1.61347180583e+09
> 
> # HELP process_virtual_memory_bytes Virtual memory size in bytes.
> 
> # TYPE process_virtual_memory_bytes gauge
> 
> process_virtual_memory_bytes 1.33189632e+08
> 
> # HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
> 
> # TYPE process_virtual_memory_max_bytes gauge
> 
> process_virtual_memory_max_bytes -1
> 
> # HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
> 
> # TYPE promhttp_metric_handler_requests_in_flight gauge
> 
> promhttp_metric_handler_requests_in_flight 1
> 
> # HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
> 
> # TYPE promhttp_metric_handler_requests_total counter
> 
> promhttp_metric_handler_requests_total{code="200"} 1873
> 
> promhttp_metric_handler_requests_total{code="500"} 0
> 
> promhttp_metric_handler_requests_total{code="503"} 0
> 
> ```
> 
> 
> 
> So apparently no clickhouse metrics are exported, only standard prometheus/go ones.

And for prometheus I installed it via helm prior to clickhouse, so I dont use prometheus installer provided here

**Comment by Slach** [comment]
ok. let's ensure metrics-exporter can scrape metrics from CHI
```
kubectl exec -n <clickhouse_operator_namespace> <clickhouse_operator_pod> -c metrics-exporter -- grep chUser|chPass -r /etc/clickhouse-operator/

kubectl exec -n <clickhouse_operator_namespace> <clickhouse_operator_pod> -c metrics-exporter -- wget -qO- "http://<chUser_from_previous_command>:<chPassword_from_previous_command>@chi-myapp-clickhouse-0-0.default.svc.cluster.local?query=SELECT Version()"
```

**Comment by bilalbayasut** [comment]
first one is
```
/etc/clickhouse-operator/..2021_04_20_05_55_13.200319453/config.yaml:chUsersConfigsPath: users.d
/etc/clickhouse-operator/..2021_04_20_05_55_13.200319453/config.yaml:# located in `chUsersConfigsPath` folder
/etc/clickhouse-operator/..2021_04_20_05_55_13.200319453/config.yaml:chUsername: myusername
/etc/clickhouse-operator/..2021_04_20_05_55_13.200319453/config.yaml:chPassword: mypassword
/etc/clickhouse-operator/config.yaml:chUsersConfigsPath: users.d
/etc/clickhouse-operator/config.yaml:# located in `chUsersConfigsPath` folder
/etc/clickhouse-operator/config.yaml:chUsername: myusername
/etc/clickhouse-operator/config.yaml:chPassword: mypassword
```

second one is a timeout @Slach

**Comment by Slach** [comment]
sorry, i miss 8123 port

`kubectl exec -n <clickhouse_operator_namespace> <clickhouse_operator_pod> -c metrics-exporter -- wget -qO- "http://myusername:mypassword@chi-myapp-clickhouse-0-0.default.svc.cluster.local:8123?query=SELECT Version()"`

**Comment by bilalbayasut** [comment]
I got `ssl_client: chi-myapp-clickhouse-0-0.default.svc.cluster.local: handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

**Comment by Slach** [comment]
hmm, looks weird, 8123 port should be HTTP only interface

could you share
`kubectl get chi -n default myapp -o yaml`

and
`kubectl exec chi-myapp-clickhouse-0-0 -n default -- grep 8123 -r /etc/clickhouse-server/`

**Comment by bilalbayasut** [comment]
@Slach I tried to see log of `metric-exporter` and got this though
```
announcer.go:262] connection.go:91:Query():FAILED Query(http://***:***@chi-myapp-clickhouse-0-1.default.svc.cluster.local:8123/) clickhouse: Code: 516, e.displayText() = DB::Exception: myusername: Authentication failed: password is incorrect or there is no user with such name (version 21.4.4.30 (official build))
```

**Comment by Slach** [comment]
hmm, could you check

`kubectl exec chi-myapp-clickhouse-0-0 -n default -- cat /etc/clickhouse-server/config.d/chop-generated-users.xml`?

**Comment by bilalbayasut** [comment]
that file is not exist. but there is in configmap
```
<yandex>
    <users>
        <default>
            <networks>
                <host_regexp>(chi-myapp-[^.]+\d+-\d+|clickhouse\-myapp)\.default\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <myuser>
            <networks>
                <host_regexp>(chi-myapp-[^.]+\d+-\d+|clickhouse\-myapp)\.default\.svc\.cluster\.local$</host_regexp>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>XXXXX</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
            <quotas>default</quotas>
        </myuser>
    </users>
</yandex>
```

**Comment by Slach** [comment]
sorry, miss users.d instead config.d
`kubectl exec chi-myapp-clickhouse-0-0 -n default -- cat /etc/clickhouse-server/users.d/chop-generated-users.xml`

so, look like you install clickhouse operator with one chUsername + chPassword
but you remove it from users, or replace it manually in configmap?

**Comment by bilalbayasut** [comment]
> @Slach that file is not exist. but there is in configmap
> 
> ```
> <yandex>
>     <users>
>         <default>
>             <networks>
>                 <host_regexp>(chi-myapp-[^.]+\d+-\d+|clickhouse\-myapp)\.default\.svc\.cluster\.local$</host_regexp>
>                 <ip>::1</ip>
>                 <ip>127.0.0.1</ip>
>             </networks>
>             <profile>default</profile>
>             <quota>default</quota>
>         </default>
>         <myuser>
>             <networks>
>                 <host_regexp>(chi-myapp-[^.]+\d+-\d+|clickhouse\-myapp)\.default\.svc\.cluster\.local$</host_regexp>
>                 <ip>127.0.0.1</ip>
>                 <ip>::/0</ip>
>             </networks>
>             <password_sha256_hex>XXXXX</password_sha256_hex>
>             <profile>default</profile>
>             <quota>default</quota>
>             <quotas>default</quotas>
>         </myuser>
>     </users>
> </yandex>
> ```

the result is exactly the same @Slach . I install clickhouse with modifying default user (which is default operator) and add one user via template which later also can be edited in configmap as in the docs

**Comment by Slach** [comment]
ok. 
echo "mypassword" | sha256sum
show exactly same whihc contains in 
`<password_sha256_hex>XXXXX</password_sha256_hex>` ?

**Comment by bilalbayasut** [comment]
yes it works, turns out the default profile is not matched with the one I modified . thanks @Slach for your help, really appreciate it :)
