### ISSUE TITLE
Liveness probe failed: HTTP probe failed with statuscode: 502

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-operator#654]
I'm seeing quite frequently the http liveness probe fail with a 502 error.
It's often a single check that fails as the pods never get actually restarted.
But it does happen quite frequently. For example 700+ times in 4 days on one of my nodes.
The nodes are barely used at the moment so it's not a resource issue as far as I can see.

**Comment by alex-zaitsev** [comment]
@electrical , what operator version are you using? The liveness check has been adjusted between 0.13 and 0.13.5 to be less aggressive. However, we have not seen any significant issues with those.

**Comment by electrical** [comment]
I'm currently using image `altinity/clickhouse-operator:0.13.5`

**Comment by electrical** [comment]
Looking at the liveness probe settings `timeoutSeconds: 1` is the default value. I guess it's a bit too short :-)
Perhaps changing it to 2 seconds or even 5 should be fine.

**Comment by alex-zaitsev** [comment]
Well, it should be instant if ClickHouse HTTP server is up.

**Comment by electrical** [comment]
From what I can see the CH instances are up constantly. I don't see any errors in the logs or anything that would indicate a problem. CH version 20.8.12.2

**Comment by alex-zaitsev** [comment]
The current LivenessProbe has the following settings:
```
		PeriodSeconds:       3,
		FailureThreshold:    10,
```
So it would try 30 seconds before giving up. 

@electrical , do you still have this issue?

**Comment by electrical** [comment]
@alex-zaitsev I'm still hitting the issue yeah. Although after further investigation I don't think it's an issue with the liveness probe itself but with Clickhouse since it returns an actual 502 error.
I recently upgraded to 21.3.6.55 and still seeing the issue.
Can you think of anything I could debug on the CH side to find out why it does this?
The CH instances have enough CPU and memory assigned to them so that shouldn't be a cause for it.

**Comment by filimonov** [comment]
> 502 error

I'm wondering where does it come from. That does not sounds like clickhouse response. But lot of loadbalancers (and similar stuff) loves to use 502 code. But health check should go to a pod directly... So that's strange.

**Comment by electrical** [comment]
I've opened an issue in the Clickhouse repo it self, see if more comes out of that.

**Comment by electrical** [comment]
Tried to debug what I can and weirdly enough the problem disappeared despite it being around for quite a long time.
I'm going to close the issue and will debug further if it happens again.
Thank you so much for the assistance.
