### ISSUE TITLE
metrics-exporter not running

### ISSUE THREAD

**Issue by kushagra391** [Altinity/clickhouse-operator#655]
It seems `metrics-exporter` has stopped running on our EKS cluster. 
Am running it on an EKS cluster with a mix of spot and on-demand nodes. 

```
kubectl -n kube-system get deployment
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
clickhouse-operator   1/1     1            1           183d
coredns               2/2     2            2           183d

kubectl -n kube-system get svc
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
clickhouse-operator-metrics   ClusterIP   10.100.204.80   <none>        8888/TCP                       183d

kubectl -n kube-system get pods
clickhouse-operator-646b4b44fc-n684z   2/2     Running   0          29h

---

> `metrics-server` is missing ^^
```

- Is there a way to restart `metrics-exporter` ? 

- And if possible, can we assign nodeSelector labels (to a running cluster) for the pods to attach to on-demand nodes ? 
Not sure if its related to metrics-exporter going down. 

Thanks a lot ! 

(operator version: `v0.12`)

**Comment by Slach** [comment]
> kubectl -n kube-system get pods
> clickhouse-operator-646b4b44fc-n684z   2/2     Running   0          29h
2/2 means 2 from 2 containers  is ready and whole pod in running state

metrics-exporter it's  a second container in clickhouse-operator pod

just check
```kubectl exec -n kube-system clickhouse-operator-646b4b44fc-n684z  -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/metrics```

**Comment by kushagra391** [comment]
@Slach 

`kubectl exec -n kube-system clickhouse-operator-646b4b44fc-n684z -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/metrics` works and i can see metrics dumped on the console.

but `http://localhost:9090/targets` shows the chop in a bad state. 

<img width="1558" alt="Screen Shot 2021-02-20 at 7 46 20 PM" src="https://user-images.githubusercontent.com/8533562/108614992-7fc73000-73b4-11eb-940c-ff8ecbd5c795.png">

--- 
we have two clickhous-operator / EKS installation, **staging** and **prod**

✅  for staging, i see `http://localhost:9090/targets` in a good state, where am seeing an extra row for `metrics-server` pod, svc, and deployments.  For eg:
```
kubectl -n kube-system get pods
clickhouse-operator-564f55cbdc-xkbf2   2/2     Running   0          25h
metrics-server-5f956b6d5f-bk6ll        1/1     Running   0          96d          << extra row

kubectl -n kube-system get deployment
clickhouse-operator   1/1     1            1           113d
metrics-server        1/1     1            1           101d.               << extra row
```

**Comment by kushagra391** [comment]
sorry i misread the issue, `context deadline exceeded` could be happening due to one of https://stackoverflow.com/questions/49817558/context-deadline-exceeded-prometheus these reasons 

I'll check although i still don't understand why those extra `metrics-server` pods / deployment are not present in one of my clusters.

**Comment by kushagra391** [comment]
i needed to update `scrape_timeout` and set `insecure_skip_verify: true`
```yaml
# prometheus-alert-rules.yaml
      scrape_interval: 2m
      scrape_timeout: 1m
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
```

its working now, although i still don't understand why those extra `metrics-server` pods / deployment are present in one of my clusters, and absent on the other one

**Comment by Slach** [comment]
look like you have big database
5 seconds for scraping is much more than I see usual, how much in `SELECT hostName() h, count() FROM cluster('all-sharded', system.parts) GROUP BY h`  in your clickhouse clutser?

**Comment by kushagra391** [comment]
right now, its taking `9-12s` for each scrape

it's a 3 * 2 setup, for **prod**. ( < 1 TB per node)
but we also have a **staging** cluster, thats running fine (scrape time <1s), with similar data. 
```
-- redacting host names
SELECT
    'X' AS h,
    cnt
FROM
(
    SELECT
        hostName() AS h,
        count() AS cnt
    FROM cluster('all-sharded', system.parts)
    GROUP BY h
)

┌─h─┬──cnt─┐
│ X │ 6352 │
│ X │ 6503 │
│ X │ 6426 │
│ X │ 6266 │
│ X │ 6214 │
│ X │ 6299 │
└───┴──────┘
```

I need to take a deeper look into it. 

Even though `http://localhost:9090/targets` now looks good, certain parts of the dashboards like Insert Queries, Select Queries, Inserted Bytes aren't showing up on the prometheus dash (mostly `chi_clickhouse_event_*` events)
I confirmed the metric exporter output does show rows for them.

**Comment by Slach** [comment]
@kushagra391  how you install prometheus in your environment? do you use `prometheus-operator`?
could you share your scraping configs?

**Comment by kushagra391** [comment]
@Slach : yea, am using `prometheus-operator`, following these steps from the [dzone blog](https://dzone.com/articles/monitoring-clickhouse-on-kubernetes-with-prometheu)

only changes i need to make for my prod cluster is in [prometheus-template.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-template.yaml#L13-L16), adding `scrape_timeout: 20s`
```shell
       kubernetes_sd_configs:
       - role: pod
       scrape_interval: 30s
+      scrape_timeout: 20s
```
<img width="404" alt="Screen Shot 2021-02-25 at 12 21 00 AM" src="https://user-images.githubusercontent.com/8533562/109124273-94326200-76ff-11eb-9d24-a08d56e2d4d5.png">

confirmed with 
```
time kubectl -n kube-system exec clickhouse-operator-646b4b44fc-hrcgn -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/metrics
real	0m10.574s
user	0m0.703s
sys	0m0.203s
```


---

> Even though http://localhost:9090/targets now looks good, certain parts of the dashboards like Insert Queries, Select Queries, Inserted Bytes aren't showing up on the Clickhouse Operator dash

this issue is now resolved, I can see the full dashbaord again.

**Comment by Slach** [comment]
please subscribe to https://github.com/ClickHouse/ClickHouse/pull/21035
I hope it can help us decrease scraping time, cause largest part of this it's a get custom metrics related to system.parts

**Comment by kushagra391** [comment]
sure, thanks !
