### ISSUE TITLE
Pods are restarted when new shards/replicas are added

### ISSUE THREAD

**Issue by xiedeyantu** [Altinity/clickhouse-operator#666]
release 0.12.0 first improvement:
Pods are no longer restarted when new shards/replicas are added.
But it will be restarted until 0.13.5.
Because of some cluster scope label changes, pods are restarted. 

clickhouse.altinity.com/chiScopeCycleOffset: "3"
clickhouse.altinity.com/chiScopeIndex: "3"
clickhouse.altinity.com/clusterScopeCycleOffset: "3"
clickhouse.altinity.com/clusterScopeIndex: "3"

Is there any way to fix this problem？

**Comment by alex-zaitsev** [comment]
Hi @xiedeyantu, could you describe what you are doing in more detail? CHI would be helpful. It looks like you are using CircularReplication, but we do not understand how it can change the cycle index and offset for existing pods.

If there is still a problem, the proper fix would be to remove those labels completely, they are just for the reference.

**Comment by xiedeyantu** [comment]
> Hi @xiedeyantu, could you describe what you are doing in more detail? CHI would be helpful. It looks like you are using CircularReplication, but we do not understand how it can change the cycle index and offset for existing pods.
> 
> If there is still a problem, the proper fix would be to remove those labels completely, they are just for the reference.

I have come up with a solution to this problem. The method is to update the labels of STS first, and then update STS. I have submitted a pr [#667](https://github.com/Altinity/clickhouse-operator/pull/667), you can see if it is feasible

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/0.14.0
