### ISSUE TITLE
Secure remote_servers section

### ISSUE THREAD

**Issue by UnamedRus** [Altinity/clickhouse-operator#668]
In order to use secure tcp port(9440 by default) while running distributed queries, it's need to add `secure` setting in `remote_servers` settings.
It would be great if clickhouse-operator could do that automatically (or at least we would be able to enable it via yaml) in case of using secure ports.

```
        <shard>
            <weight>1</weight>
            <internal_replication>true</internal_replication>
            <replica>
                <host>example01-02-1</host>
                <secure>1</secure>
                <port>9440</port>
            </replica>
            <replica>
                <host>example01-02-2</host>
                <secure>1</secure>
                <port>9440</port>
            </replica>
       <shard>
```

Also it would be great to have support for inter-server cluster secret.
https://github.com/ClickHouse/ClickHouse/pull/13156

**Comment by chancez** [comment]
I also hit this. Needs to be possible to set this to secure in the hostTemplates, or somewhere similar.

**Comment by alex-zaitsev** [comment]
Supported since https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.20.0
