### ISSUE TITLE
ClickHouse-Operator reinstall the ClickHouse Cluster will be droped.

### ISSUE THREAD

**Issue by TCeason** [Altinity/clickhouse-operator#677]
Version: 0.13.5

```bash
$ kubectl apply -f operator.yaml; # Install chop to kube-system

$ kubectl create ns test
$ install a Cluster `cktest` in ns test ; get a chi `cktest` named test.

$ kubectl delete -f operator.yaml; # drop this operator

```

Now the ClickHouse Cluster already exists.

But when I run next shell, the Cluster will be droped.

```bash
kubectl apply -f operator.yaml; # Reinstall chop to kube-system
```

**Comment by Slach** [comment]
when you said `kubectl delete -f operator.yaml`
do you mean you run `kubectl delete -f https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml` which contains CRD + service + deployment definition? 

so, when you delete whole CRD , all custom resources which related to this CRD also destroys

look like you should remove only deployment and service definition for properly uninstall clickhouse-operator without remove CRD
something like
```
kubectl delete -n <operator_namespace> -f https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-deployment.yaml

kubectl delete -n <operator_namespace> -f https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-service.yaml
```

**Comment by TCeason** [comment]
> when you said kubectl delete -f operator.yaml
do you mean you run kubectl delete -f https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml which contains CRD + service + deployment definition?
> 
> so, when you delete whole CRD , all custom resources which related to this CRD also destroys

Hmm, Now I know it's a normal phenomenon. Thanks for your reply.

**Comment by Slach** [comment]
usually, we just use the following command to re-install \ upgrade clickhouse-operator

```
kubectl apply -n <operator_namespace> -f https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml 
```
