### ISSUE TITLE
Undo last deployment of clickhouse cluster

### ISSUE THREAD

**Issue by apalmercari** [Altinity/clickhouse-operator#681]
Sometimes if we give resource requirement which can't be completed by K8S then pods are in pending state. 
Only solution is to vertically scale the nodes and complete the deployment .There's no option to undo the last deployment

**Comment by Slach** [comment]
try to 0.14.0 clickhouse-operator release, 
for example
`
git clone git@github.com:Altinity/clickhouse-operator.git
cd clickhouse-operator
git checkout 0.14.0
git pull origin 0.14.0
OPERATOR_NAMESPACE=<your_installed_operator_namespace> bash -x ./deploy/operator/clickhouse-operator-install.sh
```
this release support preemptive task queue
so you can make changes in your kind: ClickhouseIntallation manifest with scaledown
and run kubectl apply -f <your_manifest>
and no wait pending state

**Comment by apalmercari** [comment]
@Slach  Thank you will try this

**Comment by apalmercari** [comment]
Yes, it takes almost 5-7 mins and then applies the new config

**Comment by apalmercari** [comment]
@Slach just for information,
Is there any option to check the progress of the cluster deployments? It's difficult to check from logs.

**Comment by Slach** [comment]
@apalmercari just use
`kubectl describe chi -n <your_chi_namespace> <your_chi_name>`
and see events
