### ISSUE TITLE
Can't update Operator 0.13.5 to 0.14.0

### ISSUE THREAD

**Issue by ossinkine** [Altinity/clickhouse-operator#684]
We have the running operator created by applying https://github.com/Altinity/clickhouse-operator/blob/0.13.5/deploy/operator/clickhouse-operator-install-template.yaml.
After apply https://github.com/Altinity/clickhouse-operator/blob/0.14.0/deploy/operator/clickhouse-operator-install-template.yaml we get an error `The ClusterRoleBinding "clickhouse-operator-clickhouse-operator" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"clickhouse-operator-clickhouse-operator"}: cannot change roleRef`

**Comment by alex-zaitsev** [comment]
Right, ClusterRoleBinding has been updated to remove unnecessary rights.

You can also upgrade via deployment change:
https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_upgrade.md
