### ISSUE TITLE
How to install a ClickHouse Cluster on other ns?

### ISSUE THREAD

**Issue by TCeason** [Altinity/clickhouse-operator#686]
## Summary

| ClickHouse-Operator Version |
|:--:|
| 0.14.0 |

If I install a CHOP on ns `foo`, and I want to install the ClickHouse cluster in other ns `boo`, how to do it?

## Scene

I install `chop`  on ns `chop-altinity` and then I try to install a [simple.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/01-simple-layout-01-1shard-1repl.yaml) in ns `default`.

```
$ kubectl get all  -n chop-altinity 
NAME                                      READY   STATUS    RESTARTS   AGE
pod/clickhouse-operator-5c4cf66cc-wvsbz   2/2     Running   0          50m

NAME                                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/clickhouse-operator-metrics   ClusterIP   10.96.36.23   <none>        8888/TCP   50m

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/clickhouse-operator   1/1     1            1           50m

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/clickhouse-operator-5c4cf66cc   1         1         1       50m

$ kubectl exec -it clickhouse-operator-5c4cf66cc-wvsbz    -n chop-altinity -c clickhouse-operator -- /clickhouse-operator --version 
0.14.0
```

```
$ kubectl get chi              
NAME        CLUSTERS   HOSTS   STATUS
simple-01
```

@Slach

**Comment by Slach** [comment]
you shall change kubernetes configmap `etc-clickhouse-operator-files` in namespace `test-chop`
and add to data->`config.yaml` key    

```
watchNamespaces:
  - test-cluster
  - test-chop
```

**Comment by TCeason** [comment]
In my `configmap` `etc-clickhouse-operator-files`, the [len(config.WatchNamespaces) == 0](https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L595). So [IsWatchedNamespace](https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L593) will return true and the chop will watch all namespaces.



```
$ kubectl get configmap etc-clickhouse-operator-files -n chop-altinity -o yaml >  config.yaml          
$ grep -nr " watchNamespaces" ./config.yaml 
12:    #watchNamespaces:

```

**Comment by TCeason** [comment]
And I try to modify the configmap, but it still has this question:

```
$ kubectl get   configmap etc-clickhouse-operator-files -n chop-altinity -o yaml |grep -A 2 " watchName"
    watchNamespaces:
      - chop-altinity
      - test-cluster
$ kubectl get chi -n test-cluster 
NAME        CLUSTERS   HOSTS   STATUS
simple-01                      
$ kubectl get all  -n test-cluster 
No resources found in test-cluster namespace.

```

**Comment by Slach** [comment]
@TCeason configMaps updates inside pods during 60s timeout
also, you need restart clickhouse-operator to apply new config
so
`kubectl exec -n chop-altinity pod/clickhouse-operator-5c4cf66cc-wvsbz -c clickhouse-operator -- kill 1`
should help

after rest could you share following logs
`kubectl logs -n chop-altinity pod/clickhouse-operator-5c4cf66cc-wvsbz --since 1h`?

**Comment by TCeason** [comment]
> In my `configmap` `etc-clickhouse-operator-files`, the [len(config.WatchNamespaces) == 0](https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L595). So [IsWatchedNamespace](https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L593) will return true and the chop will watch all namespaces.
> 
> ```
> $ kubectl get configmap etc-clickhouse-operator-files -n chop-altinity -o yaml >  config.yaml          
> $ grep -nr " watchNamespaces" ./config.yaml 
> 12:    #watchNamespaces:
> ```

But why this is not work？Default chop will watch all namespaces.

**Comment by TCeason** [comment]
https://gist.github.com/TCeason/acdb371403c3d7844dfd531d3b9611da

**Comment by Slach** [comment]
> In my configmap etc-clickhouse-operator-files, the len(config.WatchNamespaces) == 0. So IsWatchedNamespace will return true and the chop will watch all namespaces.
NO, operator will watch all namespaces only if they will installed into `kube-system` namespace, otherwise it will watch only same namespace where clickhouse-operator installed, chop-alinity in your case

so, you should uncomment #watchNamespaces:
and setup in config.yaml as I said https://github.com/Altinity/clickhouse-operator/issues/686#issuecomment-827338033
```
 watchNamespaces:
      - chop-altinity
      - test-cluster
```
and restart clickhouse-operator to apply these changes 
as I said https://github.com/Altinity/clickhouse-operator/issues/686#issuecomment-827395866

**Comment by TCeason** [comment]
In my mind: 

A K8S Cluster should only have one ClickHouse-operator to control the whole ClickHouse clusters. 

So that the Chop should watch all ns. In [default](https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L593) it is.

So I can deploy a Helm chart that don't care about this.

But if I must manual configuration parameters `watchNamespaces`, then the how to write the chart? @Slach

**Comment by TCeason** [comment]
In my mind I want to do this:

set `watchNamespaces:[]` in cm `etc-clickhouse-operator-files` then run next shell:

```
$ kubectl create ns chop;
$ helm install chop ./clickhouse-operator.tgz -n chop;
$ kubectl create ns cluster;
$ helm install cluster-demo ./clickhouse-cluster.tgz -n cluster;

```

And then the cluster should be created on ns `cluster`.


In your comment, you mean I should set `watchNamespaces:["cluster"]` in cm `etc-clickhouse-operator-files` then run these shell commands.

But if I want to deploy a ClickHouse Cluster on other cluster,  Whether the  clickhouse-operator  should be actively aware?

**Comment by Slach** [comment]
@TCeason if you want clickhouse-operator watch all clusters in all namespaces , just once install clickhouse-operator to `kube-system` namespace, it's all

**Comment by TCeason** [comment]
> @TCeason if you want clickhouse-operator watch all clusters in all namespaces , just once install clickhouse-operator to `kube-system` namespace, it's all

Yes,you are right. But I see other operators like grafana they can install on ns `grafana` and then they can watch all product on the k8s cluster.

Just trying to explore a best practice.

**Comment by Slach** [comment]
there is no standardized behavior here
maybe we can apply `watchNamespaces: - *` as solution for your corner case

@sunsingerus @alex-zaitsev could you share your opinion?
