### ISSUE TITLE
Does expand the capacity of the cloud disk need to restart the pod?

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#689]

**Comment by Slach** [comment]
it depends on CSI storage provider and storage class, AWS EBS CSI can resize volumes without pod restart
https://www.jeffgeerling.com/blog/2019/expanding-k8s-pvs-eks-on-aws

**Comment by Sallery-X** [comment]
I known that, and I want to know If I expand cloud disk by the modifying CR, does the operator recreate statefulset?

**Comment by Sallery-X** [comment]
> it depends on CSI storage provider and storage class, AWS EBS CSI can resize volumes without pod restart
> https://www.jeffgeerling.com/blog/2019/expanding-k8s-pvs-eks-on-aws

I known that, and I want to know If I expand cloud disk by the modifying CR, does the operator recreate statefulset?

**Comment by alex-zaitsev** [comment]
Yes, operator re-creates the statefulset with modified volume claim template.

**Comment by Sallery-X** [comment]
> template

So whether to optimize this feature?
