### ISSUE TITLE
Resource detection incorrect

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-operator#690]
Not as much as a bug since I understand how it happens but wondering how to solve this.
As in the logs below it detects the resources available of the host system and not what the docker container is limited to.
The docker resource limits are set so I wonder how I can set the correct max_server_memory_usage for the instances.

```
2021.05.03 13:26:04.150734 [ 48 ] {} <Information> Application: Available RAM: 251.84 GiB; physical cores: 24; logical cores: 48.
2021.05.03 13:26:14.167103 [ 98 ] {} <Information> Application: Setting max_server_memory_usage was set to 226.65 GiB (251.84 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
```

**Comment by alex-zaitsev** [comment]
You can specify 'max_server_memory_usage' in server settings. 
```
  configuration:
    settings:
      max_server_memory_usage: <type_disired_value_here>
  ```

**Comment by electrical** [comment]
Thank you. This solved my issue. Sorry for the delay in confirming.
