### ISSUE TITLE
runAsNonRoot

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-operator#691]
In general it's best practice to run processes as a non root user.
Because of that I've enabled checking for the securityContext settings to enforce it

I see in the clickhouse docker container it already does run as the user `clickhouse` but it's not enforced in the stateful set that gets created.
Would it have any adverse effects to add this to improve security?

**Comment by alex-zaitsev** [comment]
We do not have it by default, but you can enable it in your ClickHouseInstallation:
```  templates:
    podTemplates:
      - name: pod-template-with-volumes-do-not-chown
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.8
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: data-storage-vc-template-1
                  mountPath: /var/lib/clickhouse
              command:
                - clickhouse-server
                - --config-file=/etc/clickhouse-server/config.xml
              env:
                - name: CLICKHOUSE_DO_NOT_CHOWN
                  value: "1"
```

**Comment by electrical** [comment]
Finally got around testing it and works great. Thank you! since it's security best practice perhaps you might want to consider to enable this by default :-)
