### ISSUE TITLE
Backup interval Question

### ISSUE THREAD

**Issue by juanvasquezreyes** [Altinity/clickhouse-operator#694]
I'm trying to use clickhouse-backup I'm using this as example https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-07-do-not-chown.yaml

I was just wondering how often the backup script is running? or is something that we have to control at the command?

**Comment by Slach** [comment]
this example just run clickhouse-backup server which provide REST API for create \ upload \ delete \ restore backups
you should manually create `kind: CrontabJob`

which run something like 
```bash
now=$(date -u +"%Y-%m-%d_%H-%m-%S")
curl -XPOST -H "Content-type: application/json" -d "{\"command\":\"create backup-${now}\"}" "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions"`
while [[ "success" != $(curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" | grep "create backup-${now}" | jq -c .status ) ]]; do 
   sleep 5
   if [[ "0" != $(curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" | grep "create backup-${now}" | grep -c -i "error" ) ]]; then
      curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" 
      exit 1
   done   
done
```

**Comment by juanvasquezreyes** [comment]
> this example just run clickhouse-backup server which provide REST API for create \ upload \ delete \ restore backups
> you should manually create `kind: CrontabJob`
> 
> which run something like
> 
> ```shell
> now=$(date -u +"%Y-%m-%d_%H-%m-%S")
> curl -XPOST -H "Content-type: application/json" -d "{\"command\":\"create backup-${now}\"}" "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions"`
> while [[ "success" != $(curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" | grep "create backup-${now}" | jq -c .status ) ]]; do 
>    sleep 5
>    if [[ "0" != $(curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" | grep "create backup-${now}" | grep -c -i "error" ) ]]; then
>       curl  "http://clickhouse.<your_chi_namespace>.svc.cluster.local:7171/backup/actions" 
>       exit 1
>    done   
> done
> ```

thank you, this was really helpful

I guess another approach is instead of using clickhouse-backup server option could be something like this
clickhouse-backup -c config.yml create && clickhouse-backup -c config.yml upload && **sleep** 1h

but I thought there was an option to provide an interval, your solution is so much better though, thank you

**Comment by juanvasquezreyes** [comment]
forgot to ask if your solution can be used for incremental backups https://github.com/AlexAkulov/clickhouse-backup/issues/81#issuecomment-594715949

**Comment by Slach** [comment]
you need know name previous backup
so you can try get backup list, something like this 
```curl -sL http://...:7171/backup/list | grep remote | jq .name```

latest version of clickhouse-backup currently doesn't support diff backup
you should test restore for your real data

**Comment by Slach** [comment]
@sushraju it's a complicated task, try to ask @AlexAkulov

**Comment by AlexAkulov** [comment]
Hi @sushraju !
Why removed?  `--diff-from` flag is still exists and works fine. I use it for my backups.
