### ISSUE TITLE
Taking so much time when we Added new shard to running Clickhouse installation

### ISSUE THREAD

**Issue by rgangoni** [Altinity/clickhouse-operator#697]
my configuration is
shard count: 2
replica count: 2
working fine all shards are running 

Added one  more shard  to running installation
shard count: 3
replica count: 2

why already running pods or shards  are going into pending state? 
Taking too much time it is showing in progress.

Currently i have five Nodes in place.
I also have the required PV's in place.

**Requirement:** 
*  Can i increase shard count in running clickhouse installation.
*  Is there any podDistribution which can distribute shards to all different nodes

**Comment by Slach** [comment]
which version of clickhouse-operator do you use?

**Comment by rgangoni** [comment]
Clickhouse Operator verrsion: 1.13.5
Clickhouse Server version: 20.7

**Comment by rgangoni** [comment]
If we remove the shard  from shard count :3  to 2
Taking some hours of time  it is in  in progress

**Comment by Slach** [comment]
could you try to use latest clichouse-operator 0.14.0 ?
and could share
```kubectl logs -n <operator-namespace> <clickhouse-operator-pod> --since=24h``` ?

**Comment by alex-zaitsev** [comment]
Should be fine with 0.14.0 and above.
