### ISSUE TITLE
Pod Is in pending state

### ISSUE THREAD

**Issue by sagarshrestha24** [Altinity/clickhouse-operator#701]
when there is shard 2 with replica 2 all pod are in running state.
if i kept shard  3 with  replica  2 , one pod is in pending state with this error 
"0/9 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 8 node(s) had volume node affinity conflict."
![image](https://user-images.githubusercontent.com/76894861/118250636-65d64e80-b4c6-11eb-904f-464f0061d2e5.png)

when i describe this pod it will show this error

 
![image](https://user-images.githubusercontent.com/76894861/118250788-8bfbee80-b4c6-11eb-98fe-86a3a3b8f578.png)

**Comment by alex-zaitsev** [comment]
This is a kubernetes error about non-sufficient resources. Check your available nodes or autoscaling groups of the cluster

**Comment by sagarshrestha24** [comment]
> This is a kubernetes error about non-sufficient resources. Check your available nodes or autoscaling groups of the cluster
it is due to pv issue or not ?

**Comment by sagarshrestha24** [comment]
> This is a kubernetes error about non-sufficient resources. Check your available nodes or autoscaling groups of the cluster

i have available resources why showing this error

**Comment by Slach** [comment]
by default clickhouse-operator create one StatefulSet inside one k8s node
so if you try to run a cluster with 3 shards x 3 replicas in each shard, you need 9 Kubernetes nodes
could you share your kind: ClickHouseInstallation custom resource?
