### ISSUE TITLE
Clickhouse Service access with Node IP

### ISSUE THREAD

**Issue by sagarshrestha24** [Altinity/clickhouse-operator#709]
when we port-forward the service of clickhouse with username and password it connected sucessfully.

But when we access with nodeip:nodeport with same username and password it says DB authentication issue 

![image (5)](https://user-images.githubusercontent.com/76894861/119931611-64665500-bfa1-11eb-85a2-243ffa4846dd.png)

Clickhouse-operator version : 0.14.0
kubernetes version:v1.20.5

**Comment by Slach** [comment]
look like you fail with host_regexp, check `/etc/clickhouse-server/users.d/chop-generated-users.xml`

and try to define 
```
spec:
  users:
    your_user_name/networks/ip: 0.0.0.0/0
```

**Comment by sagarshrestha24** [comment]
This is my file etc/clickhouse-server/users.d/chop-generated-users.xml
here what should i change here


            <users>
                    <admin>
                        <networks>
                            <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-repl-test)\.test\.svc\.cluster\.local$</host_regexp>
                            <ip>::1</ip>
                            <ip>127.0.0.1</ip>
                        </networks>
                        <password_sha256_hex>3b640c200bc1886a50ba7ccf6e1b6d55f</password_sha256_hex>
                        <profile>default</profile>
                        <quota>default</quota>
                    </admin>

**Comment by Slach** [comment]
@sagarshrestha24 you should change your k8s manifest `kind: ClickhouseInstallation`
as i described here https://github.com/Altinity/clickhouse-operator/issues/709#issuecomment-850167913

**Comment by sagarshrestha24** [comment]
i got this issue
cannot load data for command line suggestions: Code: 60, e.displayText() = DB::Exception: Received from <ip> DB::Exception: Table system.errors doesn't exist..

**Comment by sagarshrestha24** [comment]
thanks it working fine
