### ISSUE TITLE
How to take all backup Fastly

### ISSUE THREAD

**Issue by sagarshrestha24** [Altinity/clickhouse-operator#721]
Since We are using multiple shards in our CH cluster ,We want to take a backup by date, so taking backup manually (i.e using freeze) is not good idea since data are spread across the shards 

What is the best way to do it and achieve as fast as manaul backup (i.e freezing the table and copying it)!
I know clickhouse-backup tools but not sure how fast is it ..

I am using Clickhouse Operator v.0.14.0

**Comment by Slach** [comment]
clickhouse-backup also use FREEZE to make the local backup
FREEZE shall not long operation, cause it just creates hard links to exists data parts to prevent deletion after background merge

execution time for FREEZE depends on how many parts do you have in `system.parts`

from our experience, upload \download local backup to\from remote storage take much more time than FREEZE

when you use shards schema, you could just select one replica from each shard, run clickhouse-backup only on this replica to create local backup with FREEZE.. and upload it with a diff from the previous backup  and remove local backup after successful upload

look to https://github.com/Altinity/clickhouse-operator/blob/0.15.0/tests/configs/test-cluster-for-backups.yaml and https://github.com/Altinity/clickhouse-operator/blob/0.15.0/tests/templates/tpl-clickhouse-backups.yaml for example of clickhouse-backup installation

after `clickhouse-backup server` run you can any run commands during `INSERT INTO system.backup_actions` and poll result from `SELECT * FROM system.backup_actions ` and  `SELECT * FROM system.backup_list`

**Comment by sagarshrestha24** [comment]
you reffered us to use clickhouse-backup for this issue

**Comment by alex-zaitsev** [comment]
@sagarshrestha24 , clickhouse-operator does not handle backups on its own, but you can do it with clickhouse-backup. Please see this example how clickhouse-backup can be installed as a sidecar:
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-07-security-context.yaml
