### ISSUE TITLE
Separate volume for backups

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-operator#723]
Hi,

I'm trying to find a way to have a separate volume for the backup storage.
The goal of this is to ensure it doesn't fill up the data volume when creating multiple backups ( snapshots )

**Comment by Slach** [comment]
when clickhouse-backup create local backup it not allocate space, it just create hardlinks to prevent data parts from deletetion after background merge
look to
https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#alter_freeze-partition 
for details

so when you create local backup
you can just use mv from `backup` directory to separate storage after run `clickhouse-backup create`
so, when you store multiple backups

**Comment by electrical** [comment]
Thanks for the quick response. My plan is to do multiple snapshots per day and only transfer 1 every night out of the system.
When doing multiple snapshots they do start taking more space, because of that i was hoping to have the backup directory on a separate volume.

**Comment by electrical** [comment]
To clarify my request. How do I add a separate local storage? So far i've only found `volumeClaimTemplates` that work with the `dataVolumeClaimTemplate` but I don't see any option to add a separate volume.

**Comment by Slach** [comment]
look to https://github.com/Altinity/clickhouse-operator/tree/0.15.0/docs/chi-examples and define storage using `volumeClaimTemplates`

**Comment by electrical** [comment]
That's exactly what I was looking for. Don't know how i missed that. Thank you very much!
