### ISSUE TITLE
Cannot update clickhouse-server to version > 21.2

### ISSUE THREAD

**Issue by macobo** [Altinity/clickhouse-operator#734]
With clickhouse-operator 0.14.0, after updating clickhouse version to >= 21.2, the following error occurs:

```
⟩ kubectl logs chi-posthog-posthog-0-0-0                                                         15:48:22
chown: changing ownership of '/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..data': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/02-clickhouse-logger.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/03-clickhouse-querylog.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/04-clickhouse-partlog.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/chop-generated-settings.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/01-clickhouse-listen.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/chop-generated-remote_servers.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/02-clickhouse-logger.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/03-clickhouse-querylog.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/04-clickhouse-partlog.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/chop-generated-settings.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/01-clickhouse-listen.xml': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804/events.proto': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/..2021_07_05_12_47_44.753804804': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/events.proto': Read-only file system
chown: changing ownership of '/etc/clickhouse-server/config.d/': Read-only file system
```

This seems to be caused by:

> Docker: Explicitly set uid / gid of clickhouse user & group to the fixed values (101) in clickhouse-server Docker images. #19096 (filimonov).
From https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md

See helm chart + tests over at https://github.com/PostHog/charts-clickhouse/pull/32/files

Things I've attempted:

1. Set `securityContext` of `podTemplates` to
```
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
```

(And other variants, e.g. user 0) - the same error occurs

2. Set `CLICKHOUSE_DO_NOT_CHOWN`

The following error instead occurs:

```
⟩ kubectl logs chi-posthog-posthog-0-0-0
Necessary directory '/etc/clickhouse-server/config.d/' isn't accessible by user with id '101'
```

It seems that clickhouse-operator is mounting the volumes in this case, which is not readable by the new default uid/gid of clickhouse-server. Relevant code: https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/creator.go#L469-L496

**Comment by Slach** [comment]
looks little bit weird, 
by default `entrypoint.sh` should only try to chown in `/var/lib/clickhouse` but not in `/etc/clickhouse-server/config.d/`
https://github.com/ClickHouse/ClickHouse/tree/21.2/docker/server/entrypoint.sh#L57-L74

also when you apply securityContext to podTemplate
it should mount your config.d, conf.d and users.d configMaps with the same uid:gid as described in securityContext

**Comment by Slach** [comment]
I found root reason
https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L57
you define 
format_schema_path as `/etc/clickhouse-server/config.d/`
so `entrypoint.sh` try to chown this directory

**Comment by alex-zaitsev** [comment]
config.d is mounted readonly so it can not be chown. 

@macobo , try securityContext:
```      
    spec:
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          fsGroup: 101
```

And also change the way ClickHouse starts:
```
          command:
          - /bin/bash
          - -c
          - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
 ```

**Comment by Slach** [comment]
@macobo look to https://github.com/Altinity/clickhouse-operator/blob/0.15.0/docs/chi-examples/20-protobuf-schema-example.yaml#L44 for workaround

**Comment by macobo** [comment]
Seems like securityContext + custom command did the trick. See here: https://github.com/PostHog/charts-clickhouse/pull/32/commits/35f715d725db7e5523b7da305fb64e395256ea62 + https://github.com/PostHog/charts-clickhouse/pull/32/checks?check_run_id=2998139240  :bow: :beers: @alex-zaitsev  

I think the init container trick + changing settings is not needed. Am I missing something obvious @Slach ?

**Comment by Slach** [comment]
custom command + securityContext is enough, 
initContainer need only when you want to allow run schema initialization via `/docker-entrypoint.init.db/*.*` files

**Comment by macobo** [comment]
Thanks for the help. :clap: 

Follow-up question - this seems like something that might bite others as well. Perhaps worth updating documentation for this?

**Comment by Slach** [comment]
IMHO, usually, users don't redefine `.spec.settings.format_schema_path` value.
