### ISSUE TITLE
CLickhouse pod is in crassloopbackoff error

### ISSUE THREAD

**Issue by sagarshrestha24** [Altinity/clickhouse-operator#738]
previously our pod is crash due to insufficent disk ,we free up disk and we bring it up  

but also again pod is in crash when i go inside that pod 

```
root@chi-xxxx-1-0-0:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 14:29 ?        00:00:00 /bin/bash /entrypoint.sh
root          28       1 23 14:29 ?        00:00:25 chown -R 101:101 /var/lib/clickhouse/
root          29       0  0 14:31 pts/0    00:00:00 bash
root          38      29  0 14:31 pts/0    00:00:00 ps -ef

```
why this chown is running is this neccesary or we can skip this 

in entrypoint.sh (which starts when clickhouse starts), it runs this
8:13
```
# grep chown /entrypoint.sh
        chown -R “$USER:$GROUP” “$dir”
```

```
kubectl get pod 
chi-xxx-0-1-0   1/1     Running            0          30m
chi-xxx-1-0-0   0/1     CrashLoopBackOff   7          19m

```

**Comment by Slach** [comment]
when you have too many parts on disk (more than 100 000 files in `/var/lib/clickhouse/data` and slow disk)
`chown` will take time to make disk operations
and readiness probe will fail (by default liveness probe have InitialDelaySeconds: 10 sec)

you have following solution to avoid this:
- disabe chown via environment variable CLICKHOUSE_DO_NOT_CHOWN (use custom podTemplate in `spec.clusters.templates` or `spec.configuration.clusters[].templates.podTemplate` and change `spec.templates.podTemplates[].spec.containers[].env`
look to https://github.com/Altinity/clickhouse-operator/commit/d214c20f045b57c152914006a85e6195d9686c4b for example

- look to your data INSERTS and try to increase batch size (how many rows insert per one inserts) 
- look to your PARTITION BY clause in your tables, maybe you have wrong partition schema which product too many data parts from each INSERT
- maybe, you should re-define readiness probe in your `spec.templates.podTemplates[].spec.containers[].readinessProbe` with increased `initialDelaySeconds`, look to `kubectl explain Pod.spec.containers.readinessProbe`  for details

**Comment by sagarshrestha24** [comment]
i have done with chown part but i got crash issue 
when i logs the pod i got this error 
`Necessary directory '/var/log/clickhouse-server' isn't owned by user with id '101`'

**Comment by Slach** [comment]
please look to 
volumeMounts
on
https://github.com/Altinity/clickhouse-operator/blob/0.15.0/docs/chi-examples/03-persistent-volume-02-pod-template.yaml#L23-L27
