### ISSUE TITLE
Data rebalancing not supported

### ISSUE THREAD

**Issue by pulkitkalia1994** [Altinity/clickhouse-operator#750]
Hello,
I tried distributed engine on top of replicated merge tree with some data and 3 shards. However, when I tried to reduce the number of shards to 2 through yaml config, the data was lost and not rebalanced. I was expecting the data to be redistributed to other shards but didn't happen. 
Can anyone please help with this?

**Comment by Slach** [comment]
clickhouse itself does not support data rebalancing
subscribe to https://github.com/ClickHouse/ClickHouse/issues/13574  and watch the progress
