### ISSUE TITLE
Is the Clickhouse operator a code framework generated using kubebuilder？

### ISSUE THREAD

**Issue by fantastic2085** [Altinity/clickhouse-operator#751]

**Comment by Slach** [comment]
@fantastic2085 no, clickhouse-operator doesn't use https://github.com/kubernetes-sigs/kubebuilder

**Comment by fantastic2085** [comment]
> @fantastic2085 no, clickhouse-operator doesn't use https://github.com/kubernetes-sigs/kubebuilder
Is the Clickhouse operator code also written according to the operator SDK? The Clickhouse operator code just doesn't use the kubebuilder automated production code framework, does it?

**Comment by Slach** [comment]
@fantastic2085 look to https://github.com/Altinity/clickhouse-operator/blob/master/go.mod#L24-L27
clickhouse-operator use only native golang Kubernetes API client

what is the goal of your questions?

**Comment by fantastic2085** [comment]
> @fantastic2085 look to https://github.com/Altinity/clickhouse-operator/blob/master/go.mod#L24-L27
> clickhouse-operator use only native golang Kubernetes API client
> 
> what is the goal of your questions?

I want to have an in-depth understanding of the source code of Clickhouse operator, so I want to know what the design basis of the source code of Clickhouse operator is, because after I know about operator SDK / kubebuilder, I think Clickhouse operator does not use operator SDK / kubebuilder, so I want to know about it and thank the community for its patience
