### ISSUE TITLE
Is it possible to add another job/container in the pod for clickhouse? 

### ISSUE THREAD

**Issue by pulkitkalia1994** [Altinity/clickhouse-operator#752]
Hello Team, 
I am planning to add another service/job in the same pod as the clickhouse shard and replicas. Is it possible to do the same?
I want to send some custom metrics and transfer some data from inside the clickhouse pod.

Thank you!

**Comment by Slach** [comment]
yes, you can define custom `podTemplate` in your 
and any other container in the pod
for example please look to
https://github.com/Altinity/clickhouse-operator/blob/master/tests/templates/tpl-clickhouse-backups.yaml#L33

but if you apply this modification it will restart clickhouse pod, cause after update `podTemplate` for `statefulset`, kubernetes itself restart all pods in `statefulset`
