### ISSUE TITLE
Is it possible to have a replica and the leader shard in the same pod?

### ISSUE THREAD

**Issue by pulkitkalia1994** [Altinity/clickhouse-operator#758]
Hello,

As per the default installation, a shard and it's replica is placed under different pods. For example, if I create a manifest file with 2 shards and 2 replicas, a total of 4 pods will spin up. I would like to have a Cross backup. This should result in only 2 pods created in k8s.

*Cross backup to fully use the computing resource. an example of cross backup,
1. pod 1 - shard 1 (leader), shard 2 (follower)
2. pod 2 - shard 2 (leader), shard 1 (follower).
Will that be possible?

**Comment by Slach** [comment]
"leader" is mean this `clickhouse-server` instance is just responsible to schedule background merge, you can write to any replica
look to "is_leader" in https://clickhouse.tech/docs/en/operations/system-tables/replicas/ for details

and is not possible to run two `clickhouse-server` containers in the same pod under `clickhouse-operator`

if you want "circular replication" 
look to 
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/13-distribution-02-3x3-circular-replication.yaml
read details here
https://altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

but we don't recommend using this anti-pattern
