### ISSUE TITLE
Timeout for query of clickhouse-operator user

### ISSUE THREAD

**Issue by dsemenischev** [Altinity/clickhouse-operator#761]
clickhouse-operator user can use all connections, if can not get answer for query, for example: 
SELECT
        count(*)          AS mutations,
        sum(parts_to_do) AS parts_to_do
FROM system.mutations    AS mutations,
WHERE is_done = 0 to_do AS parts_to_do
GROUP BY database, table. 

you can replay situation:
1) create table test (id1 Uint32, id2 Uint32) ENGINE MergeTree order by id1
2) Alter table test update id2=sum(1+ (select id1 from test))  where 1=1;
3) Check query's: 1) Select *  from  system.mutations  2) Select *  from  system.mutations where table not like 'test'
4) After 30 minutes check: select * from system.processes where user='clickhouse-operator'

Best Regards, Dmitriy

**Comment by alex-zaitsev** [comment]
We have added timeouts some time ago, so it should be good now
