### ISSUE TITLE
problem with disk expansion

### ISSUE THREAD

**Issue by su-houzhen** [Altinity/clickhouse-operator#765]
I am using ClickHouse-Opeartor on K8s provided by a cloud service provider, but there is a problem with disk expansion.

The reason is that the expansion operation of the StorageClass provided by the cloud service can only be performed when status is `offline`.

I saw in the method `recreateStatefulSet` that when we reconcile PVC, we did't wait its expansion succeed, and then recreate statefulset, which led to the following problems:

a. delete statefulset && pvc offline;

b. reconcile PVCs;

c. reconcile PVCs ok && StorageClass do expand;

d. create statefulset ok (At this time, the StorageClass has not completed expansion);

d. pvc online, expansion cannot continue;

e. Expansion failed;

So do we need to add logic to wait expand success? I am not sure if other `StorageClass`es have similar problems.

**Comment by blafry** [comment]
Similar problem: https://github.com/Altinity/clickhouse-operator/issues/457

**Comment by alex-zaitsev** [comment]
@su-houzhen , what cloud provider are you using?

**Comment by su-houzhen** [comment]
my cloud provider is QingCloud.
