### ISSUE TITLE
beta CustomResourceDefinition API (apiextensions.k8s.io/v1beta1) to be removed in 1.22

### ISSUE THREAD

**Issue by gurvindersingh** [Altinity/clickhouse-operator#777]
Current installation uses [apiextensions.k8s.io/v1beta1](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml#L1) which is about to be expired in upcoming [K8s release 1.22](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/)

**Comment by Slach** [comment]
duplicated with https://github.com/Altinity/clickhouse-operator/issues/762
