### ISSUE TITLE
DB: Exception Double-distributed IN/JOIN subqueries is denied  issue 

### ISSUE THREAD

**Issue by surajmachamasi** [Altinity/clickhouse-operator#780]
i  have tried executing the sql query in the clickhouse client. i have been getting  this issue given below.  

i have set this parameter too, still got no effect.  

bash output
=========
chi-repl-prod-prdc01-0-0-0.chi-repl-prod-prdc01-0-0.suraj.svc.cluster.local :) SET  distributed_product_mode='allow'
SET distributed_product_mode = 'allow'
Ok.
0 rows in set. Elapsed: 0.003 sec. 

mysql db exception
===============
num_hosts_remaining─┬─num_hosts_active─┐
│ chi-repl-prod-prdc01-0-0 │ 9000 │    288 │ Code: 288, e.displayText() = DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny'). You may rewrite query to use local tables in subqueries, or use GLOBAL keyword, or set distributed_product_mode to suitable value. (version 20.7.4.11 (official build)) │                   1 │                0 │
│ chi-repl-prod-prdc01-1-0 │ 9000 │    288 │ Code: 288, e.displayText() = DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny'). You may rewrite query to use local tables in subqueries, or use GLOBAL keyword, or set distributed_product_mode to suitable value. (version 20.7.4.11 (official build)) │ 

please response soon.

**Comment by Slach** [comment]
You could try to add in your CHI manifest:

```yaml
spec:
  configuration:
     settings:
        distributed_product_mode: allow
``` 
And be careful, distributed_product_mode='allow' could have a lot of side effects.

**Comment by chengjoey** [comment]
```
spec:
  configuration:
    profiles:
      default/distributed_product_mode: allow
```

If you write it directly in settings, an error will be reported. This is a user-level configuration.

**Comment by Slach** [comment]
@chengjoey nice catch, thanks
