### ISSUE TITLE
Ability to change image for busybox in container-log

### ISSUE THREAD

**Issue by maver1ck** [Altinity/clickhouse-operator#781]
Hi,
Currently clickhouse-operator is creating clickhouse-log container using busybox image name from: `defaultBusyBoxDockerImage` const

How to overwrite this value ? I have environment without internet access and with custom docker registry

I tried to create custom clickhouse-log container in podTemplates but without success.

I can't find any options also in code:
https://github.com/Altinity/clickhouse-operator/blob/0926d00a22be23499d633ce455bc5473a9620d15/pkg/model/creator.go#L993

**Comment by Slach** [comment]
Currently, `clickhouse-log` container creates only when you define
`chi.spec.defaults.templates.logVolumeClaimTemaplte`

It allows kubectl exec into `clickhouse` pod and try to watch logs in `/var/log/clickhouse-server/`

Could you explain your use case? 
What is your goal to change image?

**Comment by maver1ck** [comment]
Hi,
My goal is to run clickhouse in env where there is no internet access using private docker registry.
I'm able to use custom clickhouse image, but I can't do this with busybox.

**Comment by Slach** [comment]
Ok, roger that. You have `ImagePullBackOff` state for `clickhouse-log` container when use private registry without internet access.
So make sense, look like it could be implemented.

**Comment by Slach** [comment]
feel free to make PR

**Comment by bkuschel** [comment]
@Slach can we default the container-log on ubi instead of ubi for consistency with the operator?

**Comment by calderwd** [comment]
Is it possible to disable this container while still allocating separate volume controls for data and logs ?

**Comment by Slach** [comment]
@alex-zaitsev @sunsingerus could you share your mention?

**Comment by chancez** [comment]
Why is the busy box container needed to exec into the pod at all? You can exec into the clickhouse pod directly and look at the log files. This container seems completely unneeded if that's all it's for.
