### ISSUE TITLE
Can I send a query to clickhouse-server from a container in the same pod as clickhouse-server? 

### ISSUE THREAD

**Issue by pulkitkalia1994** [Altinity/clickhouse-operator#785]
I have a pod containing clickhouse container and an additional customized container. I want to send data to clickhouse container for ingestion from the customized container and would like to do it locally and not over network(as the data is heavy).
Will it be possible to achieve it?

**Comment by Slach** [comment]
Yes, it is possible
use `spec.templates.podTemplates` and `spec.defaults.templates`

look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/02-templates-01-pod-template.yaml

You could add yet another container into `spec.templates.podTemplates[0].containers[]` with a different image where you can run your custom SQL commands via the HTTP ClickHouse interface, something like this `curl -s "http://localhost:8123/?SELECT+1"`

**Comment by pulkitkalia1994** [comment]
So the queries are sent over the http. I am worried about the performance impact to insert a 10GB data to clickhouse via http/network.
Will the insert query still be fast via http?

**Comment by Slach** [comment]
You can start a container with `"image: yandex/clickhouse-client"`
and wait when `clickhouse-server` will available on 9000 TCP port via `"command"` parameter in `containers[].spec`
after it, you can run `clickhouse-client -q "your SQL query"`
