### ISSUE TITLE
Do not restart the pod when volume is expanded

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#788]
> template

So whether to optimize this feature?

_Originally posted by @Sallery-X in https://github.com/Altinity/clickhouse-operator/issues/689#issuecomment-927246109_

**Comment by alex-zaitsev** [comment]
Re-scale w/o restart is supported in 0.20.0 release with operator controlled storage management:
```  
   defaults:
    storageManagement:
      provisioner: Operator
```
