### ISSUE TITLE
Suspiciously many (30) broken parts to remove.. 

### ISSUE THREAD

**Issue by sagarshrestha24** [Altinity/clickhouse-operator#791]
when i attach a table i got this issue

```
ATTACH TABLE ad_event_temp


Received exception from server (version 20.7.4):
Code: 231. DB::Exception: Received from localhost:9000. DB::Exception: Suspiciously many (30) broken parts to remove.. 

```

there is lots of data in this table

can anyone help ?

**Comment by alex-zaitsev** [comment]
This not an operator issue. The error tells you that the data that you are trying to attach is broken from ClickHouse prospective. Look at /var/lib/clickhouse/data/<database>/ad_event_temp folder and examine contexts. But it is better to ask this question and add more context on what has happened before (e.g. why table is detached) in the ClickHouse project.
