### ISSUE TITLE
DB::AsynchronousMetrics::update - Cannot read from file /sys/block/sdb/stat, errno: 19, strerror: No such device

### ISSUE THREAD

**Issue by matiza5** [Altinity/clickhouse-operator#798]
Hi,

I have faced an issue with clickhouse block devices monitoring. It is noticeable mostly on kubernetes (on VMWare), where all PVCs/attached disks are dynamic.
Clickhouse while starting discovers all disk devices connected to k8s worker underneath (other disks not related to clickhouse, i.e. zookeeper PV disk). ( https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/AsynchronousMetrics.cpp#L120 )

When i.e. zookeeper pod is terminated and rescheduled to other worker VMWare CSI driver detaches disk from original worker and reattach disk to another worker. On the original worker side disk (let's say `/dev/sdb`) no longer exists and clickhouse starts throwing such errors:
```
2021.10.18 10:53:27.000980 [ 312 ] {} <Error> void DB::AsynchronousMetrics::update(std::chrono::system_clock::time_point): Code: 74, e.displayText() = DB::ErrnoException: Cannot read from file /sys/block/sdb/stat, errno: 19, strerror: No such device, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8faa0fa in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x8fab0e9 in /usr/bin/clickhouse
2. DB::ReadBufferFromFileDescriptor::nextImpl() @ 0x8ffc49d in /usr/bin/clickhouse
3. DB::AsynchronousMetrics::BlockDeviceStatValues::read(DB::ReadBuffer&) @ 0xff9bf71 in /usr/bin/clickhouse
4. DB::AsynchronousMetrics::update(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >) @ 0xff92d39 in /usr/bin/clickhouse
5. DB::AsynchronousMetrics::run() @ 0xff9b5c1 in /usr/bin/clickhouse
6. ? @ 0xff9f9f4 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fead7f in /usr/bin/clickhouse
8. ? @ 0x8fee663 in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.8.7.22 (official build))
 ```
 This error message is throwed every second flooding me with false-alarm events.
 I have single PV attached to clickhouse-server, which is controlled by VMware CSI Drvier - datastore is vSAN.
 Honestly I'm not intrested in block devices stats other then clickhouse PV - is there any way to limit monitoring to only clickhouse data drive?

Clickhouse version: v21.8.7
Operator version: v0.16.0
Kubernetes cluster: GKE Anthos on Vmware v1.20.8-gke.1500

**Comment by tdminh** [comment]
I have the same issue when reinstall zookeeper. @matiza5 Did you find a way to fix it?

**Comment by jpiper** [comment]
I wonder if this has been fixed in these PRs: 
https://github.com/ClickHouse/ClickHouse/pull/27266
https://github.com/ClickHouse/ClickHouse/pull/27195

**Comment by jun0tpyrc** [comment]
seem still an issue for me

**Comment by Slach** [comment]
@jun0tpyrc issue is not related to clickhouse-operator, please try to update to latest `clickhouse-server` 21.12 version or create separate issue with stack traces on https://github.com/ClickHouse/ClickHouse/issues
