### ISSUE TITLE
Problem with CRD definition based on `x-kubernetes-preserve-unknown-fields: true`

### ISSUE THREAD

**Issue by towolf** [Altinity/clickhouse-operator#799]
We would like to use the `wait_for` feature in Terraform to wait for the reconciled state of the ClickHouseInstallation custom resource. This allows us to block on the value of the `status.status` field to become `Running`.

However this only works for fields which are properly and explicitly defined in the OpenAPI spec of the CRD, and not by relying on `x-kubernetes-preserve-unknown-fields: true` to just accept all fields.

This was introduced in https://github.com/Altinity/clickhouse-operator/pull/778 after issue https://github.com/Altinity/clickhouse-operator/issues/762

**Comment by sunsingerus** [comment]
Please check 0.16.1
Status is elaborated in CRD now

**Comment by alex-zaitsev** [comment]
@towolf ^

**Comment by towolf** [comment]
Hi @alex-zaitsev and @sunsingerus we've confirmed the fix as working. Thank you.
