### ISSUE TITLE
Large Volume Usage By Zookeeper In Cluster Setup

### ISSUE THREAD

**Issue by wemod123** [Altinity/clickhouse-operator#804]
I Setup a cluster following [this instruction](https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md), and setup 3-shardes and 3-replica cluster successfully (with 3-zookeeper replica).

Then I insert data, and found that the zookeeper volume usage increasing continually sth like this:
- each-data-node-volume: 1.5GB
- each-zookeeper-node: 5GB

Is this the way the cluster working?
Or how it be working in long term with big volume of data

---Updates----
Now I got ~10BG on each zk node, and 1.8 GB on each clickhouse node.

What is really happening under the hood? 
Means if I want to have 100GB data of clickhouse shard, I need 500GB of zookeeper volume usage? How zookeeper can handle that

**Comment by alex-zaitsev** [comment]
ZooKeeper log and snapshot usually do not exceed 10GB. You need to allocate 25GB for ZooKeeper node to be safe.
