### ISSUE TITLE
Cannot link operation not supported when using replication

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#813]
I've been following the steps in this file: https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md. The only change I made is to pull the latest image for clickhouse-server instead of 19.6.2.11.

I have zookeeper and clickhouse-operator set up as per the guides. I'm running this on AKS, I have PVCs setup for my zookeeper instances and for my clickhouseinstallations.

When I run the INSERT I get this error:

`Code: 424. DB::Exception: Received from clickhouse-blah:9000. DB::Exception: Cannot link /var/lib/clickhouse/data/default/events/shard1_all_replicas/tmp/2.bin to /var/lib/clickhouse/data/default/events/shard1_all_replicas/2.bin, errno: 95, stderror: Operation not supported.`

**Comment by alex-zaitsev** [comment]
Hi @a-dot , this error is from file system. It complains that hard links are not supported. ClickHouse users hard links very extensively, so it can not work without them. 

Could you elaborate with a couple of things:
1) Does it work if you setup a single node ClickHouse?  (no ZK and replication at all)
2) What is your storage class and file system?

**Comment by a-dot** [comment]
Hello! I just managed to get this fixed by using the `managed-premium` instead of `default` storage class in AKS. *shrug*

Thanks for the help!

**Comment by alex-zaitsev** [comment]
Excellent!
