### ISSUE TITLE
Operator doesn't update CHI configmaps without restart

### ISSUE THREAD

**Issue by rtkrnguyen** [Altinity/clickhouse-operator#814]
When updating configmaps for userdFiles the operator does not update the CHI related configmaps until restarting the operator pod.

Does the Operator have the ability to monitor configmap changes and update as needed? Unsure if there's some misconfiguration on my end.

**Comment by a-dot** [comment]
Have you looked at this page: https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_configuration.md

`Changes to etc-clickhouse-operator-files are not monitored, but picked up if operator is restarted. Changes to ClickHouseOperatorConfiguration are monitored by an operator and applied immediately.`

**Comment by rtkrnguyen** [comment]
Thanks! I must've missed that.
