### ISSUE TITLE
metrics-exporter reporting empty CHI list

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#819]
Hi,

I was following the troubleshooting steps provided by @Slach from issue #802 and when I got to `kubectl exec -n kube-system <clickhouse-operator-pod-name> -c metrics-exporter -- wget -qO- http://127.0.0.1:8888/chi` it returned an empty list `[]`. I have 4 pods running for my installation. What could explain this issue and do you have any ideas on how it could be resolved? Thanks a lot!

**Comment by Slach** [comment]
which operator version did you use?

could you share
`kubectl get deploy --all-namespaces | grep clickhouse-operator` ?

**Comment by Slach** [comment]
also, could you share 

```kubectl -n kube-system <clickhouse-operator-pod-name> -c clickhouse-operator --sinrce=24h | grep -i monitor```

**Comment by a-dot** [comment]
I'm using v0.16.0.

Output for `k get deploy --all-namespaces | grep clickhouse-operator`:
`clickhouse-operator     1/1     1            1           12d`

Output for `kubectl -n kube-system <clickhouse-operator-pod-name> -c clickhouse-operator --sinrce=24h | grep -i monitor`. (This command returned an error, I'm assuming you wanted to output the logs for the CHO container? If so, here's the only line from the logs)
`I1114 14:47:34.747789       1 announcer.go:220] includeStopped():mynamespace/ch-main:add CHI to monitoring`

**Comment by Slach** [comment]
> I1114 14:47:34.747789 1 announcer.go:220] includeStopped():mynamespace/ch-main:add CHI to monitoring

It means `ch-main` should contain in `metrics-exporter` `wget -qO- http://127.0.0.1:8888/chi`

Could you share your CHI manifest?
`kubectl -n mynamespace -o yaml ch-main`

**Comment by a-dot** [comment]
I'm rather embarassed to say this but my CHI list is now returning my pods! I'm not sure what happened between the time I posted and now. Earlier today I tried to restart my pods and that seems to have fixed something... My bad! Thanks for your help. I'll close the issue now.
