### ISSUE TITLE
Zookeeper schema configuration

### ISSUE THREAD

**Issue by AceHCL** [Altinity/clickhouse-operator#825]
Hello, I'd like to ask you, can the zookeeper cluster of a single namespace be used by multiple Clickhouse clusters under this namespace?

**Comment by Slach** [comment]
yes, it possible
but you need to setup differente `zookeeper/distributed_ddl` in `settings` section of yaml manifests and different zookeeper `path` in `Engine=ReplicatedMergeTree()` parameters to avoid wrong interactions between separate clickhouse-clusters
