### ISSUE TITLE
Error from server (MethodNotAllowed): error when creating "./test.yaml": the server does not allow this method on the requested resource (post clickhouseinstallations.clickhouse.altinity.com)

### ISSUE THREAD

**Issue by jessezax** [Altinity/clickhouse-operator#826]
i use kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle-v1beta1.yaml
 and kubectl apply -f ./test.yaml

**Comment by jessezax** [comment]
logs 
E1201 05:07:14.524422       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseOperatorConfiguration: failed to list *v1.ClickHouseOperatorConfiguration: the server could not find the requested resource (get clickhouseoperatorconfigurations.clickhouse.altinity.com)

**Comment by Slach** [comment]
@jessezax which kubernetes version do you use and which distribution? 

It's a managed or local \ bare-metal installation?
It's a Google GKE or AWS EKS or Azure AKS?

**Comment by jessezax** [comment]
> @jessezax which kubernetes version do you use and which distribution?
> 
> It's a managed or local \ bare-metal installation? It's a Google GKE or AWS EKS or Azure AKS?

v1.15.11-eks-065dce

**Comment by jessezax** [comment]
> @jessezax which kubernetes version do you use and which distribution?
> 
> It's a managed or local \ bare-metal installation? It's a Google GKE or AWS EKS or Azure AKS?

Was normal before

**Comment by Slach** [comment]
could you share output for following commands

```kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle-v1beta1.yaml```

```kubectl get pods --all-namespaces | grep clickhouse-operator```

**Comment by jessezax** [comment]
> 

```
[root@ip-172-31-41-19.ec2.internal:52.21.218.37 clickhouse]#kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle-v1beta1.yaml
customresourcedefinition.apiextensions.k8s.io/clickhouseinstallations.clickhouse.altinity.com configured
customresourcedefinition.apiextensions.k8s.io/clickhouseinstallationtemplates.clickhouse.altinity.com created
customresourcedefinition.apiextensions.k8s.io/clickhouseoperatorconfigurations.clickhouse.altinity.com created
serviceaccount/clickhouse-operator created
clusterrole.rbac.authorization.k8s.io/clickhouse-operator-kube-system created
clusterrolebinding.rbac.authorization.k8s.io/clickhouse-operator-kube-system created
configmap/etc-clickhouse-operator-files created
configmap/etc-clickhouse-operator-confd-files created
configmap/etc-clickhouse-operator-configd-files created
configmap/etc-clickhouse-operator-templatesd-files created
configmap/etc-clickhouse-operator-usersd-files created
deployment.apps/clickhouse-operator created
service/clickhouse-operator-metrics created
```

```
[root@ip-172-31-41-19.ec2.internal:52.21.218.37 clickhouse]#kubectl get pods --all-namespaces | grep clickhouse-operator
kube-system                clickhouse-operator-7987b8c8bc-d2jw4                              0/2     ContainerCreating   0          4s
operator-ll                clickhouse-operator-7987b8c8bc-z77bp                              2/2     Running             0          27m
test-clickhouse-operator   clickhouse-operator-7987b8c8bc-qsvmx                              2/2     Running             0          3d12h
```

**Comment by Slach** [comment]
look like you creating multiple clickhouse-operator installations
clickhouse-operator inside 

you should run
```
kubectl delete deployment -n operator-ll clickhouse-operator
kubectl delete deployment -n test-clickhouse-operator clickhouse-operator
```

cause `clickhouse-operator`  installed into `kube-system` will watch all another namespaces

**Comment by jessezax** [comment]
> look like you creating multiple clickhouse-operator installations clickhouse-operator inside
> 
> you should run
> 
> ```
> kubectl delete deployment -n operator-ll clickhouse-operator
> kubectl delete deployment -n test-clickhouse-operator clickhouse-operator
> ```
> 
> cause `clickhouse-operator` installed into `kube-system` will watch all another namespaces

thank you。works！
