### ISSUE TITLE
Proper way to wait for deployment of cluster to be done?

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#829]
Hi, what's the proper way to wait for a cluster deployment to be complete? (all pods for all shards/replicas are in a ready state and services are ready). I thought about using "kubectl wait" on the statefulset but CHO spawns up one statefulset per shard per replica so that's not possible. For the same reason "rollout status" can't be used on the STS because it's scattered and not a single StatefulSet. Any idea?

**Comment by sunsingerus** [comment]
CHI's `status.status` field comes to help.

**Comment by sunsingerus** [comment]
Examples:
`status: InProgress` vs `status: Completed`

**Comment by a-dot** [comment]
That would definitely work but it looks like status.status is not supported as a field selector? I'm getting a "field label status.status not supported: status.status" when trying to use it with `wait` or even to get the chi with --field-selector.

I _could_ have a shell script that looks like this:
```
#!/bin/sh

while [ 1 -eq 1 ];
do
    kubectl get chi mychi -o=jsonpath='{.status.status}' | grep Completed
    if [ $? -eq 0 ]
    then
        break
    fi

    sleep 2
done
```

But that wouldn't be as clean. Any way to use status.status as a field-selector that I'm missing? Thanks!

**Comment by Slach** [comment]
i just use 
```
while [[ "0" == $(kubectl get chi mychi | grep -c Completed) ]]; do
 sleep 2
done
```
