### ISSUE TITLE
The data are not distruted across  the Shards

### ISSUE THREAD

**Issue by surajmachamasi** [Altinity/clickhouse-operator#833]
i have two shrads up and running, the data pulled via kafka server are distributed across the shards. only shard 1 gets all the data but shards 2 is not receiving the data. is there any way to configure this in clickhouse configuration?

distrubuted table: 

     ENGINE = Distributed('cluster', 'addotnet', 'ad_event_local', toYYYYMM(event_date))

**Comment by Slach** [comment]
Issue is not related to clickhouse-operator
`toYYYYMM(event_date)` as `sharding key`, mean you will get the same "shard id" in whole month for every row when try to insert data into engine=Distributed table
