### ISSUE TITLE
How the data are distributed between the each shards ?

### ISSUE THREAD

**Issue by surajmachamasi** [Altinity/clickhouse-operator#839]
any guide configuration for to distributing the data between the shards like round-robin way. like for e.g  i want to put the half  of the table data to one shard and other half to other shard.

**Comment by alex-zaitsev** [comment]
Hi @surajmachamasi,

Use rand() function as a sharding_key Distributed table and insert into Distributed table:
https://clickhouse.com/docs/en/engines/table-engines/special/distributed/

The cluster matches the CHI cluster name. Look at examples of Replicated and so Distributed tables as described here: https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md
