### ISSUE TITLE
After upgrading to 0.17, an exception error occurs when modifying clickhouseinstallation

### ISSUE THREAD

**Issue by czhfe** [Altinity/clickhouse-operator#842]
After upgrading to 0.17 an exception error occurs when modifying clickhouseinstallation, which prevents modification and deletion of clickhouseinstallation. the error is as follows:

The ClickHouseInstallation "clickhouse" is invalid: status.errors: Invalid value: "null": status.errors in body must be of type array: "null"

**Comment by Slach** [comment]
How exactly do you upgrade to 0.17?
Did you upgrade `crds` or just update image in deployment?

Could you share the results for following command?
```
kubectl get deploy --all-namespaces | grep clickhouse-operator
```

**Comment by czhfe** [comment]
> How exactly do you upgrade to 0.17? Did you upgrade or just update image in deployment?`crds`
> 
> Could you share the results for following command?
> 
> ```
> kubectl get deploy --all-namespaces | grep clickhouse-operator
> ```

Upgrade operator first, then upgrade crd.

![image](https://user-images.githubusercontent.com/19341806/147059195-2b65495a-a82e-4759-9378-f2d43c0af44c.png)

**Comment by Slach** [comment]
Could you upgrade CRDs first
your deployment not look like after `standard installation way`
it should be clickhouse-operator instead of `clickhouse-operator-altinity-clickhouse-operator`?
Did you use some Helm chart or something else?

Could you remove this deployment (it safe)
```bash
kubecetl delete deploy -n kube-system clickhouse-operator-altinity-clickhouse-operator
```

after it and just apply
```bash
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml
```

and check results
```bash
kubectl get deploy clickhouse-operator -n kube-system 
```

**Comment by czhfe** [comment]
> Could you upgrade CRDs first your deployment not look like after it should be clickhouse-operator instead of ? Did you use some Helm chart or something else?`standard installation way``clickhouse-operator-altinity-clickhouse-operator`
> 
> Could you remove this deployment (it safe)
> 
> ```shell
> kubecetl delete deploy -n kube-system clickhouse-operator-altinity-clickhouse-operator
> ```
> 
> after it and just apply
> 
> ```shell
> kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml
> ```
> 
> and check results
> 
> ```shell
> kubectl get deploy clickhouse-operator -n kube-system 
> ```

I wrote the helm chart deployment myself

**Comment by Slach** [comment]
@czhfe ok. try update crds
in your helm chanrt
and re-install clickhouse-operator

**Comment by czhfe** [comment]
> @czhfe ok. try update crds in your helm chart and re-install clickhouse-operator

Now I do not understand why the operator and crd updated here will error, there is no solution

**Comment by Slach** [comment]
It solution cause new CRDs define status as subresources.

Compare your current CRDs with
 https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml

**Comment by czhfe** [comment]
> It solution cause new CRDs define status as subresources.
> 
> Compare your current CRDs with https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml

I upgraded from 0.13.5 to 0.17

**Comment by czhfe** [comment]
Upgrade from clickhouse-operator 0.13.5 to 0.17.0. perform the following steps.
1. Upgrade crd first
2. Upgrade operator and other resources

After the upgrade, modify ClickHouseInstallation CR encountered the following error

![image](https://user-images.githubusercontent.com/19341806/147631785-d3da9b61-58fa-455a-a977-fab49b17bf00.png)

**Comment by Slach** [comment]
Do you have `status` in your edited resource? If yes, please remove this sections and try to save

Could you share the following command results?
```bash
kubectl get chi -n ch1 clickhouse -o yaml
```

**Comment by czhfe** [comment]
> Do you have in your edited resource? If yes, please remove this sections and try to save`status`
> 
> Could you share the following command results?
> 
> ```shell
> kubectl get chi -n ch1 clickhouse -o yaml
> ```

Yes, I have tested this before by deleting the `status` section and trying to save it later, but the result is still the same.

**Comment by czhfe** [comment]
Problem recurrence：
The /spec/templating/policy in the clickhouseinstallations.clickhouse.altinity.com CRD prior to version 0.16.0 did not have its default value explicitly defined, resulting in that default value being "".
The clickhouseinstallations.clickhouse.altinity.com CRD was upgraded in version 0.16.0 of the clickhouse operator (this can be seen in the release notes in RELEASES).
In version 0.16.0 and later /spec/templating/policy was changed to be configurable as auto or manual, with the default value being manual. clickhouseinstallations.clickhouse.altinity.com before 0.16.0
CR before 0.16.0 did not explicitly define that the /spec/templating/policy field would be added automatically, so clickhouse operators and CRD versions after 0.16.0 cannot automatically update the /spec/templating/policy field, which would block
clickhouse operator to update the CR for clickhouseinstallations.clickhouse.altinity.com, which causes an error

**Comment by czhfe** [comment]
Problem recurrence：




The /spec/templating/policy in the clickhouseinstallations.clickhouse.altinity.com CRD prior to version 0.16.0 did not have its default value explicitly defined, resulting in that default value being "".
The clickhouseinstallations.clickhouse.altinity.com CRD was upgraded in version 0.16.0 of the clickhouse operator (this can be seen in the release notes in RELEASES).
In version 0.16.0 and later /spec/templating/policy was changed to be configurable as auto or manual, with the default value being manual. clickhouseinstallations.clickhouse.altinity.com before 0.16.0
CR before 0.16.0 did not explicitly define that the /spec/templating/policy field would be added automatically, so clickhouse operators and CRD versions after 0.16.0 cannot automatically update the /spec/templating/policy field, which would block
clickhouse operator to update the CR for clickhouseinstallations.clickhouse.altinity.com, which causes an error

**Comment by alex-zaitsev** [comment]
Should be fixed in earlier released, but additional rules were added at https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.22.1
