### ISSUE TITLE
ClickHouse Operator not able to watch ClickHouseOperatorConfiguration Resources

### ISSUE THREAD

**Issue by mcgrawia** [Altinity/clickhouse-operator#843]
Hi operator team,

We recently just upgraded our operator to 0.17 using the latest install bundle yaml and we noticed this warning log in the operator:
```bash
W1026 16:29:43.261016       1 reflector.go:436] pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseOperatorConfiguration ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"ClickHouseOperatorConfiguration\" is registered for version \"clickhouse.altinity.com/v1\" in scheme \"pkg/client/clientset/versioned/scheme/register.go:30\"") has prevented the request from succeeding
```

Our operator seems to be functioning normally but unsure if this is cause for concern?

I've noticed in the source code, the api doesn't seem to be registered for the ClickHouseOperatorConfiguration type in this function:
https://github.com/Altinity/clickhouse-operator/blob/9731c23e49b32688ae13e68156d6037be9e0ce5d/pkg/apis/clickhouse.altinity.com/v1/register.go#L48-L58

Thanks for the help

**Comment by sunsingerus** [comment]
@mcgrawia thanks for notification! Next operator version is under development ATM and this issue would be fixed. Please wait for operator 0.18.0 to come.

**Comment by mcgrawia** [comment]
Ok will do. Thanks @sunsingerus!

**Comment by sunsingerus** [comment]
Version 0.18.0 of the operator is about to be released, which has this issue fixed. It is stable enough, so feel free to test.
