### ISSUE TITLE
When I create the table, there is no uuid in the generated sql file, only the table name

### ISSUE THREAD

**Issue by qilitang** [Altinity/clickhouse-operator#845]
- In /var/lib/clickhouse/metadata
> ├── default
├── default.sql
├── information_schema
├── INFORMATION_SCHEMA
├── information_schema.sql
├── INFORMATION_SCHEMA.sql
├── oneclick
 │   ├── visits_v1_all.sql
 │   └── visits_v1.sql
├── oneclick.sql
├── system -> /var/lib/clickhouse/store/d93/d93ac840-7cf3-46d3-993a-c8407cf3e6d3/
└── system.sql

- cat oneclick/visits_v1.sql
>ATTACH TABLE visits_v1
(
     `CounterID` UInt32,
    `StartDate` Date
    ......
)
ENGINE = CollapsingMergeTree(Sign)
PARTITION BY toYYYYMM(StartDate)
ORDER BY (CounterID, StartDate, intHash32(UserID), VisitID)
SAMPLE BY intHash32(UserID)
SETTINGS index_granularity = 8192

-  If you use local installation, the created table has UUID
>ATTACH TABLE _ UUID 'af69a8b8-8d57-49d9-af69-a8b88d57a9d9'
(
     `CounterID` UInt32,
    `StartDate` Date
    ......
)
ENGINE = CollapsingMergeTree(Sign)
PARTITION BY toYYYYMM(StartDate)
ORDER BY (CounterID, StartDate, intHash32(UserID), VisitID)
SAMPLE BY intHash32(UserID)
SETTINGS index_granularity = 8192

**Comment by Slach** [comment]
`clickhouse-operator` prefers Ordinary Database Engine, and modern version `clickhouse-server` setup Atomic by default
https://clickhouse.com/docs/en/engines/database-engines/atomic/

look details on https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-bundle.yaml#L3455-L3463
If you will to run `CREATE DATABASE oneclick ENGINE=Atomic;`
you will achieve the same behavior

**Comment by olexiyb** [comment]
This is not enough, you also need to override default engine to be `Atomic`. Otherwise when you add new replicate any existing database will replicate with engine `Ordinary`. 

```
spec:
  configuration:
    profiles:
      default/default_database_engine: Atomic
```

**Comment by qilitang** [comment]
> This is not enough, you also need to override default engine to be `Atomic`. Otherwise when you add new replica any existing database will replicate with engine `Ordinary`.
> 
> ```
> spec:
>   configuration:
>     profiles:
>       default/default_database_engine: Atomic
> ```

thank you very much
