### ISSUE TITLE
<Error> void DB::StorageKafka::threadFunc(): Code: 252, e.displayText() = DB::Exception: Too many partitions for single INSERT block (more than 100).

### ISSUE THREAD

**Issue by surajmachamasi** [Altinity/clickhouse-operator#851]
i am getting this error several times. what could be the main issue and how to fix this isse.

**Comment by surajmachamasi** [comment]
<Error> void DB::StorageKafka::threadFunc(): Code: 252, e.displayText() = DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception.

**Comment by Slach** [comment]
Issue is not related to clickhouse-operator
you have wrong PARTITION BY clause in your tables
