### ISSUE TITLE
Operator support for ARM64 

### ISSUE THREAD

**Issue by michaelhyatt** [Altinity/clickhouse-operator#852]
Currently, there are no `arm64` published binaries for the operator, so I tried to build it myself on Raspberry Pi running Ubuntu 64-bit server and the build fails on the UBI image mentioned in the [Dockerfile](https://github.com/Altinity/clickhouse-operator/blob/master/dockerfile/operator/Dockerfile#L28).

Replacing the image with `FROM almalinux:7-minimal AS ubi7` seems to be the way to fix it, since RHEL doesn't release arm64 images for their UBI7 images.

**Comment by Slach** [comment]
Not yet released 0.18.0 (in active development) available for ARM64 and switched to ubi8
https://hub.docker.com/r/altinity/clickhouse-operator/tags?page=1&name=0.18

try to 
```bash
kubectl -f https://github.com/Altinity/clickhouse-operator/raw/0.18.0/deploy/operator/clickhouse-operator-install-bundle.yaml
```
