### ISSUE TITLE
Exclude INFORMATION_SCHEMA and information_schema from `schemer.go`

### ISSUE THREAD

**Issue by sozenh** [Altinity/clickhouse-operator#854]
I am using clickhouse-operator 0.16.0 for test. And I got a question during the test.

Prerequisite: My CHI is using high version ClickHouse, altinity/clickhouse-server:latest
Result: Since the high version of clickhouse introduced database information_schema, I found that the operator would read the table in the information_schema and rebuild it under the default database.

Why does this happen？
Looking forward to your reply, Thanks.

**Comment by Slach** [comment]
Yes, it's a bug and should be fixed on 0.18.0

**Comment by alex-zaitsev** [comment]
@su-houzhen , It is fixed in 0.17.0 already. See https://github.com/Altinity/clickhouse-operator/releases/tag/0.17.0
