### ISSUE TITLE
http: panic serving 127.0.0.1:56586: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wangqinghuan** [Altinity/clickhouse-operator#858]
1. Install Clickhouse  cluster successfully, I can connect clickhouse-server using clickhouse-client.
 
![image](https://user-images.githubusercontent.com/22762150/148783005-940be1c9-b256-4b9a-b270-f7ae4696f284.png)
sudo microk8s kubectl  get services
![image](https://user-images.githubusercontent.com/22762150/148783095-e2b5440f-f112-4ad4-9702-a16c7ad67e56.png)
sudo microk8s kubectl  get pods
![image](https://user-images.githubusercontent.com/22762150/148783877-096d3580-aef3-496c-9a10-e4f7891d00e8.png)
clickhouse-client -h 192.168.0.105  -u clickhouse_operator --password clickhouse_operator_password
![image](https://user-images.githubusercontent.com/22762150/148783640-8a33b1ee-05bb-45df-8cf7-d92a704c3875.png)
2. However,  error 'alert:Error retrieving CHIs: TypeError: Failed to fetch: undefined' appears when click 'Clickhouse Installations'.
![image](https://user-images.githubusercontent.com/22762150/148782961-0a6a0f3d-0312-4978-90a9-757193e543c7.png)
backend error 
> 2022-01-10 22:33:08.478250 I | http: panic serving 127.0.0.1:57410: runtime error: invalid memory address or nil pointer dereference
> goroutine 371 [running]:
> net/http.(*conn).serve.func1(0xc000269cc0)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:1805 +0x153
> panic(0x15a9f20, 0x3b31b80)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/runtime/panic.go:971 +0x499
> github.com/altinity/altinity-dashboard/internal/api.getPVCsFromPod(0x0, 0x0, 0x0, 0x0, 0xc000a379a0, 0x1e, 0xc000a379c0, 0x1d, 0xc000a17619, 0x7, ...)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/internal/api/api_k8s.go:77 +0x410
> github.com/altinity/altinity-dashboard/internal/api.getPodsFromK8sPods(0xc00028d1f0, 0x7, 0xc0006c6b40, 0xc00028d1f0, 0x0, 0x0)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/internal/api/api_k8s.go:126 +0x158
> github.com/altinity/altinity-dashboard/internal/api.(*ChiResource).getCHIs.func3(0xc0009b2b80, 0x0, 0x0)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/internal/api/chi.go:149 +0x234
> github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkClusters(0xc0006c74b8, 0xc0006c6f68, 0x0, 0x3b81778, 0x10b)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:226 +0xd2
> github.com/altinity/altinity-dashboard/internal/api.(*ChiResource).getCHIs(0x3b81778, 0xc000928dc0, 0xc00025db20)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/internal/api/chi.go:137 +0x888
> github.com/emicklei/go-restful/v3.(*Container).dispatch(0xc0004ceb40, 0x31da500, 0xc000542620, 0xc0001dc000)
> 	/home/runner/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.7.1/container.go:302 +0x777
> net/http.HandlerFunc.ServeHTTP(0xc0004a84b0, 0x31da500, 0xc000542620, 0xc0001dc000)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:2050 +0x44
> net/http.(*ServeMux).ServeHTTP(0xc00049ef40, 0x31da500, 0xc000542620, 0xc0001dc000)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:2429 +0x1ad
> github.com/altinity/altinity-dashboard/internal/auth.(*Handler).ServeHTTP(0xc00003aea0, 0x31da500, 0xc000542620, 0xc0001dc000)
> 	/home/runner/work/altinity-dashboard/altinity-dashboard/internal/auth/auth_handler.go:33 +0x2f2
> net/http.serverHandler.ServeHTTP(0xc000262ee0, 0x31da500, 0xc000542620, 0xc0001dc000)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:2868 +0xa3
> net/http.(*conn).serve(0xc000269cc0, 0x31dd000, 0xc0009f4cc0)
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:1933 +0x8cd
> created by net/http.(*Server).Serve
> 	/opt/hostedtoolcache/go/1.16.12/x64/src/net/http/server.go:2994 +0x39b
>

**Comment by Slach** [comment]
Issue is not related to `clickhouse-operator` itself

let fire it on https://github.com/Altinity/altinity-dashboard
