### ISSUE TITLE
0.17.0 Config excludeFromPropagationAnnotations not excluding annotations for various created resources

### ISSUE THREAD

**Issue by tanenbaum** [Altinity/clickhouse-operator#859]
If I set up a CHOP with config.yaml containing:

```
excludeFromPropagationAnnotations: ["foo"]
```
and a CHI with metadata like:

```
metadata:
  annotations:
    foo: bar
```
I would expect all created resources to be without the "foo" annotation. 

I actually find that the StatefulSets, ConfigMaps, PVCs and host specific Services have the annotation.

Tracing through the code, I think https://github.com/Altinity/clickhouse-operator/blob/dc6cdc6f2f61fc333248bb78a8f8efe792d14ca2/pkg/model/annotator.go#L112 is where the problem lies. 

```
func (a *Annotator) getHostScope(host *chiv1.ChiHost) map[string]string {
	return a.appendCHIProvidedTo(host.GetAnnotations())
}
```
Any function using `getHostScope` ends up with all the CHI annotations as `a.appendCHIProvidedTo(host.GetAnnotations())` is passing in the CHI annotations that take precedence over any of the exclusions. Other similar functions here use `a.appendCHIProvidedTo(nil)` instead.

Perhaps `(a *Annotator) appendCHIProvidedTo(dst map[string]string)` should not take an argument here, as there are no defaults used as there are with labels and therefore should always be `nil`.

**Comment by sunsingerus** [comment]
This issue was addressed in 0.18.2 version, please check

**Comment by tanenbaum** [comment]
I will be testing this change soon (next day or so). I'll get back to you
asap.

**Comment by alex-zaitsev** [comment]
Fixed in  https://github.com/Altinity/clickhouse-operator/releases/tag/0.18.2
