### ISSUE TITLE
support clickhouse-backup by operator

### ISSUE THREAD

**Issue by su-houzhen** [Altinity/clickhouse-operator#862]
Do we have plans to support cluster backup and restore functionality with built-in clickhouse-backup?
I have some ideas for this, and if you feel it fits, I will start coding and Pull requests.
Here are my thoughts, look forward to your reply.

1. Add `ClickHouse-Backup` container to the pod and expose some backup configuration. (By adding some CHI configuration or just use pod templates).
2. Add a CRD named 'ClickHouseBackup'.
3. When we deploy  a `ClickHouseBackup` CR, operator will create a Kubernetes Job / CronJob for the backup task.
4. Because `ClickHouse-Backup` does not support automatic cluster backup, we need to do some work with Kubernetes Job so that it works for cluster.
5. Add several CHI configurations so that we can require recovery from backups when create cluster.

**Comment by Slach** [comment]
We already have some examples how to use `clickhouse-backup` together with `clickhouse-operator`
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

Could you explain what exactly do you mean when say `cluster backup`?

**Comment by Slach** [comment]
Your approach looks promising!
feel free to make PRs

**Comment by su-houzhen** [comment]
@Slach 
What I mean is that the deployment of Job / CronJob is automatically performed by the operator. We only need to specify the address (CHI, namespace) of the cluster we want to backup when deploying the `clickhousebackup` CR.

At the same time, In my opinion, in this example https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes, we assume that the replicas in the shard only use replicatedMergeTree, so we only need to select one node in the shard for backup. Is it right?
This backup is problematic if we use a `Distributed + MergeTree` replica scheme, or if some nodes only have local tables.
So when I deal with cluster backups, I do backups on all nodes. But for replicas in the same shard, I would only choose one replica to backup `replicatedMergeTree` 's table data. So I need also to submit a PR to `clickhouse-backup` to support filter table by engine when backup.

This is my idea, feel free to enlighten me.

**Comment by Slach** [comment]
> we assume that the replicas in the shard only use replicated*MergeTree, so we only need to select one node in the shard for backup. Is it right?

Yes, but first replicas from shard selected only for example
we can select all replicas instead of first one

I think we can define clickhouse-backup CronJob related configurations and schedule rules inside `spec` field for `kind: ClickHouseBackup` custom resource

> So I need also to submit a PR to clickhouse-backup to support filter table by engine when backup.
PR to clickhouse-backup with e2e tests also welcome!

**Comment by su-houzhen** [comment]
Thanks. I will start coding for this.

**Comment by seuf** [comment]
Hi,
I've setup an automated incremental backup on GCS. But now I want to try to restore it to another clickhouse instance.
Is it possible ? Can you add an example in the documentation how to do this ?

**Comment by Slach** [comment]
@seuf  look https://github.com/Altinity/clickhouse-backup/commit/864bdb3ed76bd8a77017f5436154d058991ba75b

you could use kind: Job for one time restore
```yaml
# example to restore latest backup
apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-backup-restore
spec:
  backoffLimit: 0
  template:
    metadata:
      name: clickhouse-backup-restore
      labels:
        app: clickhouse-backup-restore
    spec:
      restartPolicy: Never
      containers:
      - name: clickhouse-backup-restore
        image: clickhouse/clickhouse-client:latest
        imagePullPolicy: IfNotPresent
        env:
          # use all replicas in each shard to restore schema
          - name: CLICKHOUSE_SCHEMA_RESTORE_SERVICES
            value: chi-test-backups-default-0-0,chi-test-backups-default-0-1,chi-test-backups-default-1-0,chi-test-backups-default-1-1
          # use only first replica in each shard to restore data
          - name: CLICKHOUSE_DATA_RESTORE_SERVICES
            value: chi-test-backups-default-0-0,chi-test-backups-default-1-0
          - name: CLICKHOUSE_PORT
            value: "9000"
          - name: BACKUP_USER
            value: backup
          - name: BACKUP_PASSWORD
            value: "backup_password"

        command:
        - bash
        - -ec
        - if [[ "" != "$BACKUP_PASSWORD" ]]; then
            BACKUP_PASSWORD="--password=$BACKUP_PASSWORD";
          fi;
          declare -A BACKUP_NAMES;
          CLICKHOUSE_SCHEMA_RESTORE_SERVICES=$(echo $CLICKHOUSE_SCHEMA_RESTORE_SERVICES | tr "," " ");
          CLICKHOUSE_DATA_RESTORE_SERVICES=$(echo $CLICKHOUSE_DATA_RESTORE_SERVICES | tr "," " ");
          for SERVER in $CLICKHOUSE_SCHEMA_RESTORE_SERVICES; do
            LATEST_BACKUP_NAME=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
            if [[ "" == "$LATEST_BACKUP_NAME" ]]; then
              echo "Remote backup not found for $SERVER";
              exit 1;
            fi;
            BACKUP_NAMES[$SERVER]="$LATEST_BACKUP_NAME";
            clickhouse-client -mn --echo -q "INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm ${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
          done;
          for SERVER in $CLICKHOUSE_SCHEMA_RESTORE_SERVICES; do
            while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='restore_remote --schema --rm ${BACKUP_NAMES[$SERVER]}' ORDER BY start DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
              echo "still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
              sleep 1;
            done;
            RESTORE_STATUS=$(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='restore_remote --schema --rm ${BACKUP_NAMES[$SERVER]}'  ORDER BY start DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
            if [[ "success" != "${RESTORE_STATUS}" ]]; then
              echo "error restore_remote --schema --rm ${BACKUP_NAMES[$SERVER]} on $SERVER";
              clickhouse-client -mn --echo -q "SELECT start,finish,status,error FROM system.backup_actions WHERE command='restore_remote --schema --rm ${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
              exit 1;
            fi;
            if [[ "success" == "${RESTORE_STATUS}" ]]; then
              echo "schema ${BACKUP_NAMES[$SERVER]} on $SERVER RESTORED";
              clickhouse-client -q "INSERT INTO system.backup_actions(command) VALUES('delete local ${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
            fi;
          done;
          for SERVER in $CLICKHOUSE_DATA_RESTORE_SERVICES; do
            clickhouse-client -mn --echo -q "INSERT INTO system.backup_actions(command) VALUES('restore_remote --data ${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
          done;
          for SERVER in $CLICKHOUSE_DATA_RESTORE_SERVICES; do
            while [[ "in progress" == $(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='restore_remote --data ${BACKUP_NAMES[$SERVER]}' ORDER BY start DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD) ]]; do
              echo "still in progress ${BACKUP_NAMES[$SERVER]} on $SERVER";
              sleep 1;
            done;
            RESTORE_STATUS=$(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='restore_remote --data ${BACKUP_NAMES[$SERVER]}'  ORDER BY start DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
            if [[ "success" != "${RESTORE_STATUS}" ]]; then
              echo "error restore_remote --data ${BACKUP_NAMES[$SERVER]} on $SERVER";
              clickhouse-client -mn --echo -q "SELECT start,finish,status,error FROM system.backup_actions WHERE command='restore_remote --data ${BACKUP_NAMES[$SERVER]}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
              exit 1;
            fi;
            echo "data ${BACKUP_NAMES[$SERVER]} on $SERVER RESTORED";
            if [[ "success" == "${RESTORE_STATUS}" ]]; then
              clickhouse-client -q "INSERT INTO system.backup_actions(command) VALUES('delete local ${BACKUP_NAMES[$SERVER]}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
            fi;
          done

```

**Comment by dbackeus** [comment]
Not sure why this was closed. Seems like the operator should provide more of a seamless backup / restore experience, as other operators tend to do. Maybe I missed some new feature providing this functionality?

At operator-hub this operator claims a "Full Lifecycle" level feature set (https://operatorhub.io/operator/clickhouse). The definition of Full Lifecycle is that the operator should handle backup / restores: https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-3---full-lifecycle

**Comment by dbackeus** [comment]
Thanks for the link, we can certainly use this documentation to arrange for backups.

At the same time, I don't think us manually implementing a sidecar process or cronjob using documentation from a separate project fulfils the idea of the `clickhouse-operator` managing the backup / restore process for us.

Tighter integration including CRD definitions to enable backups could be a nice improvement.

**Comment by Slach** [comment]
@dbackeus don't be shy to make pull request, we open to contributions

**Comment by macrokernel** [comment]
See how backups are implemented in CloudnativePG operator: easy to set up scheduled backups  or restore using the operator CRDs.
