### ISSUE TITLE
How to disable public access of 'clickhouse_operator' user

### ISSUE THREAD

**Issue by vanducvo** [Altinity/clickhouse-operator#865]
I try to change network ip range of pod but `clickhouse_operator` but it until access form public network.
How I can allow `clickhouse_operator` user only access in k8s network?

**Comment by alex-zaitsev** [comment]
@vanducvo , look at https://github.com/Altinity/clickhouse-operator/blob/master/config/users.d/01-clickhouse-user.xml

You can change this, it is deployed a configmap, and restart the operator.
