### ISSUE TITLE
Docker Build for 0.18.0 lacking 

### ISSUE THREAD

**Issue by johnhummelAltinity** [Altinity/clickhouse-operator#874]
When I attempted to build `clickhouse-operator 0.18.0` through the docker build instructions I encountered the following:

```bash
docker build -t altinity/clickhouse-operator -f ./dockerfile/operator/Dockerfile ./
Sending build context to Docker daemon  4.709MB
Step 1/39 : FROM --platform=${BUILDPLATFORM} golang:1.17 AS builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```

I was able to get to work by downloading 0.17.0 and running the same instructions - any other steps that we need?

**Comment by Slach** [comment]
for Support `ARM64` you should use 
`docker buildx` instead of `docker build`
look to 
https://github.com/Altinity/clickhouse-operator/blob/master/dev/image_build_universal.sh#L29-L45
for examples

**Comment by Slach** [comment]
let me explain
now, Dockerfile have multiplatform instructions `--platform`

for support new Dockerfile format
you should use 
docker buildx with qemu emulation
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

or some other docker builders which support `buildkit` properly

you need to update your docker (19.10+), and create `docker buildx create --use`

@vzakaznikov could you upgrade your python code according to
https://github.com/Altinity/clickhouse-operator/blob/master/dev/image_build_universal.sh#L29-L45 ?
