### ISSUE TITLE
clickhouse metrics not getting || Wrong Hostname

### ISSUE THREAD

**Issue by sanjeev3d** [Altinity/clickhouse-operator#876]
I'm not able to get any metric from clickhouse operator it seems 
fetching wrong hostname="chi-cliff-cliffcluster-replica0-shard1.click.svc.cluster.local",

It would be like chi-cliff-cliffcluster-replica0-shard1.click.svc.uhn7klr2c.local
Not getting option in operator to change same

Error log
`[sanjeev.gautam@lab.rmn.local@uhn5klbjhmgmt-p ~]$ curl -g -v -6 http://[240b:c0e0:102:553e:b4c4:2:0:44d8]:8888/metrics
* About to connect() to 240b:c0e0:102:553e:b4c4:2:0:44d8 port 8888 (#0)
*   Trying 240b:c0e0:102:553e:b4c4:2:0:44d8...
* Connected to 240b:c0e0:102:553e:b4c4:2:0:44d8 (240b:c0e0:102:553e:b4c4:2:0:44d8) port 8888 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: [240b:c0e0:102:553e:b4c4:2:0:44d8]:8888
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Thu, 03 Feb 2022 06:00:36 GMT
< Transfer-Encoding: chunked
<
# HELP chi_clickhouse_metric_fetch_errors status of fetching metrics from ClickHouse 1 - unsuccessful, 0 - successful
# TYPE chi_clickhouse_metric_fetch_errors gauge
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica0-shard1.click.svc.cluster.local",namespace="click"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica0-shard1.clickhouse.svc.cluster.local",namespace="clickhouse"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica0-shard2.click.svc.cluster.local",namespace="click"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica0-shard2.clickhouse.svc.cluster.local",namespace="clickhouse"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica1-shard1.click.svc.cluster.local",namespace="click"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica1-shard1.clickhouse.svc.cluster.local",namespace="clickhouse"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica1-shard2.click.svc.cluster.local",namespace="click"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system parts",hostname="chi-cliff-cliffcluster-replica1-shard2.clickhouse.svc.cluster.local",namespace="clickhouse"} 1
chi_clickhouse_metric_fetch_errors{chi="cliff",fetch_type="system.detached_parts",hostname="chi-cliff-cliffcluster-replica0-shard1.click.svc.cluster.local",namespace="click"} 1`

**Comment by sanjeev3d** [comment]
curl -g -v -6 http://[240b:c0e0:102:553e:b4c4:2:0:4b8c]:8123/ping

is working with pod IP

**Comment by alex-zaitsev** [comment]
@sanjeev3d , try defining your own rule for domain names:

https://github.com/Altinity/clickhouse-operator/blob/20ad7099b5b00402b53de35a9825e0cdcb66df85/docs/chi-examples/99-clickhouseinstallation-max.yaml#L21
