### ISSUE TITLE
remove clickhouse operator metrics for deleted clickhouse cluster

### ISSUE THREAD

**Issue by kanlee** [Altinity/clickhouse-operator#879]
Hi,  thank you for making clickhouse operator available.  It's been really helpful.  I am monitoring clickhouse operator metrics with prometheus and grafana.  I noticed that after I deleted an old clickhouse test cluster.  It's still showing up in my clickhouse operator metrics.  Is there a way to remove that from my clickhouse operator metrics?   Thank you

**Comment by kanlee** [comment]
thank you for the quick response!  I deleted all the pods, services, PVCs associated with my cluster but didn't delete the ClickhouseInstallation resource.   After deleting that, it stopped showing up in my clickhouse-operator-metrics.   Also does this mean that the best way to remove a old cluster is to just delete the ClickhouseInstallation resource and all the associated pods, services, PVCs will be deleted as well?  Thank you

**Comment by Slach** [comment]
> Also does this mean that the best way to remove a old cluster is to just delete the ClickhouseInstallation resource and all the associated pods, services, PVCs will be deleted automatically after? 

yes, exactly, `clickhouse-operator` will remove all PVC, Statefulset and related ConfigMaps after delete custom

look to ` kubectl explain chi.spec.templates.volumeClaimTemplates`
to figure out how you can define `reclaimPolicy: Retain` in `volumeClaimTemplates[]`, to avoid lost your data for case when you delete `chi` mistakenly
