### ISSUE TITLE
When Delete chi, can not delete pod and sts. use 0.18.0

### ISSUE THREAD

**Issue by qilitang** [Altinity/clickhouse-operator#881]
I created cluster by 0.18.0 
when i delete chi,  chi is deleted , but  pod and sts is not deleted .

**Comment by alex-zaitsev** [comment]
@qilitang , how do you delete the chi?

**Comment by qilitang** [comment]
> 
kubectl delete chi <chiname>

**Comment by qilitang** [comment]
> @qilitang , how do you delete the chi?

│   Info  CreateStarted        85s    clickhouse-operator  Adding tables on shard/host:1/0 cluster:little-cluster
│   Info  UpdateCompleted      85s    clickhouse-operator  Update Service default/chi-volume-hostpath-little-cluster-1-0
│   Info  UpdateCompleted      85s    clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-common-configd
│   Info  ReconcileCompleted   85s    clickhouse-operator  Reconcile Host 1-0 completed
│   Info  UpdateCompleted      84s    clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-common-configd
│   Info  ReconcileInProgress  84s    clickhouse-operator  remove items scheduled for deletion
│   Info  ReconcileInProgress  83s    clickhouse-operator  add CHI to monitoring
│   Info  ReconcileInProgress  83s    clickhouse-operator  remove items scheduled for deletion
│   Info  ReconcileCompleted   82s    clickhouse-operator  reconcile completed
│   Info  UpdateCompleted      63s    clickhouse-operator  Update Service default/clickhouse-volume-hostpath
│   Info  UpdateCompleted      63s    clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-common-configd
│   Info  UpdateCompleted      63s    clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-common-usersd
│   Info  UpdateCompleted      63s    clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-deploy-confd-little-cluster-0-0
│   Info  ReconcileStarted     63s    clickhouse-operator  Reconcile Host 0-0 started
│   Info  ReconcileStarted     63s    clickhouse-operator  reconcile started
│   Info  CreateStarted        62s    clickhouse-operator  Update StatefulSet(default/chi-volume-hostpath-little-cluster-0-0) - started
│   Info  ReconcileStarted     2s     clickhouse-operator  Reconcile Host 1-0 started
│   Info  ReconcileCompleted   2s     clickhouse-operator  Reconcile Host 0-0 completed
│   Info  UpdateCompleted      2s     clickhouse-operator  Update Service default/chi-volume-hostpath-little-cluster-0-0
│   Info  UpdateCompleted      2s     clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-common-configd
│   Info  UpdateCompleted      2s     clickhouse-operator  Update StatefulSet(default/chi-volume-hostpath-little-cluster-0-0) - completed
│   Info  CreateStarted        2s     clickhouse-operator  Adding tables on shard/host:0/0 cluster:little-cluster
│   Info  UpdateCompleted      2s     clickhouse-operator  Update ConfigMap default/chi-volume-hostpath-deploy-confd-little-cluster-1-0
│   Info  CreateStarted        1s     clickhouse-operator  Update StatefulSet(default/chi-volume-hostpath-little-cluster-1-0) - started

this is describe chi

**Comment by qilitang** [comment]
> @qilitang , how do you delete the chi?

│ I0209 07:11:34.749931       1 announcer.go:229] clear():default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:Non-reconciled objects:
│ I0209 07:11:34.749957       1 announcer.go:231] clear():default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:remove items scheduled for deletion
│ I0209 07:11:34.977748       1 announcer.go:231] worker.go:406:dropReplicas():start:default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:drop replicas based on AP
│ I0209 07:11:34.977792       1 announcer.go:229] worker.go:427:dropReplicas():end:default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:processed replicas: 0
│ I0209 07:11:34.977809       1 announcer.go:231] includeStopped():default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:add CHI to monitoring
│ I0209 07:11:35.737357       1 announcer.go:231] markReconcileComplete():default/volume-hostpath/d0603344-d1c0-45bc-992e-2f9999a7b9c4:reconcile completed

this log operator

**Comment by qilitang** [comment]
> @qilitang , how do you delete the chi?

It's my  problem . I  modify some code . 
Извините .
