### ISSUE TITLE
Change ClusterRoleBinding to RoleBinding

### ISSUE THREAD

**Issue by jmpdt** [Altinity/clickhouse-operator#891]
The operator currently requires the role "cluster-admin" which grants full permissions to the entire cluster. Could this be changed to simply a RoleBinding to limit permissions to the namespace where the operator is deployed? I'd like to run this on an enterprise K8s platform and cannot a cluster-wide role. Thank you!

**Comment by Slach** [comment]
try to following installation method

```
curl -sL https://github.com/Altinity/clickhouse-operator/raw/master/deploy/operator/clickhouse-operator-install-tf.yaml | namespace=your_namespace password=clickhouse_operator_password envsubst "${namespace} ${password}"
```
