### ISSUE TITLE
Failed to start the Clickhouse Server service and connect through 9000 port

### ISSUE THREAD

**Issue by kishorer00** [Altinity/clickhouse-operator#897]
Hi Team,

I have deployed Clickhouse Cluster using Altinity Operator and PODs are running fine.

- Deployment file used : https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml 
- Running Cliskhouse on Microk8s Cluster
- Persistance volume created as per the documentation : https://github.com/Altinity/clickhouse-operator 
- PODs are in Running state 
- Able to connect through kubectl exec -it pods-name 

Issue : - Failed to start the Clickhouse Server service  and connect through 9000 port 
-------
Error : -
------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

root@chi-clickhouse-installation-max-all-counts-1-1-0:/# service clickhouse-server start
Start clickhouse-server service: /etc/init.d/clickhouse-server: 175: ulimit: error setting limit (Operation not permitted)
Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
DONE
root@chi-clickhouse-installation-max-all-counts-1-1-0:/# service clickhouse-server status
clickhouse-server: process unexpectedly terminated
root@chi-clickhouse-installation-max-all-counts-1-1-0:/#

Failed to connect through port 9000 :- 
-------------------------------------------

root@chi-clickhouse-installation-max-all-counts-1-1-0:/# clickhouse-client
ClickHouse client version 20.6.11.1 (official build).
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000)

root@chi-clickhouse-installation-max-all-counts-1-1-0:/#

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

- Do i need start any services ?

Please assist me  ,if anything missing ...

**Comment by Slach** [comment]
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml 
maybe too complicated for your experience

>  service clickhouse-server status

it will not work, cause under Kubernetes clickhouse-server running inside container and don't use `systemd`services

ok. let's remove some unnecessary and attempt to investigate why you can't connect

first
let;'s remove following parts from you `kind: ClickHouseInstallation` manifest

usually your cluster shall be svc.cluster.local, just remove following string
```yaml
 namespaceDomainPattern:  "%s.svc.my.test"
```

remove authorization for your zookeeper, and root node
```yaml
      root: "/path/to/zookeeper/root/node"
      identity: "user:password"
```

if after these changes, you will still not able to connect

please use a simpler example like https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/01-simple-layout-02-1shard-2repl.yaml

and use 

`kubectl explain chi`
to understand how to write custom resources described your clickhouse cluster

**Comment by kishorer00** [comment]
Hi @Slach ,

I just removed the above mentioned lines and deployed the Cluster. Still running into the same issue.

Also, i tried deploying sample Cluster. It's working and able to connect through port 9000. Happy !!!.

Need your Suggestions:-  
-------------------------
Trying build Strong and Robust **Clickhouse Cluster with Persistent volumes** from the deployment files https://github.com/Altinity/clickhouse-operator/tree/master/docs/chi-examples 

Please assist me with the right YAML file for the deployment. So,that i will understand and deploy the same.

Reagrds, Kishore R.

**Comment by Slach** [comment]
@kishorer00 look to
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-05-resizeable-volume-1.yaml#L11-L13

you need define properly StorageClass and need to install to your MikroK8s proper CSI which allow use local disk or deply custom storage provisioner

for example 
```bash
# rancher HostPath CSI provisioner
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
kubectl apply -f ,/local-path-default-storageclass.yaml 
```

**local-path-default-storageclass.yaml** 
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"       
  name: default

provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

```

**Comment by kishorer00** [comment]
@Slach , 

After removing the below content, Able to deploy the Clickhouse Cluster using the deployment file : https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml 

+++++++++++++++++++++++
    hostTemplates:
      - name: host-template-custom-ports
        spec:
          tcpPort: 7000
          httpPort: 7001
          interserverHTTPPort: 7002
+++++++++++++++++++++++

Trying to Use the latest version of Click house databases image. 

++++++++++++++++++++++++++++
   - name: clickhouse-v20.6
        # type PodSpec struct {} from k8s.io/core/v1
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.6
++++++++++++++++++++++++++++

Updated the image , 

image : yandex/clickhouse-server:latest

Getting below Error ,

++++++++++++++++++++++++++++++
  Warning  FailedScheduling  83s                 default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         82s                 default-scheduler  Successfully assigned zoons/chi-clickhouse-installation-max-all-counts-0-0-0 to microk8s2
  Normal   Pulling           82s                 kubelet            Pulling image "yandex/clickhouse-server:latest"
  Normal   Pulled            79s                 kubelet            Successfully pulled image "yandex/clickhouse-server:latest" in 2.5373304s
  Normal   Created           79s                 kubelet            Created container clickhouse
  Normal   Started           79s                 kubelet            Started container clickhouse
  Normal   Pulling           79s                 kubelet            Pulling image "busybox"
  Normal   Pulled            76s                 kubelet            Successfully pulled image "busybox" in 2.403659715s
  Normal   Created           76s                 kubelet            Created container clickhouse-log
  Normal   Started           76s                 kubelet            Started container clickhouse-log
  Warning  Unhealthy         20s (x17 over 68s)  kubelet            Readiness probe failed: Get "http://10.1.101.27:8123/ping": dial tcp 10.1.101.27:8123: connect: connection refused

++++++++++++++++++++++

 Any dependencies?  Is there a way ,i can use the latest click house image?

Please assist me.

**Comment by Slach** [comment]
after change httpPort
you also change `livenessProbe` inside `podTemplates[].spec.containers`

**Comment by Slach** [comment]
What is your goal? why you do all these changes?

**Comment by kishorer00** [comment]
- Planning to build Strong and Robust Clickhouse cluster using Clickhouse Operator with shards and replicas.
- Test the Backup and Restore on the newly deployed Clickhouse cluster.


Regarding livenessProbe :-  
----------------------------
- Just gone through the YAML file ... " livenessProbe" not specified under " podTemplates[].spec.containers."
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml 

+++++++++++++++++++++++++
   - name: clickhouse-v20.6
        # type PodSpec struct {} from k8s.io/core/v1
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.6
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse
+++++++++++++++++++++++++++++

Can you help me with the spec ? Is there any YAML file with "livenessProbe" and "Readiness probe"  ?

**Comment by kishorer00** [comment]
@Slach , I have Clickhouse database running on Docker Evenvirnemt (Running in a container )

Is it possible to take the Backups and Restore it on the Clickhose Cluster built by the Clickhouse Operator?

**Comment by Slach** [comment]
> Planning to build Strong and Robust Clickhouse cluster using Clickhouse Operator with shards and replicas.
So, just remove all unnecessary changes

use something simple  with PersistentVolumes
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-05-resizeable-volume-1.yaml

> Just gone through the YAML file ... " livenessProbe" not specified under " podTemplates[].spec.containers."
cause by default liveness and readyness probes use 8123 port and add inside golang code clickhouse-operator
https://github.com/Altinity/clickhouse-operator/blob/28ca2237ba6419c9ac1019da2e462a8c42a7a919/pkg/model/creator.go#L481-L492

99-clickhouseinstallation-max.yaml it's a just "advanced" example , don't use it if you don't understand what you do

> Test the Backup and Restore on the newly deployed Clickhouse cluster.

use these manifests 
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

> Is it possible to take the Backups and Restore it on the Clickhose Cluster built by the Clickhouse Operator?
Yes it possible
you need run clickhouse-backup create_remote inside your docker
after it run clickhouse-backup restore_remote inside your Kubernetes

**Comment by kishorer00** [comment]
Hi @Slach ,

Thanks a lot for helping ... i am almost there ..

Able to deploy the Cluster using link : https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-05-resizeable-volume-1.yaml 

Below two things blocking me,

1.Issue with while Restoring it in to new Clickhouse cluster 
2.Issue with Zookeeper 

1.Issue with backup and Restore:-  I am missing something ? Using default config.yml file
---------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Backup :- (Running it on Docker container )
------
# ./clickhouse-backup -c config.yml create_remote 'remote-test' --table=abc.*
2022/03/11 07:08:20  info done                      backup=remote-test operation=create table=abc.abc_2019_07_02
2022/03/11 07:08:20  info done                      backup=remote-test operation=create table=abc.nums_temp
2022/03/11 07:08:20  info done                      backup=remote-test duration=945ms operation=create
Upload aborted: RemoteStorage set to "none"      --> Its trying upload the Backup to remote location

Restore :-(Running it on newly created CH Cluster using Operator )
---------
# ./clickhouse-backup -c config.yml restore_remote 'remote-test'
2022/03/11 07:26:55 error remote storage is 'none'        --> Its trying to download from remote location and restore
#
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2.Issue with Zookeeper:-   Unable to Create tables: https://docs.altinity.com/altinitycloud/quickstartguide/yourfirstqueries/
----------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
==> No zookeeper configs,Earlier :- 

Code: 139. DB::Exception: Received from localhost:9000. DB::Exception: There is no Zookeeper configuration in server config. (NO_ELEMENTS_IN_CONFIG)

==> I have added the zookeeper configs from 99-clickhouseinstallation-max.yaml )- :-

Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Cannot use any of provided ZooKeeper nodes (Bad arguments). (KEEPER_EXCEPTION)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Able to Run the below Queries :-
----------------------------
CREATE TABLE t1 (x String) ENGINE = Memory AS SELECT 1;
SELECT x, toTypeName(x) FROM t1;

Failed to run : Create tables: https://docs.altinity.com/altinitycloud/quickstartguide/yourfirstqueries/

**Comment by Slach** [comment]
> Upload aborted: RemoteStorage set to "none"

You not define remote_storage in `/etc/clickhouse-backup/config.yml`

look to
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

you need to define REMOTE_STORAGE environment variable
```yaml
 templates:
      podTemplates:
         - name: clickhouse-backup
         ...
                 clickhouse.backup/path: '/metrics'
           spec:
              ...
              containers:
                 ...
                 - name: clickhouse-backup
                   image: altinity/clickhouse-backup:1.3.1
                   imagePullPolicy: Always
                   command:
                      - bash
                      - -xc
                      - "/bin/clickhouse-backup server"
                   env:         
                   ...
                     - name: REMOTE_STORAGE
                        value: "s3"
```

> There is no Zookeeper configuration

you need to install zookeeper separately
look to https://github.com/Altinity/clickhouse-operator/tree/master/deploy/zookeeper/quick-start-persistent-volume
for examples
after it
define
```yaml
spec:
  configuration:
     zookeeper:
        ...
```
in your CHI manifest

**Comment by kishorer00** [comment]
Able to resolve the DNS issue with the zookeeper.

Only we have Backup and Restore .  Please assist me, How to upload my old backup to the newly created Cluster.

**Comment by kishorer00** [comment]
Hi @Slach ,

Able to deploy the Backup and Restore POD using the link : https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes 

Also, Checking https://github.com/AlexAkulov/clickhouse-backup/issues/286 for more details on Backup and Restore.

**Comment by Slach** [comment]
> Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Cannot resolve any of provided ZooKeeper hosts due to DNS error (Connection loss). (KEEPER_EXCEPTION)

check your  chi zookeeper settings

```
spec:
 configuration:
   zookeeper:
```   

> I am trying to Backup the data from Docker container and Restore it to the newly deployed Kubetnetes Cluster.

Do you run clickhouse-backup create inside docker container or outside?

you can't use restore_remote / create_remote without configure `remote_storage` in /etc/clickhouse-backup/config.yml

**Comment by Slach** [comment]
> Why is the data not syncing automatically between the shards and Replicas?
cause it not easy move data part between one shard to another

i think best solution for you will not use clickhouse-backup

forward 9000 port in your docker to host system (usually use docker-compose ports section or docker -p for it)

after it, 
just create ReplicatedMergeTree and Distributed tables inside clickhouse-operator managed cluster pods, use ON CLUSTER '{cluster}' clause to run distributed DDL

after it,
run `kubectl port-forward ...` and forward 9000:9010 port connection  to one of your pod for shard0 in your host OS

after it,
run in your Host OS where run docker container `clickhouse-client --mn --echo --progress -q "INSERT INTO TABLE FUNCTION remote("localhost:9010", db_name.distributed_table_name) SELECT * FROM db.table"`

**Comment by kishorer00** [comment]
Hi @Slach , 

I have more than 1000 + tables under my database. It's difficult to create all the tables with Specific data types.
If you can suggest me the alternative , that would be grate !!!!.

Also, looking for commands/ scripts to Sync the data to Shards and replicas in other Nodes.

Any Link/docs , how the data stores in Clisckuhouse Cluster?

**Comment by kishorer00** [comment]
Hi @Slach ,

I have tried both ways None of them working ....

1. Run through the command: -
--------------------------

`after it,
run in your Host OS where run docker container clickhouse-client --mn --echo --progress -q "INSERT INTO TABLE FUNCTION remote("localhost:9010", db_name.distributed_table_name) SELECT * FROM db.table"`

Getting connection refused error:- 
-------------------------------------
# clickhouse-client  -mn --echo --progress -q "INSERT INTO TABLE FUNCTION remote("localhost::9001", db_name.distributed_table_name) SELECT * FROM db.table" 
Code: 210. DB::NetException: Connection refused (localhost:9000)

- Hence Clickhouse is running inside the container, Its not able to connect to the Database from HOST OS.
- Also, tried running the above command from the Clickhouse container - Getting DNS error 
- Kubernetes cluster is on a different host, not sure it will INSERT the data remotely  - I think, we are missing something ...

2. Run through clickhouse-backup: -

- It's able to create databases and tables(only schema's ) but failed to load the data 
- Below are two engine types.

""engine": "Atomic"
"engine": "Ordinary","

Appreciate your help hear !!!.

**Comment by kishorer00** [comment]
@Slach ,  Any comments on the above? 

Able to Build the Clickhouse Culter but not able to use ..pls check it once.
