### ISSUE TITLE
Migration of Entire ClickHouse from Debian system to Google Kubernetes Engine

### ISSUE THREAD

**Issue by pdsaiteja** [Altinity/clickhouse-operator#900]
Hi Team,

We need to migrate a CH server which contains lots of data in Debian OS system. We need to migrate this server along with complete data to newly created GKE cluster. Could not find any proper documentation for this., please help me with the process for it.

Thanks,
Sai Teja

**Comment by Slach** [comment]
Call `kubectl apply -f your_kind_ClickHouseInstallation_manifest.yaml` and deploy cluster with empty data 
look to
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-01-default-volume.yaml
as minimal working sample

After it, you can have the following variants:
1. copy data with `INSERT INTO ... SELECT ... FROM remote()`
  * read documentation https://clickhouse.com/docs/en/sql-reference/table-functions/remote/
  * create your table schema on GKE cluster with `ReplicatedMergeTree` and `Distributed` table engine
  * execute `INSERT INTO distributed_table SELECT ... FROM remote(...)` on your GKE cluster, you can use

2. copy data with using clickhouse-copier
look to documentation https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier/ and https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-data-migration/altinity-kb-clickhouse-copier/
