### ISSUE TITLE
clickhouse-keeper example, SERVERS value

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#901]
Hi, in your clickhouse-keeper 3 node example, the SERVERS value is set to 1. Shouldn't that be set to 3?

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml#L134

Thanks!

**Comment by Slach** [comment]
Good catch, Yes it shall be 3, thanks a lot for reporting, could you make pull request?

**Comment by a-dot** [comment]
Done: https://github.com/Altinity/clickhouse-operator/pull/902

I pointed the PR to master because it does not contain any code modification. Thanks!!
