### ISSUE TITLE
Automatic schema propagation does not propagate everything

### ISSUE THREAD

**Issue by macobo** [Altinity/clickhouse-operator#903]
## Context

This chart mentions one feature:
> ClickHouse cluster scaling including **automatic schema propagation**

The behavior of this feature did not match my expectations.

## Current behavior

From @alex-zaitsev via Slack:

> Only Distributed tables and related local tables were created on a second shard [added after the fact]

This means tables which are not automatically propagated include:
- ReplicatedMergeTree tables _without_ Distributed tables (e.g. tables not using sharding)
- Kafka engine tables
- Materialized views
- Non-replicated tables

## Desired behavior

New shards should copy the full schema for everything affecting ingestion. In our usecase, this includes:

- ReplicatedMergeTree tables _without_ Distributed tables (e.g. tables not using sharding)
- Kafka engine tables
- Materialized views

Note wee'd be okay if other tables/whole schema got replicated.

As a minimum some capability to mark some tables as "to propagate" would be great.

**Comment by macobo** [comment]
@alex-zaitsev reading the release notes of 0.19.0 I _think_ this can be closed? Haven't tested the behavior though.

**Comment by alex-zaitsev** [comment]
It was fixed while ago
