### ISSUE TITLE
clickhouse-keeper readiness probe failing

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#904]
It seems like the readiness probe for clickhouse-keeper example is failing because zk_peer_state does not exist in clickhouse-keeper mntr. When a node is a follower zk_peer_state does not exist: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml#L182

Would it be sufficient to just be "ruok" ?

**Comment by Slach** [comment]
@a-dot, looks like 3 nodes is completelly broken ;( sorry for that, 

I tried to remove any readyness, and add only liveness ruok monitor on zookeeper-exporter container, but looks like something wrong with quorum in clickhouse-keeper ;(
continue to figure out

**Comment by a-dot** [comment]
It seems to be a little bit hit or miss but I'm having a semblance of reliability if I leave the livenessProbe for zookeeper-exporter untouched and modify the readinessProbe for clickhouse-keeper to: 
```
OK=$(bash -c 'exec 3<>/dev/tcp/127.0.0.1/2181 && printf \"ruok\" >&3 && timeout 5 cat <&3');
if [[ \"$OK\" == \"imok\" ]];
then
  exit 0;
else
  exit 1;
fi
```

That way all 3 nodes come up and I seem to have quorum. At least I think that's what these messages mean?
```
<Information> RaftInstance: [VOTE_RESP] peer 3 (0), resp term 1, my role candidate, granted 2, responded 2, num voting members 3, quorum 2
[...]
<Debug> KeeperDispatcher: Quorum initialized
```

**Comment by Slach** [comment]
fixed on https://github.com/Altinity/clickhouse-operator/releases/0.18.4
