### ISSUE TITLE
Symlink makes it impossible to import package

### ISSUE THREAD

**Issue by erikdubbelboer** [Altinity/clickhouse-operator#907]
Go doesn't follow symlink in import parts. Because of [this](https://github.com/Altinity/clickhouse-operator/blob/cecb54ad1ade33a9d748a0108e765abad9b2412e/pkg/client) symlink it is now impossible to import this package:
```sh
% cat main.go
package main

import "github.com/altinity/clickhouse-operator/pkg/apis/metrics"

func main() {
	_ = metrics.NewExporter
}

% go mod tidy
go: finding module for package github.com/altinity/clickhouse-operator/pkg/apis/metrics
go: found github.com/altinity/clickhouse-operator/pkg/apis/metrics in github.com/altinity/clickhouse-operator v0.0.0-20220307063955-cecb54ad1ade
go: finding module for package github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned
example imports
	github.com/altinity/clickhouse-operator/pkg/apis/metrics imports
	github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned: module github.com/altinity/clickhouse-operator@latest found (v0.0.0-20220307063955-cecb54ad1ade), but does not contain package github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned
```

I suggest that all import statements get changed to the new path. I don't see any reason to keep the old imports and have this symlink in place.

**Comment by erikdubbelboer** [comment]
The clickhouse prometheus endpoint doesn't expose enough to make the Altinity alerts config work. What is the harm in making it possible to import code from this package? We have successfully done this for the last year. The only thing that needs to change now is this symlink.

**Comment by Slach** [comment]
> What is the harm in making it possible to import code from this package
We could change it in future and not have resource to maintain it as library with backwards compatibility

**Comment by erikdubbelboer** [comment]
You don't have to guarantee backwards compatibility. I don't care if you break backwards compatibility, people can just change their code to match your changes. But being able to import in the past and not being able to import now is annoying.

**Comment by sunsingerus** [comment]
code generator reworked
please check 0.23.3 version
hope it helps
