### ISSUE TITLE
Blocking Vulnerability for 0.18.3 Images

### ISSUE THREAD

**Issue by mcgrawia** [Altinity/clickhouse-operator#913]
Hi Altinity team,

Similar to #766, my organization has flagged [a vulnerability](https://access.redhat.com/errata/RHSA-2022:0896) in the 0.18.3 images that are preventing us from upgrading. I see RedHat has already fixed the vulnerability in the base image. Would it be possible to kick off another build for 0.18.3 to take advantage of the patched base image?

Thanks!

**Comment by alex-zaitsev** [comment]
Thanks @mcgrawia , we are working on an update

**Comment by mcgrawia** [comment]
Hey @alex-zaitsev, have there been any updates on this? I was hoping it should just be a quick re-run of the CICD pipeline to rebuild the image.

**Comment by alex-zaitsev** [comment]
@mcgrawia , check 0.18.4. The fix is going to be released as a new minor version.

**Comment by mcgrawia** [comment]
Thanks @alex-zaitsev, will look for that when it's released

**Comment by alex-zaitsev** [comment]
Released in https://github.com/Altinity/clickhouse-operator/releases/tag/0.18.4

**Comment by mcgrawia** [comment]
Thanks @alex-zaitsev!
