### ISSUE TITLE
E0508 Exec():FAILED ...table already exists

### ISSUE THREAD

**Issue by gauravphoenix** [Altinity/clickhouse-operator#927]
Is there a way to use CHOP without letting it manage the tables? every now and then I get this error `(REPLICA_IS_ALREADY_EXIST) (version 22.3.2.1)`. The error is harmless but it makes updates really slow as it gets into back-off loop (retries). 

chop version- `0.18.2`

**Comment by Slach** [comment]
do you use {shard} {cluster} {database} {table} and {replica} macros in your `ENGINE=ReplicatedMergeTree`?

**Comment by gauravphoenix** [comment]
yes! we do.

**Comment by Slach** [comment]
could you look to `clickhouse-pod` container log in your clickhouse pod and share full error?
I mean ReplicatedMergeTree `path` patemeter should be unique for different shards and the same for the same shard

Also, could you upgrade clickhouse-operator to 0.18.5?
