### ISSUE TITLE
clickhouse metrics are not working.

### ISSUE THREAD

**Issue by Travonka** [Altinity/clickhouse-operator#933]
Heya!
Im testing clickhouse and trying to export metrics to prometheus, but I only get ` chi_clickhouse_metric_fetch_errors gauge`.
My simple config : 

> apiVersion: "clickhouse.altinity.com/v1"
> kind: "ClickHouseInstallation"
> metadata:
>         name: "clickhouse"
> spec:
>   configuration:
>     zookeeper:
>         nodes:
>         - host: zookeeper.zoo1ns
>           port: 2181
>     clusters:
>       - name: "clickhouse"
>         layout:
>           shardsCount: 1
>           replicasCount: 1
>         templates:
>           podTemplate: clickhouse-stable
>   templates:
>     podTemplates:
>       - name: clickhouse-stable
>         spec:
>           containers:
>           - name: clickhouse
>             image: altinity/clickhouse-server:21.8.15.15.altinitystable

 I might have found the reason, but I don't know how to fix it. 
 If I do `kubectl logs -n kube-system -l app=clickhouse-operator -c metrics-exporter --since=24h | grep -i fail` I get the following thing: 

>  E0516 15:11:54.189120       1 connection.go:83] connect():FAILED Ping(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/). Err: context deadline exceeded
> E0516 15:11:54.189203       1 connection.go:120] QueryContext():FAILED connect(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/) for SQL: SELECT
>         database,
>         table,
>         toString(active)                       AS active,
>         toString(uniq(partition))              AS partitions,
>         toString(count())                      AS parts,
>         toString(sum(bytes))                   AS bytes,
>         toString(sum(data_uncompressed_bytes)) AS uncompressed_bytes,
>         toString(sum(rows))                    AS rows,
>        toString(sum(bytes_on_disk))           AS metric_DiskDataBytes,
>        toString(sum(primary_key_bytes_in_memory_allocated)) AS metric_MemoryPrimaryKeyBytesAllocated
> FROM system.parts
> GROUP BY active, database, table
> E0516 15:12:04.190579       1 connection.go:83] connect():FAILED Ping(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/). Err: context deadline exceeded
> E0516 15:12:04.190986       1 connection.go:120] QueryContext():FAILED connect(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/) for SQL: SELECT
>         database,
>         table,
>         toString(is_session_expired) AS is_session_expired
> FROM system.replicas
> E0516 15:12:14.195386       1 connection.go:83] connect():FAILED Ping(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/). Err: context deadline exceeded
> E0516 15:12:14.196293       1 connection.go:120] QueryContext():FAILED connect(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/) for SQL: SELECT
>         database,
>         table,
>         count()          AS mutations,
>         sum(parts_to_do) AS parts_to_do
> FROM system.mutations
> WHERE is_done = 0
> GROUP BY database, table
> E0516 15:12:24.197278       1 connection.go:83] connect():FAILED Ping(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/). Err: context deadline exceeded
> E0516 15:12:24.197355       1 connection.go:120] QueryContext():FAILED connect(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/) for SQL:   SELECT
>       name,
>          toString(free_space) AS free_space,
> toString(total_space) AS total_space
>      FROM system.disks
> E0516 15:12:24.199950       1 connection.go:83] connect():FAILED Ping(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/). Err: dial tcp: lookup chi-clickhouse-clickhouse-0-0.default.svc.cluster.local on 10.96.0.10:53: read udp 192.168.0.56:47559->10.96.0.10:53: i/o timeout
> E0516 15:12:24.200012       1 connection.go:120] QueryContext():FAILED connect(http://***:***@chi-clickhouse-clickhouse-0-0.default.svc.cluster.local:8123/) for SQL: SELECT
>         count() AS detached_parts,
>         database,
>         table,
>         disk,
>         if(coalesce(reason,'unknown')='','detached_by_user',coalesce(reason,'unknown')) AS detach_reason
> FROM system.detached_parts
> GROUP BY
>         database,
>         table,
>         disk,
>         reason

 
 Maybe you will help me?

**Comment by Slach** [comment]
sorry for issue without response, but you found root reason in logs

to avoid it in future don't INSERT data in small parts, use 
engine=Buffer table https://clickhouse.com/docs/en/engines/table-engines/special/buffer or 
async_insert=1 https://clickhouse.com/docs/en/operations/settings/settings#async-insert

**Comment by a-dot** [comment]
@Slach that looks to me like a bad query instead? It's attempting to Group By `reason` but reason doesn't exist, it's called `detach_reason`. https://github.com/Altinity/clickhouse-operator/blob/master/pkg/apis/metrics/clickhouse_fetcher.go#L119-L125

**Comment by Slach** [comment]
query is correct,
`reason` is column in system.detached_parts

`detached_reason` is alias

group by reason 
possible in selected fragment cause `detached_reason` is deterministic relative to `reason`
