### ISSUE TITLE
Operator Helm Chart 

### ISSUE THREAD

**Issue by dvirp-dt** [Altinity/clickhouse-operator#941]
Hey all, 

I'm using [charts-clickhouse](https://github.com/PostHog/charts-clickhouse) as part of the Posthog installation.
Currently, all the dependencies are imported as sub chart except clickhouse-operator.
The method Clickhose is implementing now is to generate the manifest from this repo and add it under the Helm chart templates folder.

Is there any plan for an official Helm chart?
I saw @ganievs PR #925 is merged and I'm wondering what is the next step.

Thanks.

**Comment by Slach** [comment]
the next step use this script in github actions and test generated helm chart, but we have not dead line for this task

feel free test generator and generated helm chart
after it make pull request

**Comment by dvirp-dt** [comment]
Hey @Slach thanks for your reply.

Do you have a reference or any specific instructions to do so?
I've never contributed to an open-source repo.

**Comment by alex-zaitsev** [comment]
https://artifacthub.io/packages/helm/altinity-clickhouse-operator/altinity-clickhouse-operator
