### ISSUE TITLE
Chown Operation not permitted

### ISSUE THREAD

**Issue by visla-xugeng** [Altinity/clickhouse-operator#956]
Hi All,

I got these errors, after the installation of zookeeper. Of course, the 3 zookeeper pods keep restart. 
```
+ chown -Rv zookeeper /var/lib/zookeeper/data /var/lib/zookeeper/datalog /logs /conf
chown: changing ownership of '/var/lib/zookeeper/data/myid': Operation not permitted
failed to change ownership of '/var/lib/zookeeper/data/myid' from 1009 to zookeeper
chown: changing ownership of '/var/lib/zookeeper/data': Operation not permitted
chown: changing ownership of '/var/lib/zookeeper/datalog': Operation not permitted
failed to change ownership of '/var/lib/zookeeper/data' from 1009 to zookeeper
failed to change ownership of '/var/lib/zookeeper/datalog' from 1009 to zookeeper
ownership of '/logs' retained as zookeeper
ownership of '/conf/zoo.cfg' retained as zookeeper
ownership of '/conf/log4j.properties' retained as zookeeper
ownership of '/conf/java.env' retained as zookeeper
ownership of '/conf/configuration.xsl' retained as zookeeper
ownership of '/conf/logback.xml' retained as zookeeper
ownership of '/conf/zoo_sample.cfg' retained as zookeeper
ownership of '/conf' retained as zookeeper
```

```
 kubectl -n zookeeper get pod
NAME          READY   STATUS             RESTARTS         AGE
zookeeper-0   0/1     CrashLoopBackOff   19 (2m16s ago)   74m
zookeeper-1   0/1     CrashLoopBackOff   19 (118s ago)    74m
zookeeper-2   0/1     CrashLoopBackOff   10 (13s ago)     26m
```

I followed this link to install the zookeeper cluster, https://github.com/Altinity/clickhouse-operator/blob/master/docs/zookeeper_setup.md#advanced-setup
I created a namespace, zookeeper and applied all of these yamls into this namespace. My EKS cluster already has storage class configured, I just use it in my zookeeper setting. Nothing else.

**Comment by visla-xugeng** [comment]
I also tried this yaml file which is quick start and got same error. What permission do I need here?

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/zookeeper/quick-start-persistent-volume/zookeeper-3-nodes.yaml

**Comment by Slach** [comment]
looks like your container started not under root and `chown` returns permission fail

Do you have default securityContext restrictions in your EKS?
Did you change volumeTemplateClaim section from

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/zookeeper/quick-start-persistent-volume/zookeeper-3-nodes.yaml#L233-L241 ?

could you share
```
kubectl get storageclass -o wide
```
from your EKS?

**Comment by visla-xugeng** [comment]
@Slach Thanks,

"Do you have default securityContext restrictions in your EKS?" I noticed that some third party open sources deployments have this securityContext setting. (Not all of them. )

Please see part of my config of statefulSet:

```
volumeClaimTemplates:
    - metadata:
        name: datadir-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: efs-sc
```
 

```
kubectl get storageclass -o wide
NAME               PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
efs-sc             efs.csi.aws.com         Retain          Immediate              false                  72d
gp2                kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  72d
```

**Comment by Slach** [comment]
look like you faced with https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300
just try to remove `chown` from manifest
if zookeeper failed, then EFS is not applicable for this use case

we use standart EBS gp3 storage classes for our altinity.cloud

**Comment by Davidrjx** [comment]
possibly manifest update works with 
```
...
securityContext:
        runAsUser: 999
...
```
