### ISSUE TITLE
how to setup dns for ch to connect pods/sevices in different namespace

### ISSUE THREAD

**Issue by xgengsjc2021** [Altinity/clickhouse-operator#966]
Hi,
My CH (in **clickhouse** namespace) could not reach out kafka pod/service (in **posthog** namespace). I tried to configure namespaceDomainPattern in CH, did not work. 

```
  namespaceDomainPattern:  "posthog.svc.cluster.local"
```

The error I got from my CH pod:
```
2022.07.01 00:02:47.009864 [ 328 ] {} <Error> StorageKafka (kafka_session_recording_events): [rdk:FAIL] [thrd:posthog-posthog-kafka:9092/bootstrap]: posthog-posthog-kafka:9092/bootstrap: Failed to resolve 'posthog-posthog-kafka:9092': Name or service not known (after 2ms in state CONNECT, 28 identical error(s) suppressed)
2022.07.01 00:02:47.009993 [ 273 ] {} <Error> StorageKafka (kafka_session_recording_events): [rdk:ERROR] [thrd:app]: ClickHouse-chi-ch-install-dev-shard0-0-0.chi-ch-install-dev-shard0-0.clickhouse.svc.cluster.local-posthog-kafka_session_recordi: posthog-posthog-kafka:9092/bootstrap: Failed to resolve 'posthog-posthog-kafka:9092': Name or service not known (after 2ms in state CONNECT, 28 identical error(s) suppressed)
```

**Comment by xgengsjc2021** [comment]
from the ch pod, I only see this one, but I want to add something like this one "posthog.svc.cluster.local". Not figure out how to add it. 

```
cat /etc/resolv.conf 
nameserver 172.20.0.10
search clickhouse.svc.cluster.local svc.cluster.local cluster.local cn-northwest-1.compute.internal
options ndots:5
```

**Comment by Slach** [comment]
if you need to connect to pods and services 
you don't need to change nameserver or change `namespaceDomainPattern`
use standartd kubernetes  name conversion
service_name.namespace.svc.cluster.local (or just service_name.namespace)
or
pod_name.service_name.namespace.svc.cluster.local (or pod_name.service_name.namespace)

for posthog namespace
just use posthog-posthog-kafka.posthog:9090 if you have service name `posthog-posthog-kafka` in `posthog` namespace
look https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ for details

**Comment by xgengsjc2021** [comment]
@Slach From the log, you can see that the CH pod could not resolve the posthog service, since the posthog is in different namespace. 
In my Posthog namespace, I do have posthog-posthog-kafka. 

```
kubectl -n posthog get svc
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
posthog-posthog-kafka                ClusterIP   172.20.95.164    <none>        9092/TCP                     5h42m
```
The question is that the CH pod does not know this service is in different namespace. When it tries to talk to this service, it will think this **posthog-posthog-kafka** is in the same namespace as CH pod. Then the error coma out. 
If the pod has something like this "posthog.svc.cluster.local" in their /etc/resolve.conf, then the pod can resolve this **posthog-posthog-kafka service** in posthog namespace. Then it will be able to talk this service correctly. 

That's reason why I am asking you how to configure this on CH pod. For now, the /etc/resolve.conf in CH pod is 
```
cat /etc/resolv.conf 
nameserver 172.20.0.10
search clickhouse.svc.cluster.local svc.cluster.local cluster.local cn-northwest-1.compute.internal
options ndots:5
```

**Comment by xgengsjc2021** [comment]
@Slach can you take a look this again? The question is that the CH pod does not know that the **posthog-posthog-kafka**  is in different namespace. From the error message, you can see that, the CH talk to **posthog-posthog-kafka**   directly. Did not add posthog namespace. This is the reason I am asking where to add this dns setting, I did not find in the installation file. 

```
2022.07.01 04:07:54.507213 [ 284 ] {} <Error> StorageKafka (kafka_plugin_log_entries): [rdk:FAIL] [thrd:posthog-posthog-kafka:9092/bootstrap]: posthog-posthog-kafka:9092/bootstrap: Failed to resolve 'posthog-posthog-kafka:9092': Name or service not known (after 1ms in state CONNECT, 28 identical error(s) suppressed)
```
