### ISSUE TITLE
Take effect without restart by updating some clickhouse configuration

### ISSUE THREAD

**Issue by xzy256** [Altinity/clickhouse-operator#978]
Clickhouse support some configuration take effect without restart, such as `keep_alive_timeout` 、`max_thread_pool_size` 、`max_connections` etc.
But when i use operator,   no matter config
```
configuration:
    files:
      config.d/xxx.xml
```
or
```
configuration:
    files:
      conf.d/xxx.xml
```
or
```
configuration:
    settings:
        key: value
```
When apply yaml by `kubectl`, the pods restart after some seconds. Does operator support the function or not ?

**Comment by alex-zaitsev** [comment]
We plan to add a special syntax to specify if clickhouse needs to be restarted for a particular setting change or not.

**Comment by xzy256** [comment]
very nice.
