### ISSUE TITLE
ck operator password

### ISSUE THREAD

**Issue by zlcnju** [Altinity/clickhouse-operator#986]
I want to know why we use the same operator password for all the ck instance. It is not safe enough, I think we should use give the ability to give every instance different password。And if you agree, I can try it.

**Comment by alex-zaitsev** [comment]
Hi @zlcnju , do you mean generating operator password?

In prod environments, default operator password is never used. Kubernetes secret is preferable. We are actually going to change the default configuration to secret based to make it transparent.
Also, clickhouse_operator user is restricted to connect only from clickhouse_operator pod's IP address, so it can not be easily used from outside.

**Comment by zlcnju** [comment]
If clickhouse_operator user is restricted to connect only from clickhouse_operator pod's IP address, it is better
