### ISSUE TITLE
when will you add this commit? https://github.com/ClickHouse/ClickHouse/issues/36367

### ISSUE THREAD

**Issue by xgengsjc2021** [Altinity/clickhouse-operator#997]
Hi, 
I see CH closed this ticket and mentioned fixed the issue. When will you add it to the latest release?

**Comment by xgengsjc2021** [comment]
https://github.com/ClickHouse/ClickHouse/issues/36367

https://github.com/ClickHouse/ClickHouse/pull/40732

**Comment by Slach** [comment]
These changes not depends on `clickhouse-operator`
wait when next releases 22.x with cherry-picked commits will release by ClickHouse team, and you can use it via `podTemplate`
