### ISSUE TITLE
Cross-cluster replication

### ISSUE THREAD

**Issue by djosephsen** [Altinity/clickhouse-operator#999]
Heya! Thanks for this great project; quick question:

Currently, it doesn't seem to be possible to configure the operator with clickhouse replication partners outside the local k8s cluster. In other words,  I'd like to be able to provide an external fqdn for my \<replica\> -> \<host\> 's.  Am I missing something?  Thanks in advance! 

```
    <testsimple>
      <shard>
        <internal_replication>false</internal_replication>
        <replica>
            <host>some.external.fqdn.com</host>
            <port>9000</port>
        </replica>
      </shard>
    </testsimple>
```

**Comment by UnamedRus** [comment]
You can provide your own config files with any content.
https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-05-files-nested.yaml#L30


So you can just define new cluster definition in separate config file.
